### ISSUE TITLE
How to enable gnome extension out of the box?

### ISSUE THREAD

**Issue by Niladrithub** [PJ-Singh-001/Cubic#10]
I want to know, is there a way by which the extension I add in the iso comes pre-activated when I use the iso for the first time?
Like how the Zorin team made their zorin taskbar, if I wanted the same effect with dash to panel and ubuntu. And in my specific case I want to make the user theme extension enabled by default.

**What I have tried**
I have added the extension user themes. When I boot from the iso and click the try option from ubiquity, I go to the extension app and see the user theme extension is disabled. Although my gtk themes are working, but the shell theme doesn't seem to change from the default yaru.

**Expected behavior**
I want the extensions I choose to be enabled as the way I want out of the box. So that I don't have to open the extension app to tweak it on and customize it after booting.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 20.04.3

**Cubic Information (please complete the following information):**
 - Cubic Version:  2021.12.68
 - ISO Customizing: ubuntu-20.04.3-desktop-amd64.iso
 - Download Link: https://ubuntu.com/download/desktop/thank-you?version=20.04.3&architecture=amd64

**Comment by PJ-Singh-001** [comment]
### Enable an Extension by Default

 1. On your host system, create a file named...

        90_ubuntu-settings.gschema.override

 2. Add the following to the file, and save it.

        [org.gnome.shell]
        enabled-extensions = ['user-theme@gnome-shell-extensions.gcampax.github.com']

    You can add additional extensions that should be active by default; just make sure they are single quoted and comma separated inside the brackets `[...]`.

 3. In Cubic's Terminal page, change to the `schemas` directory.

        cd /usr/share/glib-2.0/schemas/

 4. Then drag your new file, `90_ubuntu-settings.gschema.override`, onto the Terminal page. Click the <kbd>Copy</kbd> button to copy the file into the current directory.

 5. Recompile the schemas.

        glib-compile-schemas /usr/share/glib-2.0/schemas/

You didn't mention where you were installing your extension, but I recommend placing the extension's directory and files in...

    /usr/share/gnome-shell/extensions

...instead of `/etc/skel/.local/share/gnome-shell/extensions`.

**Comment by PJ-Singh-001** [comment]
### How to Customize an Extension

I'll assume you have installed your extension under `/usr/share/gnome-shell/extensions`.

 1. In Cubic's Terminal page, change to the extension's `schemas` directory.

        cd /usr/share/gnome-shell/extensions//user-theme@gnome-shell-extensions.gcampax.github.com/schemas

 2. Edit the default configuration. Do not change the `summary` or `description` fields.

        nano org.gnome.shell.extensions.user-theme.gschema.xml

 3. Replace the default  (`""`) value with your preference. In this example, I used `"Yaru-light"`.

        <schemalist gettext-domain="gnome-shell-extensions">
          <schema id="org.gnome.shell.extensions.user-theme" path="/org/gnome/shell/extensions/user-theme/">
            <key name="name" type="s">
              <default>"Yaru-light"</default>
              <summary>Theme name</summary>
              <description>The name of the theme, to be loaded from ~/.themes/name/gnome-shell</description>
            </key>
          </schema>
        </schemalist>

 4. Save the file and exit `nano`.

    <kbd>Ctrl</kbd><kbd>X</kbd>, <kbd>Y</kbd>, <kbd>Enter</kbd>

 5. Recompile the schemas.

        glib-compile-schemas /usr/share/gnome-shell/extensions//user-theme@gnome-shell-extensions.gcampax.github.com/schemas
