### ISSUE TITLE
UEFI builds with VMWare Workstation

### ISSUE THREAD

**Issue by dgillespie312** [PJ-Singh-001/Cubic#102]
I am using VMWare Workstation set to UEFI as my Cubic host.  I also use Ubuntu cloud-init to automate my installs. Once I burn my ISO to a USB it boots, but does not use the nocloud datasource.

I'm just looking for some guidance or direction to help me switch to UEFI.  I've been successfully using BIOS for some time.

Thanks to all.

**Comment by dgillespie312** [comment]
If I need to provide more information please let me know. This is for a company project so I would be glad to donate for assistance.

Thanks

**Comment by dgillespie312** [comment]
I have tested with 22.04, 20.04 and all the physical hardware I have including VMWare. All of my media boots but never starts the automated install.

**Comment by dgillespie312** [comment]
I am still seeking assistance. I have always received very timely responses with my issues and questions. It's leaving me to wonder if it's a question that's already been covered or just not appropriate for this forum.

Thanks again.

**Comment by dgillespie312** [comment]
Can someone confirm if the information provided in the following link is still accurate for Ubuntu 20.04?

https://answers.launchpad.net/cubic/+question/387566

**Comment by dgillespie312** [comment]
Well I ended up no using the preseed or supplying user-data in the cubic wizard. The most reliable solution for me was to use cubic for customization then use the iso from cubic as the source for ubuntu-autoinstall-generator.sh.

**Comment by PJ-Singh-001** [comment]
@dgillespie312,
I'm glad you were able to find an approach that works for you.
I do not have experience with nocloud, so I was hoping someone would chime in and supply some insight.
I'll keep your question in mind, and let you know if I learn something useful.
