### ISSUE TITLE
Upgrading Ubuntu20.04 to 22.04 

### ISSUE THREAD

**Issue by wbw455** [PJ-Singh-001/Cubic#103]
Hello,

Is it possible to upgrade my version to a later Ubuntu release, using the old .iso as a base.

**What you have tried**
I tried booting 20.04 iso
apt install update-manager-core
do-release-upgrade

Everything installs OK.

When booting live CD, an error occours:

![Screenshot from 2022-10-06 15-53-38](https://user-images.githubusercontent.com/43434178/194331634-cd4d6c3f-3088-4146-a4b8-559623fd22f8.png)

Since the live cd still has to older kernel.

In Cubic I cannot see that any other kernel is available.

![Screenshot from 2022-10-06 15-57-15](https://user-images.githubusercontent.com/43434178/194332246-a909e5cd-5d8d-4c31-b464-4c512af4a709.png)

In virtual environment:
$uname -a 
Linux cubic 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Thankful for any advice!

**Comment by PJ-Singh-001** [comment]
The Linux filesystem on the original ISO does not come with a kernel installed, because the ISO's boot strap kernel is used in the live environment.

To see this for yourself, on the Terminal Page in Cubic, execute the following:

    cd /boot
    ls -l

You will see two broken sym-links for `initrd.img` and `vmlinuz`.

Therefore, you should install the kernel corresponding to your release manually.

    apt update
    apt install --yes --reinstall linux-headers-5.13.0-19 linux-headers-5.13.0-19-generic linux-image-5.13.0-19-generic

(This is just an example, so be use the correct kernel version that you need).

**Comment by wbw455** [comment]
Hello,

Thank you for this information.

After installing the kernel I can now see an aditional entry in the kernel config.

I am getting the same errors as before. I tried booting both into VMware and a PC.

I noticed that some errors when booting

![Screenshot from 2022-10-07 17-15-32](https://user-images.githubusercontent.com/43434178/194588880-bf55bf77-8f43-43e3-bc2e-d7be96e48078.png)

and when looking in the crash log :  
 `
$ grep -rn "ERROR"


1665126534.256698608.install_fail.crash:1693: 2022-10-07 07:08:54,256 ERROR root:39 finish: subiquity/Install/install/configure_apt: FAIL: Command '['systemd-run', '--wait', '--same-dir', '--property', 'SyslogIdentifier=subiquity_log.2364', '--property', 'PrivateMounts=yes', '--setenv', 'PATH=/snap/subiquity/3698/bin:/snap/subiquity/3698/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/subiquity/3698/bin', '--setenv', 'PYTHONPATH=:/snap/subiquity/3698/lib/python3.8/site-packages', '--setenv', 'PYTHON=/snap/subiquity/3698/usr/bin/python3.8', '--setenv', 'SNAP=/snap/subiquity/3698', '--', '/snap/subiquity/3698/usr/bin/python3.8', '-m', 'curtin', '--showtrace', '-vvv', '--set', 'json:reporting={"subiquity": {"type": "journald", "identifier": "curtin_event.2364.2"}}', 'in-target', '-t', '/tmp/tmpzj0yp1rx/mount', '--', 'apt-get', 'update']' returned non-zero exit status 100.
1665126534.256698608.install_fail.crash:1696: 2022-10-07 07:08:54,259 ERROR root:39 finish: subiquity/Install/install: FAIL: Command '['systemd-run', '--wait', '--same-dir', '--property', 'SyslogIdentifier=subiquity_log.2364', '--property', 'PrivateMounts=yes', '--setenv', 'PATH=/snap/subiquity/3698/bin:/snap/subiquity/3698/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/subiquity/3698/bin', '--setenv', 'PYTHONPATH=:/snap/subiquity/3698/lib/python3.8/site-packages', '--setenv', 'PYTHON=/snap/subiquity/3698/usr/bin/python3.8', '--setenv', 'SNAP=/snap/subiquity/3698', '--', '/snap/subiquity/3698/usr/bin/python3.8', '-m', 'curtin', '--showtrace', '-vvv', '--set', 'json:reporting={"subiquity": {"type": "journald", "identifier": "curtin_event.2364.2"}}', 'in-target', '-t', '/tmp/tmpzj0yp1rx/mount', '--', 'apt-get', 'update']' returned non-zero exit status 100.
1665126534.256698608.install_fail.crash:1752: 2022-10-07 07:08:54,256 ERROR root:39 finish: subiquity/Install/install/configure_apt: FAIL: Command '['systemd-run', '--wait', '--same-dir', '--property', 'SyslogIdentifier=subiquity_log.2364', '--property', 'PrivateMounts=yes', '--setenv', 'PATH=/snap/subiquity/3698/bin:/snap/subiquity/3698/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/subiquity/3698/bin', '--setenv', 'PYTHONPATH=:/snap/subiquity/3698/lib/python3.8/site-packages', '--setenv', 'PYTHON=/snap/subiquity/3698/usr/bin/python3.8', '--setenv', 'SNAP=/snap/subiquity/3698', '--', '/snap/subiquity/3698/usr/bin/python3.8', '-m', 'curtin', '--showtrace', '-vvv', '--set', 'json:reporting={"subiquity": {"type": "journald", "identifier": "curtin_event.2364.2"}}', 'in-target', '-t', '/tmp/tmpzj0yp1rx/mount', '--', 'apt-get', 'update']' returned non-zero exit status 100.
1665126534.256698608.install_fail.crash:1754: 2022-10-07 07:08:54,259 ERROR root:39 finish: subiquity/Install/install: FAIL: Command '['systemd-run', '--wait', '--same-dir', '--property', 'SyslogIdentifier=subiquity_log.2364', '--property', 'PrivateMounts=yes', '--setenv', 'PATH=/snap/subiquity/3698/bin:/snap/subiquity/3698/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/subiquity/3698/bin', '--setenv', 'PYTHONPATH=:/snap/subiquity/3698/lib/python3.8/site-packages', '--setenv', 'PYTHON=/snap/subiquity/3698/usr/bin/python3.8', '--setenv', 'SNAP=/snap/subiquity/3698', '--', '/snap/subiquity/3698/usr/bin/python3.8', '-m', 'curtin', '--showtrace', '-vvv', '--set', 'json:reporting={"subiquity": {"type": "journald", "identifier": "curtin_event.2364.2"}}', 'in-target', '-t', '/tmp/tmpzj0yp1rx/mount', '--', 'apt-get', 'update']' returned non-zero exit status 100. `

`grep -rn "FAIL"


1665126534.256698608.install_fail.crash:1693: 2022-10-07 07:08:54,256 ERROR root:39 finish: subiquity/Install/install/configure_apt: FAIL: Command '['systemd-run', '--wait', '--same-dir', '--property', 'SyslogIdentifier=subiquity_log.2364', '--property', 'PrivateMounts=yes', '--setenv', 'PATH=/snap/subiquity/3698/bin:/snap/subiquity/3698/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/subiquity/3698/bin', '--setenv', 'PYTHONPATH=:/snap/subiquity/3698/lib/python3.8/site-packages', '--setenv', 'PYTHON=/snap/subiquity/3698/usr/bin/python3.8', '--setenv', 'SNAP=/snap/subiquity/3698', '--', '/snap/subiquity/3698/usr/bin/python3.8', '-m', 'curtin', '--showtrace', '-vvv', '--set', 'json:reporting={"subiquity": {"type": "journald", "identifier": "curtin_event.2364.2"}}', 'in-target', '-t', '/tmp/tmpzj0yp1rx/mount', '--', 'apt-get', 'update']' returned non-zero exit status 100.
1665126534.256698608.install_fail.crash:1696: 2022-10-07 07:08:54,259 ERROR root:39 finish: subiquity/Install/install: FAIL: Command '['systemd-run', '--wait', '--same-dir', '--property', 'SyslogIdentifier=subiquity_log.2364', '--property', 'PrivateMounts=yes', '--setenv', 'PATH=/snap/subiquity/3698/bin:/snap/subiquity/3698/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/subiquity/3698/bin', '--setenv', 'PYTHONPATH=:/snap/subiquity/3698/lib/python3.8/site-packages', '--setenv', 'PYTHON=/snap/subiquity/3698/usr/bin/python3.8', '--setenv', 'SNAP=/snap/subiquity/3698', '--', '/snap/subiquity/3698/usr/bin/python3.8', '-m', 'curtin', '--showtrace', '-vvv', '--set', 'json:reporting={"subiquity": {"type": "journald", "identifier": "curtin_event.2364.2"}}', 'in-target', '-t', '/tmp/tmpzj0yp1rx/mount', '--', 'apt-get', 'update']' returned non-zero exit status 100.
1665126534.256698608.install_fail.crash:1752: 2022-10-07 07:08:54,256 ERROR root:39 finish: subiquity/Install/install/configure_apt: FAIL: Command '['systemd-run', '--wait', '--same-dir', '--property', 'SyslogIdentifier=subiquity_log.2364', '--property', 'PrivateMounts=yes', '--setenv', 'PATH=/snap/subiquity/3698/bin:/snap/subiquity/3698/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/subiquity/3698/bin', '--setenv', 'PYTHONPATH=:/snap/subiquity/3698/lib/python3.8/site-packages', '--setenv', 'PYTHON=/snap/subiquity/3698/usr/bin/python3.8', '--setenv', 'SNAP=/snap/subiquity/3698', '--', '/snap/subiquity/3698/usr/bin/python3.8', '-m', 'curtin', '--showtrace', '-vvv', '--set', 'json:reporting={"subiquity": {"type": "journald", "identifier": "curtin_event.2364.2"}}', 'in-target', '-t', '/tmp/tmpzj0yp1rx/mount', '--', 'apt-get', 'update']' returned non-zero exit status 100.
1665126534.256698608.install_fail.crash:1754: 2022-10-07 07:08:54,259 ERROR root:39 finish: subiquity/Install/install: FAIL: Command '['systemd-run', '--wait', '--same-dir', '--property', 'SyslogIdentifier=subiquity_log.2364', '--property', 'PrivateMounts=yes', '--setenv', 'PATH=/snap/subiquity/3698/bin:/snap/subiquity/3698/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/subiquity/3698/bin', '--setenv', 'PYTHONPATH=:/snap/subiquity/3698/lib/python3.8/site-packages', '--setenv', 'PYTHON=/snap/subiquity/3698/usr/bin/python3.8', '--setenv', 'SNAP=/snap/subiquity/3698', '--', '/snap/subiquity/3698/usr/bin/python3.8', '-m', 'curtin', '--showtrace', '-vvv', '--set', 'json:reporting={"subiquity": {"type": "journald", "identifier": "curtin_event.2364.2"}}', 'in-target', '-t', '/tmp/tmpzj0yp1rx/mount', '--', 'apt-get', 'update']' returned non-zero exit status 100.
1665126534.256698608.install_fail.meta:2:    "kind": "INSTALL_FAIL",


`
It all apears to be related to systemd. Could this be due the fact that systemd is not acctually running in the virtual environment and thus cannot re-configure the programs after updating?

**Comment by PJ-Singh-001** [comment]
Services do not run in the Terminal page in Cubic.
I’ve explained the reasons in other posts/answers. 

As a result, managing snaps is not possible. I think the upgrade process attempts to upgrade some snaps, based on a cursory inspection of your logs.

Perhaps it may be possible to upgrade by first uninstalling `snapd` ? (Just a thought).

Instead of upgrading from 20.04, why don’t you just try to customize the 22.04 ISO? (I’m genuinely curious what your use case for this approach is for?)

If you have a lot of customizations you always like to make, I suggest creating a script for the changes you  wish to make, and then just running that script in Cubic’s Terminal, whenever you want to base your customizations on a newer version of Ubuntu.

**Comment by wbw455** [comment]
Hello Singh,

Yes that was the case
 for example
/run/sshd
was missing after upgrading the system, along with a bunch of other stuff that needed to be re-configured manually.

> I’m genuinely curious what your use case for this approach is for? 

I was hoping that I could upgrade an already configured image that is running offline.

> If you have a lot of customizations you always like to make, I suggest creating a script for the changes you wish to make, and then just running that script in Cubic’s Terminal, whenever you want to base your customizations on a newer version of Ubuntu.

I think this is the correct answer, I was just hoping for a quick fix :)

Anyway, thank you for the help!
