### ISSUE TITLE
Query regarding Ubuntu server

### ISSUE THREAD

**Issue by Axer31** [PJ-Singh-001/Cubic#105]
Can we rebuild ubuntu ISO from ubuntu server Image?

**Comment by PJ-Singh-001** [comment]
Yes.
There was a [bug which I fixed in January 2022](https://github.com/PJ-Singh-001/Cubic/issues/19), so It should work fine now.
Please let me know if you encounter any issues.

**Comment by PJ-Singh-001** [comment]
@Axer31,

There is an issue customizing newer versions of Ubuntu Server using Cubic.
I am tracking this in Issues #106.
