### ISSUE TITLE
"clean" test environment for a install script

### ISSUE THREAD

**Issue by herrdeh** [PJ-Singh-001/Cubic#107]
**Describe the question**

I'm working on an install script for some software packages. In order to have a clean, vanilla system, I'd like to use a life system. My guess was that I can use a cubic created system to have a casper filesystem, install software which will be when I delete these files.

Now I cannot install software with apt install - packages are not found or not available. With gnome software center, it IS possible to install software, but snaps only seem to be available. 

What would I have to do in order to obtain a system which can be enhanced with software from standard repos, using apt?

**OS Information (please complete the following information):**
 - OS/Distro Name: ubuntu
 - OS Version 20.04

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.06.72
 - ISO Customizing: [e.g. ubuntu-22.10-desktop-amd64.iso]
 - Download Link:  [The download link for the ISO you are customizing](https://ubuntu.com/download/desktop/thank-you?version=22.04.1&architecture=amd64)

**Comment by PJ-Singh-001** [comment]
Your description seems a bit confusing to me:
1. `apt` works fine in Cubic and is the way to install software packages.
2. Snap does *not* work in Cubic (because services do not run in the virtual environment, so the `snapd` service does not run).

Here are a few things to consider:
- Are you sure you have Internet access?
- Did you remember to add the necessary repositories?
- Did you remember to run `apt-update`?

**Comment by herrdeh** [comment]
Hello, thanks for your quick reply. It seems always to be difficult to understand each other. It looks as if
* you were talking about cubic's virtual environment and
* I about the USB stick cubic created

I think I cannot use cubic's VirtEnv for my purpose because I need a running X-server. But you made me think further and I came (late, but not too late) to the conclusion, that a _virtual machine_ should be the ideal testing environment, when I always take a snapshot at the beginning.
Thank you for your time and making me think.
