### ISSUE TITLE
cant open folder in the terminal section

### ISSUE THREAD

**Issue by kassrose** [PJ-Singh-001/Cubic#108]
so I am trying to open the folder located in /usr/share/wallpapers to change the default wallpapers to do so I typed in cd/usr/share/wallpapers and hit enter expecting it to cd into the folder so I could drag and drop new wallpaper into the terminal to add the wallpaper to the folder but nope it gave me the following when I tried to open the folder:  cd: /usr/share/backgrounds: No such file or directory

**Comment by PJ-Singh-001** [comment]
May be you mistyped your commands?...

Make sure there is a space between the command `cd` and the directory path `/usr/share/backgrounds`, as shown:

    cd /usr/share/backgrounds

Also, there should be no `:` character after the `cd` command.

Ubuntu (GNOME) uses the `/usr/share/backgrounds` directory, not `/usr/share/wallpapers`.

When adding new wallpapers, make sure you list the new wallpapers in an `*.xml` file under the directory `/usr/share/gnome-background-properties`, otherwise Gnome will not recognize your wallpapers.

**Comment by kassrose** [comment]
I am using kde neon for my base iso file i am customizing and i have made sure to path to the right directory and encluded a space after "cd" but still no avail

October 14, 2022 at 6:26:03 PM CEST PJ Singh ***@***.***> wrote:

May be you mistyped your commands?...
Make sure there is a space between the command cd and the directory path /usr/share/backgrounds, as shown:cd /usr/share/backgrounds
Also, there should be no : character after the cd command.
Ubuntu (GNOME) uses the /usr/share/backgrounds directory, not /usr/share/wallpapers.
When adding new wallpapers, make sure you include the new wallpapers in an *.xml file under the directory /usr/share/gnome-background-properties, otherwise Gnome will not recognize your wallpapers.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

-Thank you for your valuable time.
      With best regards Kassie R. Black (A.K.A. Kody Jiles)

-- Sent with https://mailfence.com  Secure and private email

**Comment by PJ-Singh-001** [comment]
KDE is different than GNOME.

KDE uses the directory `/usr/share/wallpapers` to store the backgrounds.

When you are on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) in Cubic, and you type the following:

    cd /usr/share/wallpapers

You get the following error?

    -bash: cd: /usr/share/wallpapers: No such file or directory

What is the URL for the Neon ISO that you have downloaded?

Also, add a screenshot of Cubic with the error.

**Comment by PJ-Singh-001** [comment]
I'll assume the above information has helped you to solve your problem, or you no longer have this problem, so I will close this issue.
