### ISSUE TITLE
Nvidia-SMI can't communicate with driver in chroot

### ISSUE THREAD

**Issue by markwillowtree** [PJ-Singh-001/Cubic#113]
In the host OS (Ubuntu Jammy) I've got the nvidia driver running with the following commands

`sudo apt install nvidia-driver-520`
`sudo apt install nvidia-dkms-520`
`sudo prime-select nvidia`
`sudo nvidia-modprobe`
`sudo nvidia-smi`

This returns the GPU info as expected 

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P0    N/A /  N/A |      1MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

However, if I run the same commands (without the sudo) in the cubic chroot, I get this error when running nvidia-smi.
`NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
`

Is there any way to get the chroot to be able to load the nvidia driver? I need it in order to do some work in the chroot environment. 

The nvidia drivers work correctly when booting from the ISO generated by Cubic.  

P.S. Thanks for creating this app, its been a huge time saver for me.

**Comment by PJ-Singh-001** [comment]
What are you doing that you need to load this driver in [Cubic's Terminal](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) ?

**Comment by markwillowtree** [comment]
I need to run a script which creates files I want on the ISO, but the script requires the nvidia drivers to run.

**Comment by PJ-Singh-001** [comment]
What is the output of, executed from inside Cubic?...

    ls -l /boot

**Comment by markwillowtree** [comment]
```
root@cubic:~# ls -l /boot
total 6916
-rw------- 1 root root 6250707 Jul 12 09:51 System.map-5.15.0-43-generic
-rw-r--r-- 1 root root  261694 Jul 12 09:51 config-5.15.0-43-generic
drwxr-xr-x 2 root root    4096 Aug  9 12:51 grub
lrwxrwxrwx 1 root root      28 Aug  9 12:51 initrd.img -> initrd.img-5.15.0-43-generic
lrwxrwxrwx 1 root root      28 Aug  9 12:51 initrd.img.old -> initrd.img-5.15.0-43-generic
-rw-r--r-- 1 root root  182800 Feb  6  2022 memtest86+.bin
-rw-r--r-- 1 root root  184476 Feb  6  2022 memtest86+.elf
-rw-r--r-- 1 root root  184980 Feb  6  2022 memtest86+_multiboot.bin
lrwxrwxrwx 1 root root      25 Aug  9 12:51 vmlinuz -> vmlinuz-5.15.0-43-generic
lrwxrwxrwx 1 root root      25 Aug  9 12:51 vmlinuz.old -> vmlinuz-5.15.0-43-generic
```

I've also included the results of lsmod | grep nvidia below in case it's useful.

```
root@cubic:~# lsmod  | grep nvidia
nvidia_uvm           1339392  0
nvidia_drm             69632  8
nvidia_modeset       1183744  8 nvidia_drm
nvidia              55209984  409 nvidia_uvm,nvidia_modeset
drm_kms_helper        311296  2 nvidia_drm,i915
drm                   622592  13 drm_kms_helper,nvidia,nvidia_drm,i915,ttm

```

**Comment by PJ-Singh-001** [comment]
I get the same message on my end.

My initial thought is that the `nvidia-smi` command requires a back-end service, possibly the `dbus` service, since the message is about communication.

[As you know](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), services do not run in Cubic's Terminal. 

In any case, perhaps there is a work-around. I'll look into this further.

**Comment by PJ-Singh-001** [comment]
I don't think this is a `dbus` issue.
I was actually able to start `dbus`, and still got the error message.
I tested on `xubuntu-20.04.1-desktop-amd64.iso` wile running Cubic in Ubuntu 22.10...

    apt update
    ubuntu-drivers --gpgpu install nvidia

    service dbus status
    * dbus is not running

    service dbus start 
    * Starting system message bus dbus

    service dbus status
    * dbus is running

    nvidia-smi
    NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
