### ISSUE TITLE
How to disable mounting hard disk in live ISO?

### ISSUE THREAD

**Issue by c05772** [PJ-Singh-001/Cubic#122]
**Describe the question**

I  want to use a customized version of Linux Mint Live ISO (on a bootable USB) which does not mount the hard disks of the host computer, my guess is that it should be easy with Cubic but any help to locate the files or scripts to remove would be nice!

For now, I am able to create an updated version of the live ISO with some appimages (executable) on the Desktop: very convenient. But, if the host computer is a window machine and if you click on the Computer icon on the Desktop, all the files of the NTFS Windows hard disks are visible, which I want to prevent because the user of the live ISO is not necessarily the machine owner.

It would be better to have a solution which does not mount any local disks (NTFS or ext4).

=============================
**What you have tried**

One way to do it is the following:
In terminal mode, it is possible to remove two packages:
root@cubic:/# apt-get remove --purge ntfs-3g
and 
root@cubic:/# apt-get remove --purge fuse3 

This works. The customized ISO will boot correctly on the USB, the live distro will be functional and you have internet access via firefox. Now this method seems "brutal" because 
a) the appimage will not work anymore, (the diagnostic says "check fuse", but no surprise, it was removed!)
b) the windows partition still appears if you click on the "Computer" icon but, if you want to mount it you also get a diagnostic about ntfs, no surprise again.

So it is functional but not very clean. One advantage though is that the icon "install Mint" on the Desktop has disappeared .

=============================
**Expected behavior**

The goal is to get the same behavior without "seeing" the unmountable partition, being able to use an appimage package (appimages are really convenient for a live distro, just click and it's work, no knowledge necessary...)

=============================

**OS Information (please complete the following information):**
 - OS/Distro Name: Mint
 - OS Version 21.0

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.06.72
 - ISO Customizing: linuxmint-21-cinnamon-64bit.iso
 - Download Link:  https://www.linuxmint.com/edition.php?id=299

**Screenshots**

**Comment by PJ-Singh-001** [comment]
Let's see what your current situation is... 

 1. Boot into a Live ISO (without `ntfs-3g` or `fuse3`) purged.
 2. Mount all of the partitions.
 3. Then execute the following:

        mount | grep "^/dev"

4. Share (cut and paste) this output.
5. Also indicate which of the listed partitions you do NOT want to be mountable.

Questions:
 1. Would it be sufficient to simply remove the Computer icon on the Desktop?
 2. Are you OK with not mounting any NTFS file systems, or it must be all of the partitions?

**Comment by PJ-Singh-001** [comment]
I haven't heard from you in 25 days.
I am going to mark this issue as invalid.
If you continue to have this problem, please supply the requested information.
