### ISSUE TITLE
How to install Nvidia drivers in Cubic?

### ISSUE THREAD

**Issue by dakan-kankan** [PJ-Singh-001/Cubic#123]
I tried to install it with NVIDIA-xx.run but it didn't work.

**Comment by PJ-Singh-001** [comment]
sudo apt install ubuntu-drivers --gpgpu install nvidia

**Comment by PJ-Singh-001** [comment]
ubuntu-drivers --gpgpu install nvidia

**Comment by MiguelRuizct** [comment]
I think the correct command is: 
```ubuntu-drivers --gpgpu install nvidia
```

**Comment by MiguelRuizct** [comment]
I think the correct command is:  
```
 ubuntu-drivers --gpgpu install nvidia
