### ISSUE TITLE
cant find the key to verify iso

### ISSUE THREAD

**Issue by pixl3ros3** [PJ-Singh-001/Cubic#126]
"I am on the most recent version of cubic (installed it 3 days ago and did a full system update since installation of cuib occured) and everything works fine for the most part. once i make the iso file and i go to install it on a usb i am given a message that says "cant find the key to verify iso image" but i dont have that problem with any other iso file i try to use.

**Comment by PJ-Singh-001** [comment]
When you say "install it on usb" do you mean you are trying to?...

 1. Install your customized OS to a USB (instead of a physical disk on your computer)?
 ..or...
 2. Create a bootable USB stick using the customized *.iso file?
    If this is what you are trying to do, which tool are you using to write the *.iso to the USB ?

Also, please attach a screenshot of the error.

**Comment by PJ-Singh-001** [comment]
I haven't heard back from you in 15 days.
It's not clear what your issue is without additional context.
I am going to mark this question as invalid.

If you continue to have issues, you may open a new Question. Be sure to answer all question in the template and include details and screenshots.
