### ISSUE TITLE
How to customize the Ubiquity slideshow in Ubuntu (GNOME)?

### ISSUE THREAD

**Issue by apage-pi** [PJ-Singh-001/Cubic#127]
---
How can I change the installer's (Ubiquity in this case) splash screens??
---

**Describe the question**

A clear and concise description of what the question is.

I've tried looking it up, nothing useful

I just want the backgrounds/text to be modified.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version 22.04 LTS

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.11.06
 - ISO Customizing: ubuntu-21.10-desktop-amd64.iso
 - Download Link:  N/A

**Comment by PJ-Singh-001** [comment]
Can you share a screenshot or picture of what you mean by "splash screens" ?
(I'd like to see your entire desktop or screen and the window(s) or screen where you want the "splash screen" to appear).

**Comment by apage-pi** [comment]
As in Ubiquity, when installing.![fcf704b0-complete-installation (2).png](https://user-images.githubusercontent.com/72623953/202855375-e01a243c-e681-4321-8792-5d343aa277fa.png)

**Comment by PJ-Singh-001** [comment]
OK. Splash screen usually refers to what you see when your computer boots.
For example...

![image](https://user-images.githubusercontent.com/19394936/202864525-b8df51dc-3d14-4434-878f-61c90a67375e.png)

**Comment by PJ-Singh-001** [comment]
Here is [How to customize the Boot Splash Screen (Plymouth)](https://github.com/PJ-Singh-001/Cubic/issues/5#issuecomment-1001224949)

**Comment by PJ-Singh-001** [comment]
However, you are asking how to customize the "Ubiquity Slide Show".

See [How to customize the Ubiquity slideshow?](https://github.com/PJ-Singh-001/Cubic/issues/9#issuecomment-1005322090)

The files you need to modify are in `/usr/share/ubiquity-slideshow/slides/`.

For [Ubuntu (GNOME)](https://packages.ubuntu.com/jammy/all/ubiquity-slideshow-ubuntu/filelist), the screenshots are located in `/usr/share/ubiquity-slideshow/slides/screenshots/`.

Be sue to `cd` to the correct directory before copying files into [Cubic's Terminal](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) window, as described [here](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Copy-Page).
