### ISSUE TITLE
Creating a user  removes the option to install the resultant iso

### ISSUE THREAD

**Issue by antcj59** [PJ-Singh-001/Cubic#128]
**Describe the question**
I'm installing Linux mint mate 21
I added a user to the chroot 
On the ISO generation and resultant test there is no install Linux option
OK i get that i created a user and from the login prompt i can get to my user that i created ,but i cant get to the "live session user" because it asks for a password .
As an aside, Im also unable to get my user to have elevated privileges.

I ideally would like to add a user as it will then allow me to have all my networking saved

**What you have tried**
Ive tried many pass words from googling this issue
Ive had no luck in changing the user from std to elevated

**Expected behavior**
I expected the live session to not have a password

**OS Information (please complete the following information):**
 - OS mint 21

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.06.72
 - ISO Customizing: linuxmint-21-mate-64bit-7-11-22.iso
 - Download Link:  [The download link for the ISO you are customizing](https://linuxmint.com/download.php)

**Comment by PJ-Singh-001** [comment]
Regarding your question about elevating users' privileges, did you create users with `sudo` privileges, or just regular users? Share the command(s) you used.

Regarding not having an option to login with a live user (ie. `mint`), in my experience, once you create users while customizing the ISO, you do not get the live user listed on the login screen. (I'll have to check if the user Live ISO even configures this Live user when booting into the system; it may be that this user is only configured upon boot up if no other users exist).

Regarding not being able to login without a password, did you configure GNOME to not require the user's password, for each user you do not want to have to enter a password?

How does adding a user allow you to have all your networking saved? Please share what steps you take _from a network configuration perspective_ that requires specific users to exist in the Live environment?

**Comment by PJ-Singh-001** [comment]
By the way, you can still launch Ubiquity from the Applications menu in order to install your OS.

I'll see if the live user can be made available while still having existing users in the Live ISO. 

In the mean time,  answer the questions above.

**Comment by antcj59** [comment]
Thank you for taking the time to reply


Regarding your question about elevating users' privileges, did you create
users with sudo privileges, or just regular users?

I was under the impression chroot was elevated?

Regardless I used      sudo adduser <user> sudo

Regarding not having an option to login with a live user (ie. ubuntu), in
my experience, once you create users while customizing the ISO, you do not
get the live user listed on the login screen. (I'll have to check if the
user Live ISO even configures this Live user when booting into the system;
it may be that this user is only configured upon boot up if no other users
exist).

Regarding not being able to login without a password, did you configure
GNOME to not require the user's password, for each user you do not want to
have to enter a password?

Sorry no I may have misled here. The initial boot up allows me to gain
access via the user I set with password. However as  there was no option to
install ,I was trying to access the live user session login that was made
available.

Its this password that I was looking for

How does adding a user allow you to have all your networking saved? Please
share what steps you take *from a network configuration perspective* that
requires specific users to exist in the Live environment?

Ok I have a nas. I mount the shares via cifs

To that end using nano I was able to set up my shares on the nas directly
accessible via my user

so I will inchroot          *nano
<https://askubuntu.com/questions/1292278/nvidia-driver-is-installed-but-the-driver-is-not-loaded>**/etc/auto.master
<https://askubuntu.com/questions/1292278/nvidia-driver-is-installed-but-the-driver-is-not-loaded>
          and    **add the following line after the "+auto.master" line:*




*# Note that if there are entries for /net or /misc (as # above) in the
included master map any keys that are the # same will not be seen as the
first read key seen takes # precedence.
<https://askubuntu.com/questions/1292278/nvidia-driver-is-installed-but-the-driver-is-not-loaded>**NOTE
the double dash before ghost!!
<https://askubuntu.com/questions/1292278/nvidia-driver-is-installed-but-the-driver-is-not-loaded>*

* #
<https://askubuntu.com/questions/1292278/nvidia-driver-is-installed-but-the-driver-is-not-loaded>*
*+auto.master*

* /mnt/Samba /etc/auto.sambashares --timeout=30 –ghost*


*then *


nano /etc/auto.sambashares

I add 3 lines here for my cifs users

eg user -fstype=cifs,rw,username=user,password=xxxx,uid=1000,iocharset=utf8
://server ip/user

this worked straight out the box, nothing additional to do

i will have a look at the ubiquity option u suggested in the 2nd email




regards
Anthony Jordan
0204 668006

**Comment by antcj59** [comment]
i just realised i missed a step on the add user. (in my reply to you)
what i did was:
sudo adduser ant
then
sudo adduser ant sudo
adding ant to sudo group

regards
Anthony Jordan
0204 668006

**Comment by antcj59** [comment]
Thank you
Using ubiquity worked great. I was unaware of it.

The only thing that occurred to me was that I had already set up the user
under cubic chroot, and essentially was doing the same again
But it did not seem to affect anything and the user was still part of the
sudo group when i checked.

so i am really happy , i can create an iso with most of my settings
including networking and shares.
You have done a brilliant job.


regards
Anthony Jordan
0204 668006

**Comment by PJ-Singh-001** [comment]
When you create your users, if you want them to have the Ubiquity launcher on their desktops, add the launcher to `/etc/skel/Dekstop/ubiquity.desktop`. Do this _before_ creating your users. [Here is info on`skel`](https://github.com/PJ-Singh-001/Cubic/issues/115#issuecomment-1308835280).

For reference, [here is a an answer on how to create users](https://github.com/PJ-Singh-001/Cubic/issues/3#issuecomment-997134540), which I think you already have done.

If you don't have any open questions, shall we close this issue?

**Comment by antcj59** [comment]
Than you yes i  would say that sorts the issue out.
Using ubiquity from cli will probably be the way i go

thank you for all your work


regards
Anthony Jordan
0204 668006
