### ISSUE TITLE
Feature Request: Open new Cubic instance with project folder pre-selected

### ISSUE THREAD

**Issue by PicoMitchell** [PJ-Singh-001/Cubic#13]
Thinking about if [this other feature request](https://github.com/PJ-Singh-001/Cubic/issues/12) were done, I'm imagining another convenience in automating Cubic would be able to open a new instance with a specific project folder pre-selected.

I'm thinking this could just be done as a path argument to the `cubic` command so that I could call `cubic /path/to/project` at the end of a script which prepared a new project (referenced in the other feature request) to open up Cubic with my new project folder pre-selected.

Thanks so much for considering these automation/convenience features, Cubic is such a fantastic tool!

**Comment by PJ-Singh-001** [comment]
Added the ability to pass command line arguments to Cubic, including the ability to specify the project directory.

    cubic --help

    usage: cubic [-h] [-v] [-V] [directory] [iso]

    Cubic (Custom Ubuntu ISO Creator) is a GUI wizard to create a customized Live ISO image for Ubuntu based
    distributions.

    positional arguments:
      directory      directory for a new or existing project
      iso            original ISO file for a new project (ignored for existing projects)

    optional arguments:
      -h, --help     show this help message and exit
      -v, --verbose  output formatted log to the console
      -V, --version  print version information and exit

Updated the man page accordingly, and made logging optional (enabled using the `-v, --verbose` options).

**Comment by PJ-Singh-001** [comment]
Fix released in Cubic version 2022.01.69.

**Comment by PicoMitchell** [comment]
Awesome, thank you!

Being able to specify an iso for a new project was a great idea as well!
