### ISSUE TITLE
Help "Generate Page Error.Not Enough space on disk"

### ISSUE THREAD

**Issue by AchmadDanniMPA** [PJ-Singh-001/Cubic#135]
I am new to Ubuntu and I got an assignment to remaster, 
I'm using cubic and follow my teacher instruction up until the point on the Generate Page. 
I got an "Error. Not enough space on disk"
I've been searching around the internet and didn't find an answer and now I'm stuck.
If anyone know how to fix please tell me how to fix this.
and thank you.
![Screenshot_20221204_063749](https://user-images.githubusercontent.com/113399342/205488818-40d28f74-ee54-4be8-98ae-5dccdc89b46e.png)

**Comment by PJ-Singh-001** [comment]
You do not have enough disk space.
You didn't share which ISO you are customizing?
I you supply that information, I can give you a rough estimate of how much space you will need.
How much customization did you do? (In other words, how many packages did you add, how many did you remove, did you add any large files such as wall papers?)
How much free disk space does your computer have?
(If it's not too personal, I'm curious which educational institution you're with?)

**Comment by AchmadDanniMPA** [comment]
I see I just noticed today the linux said it have more than 6gb but when I check at the terminal only shows around 2.5gb I'm gonna try to add more space thanks for the answer 😄

**Comment by PJ-Singh-001** [comment]
Based on your screenshot above, you will need at least 4 GiB *additional* space.
