### ISSUE TITLE
How to view the changelog for Cubic releases?

### ISSUE THREAD

**Issue by Augusto7743** [PJ-Singh-001/Cubic#136]
Thanks very much PJ-Singh-001 for doing Cubic.
Well ... where is the changelog ? What feature or fix was done in recent release ?

Thanks for reading and have an good week.

**Comment by PJ-Singh-001** [comment]
@Augusto7743,

Excellent question, and thanks for asking!

Execute the following to see the change log:

    zcat /usr/share/doc/cubic/changelog.Debian.gz

(You are supposed to be able to view the change log during a package update, if you are using the graphical "Software Updater" tool in Ubuntu. Unfortunately, that tool does not show the change log for PPA packages, only official Ubuntu repository packages-- this is a known issue).

**Comment by Augusto7743** [comment]
Thanks very much my friend replying and changing the topic title to an better naming.
Have an nice week.
