### ISSUE TITLE
How do I install Cubic on a non-Ubuntu system?

### ISSUE THREAD

**Issue by guest123guest** [PJ-Singh-001/Cubic#139]
**Describe the question**

The only way I can see on installing this application software is via the PPA repositories, but Linux Mint Debian edition doesn't support PPAs. This seems to be python based, so is there a .deb file available for Debian based systems?

**What you have tried**

I looked at the source code on launchpad, but I can't figure out the instructions on compiling it.

**Expected behavior**

IDK what to put here

**OS Information (please complete the following information):**
 - OS/Distro Name: Linux Mint Debian edition
 - OS Version LMDE 5 Elsie

**Cubic Information (please complete the following information):**
 - Cubic Version: None (Haven't installed it)

**Screenshots**

N/A

**Comment by PJ-Singh-001** [comment]
Yes...

 1. Download the `deb` file using:

        wget -c https://code.launchpad.net/~cubic-wizard/+archive/ubuntu/release/+files/cubic_2022.12-74-release~202212012321~ubuntu22.04.1_all.deb

 2. Get the `gdebi` tool, available from the [`gdebi-core` package](https://packages.debian.org/stable/gdebi-core), to ensure you automatically get all of the required dependencies when you install Cubic.

        sudo apt install gdebi-core

 4. Finally, use `gdebi` to install Cubic and the (absolute minimum) required packages.

        sudo gdebi --option "APT::Install-Recommends=0" cubic_2022.12-74-release~202212012321~ubuntu22.04.1_all.deb

    (Adding the `"APT::Install-Recommends=0"` argument is equivalent to `apt install --no-install-recommends` described in the [Cubic installation instructions](https://github.com/PJ-Singh-001/Cubic/wiki/Install-Cubic)).

**Comment by guest123guest** [comment]
```
dpkg-deb: error: archive 'cubic_2022.12-74-release~202212012321~ubuntu22.04.1_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive cubic_2022.12-74-release~202212012321~ubuntu22.04.1_all.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 cubic_2022.12-74-release~202212012321~ubuntu22.04.1_all.deb
```
I get this error, is the deb file broken?
EDIT: I did find a way to install it. (I haven't tested if it works for creating custom ISOs yet though) You have to extract the files from the broken "zst" files inside the deb file into a singular working folder, with the control.tar.zst files being inside the DEBIAN folder. Then remake the deb file using dpkg-deb. It seems to work that way for some reason.

**Comment by PJ-Singh-001** [comment]
I've kicked off the process to make [Cubic available in the Debian repository](https://github.com/PJ-Singh-001/Cubic/issues/141).
Progress can be tracked in Issue #141.

**Comment by PJ-Singh-001** [comment]
See is [How to install Cubic on Debian and Derivatives](https://github.com/PJ-Singh-001/Cubic/wiki/Install-Cubic#-debian-and-derivatives) helps.
