### ISSUE TITLE
Is there a headless mode?

### ISSUE THREAD

**Issue by lindhe** [PJ-Singh-001/Cubic#14]
Hi! I've tried looking through the Wiki but didn't find any mention of it, so thought I'd try to ask this way... Is there a headless mode of operations for the `cubic` program?

Cubic is the best GUI I've found for creating custom Linux distros, but sometimes I would like to automate the creation of new images without having to do it manually via the Cubic GUI. What I'm really looking for is to create it via GUI the first time, and run a CLI tool on consecutive times. Is this supported? If not: is there an easy way to manually build the image based on what's created before by Cubic?

**Comment by PJ-Singh-001** [comment]
Cubic does not have a command-line only interface.
There is no way to do this in a "headless" mode using the Cubic GUI application.

As of version 2022.01.69, Cubic now accepts the following arguments which may make it easier to open an existing project (or create a new project) from the command line. But you still have to click through the header bar buttons to generate the ISO.

    usage: cubic [-h] [-v] [-V] [directory] [iso]

    positional arguments:
      directory      directory for a new or existing project
      iso            original ISO file for a new project (ignored for existing projects)

    optional arguments:
      -h, --help     show this help message and exit
      -v, --verbose  output formatted log to the console
      -V, --version  print version information and exit

**Comment by rauldipeas** [comment]
This is a greatest feature to add, I want to use Cubic to build a custom ISO on GitHub Actions.

**Comment by athamour1** [comment]
Yes, it could be very helpful to create images from a CI/CD pipeline.
