### ISSUE TITLE
Force Cubic to pull initrd from custom-root even when version hasn't changed?

### ISSUE THREAD

**Issue by PicoMitchell** [PJ-Singh-001/Cubic#140]
**Describe the question**

I have a script I run in the Cubic Terminal which runs updates and then re-builds the `initrd` with added USB network adapter modules. This all works perfectly when there was a kernel update since Cubic detects that version change and pulls the latest `initrd` from the `custom-root` (which has the added USB network adapter modules) and places it in the `custom-disk`. But, when there was no kernel update, Cubic does not copy the `initrd` from the `custom-root` and place it in the `custom-disk` because the version number hasn't changed from what is in the `source-disk` even though I manually re-created the `initrd` in the `custom-root` with the added USB network adapter modules. Is there any way to get (or trick) Cubic into copying the `initrd` from the `custom-root` to the `custom-disk` even if the version is the same as what was in the `source-disk`?

**What you have tried**

I tried manually deleting the `initrd` file in the `casper` folder of the `custom-disk`, but that doesn't help since Cubic still just copies the original from the `source-disk` instead of the manually updated version from the `custom-disk` since the version numbers are the same between the `source-disk` and `custom-disk`.

**Expected behavior**

An manually updated `initrd` from the `custom-root` should be copied into the `custom-disk` even if the version number hasn't changed from what was in the `source-disk`.

**OS Information (please complete the following information):**
 - OS/Distro Name: Linux Mint Cinnamon
 - OS Version: 21.1 beta

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.12.74
 - ISO Customizing: linuxmint-21.1-cinnamon-64bit-beta.iso

**Comment by PJ-Singh-001** [comment]
Cubic *always* copies a set of kernel files (`vmliuz` and `initrd`) from one of two locations:
 1. From the original ISO (`source-disk`)
 2. From inside your customized Linux File system (`custom-root`)

On the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) of the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), you can select the kernel from # 1 or one of the kernels from # 2. Cubic does not check to see if these files have been modified. Every time you generate a new ISO, the selected files are *always* copied to the customized ISO (`custom-disk`). By default, Cubic always selects the highest version, so you need to manually pick a different version, if you want a lower version to be selected.

Please answer these questions:

 1. Are you are modifying files in `source-disk` or `custom-disk` outside of Cubic?

 2. Please execute the following in [Cubic's Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), and share the output. Also, let me know which of the kernels listed (`vmliuz` and `initrd`) in `/boot` you have rebuilt.

        ls -la /boot

 3. From the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), please share a screenshot of your [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), and let me know which kernel you are selecting there.

---

To help explain it better, here is a screen shot of the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) from the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), showing multiple kernels, their origins, and the default selection.

![Cubic Options Page Kernel Tab](https://user-images.githubusercontent.com/19394936/206593072-e0792444-6d59-423d-86b8-aaee50abb1a4.png)

**Comment by PicoMitchell** [comment]
Thanks for getting back to me!

Everything normally works perfectly when there is an updated `initrd` from the `custom-root` for Cubic to copy to the `custom-disk`.

But, the issue right now is that my source ISO is the Mint 21.1 beta which has the latest 5.15.0-56 already included in the `source-disk`.

So, when my script runs in the Cubic Terminal to install system updates and then create a customized `initrd` with the added USB network adapter modules, the kernel version is still the same as the version in the source ISO and Cubic only shows a single option in the Kernels list.

In this first screenshot you can see the customized `initrd` and the source `initrd`, both of which are version 5.15.0-56, but note that the customized `initrd` in the Cubic Terminal is around 76MB because it was compressed with XZ while the source `initrd` is 119MB since it is using the default GZIP compression:
![cubic-updated-kernel-and-source-kernel](https://user-images.githubusercontent.com/7358089/206605604-040cc3e4-8318-466a-9967-b38485b3dc37.png)

Here is the Cubic Kernels list, which only shows a single 5.15.0-56 option, which will copy from the `source-disk` instead of the `custom-disk` since they are both the same version:
![cubic-kernels-list](https://user-images.githubusercontent.com/7358089/206605631-6f5c2599-5466-43d9-b0dd-f08d3fb46be3.png)

Here is the `custom-disk` `casper` contents after Cubic has started creating the ISO and copied the original `initrd` from the `source-disk` instead of the `custom-root`, note the file size and extension to see that it is the larger GZIP instead of the smaller XZ from the `custom-root`.
![cubic-copied-source-kernel](https://user-images.githubusercontent.com/7358089/206605658-11b80d05-3026-4fa2-8c92-577a9235b307.png)

**Comment by PJ-Singh-001** [comment]
OK, thanks for the screen shots.

In your second screen shot, Cubic should list your 76MB `initrd` and corresponding `vmlinuz`, in addition to the files from the original ISO. In other words, you should see two rows.

I'll check that the algorithm that detects these files doesn't have a conflict when the version numbers are the same. Please give me a little time to do this investigation.

If the algorithm is working the way it should, I may then ask you to do some tests on your end as well, so please keep this Cubic project handy.

**Comment by PicoMitchell** [comment]
Digging a little deeper, it looks like maybe the issue is that there is no matching `vmlinuz` file in the `/custom-root/boot` after I only manually created a customized `initrd`. That can be seen in the previous screenshots, and is also noted in the verbose logging from Cubic: [cubic-kernel-log.txt](https://github.com/PJ-Singh-001/Cubic/files/10197280/cubic-kernel-log.txt)

**Comment by PicoMitchell** [comment]
Confirmed that if I manually copy the `source-disk/casper/vmlinuz` file over to `custom-disk/boot/vmlinuz-5.15.0.56-generic` then the Kernels list in Cubic correctly lists both options.

![cubic-fixed-kernels-list](https://user-images.githubusercontent.com/7358089/206774013-feca4ec3-98a4-40c8-ab0b-a97d446ab183.png)

So, this was not a Cubic bug at all and was just because my code was only manually creating an `initrd` file without the latest `vmlinuz` file getting placed into `custom-root/boot` which is the part that happens automatically when system updates installs a kernel update. Now I just need to automate the `vmlinuz` file being copied from `source-disk/casper` into `custom-root/boot` in this scenario!

**Comment by PJ-Singh-001** [comment]
This is exactly the issue!
(I should have spotted this in your screenshot).
