### ISSUE TITLE
Package for Debian?

### ISSUE THREAD

**Issue by 343GuiltySpark-04** [PJ-Singh-001/Cubic#141]
Is there a repo or .deb for installing it on Debian 11, or is the Ubuntu repo compatible? I tried using the PPA but it won't work.

**Comment by 343GuiltySpark-04** [comment]
![Screenshot from 2022-12-10 00-15-00](https://user-images.githubusercontent.com/69496138/206830523-c380f6a7-0727-45d1-b6b4-e97853c7a83b.png)

hope this helps too

**Comment by PJ-Singh-001** [comment]
There is no Debian repo for Cubic.

I had provided instructions on how to download the Ubuntu `*.deb` and install it in Debian:
[How do I install Cubic on a non-Ubuntu system?](https://github.com/PJ-Singh-001/Cubic/issues/139)

However, the Ubuntu `*.deb` format apparently uses `zst` compression for some files, which Debian does not support. (There is an open bug report to add `zst` support to Debian: [dpkg: Please add decompression support for zstd](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664)).

I would be willing to add Cubic to a Debian repository, but do not know the process. If you could point me in the right direction, I will look into it?

**Comment by 343GuiltySpark-04** [comment]
certainly, I'll do some research into it today and get back to you.

**Comment by PJ-Singh-001** [comment]
Regarding the `apt-key is deprecated` warning, this is something you would fix on your end.

Here is a resource you an use to read more: https://itsfoss.com/apt-key-deprecated

(I assume this info also applies to Debian).

**Comment by 343GuiltySpark-04** [comment]
> However, the Ubuntu *.deb format apparently uses zst compression for some files, which Debian does not support. (There is an open bug report to add zst support to Debian: [dpkg: Please add decompression support for zstd](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664)).

from what i can tell in the thread they don't seem to have any intention of doing so.

**Comment by 343GuiltySpark-04** [comment]
https://earthly.dev/blog/creating-and-hosting-your-own-deb-packages-and-apt-repo/

this looks like a good guide

**Comment by 343GuiltySpark-04** [comment]
i managed to get the PPA repo working but the zstd issue still applies so you'll have to either make a separate .deb for Debian or use the compression method Debian uses as its compatible with Ubuntu as well.

**Comment by PJ-Singh-001** [comment]
I just submitted the requisite bug report to kick-off the process to add Cubic to the Debian repository. I'll share the bug number, once it is generated, and share progress as well.

> Content-Type: text/plain; charset="us-ascii"
> MIME-Version: 1.0
> Content-Transfer-Encoding: 7bit
> From: Debian Live user <psingh.cubic@gmail.com>
> To: Debian Bug Tracking System <submit@bugs.debian.org>
> Subject: ITP: cubic -- Cubic is a GUI wizard to create a customized Live ISO image for Ubuntu and Debian based distributions. Cubic was first released for Ubuntu in November 2015.
> Message-ID: <167072756277.2921.15284899084178481339.reportbug@localhost>
> X-Mailer: reportbug 7.10.3+deb11u1
> Date: Sun, 11 Dec 2022 02:59:22 +0000
> 
> Package: wnpp
> Severity: wishlist
> Owner: Debian Live user <psingh.cubic@gmail.com>
> X-Debbugs-Cc: debian-devel@lists.debian.org
> 
> * Package name    : cubic
>   Version         : 2022.12.74
>   Upstream Author : PJ Singh <psingh.cubic@gmail.com>
> * URL             : https://launchpad.net/cubic
> * License         : GPL v3
>   Programming Lang: Python
>   Description     : Cubic is a GUI wizard to create a customized Live ISO image for Ubuntu and Debian based distributions. Cubic was first released for Ubuntu in November 2015.
> 
> Cubic (Custom Ubuntu ISO Creator) is a GUI wizard to create a customized Live ISO image for Ubuntu and Debian based distributions.
> 
> Cubic permits effortless navigation through the ISO customization steps and features an integrated virtual command line environment to customize the Linux file system. You can create new customization projects or modify existing projects. Important parameters are dynamically populated with intelligent defaults to simplify the customization process.
> 
> Screenshots are available at https://github.com/PJ-Singh-001/Cubic/wiki.
> 
> Cubic is a unique application, and I am not aware of other actively maintained GUI based software that offers the same customization flexibility and ease of use as Cubic.
> 
> Cubic has numerous active users all over the world and has been available via PPA for Ubuntu since 2015. To confirm the community interest in Cubic, please see the bug reports on Lauchpad, the Questions and Answers on Launchpad, the Issues in GitHub, or search the internet for the various Cubic tutorials and videos created by users.
> 
> I will maintain this package, but I require a sponsor to add Cubic to the Debian repository. Cubic is a mature application that is already packaged for Ubuntu.

**Comment by 343GuiltySpark-04** [comment]
Excellent i hope they see the value in this tool as much as we do!

**Comment by TheElectronWill** [comment]
zstd support [has been implemented](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664#137) in Debian's dpkg :tada: It's available in dpkg >= 1.21.18

**Comment by PJ-Singh-001** [comment]
@TheElectronWill,

> zstd support [has been implemented](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664#137) in Debian's dpkg tada It's available in dpkg >= 1.21.18

Thank you for sharing this important information !!!

**Comment by PJ-Singh-001** [comment]
1. Make sure you have `dpkg` version 1.21 or higher...

    (Special thanks to @343GuiltySpark-04 and @TheElectronWill for their research).

    Debian `bookworm` already includes `dpkg` version 1.21.20, so you can skip this step if you are running Debian `bookworm` or newer.

    However, if you are running Debian `bullseye`, you will need to install `dpkg` version 1.21.20 and its required (newer) dependencies as well.

    I temporarily used the `bookworm` repositories to make sure I got all of the necessary packages.

    _However, be careful with this hack, as this may break your system._

        cd /etc/apt
        cp sources.list sources.list.original
        sed -i "s|bullseye|bookworm|g" sources.list
        apt update

        apt install dpkg

        cp sources.list.original sources.list
        apt update

 2. Once you have `dpkg` version 1.21 or higher...

        apt-add-repository ppa:cubic-wizard/release
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 081525E2B4F1283B
        apt update
        apt install cubic

**Comment by 343GuiltySpark-04** [comment]
>  1. Make sure you have `dpkg` version 1.21 or higher...
> 
>     (Special thanks to @343GuiltySpark-04 and @TheElectronWill for their research).
> 
>     Debian `bookworm` already includes `dpkg` version 1.21.20, so you can skip this step if you are running Debian `bookworm` or newer.
> 
>     However, if you are running Debian `bullseye`, you will need to install `dpkg` version 1.21.20 and its required (newer) dependencies as well.
> 
>     I temporarily used the `bookworm` repositories to do make sure I got all of the necessary packages.
> 
>     _However, be careful with this hack, as this may break your system._
> 
>         cd /etc/apt
>         cp sources.list sources.list.original
>         sed -i "s|bullseye|bookworm|g" sources.list
>         apt update
> 
>         apt install dpkg
> 
>         cp sources.list.original sources.list
>         apt update
> 
>  2. Once you have `dpkg` version 1.21 or higher...
> 
>         apt-add-repository ppa:cubic-wizard/release
>         apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 081525E2B4F1283B
>         apt update
>         apt install cubic
> 

no problem mate, also bookworm is out already? guess I have weekend plans now.

**Comment by PJ-Singh-001** [comment]
>  bookworm is out already?

`bookworm` is currently in testing.
`bullseye` is still the stable release.

**Comment by 343GuiltySpark-04** [comment]
I'll check my dpkg version tomorrow after work and let you know if any complications arise.

**Comment by 343GuiltySpark-04** [comment]
The apt source changes in bullseye can be reverted after upgrading dpkg

**Comment by 343GuiltySpark-04** [comment]
@PJ-Singh-001 yep everything works as expected, that said i'll keep an eye on my system for any side effects

**Comment by PJ-Singh-001** [comment]
This is good news!

I still haven’t heard back from Debian regarding including Cubic in their repos. Followed up and no response :-(. Guess they are too busy for us ;-). Any way, we have a working solution.

**Comment by 343GuiltySpark-04** [comment]
it would seem that adding it to their repos while nice is a moot point now since this .deb format works in the latest dpkg version.

**Comment by PJ-Singh-001** [comment]
I agree. I’ll probably close this issue, if no one has issues with the PPA in Debian.

**Comment by 343GuiltySpark-04** [comment]
I'd leave it open for a few days in case their are any unintended side effects from the dpkg upgrade hack

**Comment by PJ-Singh-001** [comment]
Looks like this is working for folks.
