### ISSUE TITLE
cant make bootable usb

### ISSUE THREAD

**Issue by kassrose** [PJ-Singh-001/Cubic#144]
**Describe the bug**

when i open kde iso image writer or any iso image writer to make a bootable usb with my custom iso file it tells me "error could not write last block abort" 

**To Reproduce**

take custom iso and insert into iso image writer and click make bootable usb.

**Expected behavior**

it should make a bootable usb

**OS Information (please complete the following information):**
 - OS/Distro Name: kde neon
 - OS Version kde neon 5.26

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.12.74
 - ISO Customizing: kde neon 5.26
 - Download Link: https://neon.kde.org/download
**Cubic Log:**
Gtk-Message: 10:06:21.068: Failed to load module "xapp-gtk3-module"

Cubic - Custom Ubuntu ISO Creator                                               

  • Set application directory.............. /usr/share/cubic                    
  • Set application user home.............. /home/captian-black                 
  • Execute synchronously.................. dpkg-query                          
                                            --admindir="/var/lib/dpkg" --show   
                                            --showformat="${Version} " "cubic"  
  • The process id is...................... 15050                               
  • Set application cubic version.......... 2022.12-74-                         
                                            release~202212012321~ubuntu22.04.1  
  • Set application kernel version......... 5.15.0-56-generic                   

  Setup pages                              

  • Setup.................................. boot copy page                      
  • Setup.................................. compression page                    
  • Setup.................................. delete page                         
  • Setup.................................. extract page                        
  • Setup.................................. finish page                         
  • Setup.................................. generate page                       
  • Setup.................................. migrate page                        
  • Setup.................................. options page                        
  • Setup.................................. packages page                       
  • Setup.................................. prepare page                        
  • Setup.................................. preseed copy page                   
  • Setup.................................. project page                        
  • Setup.................................. start page                          
  • Setup.................................. terminal copy page                  
  • Setup.................................. terminal page                       
  • Set terminal colors?................... Skip                                
  • Setup.................................. test 1 page                         
  • Setup.................................. test 2 page                         

  Setup file choosers                      

  • Setup (ignore warnings)................ copy file chooser                   
  • Setup (ignore warnings)................ directory chooser                   
  • Setup (ignore warnings)................ iso image chooser                   

Handle navigation from no page on open action                                   

  • Interrupt previous thread.............. No thread                           

Get the new page                                                                

  • Current page........................... no page                             
  • Action................................. open                                
  • New page............................... start page                          

  • The thread id is....................... 139804876469824                     
Navigate from no page to start page on open action                              

  • Set application configuration.......... /home/captian-                      
                                            black/.config/cubic/cubic.conf      

  Load application configuration           

  • Load application configuration......... 2022 layout from /home/captian-     
                                            black/.config/cubic/cubic.conf      
  • Set application visited sites.......... []                                  
  • Set application projects............... ['/home/captian-black/cubic         
                                            project']                           
  • Set application iso file path.......... /home/captian-black/Downloads/neon- 
                                            user-20221215-0715.iso              

  Transition pages                         

  • Show new page.......................... start page

**Screenshots**

**Comment by PJ-Singh-001** [comment]
If you are able to test the generated iso in Qemu or another virtual machine, I highly doubt this is an issue with Cubic. You should check your USB drive and make sure it is not defective.

Also, this could be an issue with the software you are using to write the USB stick.

Cubic does not “write” your ISO, and the error you reported does not occur while you are using Cubic. Why don’t you open a bug with the software you are actually using (KDE writer)?

**Comment by PJ-Singh-001** [comment]
Regarding the error,

    Failed to load module "xapp-gtk3-module"

Try reinstalling the `gir1.2-xapp-1.0` package:

    sudo apt install --reinstall gir1.2-xapp-1.0

(This error shouldn't affect Cubic's ability to generate your custom ISO, and you should be able to ignore this message. Xapp is used to render GUI elements on different Desktop Environments).

Try using a different USB stick to write to. Make sure the USB has enough space to write the entire *.iso file. You may want to do a full format of the ISO first.

**Comment by PJ-Singh-001** [comment]
I haven’t heard back from you, so I am marking this issue as invalid and closing it.
