### ISSUE TITLE
modifications of passwd file are reversed during installation of custom image

### ISSUE THREAD

**Issue by Merc718** [PJ-Singh-001/Cubic#152]
Using Ubuntu server img 20.04 to customize, I started Cubic. Using chroot, I added users using the adduser command. Enter all user info. Gave both users I added su.i then Verified that passwd file had new users. Outside of cubic, using the terminal, I modified passwd file to disable root ( setting root to 'sbin/nologin'). In chroot, I installed additional packages (2fa, ufw, fail2ban) and then, outside of cubic, i used local terminal to modify the configuration file for their respective packages. Finally, I packaged the iso and installed the custom iso. 

During installation, the wizard ask me for a new user and password (I think this process resets the passwd file). After the installation is done, I am unable to log into any of the users I created with Cubic. However, I can login with the user created with the wizard. When I login with the wizard created user, all the packages I installed, along with the configuration files I modified, are intact. The home folders for the user I created with cubic are also fine. However, the passwd file doesn't have the user entries from cubic and the modifications to root is also not there.

This may not be a cubic issue, but how do i bypass the installation wizard 'create user' portion and just have ubuntu install

**Comment by PJ-Singh-001** [comment]
On the [Issues tab](https://github.com/PJ-Singh-001/Cubic/issues), you can click on [Closed](https://github.com/PJ-Singh-001/Cubic/issues?q=is%3Aissue+is%3Aclosed) link, and search for previous answers and solutions to your current problem.

See if [this](https://github.com/PJ-Singh-001/Cubic/issues/101#issuecomment-1336728758) helps with your issue.

Also, please note that Cubic does not work with the Ubuntu 22.04 Server ISO (see [this](https://github.com/PJ-Singh-001/Cubic/issues/106) issue). However, I recall 20.04 does work.
