### ISSUE TITLE
Can Cubic download Flatpak updates

### ISSUE THREAD

**Issue by eband** [PJ-Singh-001/Cubic#156]
Lately since Linux Mint 21.1,  the GUI updater installs Flatpak updates on the fly.

I'm wondering, can Cubic do that or is this merely restricted to the Linux Mint 21.1 Updater?

**Comment by PJ-Singh-001** [comment]
You should be able to install flatpak applications in the Cubic Terminal environment. For example, for Spotify:

    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    flatpak install --assumeyes --noninteractive flathub com.spotify.Client

You can update using:

    flatpak update com.spotify.Client

However, I have an Nvidia card, and trying to install `com.spotify.Client`, I got errors about flatpak not installing Nvidia drivers.

Nevertheless, I suggest trying this for yourself.

Please post back and let us know if this is working or not.

**Comment by PJ-Singh-001** [comment]
Closing this issue with the above resolution.

**Comment by PJ-Singh-001** [comment]
Closing this issue with the above resolution.
