### ISSUE TITLE
Can't find bootable partition on UEFI system after Cubic modifications

### ISSUE THREAD

**Issue by ivanzivotic** [PJ-Singh-001/Cubic#157]
Hi,

I have an issue with flashing the Ubuntu Desktop 20.04.5 ISO changed using Cubic to the Fujitsu Stylistic Q5010 tablet, running with Intel Celeron N5100 CPU. When I finish the changes made over Cubic and create a live USB for flashing the device, the installation finishes completely, but after the reboot I get a message from device BIOS saying "Bootable device was not found". The boot system on the device is UEFI. The option I use for disk partitioning is "Erase disk and install Ubuntu", but even when I try to manually create new partition table and create two partitions (one EFI and one EXT4 partition) I get the same error.

When I try installing the regular Ubuntu Desktop 20.04.5 OS downloaded from Canonical website, the installation works correctly and I am able to boot the OS without issues. When I try installing my tweaked ISO after installing that base Ubuntu, the system is unable to boot, but it gets to the GRUB minimal terminal and the kernel is not loaded. I assume this happens because my customized ISO does not change the EFI system partition.

I tried executing the Cubic ISO creation both on the host machine that has a Legacy BIOS boot and the UEFI boot system, but it doesn't change anything and the issue persists with both ISOs.

I was previously able to install the Ubuntu Desktop 18.04.6 customized ISO on that same device without any issues and that ISO was created on the host machine that has a Legacy BIOS boot system.

Thanks in advance,
Ivan

**Comment by PJ-Singh-001** [comment]
What is your Cubic version?

**Comment by ivanzivotic** [comment]
On Legacy BIOS booting machine my Cubic version is 2022.06.72. On UEFI booted host machine on which I was trying to create an ISO it's 2022.12.74

**Comment by PJ-Singh-001** [comment]
Definitely update your other machine to the latest version of Cubic. (See Issue #155).

On your UEFI machine, are you sure you are selecting the correct partition to install the bootloader for your OS?
You need to have an explicit EFI partition.

Also, make sure secure boot is off in your BISO/UEFI settings.

**Comment by ivanzivotic** [comment]
Update:

We discovered that the issue was not related to Cubic after all. We tried using the base Ubuntu and just unpacking and repacking it using Cubic and the installation worked. After that, we tried doing an apt update and upgrade on that base Ubuntu Desktop 20.04 and we encountered two issues:

1. There was a problem with `grub-efi-amd64-signed` package compatibility included in installer with the rest of the GRUB packages acquired doing the apt upgrade. We solved that by installing it manually inside Cubic shell (by running `sudo apt install grub-efi-amd64-signed`).
2. The other issue was that we were receiving `error: out of memory` message after installation completes and the system reboots. We solved that by doing [this](https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1970402/comments/25). 

After these changes, the installation process was executing well for the original Ubuntu, but we still had to figure out why our installation wasn't formatting and installing EFI partition correctly. After a lot investigation, we found that one of our installation scripts impacted the order of FAT32 EFI and EXT4 partitions mounting on path `/target`. Namely, in the regular Ubuntu installation, the installer was first mounting the EXT4 formatted partition to path `/target` and, after that, mounting the EFI FAT32 partition to the path `/target/boot/efi`. On the other hand, our customized Ubuntu ISO was mounting the EFI partition first to the path `/target/boot/efi` and mounting the EXT4 partition next to the path `/target`, causing the `boot` folder inside of it to become inaccessible, causing the installer to think that Ubuntu is not being installed to the UEFI boot system. I am attaching the script that was causing the issue for us, just for people to be aware of it if they encounter they same problem again. The script is used for installing Robot Operating System 2 (ROS 2). We are still investigating which part of the script was actually causing the mount order to revert and will comment which part of it was causing the issue.

Thanks

```
#!/bin/bash
set -e
set -x

# this script is run by the root user in the virtual machine
# it installs ROS2 from source according to this tutorial: https://docs.ros.org/en/humble/Installation/Alternatives/Ubuntu-Development-Setup.html

# setup locale
sudo apt update && sudo apt install locales
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8

# add repo
sudo apt install software-properties-common
sudo add-apt-repository universe
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

# install needed apt packages
sudo apt update && sudo apt install -y \
    build-essential \
    python3-colcon-common-extensions \
    python3-flake8 \
    python3-rosdep \
    python3-setuptools \
    python3-vcstool \
    wget

# install needed pip3 packages
sudo -H pip3 install \
    flake8-blind-except \
    flake8-builtins \
    flake8-class-newline \
    flake8-comprehensions \
    flake8-deprecated \
    flake8-docstrings \
    flake8-import-order \
    flake8-quotes \
    pytest \
    pytest-cov \
    pytest-repeat \
    pytest-rerunfailures

# create a workspace
mkdir -p ${HOME}/ros2_humble/src
cd ${HOME}/ros2_humble
wget https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos
vcs import src < ros2.repos

export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

# download additional, non standard packages
git clone https://github.com/ros-geographic-info/geographic_info.git ${HOME}/ros2_humble/src/geographic_info
cd ${HOME}/ros2_humble/src/geographic_info
git checkout ros2

git clone https://github.com/ros/angles.git ${HOME}/ros2_humble/src/angles
cd ${HOME}/ros2_humble/src/angles
git checkout ros2

git clone https://github.com/ros/diagnostics.git  ${HOME}/ros2_humble/src/diagnostics
cd ${HOME}/ros2_humble/src/diagnostics
#git checkout humble
sed -i "s/<package>/<package format=\"2\">/g" ${HOME}/ros2_humble/src/diagnostics/diagnostic_common_diagnostics/package.xml

git clone https://github.com/ros/eigen_stl_containers.git  ${HOME}/ros2_humble/src/eigen_stl_containers
cd ${HOME}/ros2_humble/src/eigen_stl_containers
git checkout ros2

# install dependencies 
sudo apt upgrade
cd ${HOME}/ros2_humble
sudo rm -rf /etc/ros/rosdep/sources.list.d/20-default.list 
sudo rosdep init
rosdep update
rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-6.0.1 urdfdom_headers diagnostic_common_diagnostics"

# FIXME: Related to Python latest version update
#sudo apt remove -y pybind11-dev
#sudo -H pip3 install pybind11
#sudo -H python3.8 -m pip install setuptools pytest pybind11
#sudo sed -i "1s/python3$/python3.8/" "$(which colcon)"


# build underlay ROS from source
cd ${HOME}/ros2_humble/
colcon build --packages-skip \
    examples_rclcpp_async_client \
    examples_rclcpp_cbg_executor \
    examples_rclcpp_minimal_action_client \
    examples_rclcpp_minimal_action_server \
    examples_rclcpp_minimal_client \
    examples_rclcpp_minimal_composition \
    examples_rclcpp_minimal_publisher \
    examples_rclcpp_minimal_service \
    examples_rclcpp_minimal_subscriber \
    examples_rclcpp_minimal_timer \
    examples_rclcpp_multithreaded_executor \
    examples_rclcpp_wait_set \
    examples_rclpy_executors \
    examples_rclpy_guard_conditions \
    examples_rclpy_minimal_action_client \
    examples_rclpy_minimal_action_server \
    examples_rclpy_minimal_client \
    examples_rclpy_minimal_publisher \
    examples_rclpy_minimal_service \
    examples_rclpy_minimal_subscriber \
    examples_rclpy_pointcloud_publisher \
    examples_tf2_py \
    rviz2 \
    rviz_assimp_vendor \
    rviz_common \
    rviz_default_plugins \
    rviz_ogre_vendor \
    rviz_rendering \
    rviz_rendering_tests \
    rviz_visual_testing_framework \
    rqt \
    rqt_action \
    rqt_bag \
    rqt_bag_plugins \
    rqt_console \
    rqt_graph \
    rqt_gui \
    rqt_gui_cpp \
    rqt_gui_py \
    rqt_msg \
    rqt_plot \
    rqt_publisher \
    rqt_py_common \
    rqt_py_console \
    rqt_reconfigure \
    rqt_service_caller \
    rqt_shell \
    rqt_srv \
    rqt_topic \
    qt_gui \
    qt_gui_app \
    qt_gui_py_common \
    qt_gui_cpp \
    qt_gui_core \
    demo_nodes_py \
    demo_nodes_cpp \
    action_tutorials_py \
    action_tutorials_cpp \
    test_launch_ros \
    test_tf2 \
    quality_of_service_demo_py \
    quality_of_service_demo_cpp \
    test_quality_of_service \
    test_tracetools \
    test_tracetools_launch \
    logging_demo \
    test_communication \
    test_rclcpp \
    test_rclpy \
    launch_testing_examples \
    test_rmw_implementation \
    test_cli \
    test_cli_remapping \
    test_launch_testing \
    topic_statistics_demo \
    dummy_map_server \
    dummy_sensors \
    intra_process_demo \
    demo_nodes_cpp_native \
    dummy_robot_bringup \
    --cmake-args "-DCMAKE_BUILD_TYPE=Release"

sudo rm -rf ${HOME}/ros2_humble/{src,build,log}
```
