### ISSUE TITLE
Link to Cubic source code

### ISSUE THREAD

**Issue by lindhe** [PJ-Singh-001/Cubic#16]
Hi!

Since this repo seems to be just the documentation page for Cubic, it would be nice to have a link to the source code and bug tracker for the actual Cubic software.

I think many people (including me) ends up here believing to have found the Cubic source code repository, before a closer look. Having a link to the actual repo would be very handy.

**Comment by lindhe** [comment]
I guess this is it: https://launchpad.net/cubic

**Comment by PJ-Singh-001** [comment]
You are correct, the source code is on launchpad at https://launchpad.net/cubic.
I now track all bugs here on GitHub.

**Comment by lindhe** [comment]
I'm glad to hear! What about the source code, will that too be migrated here eventually?
