### ISSUE TITLE
Backup current installation for for future tweaking

### ISSUE THREAD

**Issue by alator21** [PJ-Singh-001/Cubic#161]
Is there a way to backup the customization i am working on, in a external hard drive and continue working on it in the future?
I would like to have a 'master' version of the OS and have it backed up, but I would probably need to update it now and then so i should be able to backup/restore it from a  usb/online storage 

I tried this process with Ubuntu 20.04 some time ago but when i tried  loading the files to another machine(same OS) it didn't work properly.

**Comment by PJ-Singh-001** [comment]
You mean backup your Cubic project so you can return to it in the future, or backup your currently running OS ?

**Comment by alator21** [comment]
Backup my current cubic project.

e.g.

I install `git` and produce a new ISO with `git` in it.
In the future(possible using another machine) i would like to update the `git` version and re-produce the ISO.

**Comment by PJ-Singh-001** [comment]
To backup your Cubic project, you will need to copy these files and directories.

    Your Cubic Project
    ├── cubic.conf
    ├── custom-disk
    ├── custom-root
    ├── partition-1.img
    └── partition-2.img

Make sure you backup these files without altering the file permissions. For example, most files in `custom-root` are owned by `root`, and this is also where your Linux File system customizations are stored. Therefore you should not change the ownership of these files while making your backup or restoring it.
