### ISSUE TITLE
license

### ISSUE THREAD

**Issue by massimiliano-dalcero** [PJ-Singh-001/Cubic#163]
Hello,
searching in the repository I did not find the license.  Under what license is the software released?

Thanks & best regatds,
M.

**Comment by palob** [comment]
The actual code appears to be here with .py and shell  files containing a GPLv3+ header.
https://bazaar.launchpad.net/~cubic-wizard/cubic/release/files

**Comment by PJ-Singh-001** [comment]
Files under `/usr/share/bash-completion/cubic` are Apache-2.0.
Files under `/usr/share/icons` are Creative Commons Attribution-NonCommercial-ShareAlike 4.0.
All other files are GPL-3.

You can view the licensee information using:

    cat /usr/share/doc/cubic/copyright
