### ISSUE TITLE
Is Cubic recompiling source code ?

### ISSUE THREAD

**Issue by newtondotcom** [PJ-Singh-001/Cubic#164]
**Describe the question**

Is Cubic recompiling source code ?

In fact, `Ubuntu Intellectual property rights policy` says that : 
<em>Any redistribution of modified versions of Ubuntu must be approved, certified or provided by Canonical if you are going to associate it with the Trademarks. Otherwise you must remove and replace the Trademarks and will need to recompile the source code to create your own binaries. This does not affect your rights under any open source licence applicable to any of the components of Ubuntu. If you need us to approve, certify or provide modified versions for redistribution you will require a licence agreement from Canonical, for which you may be required to pay. For further information, please contact us (as set out below).</em>

Since I want to modify and create a new Ubuntu distro and maybe sell it, i would like to know this. 

**What you have tried**
I have been searching online but have not found any clear answer.

**Comment by PJ-Singh-001** [comment]
Cubic itself does not recompile anything.

This is what Cubic does:

1. "Unpacks" the original Live ISO
2. Presents you with a [Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) where you can make customizations (including compiling source code into binaries yourself, if you wish or need to)
3. "Repacks" your changes into a new bootable Live ISO

I am not an attorney, so I can not advise you on this matter.

[Here is a similar question](https://askubuntu.com/questions/1452639/how-can-i-legally-prove-that-i-have-recompiled-the-ubuntu-source) that you may find useful.
