### ISSUE TITLE
"About Cubic" dialog

### ISSUE THREAD

**Issue by danimesq** [PJ-Singh-001/Cubic#165]
It does still display "© 2015, 2020 PJ Singh" instead of "© 2015, 2023 PJ Singh"

**Comment by PJ-Singh-001** [comment]
Daniella,

I really appreciate your attention to detail!

My understanding of the copyright dates are that they indicate the 1st date that something was copyrighted.
If the thing changes significantly, it is necessary to copyright the newer / changed version as well.

Cubic was first created in 2015.
In 2020, I completely re-wrote the application.
Therefore the copyright reflects these dates.

I am not an attorney, so if you have other information, please let me know?

**Comment by danimesq** [comment]
I have no understanding about copyright laws, although all I know is my memories of software and sites that updated the year every year despite no groundbreaking changes; as a way to display the site/software is still being developed.

**Comment by PJ-Singh-001** [comment]
Ok. This is good info. Perhaps I will adopt this approach as well. (I'll just double check the recommended practice, first).

**Comment by PJ-Singh-001** [comment]
Based on [this accepted answer](https://stackoverflow.com/a/2391555) on StackOverflow:

> The date on the notice establishes how far back the claim is made. This means if you update the date, you are no longer claiming the copyright for the original date and that means if somebody has copied the work in the meantime and they claim its theirs on the ground that their publishing the copy was before your claim, then it will be difficult to establish who is the originator of the work.

**Comment by danimesq** [comment]
They mean updating/overwriting the original date, not about adding a sufix such as the current date after 😬

Personally I think that preserving the original date is what is crucial, not what comes after.
