### ISSUE TITLE
How to install Cubic on Debian?

### ISSUE THREAD

**Issue by ZGStuff** [PJ-Singh-001/Cubic#168]
**Describe the question**
So, I have a Debian-based WSL install. Ubuntu doesn't work, so yeah.
I want to use Cubic to create my own version of Ubuntu called Cubuntu, based off of the Cinnamon desktop environment.
Now, how do I get Cubic to run on Debian?

**What you have tried**

tried adding a PPA to Debian... failed
tried ubuntu WSL2 again... failed

**Expected behavior**

What I expected to happen:
be up and running with Cubic in a few minutes

**OS Information (please complete the following information):**
OS Name: Debian (via WSL2 and WSLg)
OS Version: version 11 (Bullseye)

**Cubic Information (please complete the following information):**
 - Cubic Version: Latest
 - ISO Customizing: ubuntu-22.04.2-desktop-amd64.iso
 - Download Link:  https://releases.ubuntu.com/jammy/ubuntu-22.04.2-desktop-amd64.iso

**Screenshots**

no screenshots sadly...

**Comment by PJ-Singh-001** [comment]
I'll see if I can figure out a workaround or document the steps, but it may take me some time.

In the mean time, take a look at [Package for Debian?](https://github.com/PJ-Singh-001/Cubic/issues/141).

**Comment by ZGStuff** [comment]
@PJ-Singh-001 
alright

**Comment by PJ-Singh-001** [comment]
1. Make sure you have `dpkg` version 1.21 or higher...

    (Special thanks to @343GuiltySpark-04 and @TheElectronWill for their research).

    Debian `bookworm` already includes `dpkg` version 1.21.20, so you can skip this step if you are running Debian `bookworm` or newer.

    However, if you are running Debian `bullseye`, you will need to install `dpkg` version 1.21.20 and its required (newer) dependencies as well.

    I temporarily used the `bookworm` repositories to make sure I got all of the necessary packages.

    _However, be careful with this hack, as this may break your system._

        cd /etc/apt
        cp sources.list sources.list.original
        sed -i "s|bullseye|bookworm|g" sources.list
        apt update

        apt install dpkg

        cp sources.list.original sources.list
        apt update

 2. Once you have `dpkg` version 1.21 or higher...

        apt-add-repository ppa:cubic-wizard/release
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 081525E2B4F1283B
        apt update
        apt install cubic

**Comment by PJ-Singh-001** [comment]
@ZGStuff,

Please let me know if this solution works for you?

**Comment by ZGStuff** [comment]
tbh
i'll just update my whole system to Bookworm
works better anyways
plus new dpkg

**Comment by matoken** [comment]
I tried it on debian bookworm amd64 environment.

`apt-add-repository` fails.

```
$ sudo apt-add-repository ppa:cubic-wizard/release
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/apt-add-repository", line 345, in main
    shortcut = handler(source, **shortcut_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
    return handler(shortcut, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 86, in __init__
    if self.lpppa.publish_debug_symbols:
       ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 126, in lpppa
    self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
                  ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 113, in lpteam
    self._lpteam = self.lp.people(self.teamname)
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'people'
```
This required `python3-launchpadlib` .

```
$ sudo apt install  python3-launchpadlib
```

And when I did apt-add-repository and apt update, I couldn't find the bookworm Release file.

```
$ sudo apt-add-repository ppa:cubic-wizard/release
$ sudo apt update
  :
  :
Ign:12 https://ppa.launchpadcontent.net/cubic-wizard/release/ubuntu bookworm InRelease
Err:13 https://ppa.launchpadcontent.net/cubic-wizard/release/ubuntu bookworm Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/cubic-wizard/release/ubuntu bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Looking `https://ppa.launchpadcontent.net/cubic-wizard/release/ubuntu/dists/` , it seems that there is no Debian's directory.
 
It looks like you need to create a `https://ppa.launchpadcontent.net/cubic-wizard/release/ubuntu/dists/bookworm/` or modify `/etc/apt/sources.list.d/cubic-wizard-ubuntu-release-bookworm.list` and change it to Ubuntu's codename.

**Comment by ZGStuff** [comment]
huh

**Comment by PJ-Singh-001** [comment]
@matoken,

When I had executed `apt-add-repository ppa:cubic-wizard/release`, the `/etc/apt/sources.list.d/cubic-wizard-ubuntu-release-bookworm.list` file automatically had `lunar` in it. (Lunar is the upcoming Ubuntu release).

I thought this was *odd*, but just assumed `apt-add-repository` automatically picked the most recent Ubuntu release when adding an Ubuntu PPA on Debian.

I won't be able to add the `dists/bookworm/` directory as you suggested, because this part is handled by Launchapd, and Launchpad only allows you to select currently supported or upcoming Ubuntu releases.

Therefore, instead of using `apt-add-repository`, a better approach would be:

    echo "deb https://ppa.launchpadcontent.net/cubic-wizard/release/ubuntu/ jammy main" | tee /etc/apt/sources.list.d/cubic-wizard-release.list
    apt update

(Jammy is a long term Ubuntu release that is supported until April 2027).
