### ISSUE TITLE
Ubuntu 23.04 Dev Release Unable to be edited

### ISSUE THREAD

**Issue by gold-is-eepy-now** [PJ-Singh-001/Cubic#177]
Ubuntu 23.04 cant be edited as it says ubiquity isnt installed

**Comment by PJ-Singh-001** [comment]
What do you mean by "dev" release?

Are you talking about the [daily builds](http://www.cdimage.ubuntu.com/daily-live/current)?

I do not experience this problem using the [lunar-desktop-amd64.iso](http://www.cdimage.ubuntu.com/daily-live/current/lunar-desktop-amd64.iso) from 2023-03-17 10:31.

Please provide more information, including:
- Cubic version?
- OS you are running Cubic in?
- When does Cubic fail in the process (i.e. which [page](https://github.com/PJ-Singh-001/Cubic/wiki))
- What were you trying to do when the failure happened?
- Log output of the failure (by running Cubic using `cubic --verbose`)

**Comment by PJ-Singh-001** [comment]
Is this the same issue as Issue #179, [ Error No root device specified when booting customized Ubuntu 23.04 daily](https://github.com/PJ-Singh-001/Cubic/issues/179)?

If so, please update to Cubic version 2023.03.79, test, and let me know it it resolved your issue?

(Also, please consider to the above bug report as an example of the kinds details you should _always_ include in any bug report for all software. It really helps the application developer get a fix out to you as fast as possible. :-) ).

**Comment by PJ-Singh-001** [comment]
I'll assume Cubic version 2023.03.79, which includes the fix for Issue #179, [ Error No root device specified when booting customized Ubuntu 23.04 daily](https://github.com/PJ-Singh-001/Cubic/issues/179), solved your problem.
