### ISSUE TITLE
How to install Wine on Ubuntu 22.04 and above?

### ISSUE THREAD

**Issue by xybytz** [PJ-Singh-001/Cubic#178]
i tried to install wine on a new version since my old one will have dropped support soon. therefore, I want to do this on 22.04. but as soon as I do apt install winehq-stable, it spits errors. I tried using the kinetic sources file and the jammy sources file. I also tried installing aptitude. Also did not work. to reproduce, download regular desktop image from ubuntu and then attempt to install wine. using ubuntu 22.04 as host machine on 2011 Lenovo thinkpad t420s

**Comment by PJ-Singh-001** [comment]
What errors is it "spitting" out?

**Comment by xybytz** [comment]
It gives dependency errors, such as wine-stable is needed/ Then when i try to instlal that it gives tons of dependency errors, that are unfixable.  i386 stuff. also tried it on 22.10, also didnt work. i think for 22.04 and up there is an issue

**Comment by xybytz** [comment]
Works on 18.04 though. it runs perfectly fine.

**Comment by PJ-Singh-001** [comment]
I'll check it out.
Usually dependency errors are not Cubic related, but I'll see if I can provide some insight.
Please give me some time.

**Comment by PJ-Singh-001** [comment]
I'll assume you are installing from the official Ubuntu reposotories instead of a PPA.
Did you add the `universe` repository?
Did you try to install `wine-stable` instead of `winehq-stable`? (See this answer for [E: Unable to locate package winehq-stable](https://askubuntu.com/questions/984844/e-unable-to-locate-package-winehq-stable)).

I had no issues with the following:

    apt-add-repository universe
    apt remove zsys # Optional
    apt install wine-stable

**Comment by xybytz** [comment]
I tried wine-stable, but not universe. will try that.

**Comment by xybytz** [comment]
That works on kinetic kudu. Pretty sure that works on Jammy too.. thanks!
