### ISSUE TITLE
UEFI-Boot with a BIOS-HOST-System

### ISSUE THREAD

**Issue by lmaudio** [PJ-Singh-001/Cubic#181]
Hello there!

Using Cubic on Linux Mint 21.1 Mate 64bit and have some questions about UEFi-Boot, like: https://answers.launchpad.net/cubic/+question/387566

Do i understand it right, that it's not possible to make a UEFI-bootable custom.iso with cubic, if i am on a pure BIOS-based host-machine WITHOUT UEfi, or it is possible to make it whith some commands and edits during remastering-process??

Is it also possible to edit an existing custom-rom made with cubic (but WITHOUT Uefi-files) to get it bootable with UEFI too. And without remastering again?

-> Made 1 great custom.iso and everything is right and stable, but UEFI-Files are missing, because i made and test it on old Bios-based machines.

Would be great to get it work with UEFI too.

Other way: if it´ s like i guess, is it maybe possible in the future that people with BIOS-based NON-Uefi hostmachines could make UEFI-boot-compatible custom.iso with cubic too?
Or is it not possible or too difficult to implement this option!??

**Comment by PJ-Singh-001** [comment]
Just so I understand your situation, please confirm?...

1. You have an older BIOS-only system
2. You run Cubic on this system
3. You want to generate a custom `*.iso` that boots on a UEFI-based system

The question you linked to, [Can't create bootable USB flash drive](https://answers.launchpad.net/cubic/+question/387566), is quite old. The way Cubic creates the ISO has changed since then, so I do not think the answer there applies anymore.

I'll have to go back and verify the code, but you should be able to create the custom ISO and install it on a BIOS _or_ UEFI system.

Have you tried to do this?

**Comment by lmaudio** [comment]
Hi! Thank's for answering!

Yes, i made a custom.iso with Cubic on an older Bios-only system and it's booting and i can install it - but on UEFI-systems it don't boots. When i look into the live-system-folder, than i noticed that the /boot folder is empty, no grub or EFI files and just an isolinux-folder that boots the image in Bios-only mode.

When i read the old link-question i thought maybe it belongs to the fact that my hostmachine is NOT Uefi-installed!?

Would be great to know if this is really possible now in newer cubic-versions to make a custom.iso on a bios-only host system that is bootable on both: Bios-only and UEFI-systems!

The other question was, if it's possible to modify the existing custom.iso and make it compatible with uefi-boot.
i just deleted the whole project folder and if there is a way to make this faster, it could be great - because the rest of the custom.iso is really nice and stable. a lot of work of weeks in it.

So if it don't belongs to cubic and you will say that it's really possible to create an uefi-compatible custom.rom on a bios-only system, i have to try and remaster it again. Maybe i did something wrong!?

Other way: if you say now that i need an uefi-based hostsystem to make compatible custom.iso, i have to search for an uefi-based machine.




Two last questions for the case i have to remaster with cubic my custom.rom again:

1. i have installed xorriso! is this recommend or better not to have on a host-system with cubic!??
2. If i drag n drop files in chroot to the custom-image with cubic, should i load the original files from an open window with admin-rights or is it ok just to put it from normal windows?

**Comment by PJ-Singh-001** [comment]
Please give me some time to get back to you.

**Comment by lmaudio** [comment]
Ok, got it! Don't know exactly why the first image made with cubic didn't works with UEFI, but i remastered everything fresh again in a new project and now i got some images that really works fine and stable - with UEFI or/and BIOS-Boot.
Great cubic. Thank's

**Comment by PJ-Singh-001** [comment]
Excellent!

I expected Cubic to generate images that work in both UEFI and legacy BIOS.
