### ISSUE TITLE
How do I customize the desktop background?

### ISSUE THREAD

**Issue by real-nickel** [PJ-Singh-001/Cubic#182]
I am looking for how to change the wallpapers loaded on the ubuntu. Can someone help?

I haven't tried it as I'm not sure what will happen.

 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 22.04 LTS

 - Cubic Version: 2023.03.79
 - ISO Customizing: ubuntu-22.04.2-desktop-amd64.iso
 - Download Link:  https://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-desktop-amd64.iso

**Comment by PJ-Singh-001** [comment]
Please see Issue #22,  [How to customize the wallpaper, icon theme, desktop theme, and Plymouth boot splash theme (in English & Japanese)?](https://github.com/PJ-Singh-001/Cubic/issues/22#issuecomment-1032011784)

_Tip: To search through questions that have already been answered, click on "[Closed](https://github.com/PJ-Singh-001/Cubic/issues?q=is%3Aissue+is%3Aclosed)" (next to "Open" on the [Issues tab](https://github.com/PJ-Singh-001/Cubic/issues) of the [Cubic Github page](https://github.com/PJ-Singh-001/Cubic)), type your search text in the "Filters" text entry, and press <kbd>Enter</kbd>._
