### ISSUE TITLE
How to boot into the Live environment for Ubuntu Server 20.04.5?

### ISSUE THREAD

**Issue by secretwpn** [PJ-Singh-001/Cubic#183]
Hi! Thanks for the excellent tool!

I have a question: if I try creating a customized ISO from `ubuntu-20.04.5-live-server-amd64.iso` (same with `18.04.6`, `22.04.2`),

Even going through all steps without adding any customizations: just next, next, next 

When I get to the Test step - Qemu boots into installer and I just can't figure how to get into live mode. 

I am pretty sure one of the first times I tried Cubic I did manage to create a live mode ISO from second attempt, thinking it could be Ubuntu version specific thing - whether it boots into live or installer, but now even trying this with all the ISOs I have used - they all result in running installer and not live mode. 

Is this a known thing? Am I missing something? 

Thanks in advance!

**Comment by PJ-Singh-001** [comment]
1. Use the up arrow to highlight the “Help” button.
2. Press <kbd>Enter</kbd> to open the "Help" drop down menu.
3. Select “Enter shell” and press <kbd>Enter</kbd>.

![image](https://user-images.githubusercontent.com/19394936/228390840-e1661644-2480-4fc3-9b4d-ff8b6ada3770.png)
