### ISSUE TITLE
Squashfs error after install from image

### ISSUE THREAD

**Issue by lmaudio** [PJ-Singh-001/Cubic#186]
I got a not really nice "SQUASHFS error: Unable to read data.cache entry block...." after i install my with cubic made image (custom image of Linux Mint 21.1 Mate 64bit) on a computer!

Booting a livesystem from pendrive and installing the system was going without errors!
The system i installed from livesystem/image i made with cubic is stable and nice.
All custom changes included.

BUT to stop this endless sqashfs-error-message at the end of the install-process the user has to turn off the machine by pushing the power button.

The error starts after the message to put off the installmedium. 

(Should i leave the pendrive in it!?)

I reproduced this error with 3 different images i made with cubic on 2 different computers.
Is there maybe a kernelparameter i should choose to prevent this bug!?

**Comment by PJ-Singh-001** [comment]
- What compression algorithm are you selecting in Cubic?
- What is the size of your installation media (pen drive)?
- What is the size of your `*.iso` file?
- How old is your installation media?
- Have you tried full formatting it (i.e. “zeroing it out”) before writing the ISO image?
- What tool are you using to write the ISO image to the installation media?
- Have you tried using a different installation media?

Have you seen this?…
https://askubuntu.com/questions/1236021/why-do-i-see-a-message-squashfs-errorunable-to-read-data-and-page-while-install#1236025

**Comment by lmaudio** [comment]
I used gzip amd zstd with same results.

the first pendrive was an old one of 16Gb. the image is 6 GB.

i used the USB STICK FORMATER and USB Image Writer Tool from Linux Mint inside.

but now i noticed that with a new USB 3.1 32GB pendrive everything is running fine!
So i think it was what you guess; an error with the pendrive not with cubic!

Our new release; https://qstudio64.tumblr.com/

Thank you for helping us!
