### ISSUE TITLE
Debian Bookworm

### ISSUE THREAD

**Issue by junocomp** [PJ-Singh-001/Cubic#187]
I've downloaded the latest bookworm iso and Cubic is not able to mount the iso. It says

`Unable to locate the compressed Linux File System`

**Comment by PJ-Singh-001** [comment]
Which version of Cubic are you using?
(Would have been nice if you shared the ISO download link, as requested in the bug report template).

**Comment by PJ-Singh-001** [comment]
I have not been able to recreate your issue.

If you continue to have a problem, please open a new issue, and include all required information.

Here are screenshots of Debian Bookworm working perfectly in Cubic.

As you can see, Cubic is able to successfully mount and [extract](https://github.com/PJ-Singh-001/Cubic/wiki/Extract-Page) the Debian Bookworm ISO, and you can customize it in Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

![Cubic Extract Page for Debian Bookworm](https://user-images.githubusercontent.com/19394936/229946985-64fbbeb6-8cf6-411e-85a7-a684f027a708.png)

![Cubic Terminal Page for Debian Bookworm](https://user-images.githubusercontent.com/19394936/229946994-680cafa3-4695-4a0b-9983-410f68d41807.png)
