### ISSUE TITLE
How to add a firewall rule when building an ISO?

### ISSUE THREAD

**Issue by jeffshead** [PJ-Singh-001/Cubic#188]
I am building an Ubuntu 22.04 Desktop ISO that will be used as a live CD. I would like to add UFW rules that allow traffic to port 22 (SSH) from only certain IP addresses. I get the following error if I run `ufw allow from 192.168.0.0/24 to any port 22`.

**Error:**
```
Skipping adding existing rule
WARN: initcaps
[Errno 2] iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Permission denied (you must be root)
```
I realize the rule(s) cannot be added by running that command but I wanted to demonstrate what I'm trying to achieve.

So how can I manually add firewall rules that will work, out of the box, when using the ISO in live mode?

I saw this [post ](https://github.com/PJ-Singh-001/Cubic/issues/17) but nothing I've tried works.

Has anyone been successful in doing what I'm attempting to do? If so, please share how you accomplished it.

**Comment by PJ-Singh-001** [comment]
@jeffshead,

Does this help?...

https://serverfault.com/questions/198398/ubuntu-how-to-add-an-iptables-rule-that-ufw-cant-create

> According to [this Ubuntu wiki page](https://wiki.ubuntu.com/UncomplicatedFirewall) (scroll down to "Advanced Functionality"), you can achieve what you want by putting your own iptables rules into the following files:
> 
>     /etc/ufw/before.rules
>     /etc/ufw/after.rules
> 
> The before file is evaluated before any ufw rules are applied; the after file is evaluated after. (There are also corresponding before6 and after6 rules files, for your ip6tables rules.)
> 
> These rules files are expected to be in iptables-restore-compatible syntax, presumably because ufw simply loads them using iptables-restore. Finally, note that you need to stop and restart ufw after you make any changes to the rules files.

**Comment by PJ-Singh-001** [comment]
Closing this issue with the [solution provided above](https://github.com/PJ-Singh-001/Cubic/issues/188#issuecomment-1495005774).
