### ISSUE TITLE
Unable to locate the squashfs file during customization of Ubuntu Server

### ISSUE THREAD

**Issue by FedeFofo** [PJ-Singh-001/Cubic#19]
**Describe the bug**

When customizing an Ubuntu Server Image, it looks (and fails to find) filesystem.squashfs

**To Reproduce**

1. Use Cubic to customize Ubuntu Server
2. Look at the log

**Expected behavior**

It should look for all the different .squashfs files, as noted in the launchpad bug report [#699265
](https://answers.launchpad.net/cubic/+question/699265)

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu MATE
 - OS Version Ubuntu MATE 21.10
 
**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.01.69
 - ISO Customizing: Ubuntu-Server 21.10 arm64
 - Download Link:  https://ubuntu.com/download/server/arm
 
**Cubic Log:**

 The below is from running `cubic -v`

    Cubic - Custom Ubuntu ISO Creator

      • Set application directory.............. /usr/share/cubic
      • Set application user home.............. /home/james
      • Set application cubic version.......... 2022.01-69-release~202201160230~ubun
                                                tu21.10.1
      • Set application kernel version......... 5.13.0-1009-raspi

      Setup pages

      • Setup.................................. boot copy page
      • Setup.................................. compression page
      • Setup.................................. delete page
      • Setup.................................. extract page
      • Setup.................................. finish page
      • Setup.................................. generate page
      • Setup.................................. migrate page
      • Setup.................................. options page
      • Setup.................................. packages page
      • Setup.................................. prepare page
      • Setup.................................. preseed copy page
      • Setup.................................. project page
      • Setup.................................. start page
      • Setup.................................. terminal copy page
      • Setup.................................. terminal page
      • Set terminal colors?................... Skip
      • Setup.................................. test 1 page
      • Setup.................................. test 2 page
      • Read lines from file................... /home/james/.config/cubic/visited_si
                                                tes.conf
      • Number of lines read................... 4
      • Set application visited sites.......... {'cubic_page_help', 'cubic_wiki',
                                                'cubic_website', 'cubic_donate'}

      Setup file choosers

      • Setup (ignore warnings)................ copy file chooser
      • Setup (ignore warnings)................ directory chooser
      • Setup (ignore warnings)................ iso image chooser

    Handle navigation from no page on open action

      • Interrupt previous thread.............. No thread

    Get the new page

      • Current page........................... no page
      • Action................................. open
      • New page............................... start page

    Navigate from no page to start page on open action
      • The thread id is....................... 281472978497872

      • Read lines from file................... /home/james/.config/cubic/projects.c
                                                onf
      • Number of lines read................... 1
      • Set application projects............... ['/home/james/James OS/Image']

      Transition pages

      • Show new page.......................... start page

      Clicked start page project directory open
      button

      Clicked directory chooser select button

      • The selected file path is.............. /home/james/James OS/Image

      Directory selected

      • Directory.............................. /home/james/James OS/Image

      Project directory changed

      • Set project directory.................. /home/james/James OS/Image
      • Check if directory is writable......... /home/james/James OS/Image
      • Directory is writable?................. True
      • Get file system type................... /home/james/James OS/Image
      • Execute synchronously.................. df --output=fstype
                                                "/home/james/James OS/Image"
      • The process id is...................... 190709
      • The file system type is................ ext4
      • Set project iso mount point............ /home/james/James OS/Image/source-
                                                disk
      • Set project custom root directory...... /home/james/James OS/Image/custom-
                                                root
      • Set project custom disk directory...... /home/james/James OS/Image/custom-
                                                disk
      • Set project configuration file path.... /home/james/James
                                                OS/Image/cubic.conf

      Load configuration

      • Set project cubic version.............. 2022.01-69-release~202201160230~ubun
                                                tu21.10.1
      • Load configuration..................... 2021 Layout
      • Set project create date................ 2022-01-20 20:28
      • Set original iso file name............. ubuntu-21.10-live-server-arm64.iso
      • Set original iso directory............. /home/james/Downloads
      • Set original iso volume id............. Ubuntu-Server 21.10 arm64
      • Set original iso release name.......... Impish Indri
      • Set custom iso version number.......... 2022.01.20
      • Set custom iso file name............... jamesos-beta-arm64.iso
      • Set custom iso directory............... /home/james/James OS/Image
      • Set custom iso volume id............... JamesOS
      • Set custom iso release name............ Beta
      • Set custom iso disk name............... JamesOS "Beta"
      • Set status is success copy............. False
      • Set status is success extract.......... False
      • Set options update os release.......... True
      • Set options boot configurations........ ['boot/grub/grub.cfg',
                                                'boot/grub/loopback.cfg',
                                                'isolinux/txt.cfg']
      • Clicked................................ Next

    Handle navigation from start page on next action

      • Interrupt previous thread.............. No thread

    Get the new page

      • Current page........................... start page
      • Action................................. next
      • New page............................... project page

    Navigate from start page to project page on next action

      • The thread id is....................... 281472988520784
      • Create all directories in the path..... /home/james/.config/cubic
      • Cannot create directories.............. The directory path already exists
      • Write to file.......................... /home/james/.config/cubic/projects.c
                                                onf

      Check if the mount point is mounted

      • The mount point is..................... /home/james/James OS/Image/source-
                                                disk
      • Is mounted?............................ True

      Check if the ISO image is mounted

      • The mount point is..................... /home/james/James OS/Image/source-
                                                disk
      • The ISO file path is................... /home/james/Downloads/ubuntu-21.10-l
                                                ive-server-arm64.iso
      • Execute synchronously.................. mount
      • The process id is...................... 190711
      • Is mounted?............................ True

      Get ISO image release notes URL

      • ISO image mount point.................. /home/james/James OS/Image/source-
                                                disk
      • Read file.............................. /home/james/James OS/Image/source-
                                                disk/.disk/release_notes_url
      • Error. File does not exist............. /home/james/James OS/Image/source-
                                                disk/.disk/release_notes_url

      Get ISO image release notes URL

      • ISO image mount point.................. /home/james/James OS/Image/custom-
                                                disk
      • Read file.............................. /home/james/James OS/Image/custom-
                                                disk/.disk/release_notes_url

      Initialize the status fields from the
      model

      • Set status is success copy............. False
      • Set status is success extract.......... False
      • Set status iso template................ Empty
      • Set status casper directory............ Empty
      • Set status squashfs file name.......... Empty
      • Set status iso checksum................ Empty
      • Set status iso checksum file name...... Empty

      Initialize the options fields from the
      model

      • Set options boot configurations........ ['boot/grub/grub.cfg',
                                                'boot/grub/loopback.cfg',
                                                'isolinux/txt.cfg']
      • Set options compression................ Empty

      Initialize the original fields from the
      model

      • Set original iso file name value....... ubuntu-21.10-live-server-arm64.iso
      • Set original iso directory value....... /home/james/Downloads
      • Set original iso volume id value....... Ubuntu-Server 21.10 arm64
      • Set original iso release name value.... Impish Indri
      • Is original iso version number
        valid?................................. True

      Check if the ISO image is mounted

      • The mount point is..................... /home/james/James OS/Image/source-
                                                disk
      • The ISO file path is................... /home/james/Downloads/ubuntu-21.10-l
                                                ive-server-arm64.iso
      • Execute synchronously.................. mount
      • The process id is...................... 190712
      • Is mounted?............................ True
      • Is original iso file name valid?....... True
      • Is original iso directory valid?....... True
      • Is original iso volume id valid?....... True
      • Is original iso release name valid?.... True
      • Is original iso disk name valid?....... True
      • Is original iso release notes url
        valid?................................. True
      • Is original options update os
        release valid?......................... True

      Initialize the custom fields from the
      model

      • Set custom iso version number value.... 2022.01.20
      • Set custom iso file name value......... jamesos-beta-arm64.iso
      • Set custom iso directory value......... /home/james/James OS/Image
      • Set custom iso volume id value......... JamesOS
      • Set custom iso release name value...... Beta
      • Set custom iso disk name value......... JamesOS "Beta"
      • Set custom options update os release
        value.................................. True
      • Is custom iso version number valid?.... True
      • Is custom iso file name valid?......... True
      • Check if directory is writable......... /home/james/James OS/Image
      • Directory is writable?................. True
      • Is custom iso directory valid?......... True
      • Is custom iso volume id valid?......... True
      • Is custom iso release name valid?...... True
      • Is custom iso disk name valid?......... True
      • Is custom iso release notes url
        valid?................................. True
      • Is custom options update os release
        valid?................................. True

      Save the generated ISO values from the
      model

      • Set generated iso version number....... 2022.01.20
      • Set generated iso file name............ jamesos-beta-arm64.iso
      • Set generated iso directory............ /home/james/James OS/Image
      • Set generated iso volume id............ JamesOS
      • Set generated iso release name......... Beta
      • Set generated iso disk name............ JamesOS "Beta"
      • Is page valid?......................... True
      • The generated ISO file path is......... /home/james/James OS/Image/jamesos-
                                                beta-arm64.iso
      • Does the custom ISO file exist?........ No
      • Enable testing?........................ No

      Transition pages

      • Hide old page.......................... start page
      • Show new page.......................... project page
      • Clicked................................ Next

    Handle navigation from project page on next action

      • Interrupt previous thread.............. No thread

    Get the new page

      • Current page........................... project page
      • Action................................. next
      • New page............................... extract page

    Navigate from project page to extract page on next action
      • The thread id is....................... 281472988520784

      • Set project modify date................ 2022-01-22 19:52
      • Set options update os release.......... True

      Save configuration

      • Save configuration..................... 2021 Layout

      Update the custom ISO release notes url

      • The custom ISO release notes URL is.... Empty
      • Create all directories in the path..... /home/james/James OS/Image/custom-
                                                disk/.disk
      • Cannot create directories.............. The directory path already exists
      • Write to file.......................... /home/james/James OS/Image/custom-
                                                disk/.disk/release_notes_url

      Transition pages

      • Hide old page.......................... project page
      • Show new page.......................... extract page
      • Delete existing files with pattern..... /home/james/James
                                                OS/Image/partition-[1-9].img
      • Delete file............................ /home/james/James
                                                OS/Image/partition-1.img
      • Execute synchronously.................. delete-path /home/james/James
                                                OS/Image/partition-1.img
      • The process id is...................... 190714
      • The result is.......................... None
      • The exit status, signal status is...... 0, None
      • Delete file............................ /home/james/James
                                                OS/Image/partition-2.img
      • Execute synchronously.................. delete-path /home/james/James
                                                OS/Image/partition-2.img
      • The process id is...................... 190718
      • The result is.......................... None
      • The exit status, signal status is...... 0, None

      Generate the ISO template

      • Get ISO report for..................... /home/james/Downloads/ubuntu-21.10-l
                                                ive-server-arm64.iso
      • Execute synchronously.................. xorriso -indev "/home/james/Download
                                                s/ubuntu-21.10-live-server-
                                                arm64.iso" -report_el_torito
                                                as_mkisofs
      • The process id is...................... 190722
      • The ISO report is...................... -V 'Ubuntu-Server 21.10 arm64'
                                                --modification-
                                                date='2021101314202800'
                                                -partition_cyl_align all
                                                -partition_offset 16
                                                -partition_hd_cyl 74
                                                -partition_sec_hd 32
                                                -append_partition 2 0xef --interval:
                                                local_fs:2401152d-2410623d::'/home/j
                                                ames/Downloads/ubuntu-21.10-live-
                                                server-arm64.iso'  -G --interval:loc
                                                al_fs:0s-15s:zero_mbrpt:'/home/james
                                                /Downloads/ubuntu-21.10-live-server-
                                                arm64.iso'  -iso_mbr_part_type 0xcd
                                                -c '/boot/boot.cat'  -e '--interval:
                                                appended_partition_2_start_600288s_s
                                                ize_9472d:all::'  -no-emul-boot
                                                -boot-load-size 9472
      • The interval path is................... -append_partition 2 0xef --interval:
                                                local_fs:2401152d-2410623d::'/home/j
                                                ames/Downloads/ubuntu-21.10-live-
                                                server-arm64.iso'
      • The interval is........................ 2401152d-2410623d
      • The start block is..................... 2401152
      • The block units are.................... d
      • The block size is...................... 512
      • The stop block is...................... 2410623
      • The block count is..................... 9472
      • Extract image from..................... /home/james/Downloads/ubuntu-21.10-l
                                                ive-server-arm64.iso
      • Extract image to....................... /home/james/James
                                                OS/Image/partition-1.img
      • Extract image blocks................... block size: 512, skip blocks:
                                                2401152, block count: 9472
      • Execute synchronously.................. dd if="/home/james/Downloads/ubuntu-
                                                21.10-live-server-arm64.iso"
                                                bs="512" skip="2401152" count="9472"
                                                of="/home/james/James
                                                OS/Image/partition-1.img"
      • The process id is...................... 190723
      • The result is.......................... 9472+0 records in  9472+0 records
                                                out  4849664 bytes (4.8 MB, 4.6 MiB)
                                                copied, 0.184432 s, 26.3 MB/s
      • The exit status, signal status is...... 0, None
      • The interval path is................... -append_partition 2 0xef --interval:
                                                local_fs:0d-9471d::'{boot_image_dire
                                                ctory}/partition-1.img'
      • The interval path is................... -G --interval:local_fs:0s-15s:zero_m
                                                brpt:'/home/james/Downloads/ubuntu-2
                                                1.10-live-server-arm64.iso'
      • The interval is........................ 0s-15s
      • The start block is..................... 0
      • The block units are.................... s
      • The block size is...................... 2048
      • The stop block is...................... 15
      • The block count is..................... 16
      • Extract image from..................... /home/james/Downloads/ubuntu-21.10-l
                                                ive-server-arm64.iso
      • Extract image to....................... /home/james/James
                                                OS/Image/partition-2.img
      • Extract image blocks................... block size: 2048, skip blocks: 0,
                                                block count: 16
      • Execute synchronously.................. dd if="/home/james/Downloads/ubuntu-
                                                21.10-live-server-arm64.iso"
                                                bs="2048" skip="0" count="16"
                                                of="/home/james/James
                                                OS/Image/partition-2.img"
      • The process id is...................... 190724
      • The result is.......................... 16+0 records in  16+0 records out
                                                32768 bytes (33 kB, 32 KiB) copied,
                                                0.00135885 s, 24.1 MB/s
      • The exit status, signal status is...... 0, None
      • The interval path is................... -G --interval:local_fs:0s-15s:zero_m
                                                brpt:'{boot_image_directory}/partiti
                                                on-2.img'
      • The interval path is................... -e '--interval:appended_partition_2_
                                                start_600288s_size_9472d:all::'
      • The interval path is................... -e '--
                                                interval:appended_partition_2:all::'
      • Set status iso template................ 789C8D90316E032110457B4E31DD56637BB1
                                                132B5CC037488B30CC6E90604180ADAC2DDF
                                                DDEC26B22852A49962FEFCC7FFE02774F76B
                                                70174FD29A47C730AA546CB161927A765239
                                                3B4EA09C6B85300C990AF4EFEDF2CB2C0638
                                                1EDA65265D05D873862A469A8C7C69C061F7
                                                4D0320DAA950BA2A275CD0CAC9218B9DC18F
                                                C3B1374274F77308455AAF4692C626D225A4
                                                F9B17D61B0DF583FD6DCA7BF4919FBB72C6E
                                                9482F4E714CB3F88FC9768F3EA5923CB3247
                                                AA81B561A8A1DB2E8C756CB42AF596A06B9E
                                                FFE94A4D5BC945FDC4DA87E11490FCC5E1E2
                                                66EB441794C16C6F04B536674FC4F08F01

      Find the compressed Linux file system

      • Find the directory for
        filesystem.squashfs in................. /home/james/James OS/Image/source-
                                                disk

**Comment by PJ-Singh-001** [comment]
Thanks for reporting this and providing the details. I’ll take a look, and if I have questions, I’ll let you know.

**Comment by FedeFofo** [comment]
Great! Thanks for the fast reply.

**Comment by PJ-Singh-001** [comment]
FedeFofo,

Would you please share the rest of the log after that last line...

      Find the compressed Linux file system

      • Find the directory for
        filesystem.squashfs in................. /home/james/James OS/Image/source-
                                                disk

**Comment by FedeFofo** [comment]
That is the end of the log, since there is no filesystem.squashfs, it just hangs at that point.

**Comment by PJ-Singh-001** [comment]
### Fix released

Fix released in Cubic version 2022.01.70.

### Cause

The link `ubuntu` in the ISO's root directory points to the ISO's root directory (i.e. `ubuntu -> .`). When this link was followed while searching for the squashfs file, it resulted in an infinite loop. This issue could potentially occur in other Ubuntu versions, including the desktop version, so it is not limited to the Ubuntu server ISO.

### Resolution

The solution was to not follow links while searching for the squashfs file.

### Note

Remember, you will not be able to customize Ubuntu-Server 21.10 arm64 if your host has a different architecture.

I assume the Ubuntu MATE 21.10 that Cubic is running on is also an arm64 architecture.

**Comment by PJ-Singh-001** [comment]
I am closing this issue with the above fix release.

Please test, and if Cubic still hangs on the [Extract page](https://github.com/PJ-Singh-001/Cubic/wiki/Extract-Page), feel free to reopen this issue.
