### ISSUE TITLE
Unable to locate the compressed Linux file system debian-10.10.0-amd64-DVD-1 

### ISSUE THREAD

**Issue by mohaddesehrezaee** [PJ-Singh-001/Cubic#193]
Hi there!
My name is Mohaddeseh, and I am a user of your project. 
I am experiencing an error when trying to customize Debian 10.10  and I would like to request some help resolving it. the image can not be even extracted. 
![Clipboard - April 11, 2023 3_11 PM (1)](https://user-images.githubusercontent.com/96718772/231152782-37f4e87b-7aa7-4204-bc36-b62d19b9da42.png)
![Clipboard - April 11, 2023 3_11 PM](https://user-images.githubusercontent.com/96718772/231152763-0571160c-bc40-4365-b271-dbb2f8799793.png)

Thank you for all of the hard work you have put into this project, and I appreciate any assistance you can provide

**Comment by PJ-Singh-001** [comment]
Mohaddeseh,

Please share the download link that you used for Debian 10.10?

**Comment by PJ-Singh-001** [comment]
Are you aware that Debian no longer supports Buster 10.10?
It's end of life date was [September 10, 2022](https://www.debian.org/News/2022/20220910).
Debiab Buster was superseded by Debian [Bullseye](https://wiki.debian.org/DebianBullseye) on 2021-08-14.buntu, Debian

---
Nevertheless, you can still customize older releases of Ubuntu, Debian, or other Distros using Cubic.
The only limitation is that repositories for software and security updates will not be available, so you will have to deal with that.

I found the download link: https://cdimage.debian.org/mirror/cdimage/archive/10.10.0/amd64/iso-dvd/.
If you had supplied this earlier, I could have helped you sooner.

You are customizing the wrong kind of ISO.
_**Cubic is used to customize Live ISOs.**_
_`debian-10.10.0-amd64-DVD-1.iso` is not a Live ISO._

Instead, download one of the [Live ISOs from here](https://cdimage.debian.org/mirror/cdimage/archive/10.1.0-live/amd64/iso-hybrid/), to customize in Cubic.

![image](https://user-images.githubusercontent.com/19394936/231609620-29833e10-fc67-448d-acaf-7a3e63de55c8.png)

**Comment by PJ-Singh-001** [comment]
One final note:

Based on your screenshot above, I can see that you had already extracted a Live ISO. Then you clicked <kbd>Back</kbd> to return to the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page), where you changed the Filename in the Original Disk section to `debian-10.10.0-amd64-DVD-1.iso`.

(This is something that _can_ be done in Cubic, but you should know _what_ you are doing and _why_).

I just wanted to point this out, in case you had done this inadvertently. If you want to customize a new ISO, you should delete your existing project using the delete button in the header bar, or you should create a new project.

(Also, if you had modified your project's `cubic.conf` file manually, you should not be doing that!)

**Comment by junocomp** [comment]
@PJ-Singh-001 I am having the same issue but with Bookworm RC1. 

Downloaded from here

https://cdimage.debian.org/cdimage/bookworm_di_rc1/amd64/iso-dvd/
