### ISSUE TITLE
How to execute a script on the first time login after the system install

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [PJ-Singh-001/Cubic#194]
**Describe the question**

A lot of customisation only works when the user had login in after the installation. So I am looking for a way in Linux that can execute a command when the user login for the first time.

**What you have tried**

I have tried creating a .desktop file in the /etc/skel/.config/autostart folder that links to a script and it deletes the .desktop file after it has finished running
Right now I can only create a folder on the Desktop with all the scripts in there and ask the user to manually run all of them, which is not very user-friendly :(

**Comment by gbardini** [comment]
What kind of customization are you trying to do?

**Comment by gbardini** [comment]
I have pre installed a few packages on the mint iso and the "custom" desktop i have put the .config folder on /etc/skel, so every user that is created have that "custom environment"

**Comment by PJ-Singh-001** [comment]
@ImGGAAVVIINN,

@gbardini has a good point. You may be trying to solve your problem with the incorrect solution. Describe what your scripts do. There may be another way of setting up new users, without a script.

**Comment by PJ-Singh-001** [comment]
@ImGGAAVVIINN,

You haven't described the original problem you are trying to solve (which may be solved without using a startup script).
Shall I close this issue?

**Comment by PJ-Singh-001** [comment]
Marking this question as invalid and closing, since no information was provided.
