### ISSUE TITLE
How to install PyCharm (LinuxMint)?

### ISSUE THREAD

**Issue by fornakter** [PJ-Singh-001/Cubic#198]
Im try to add pycharm to my version of Mint.
But i cant run pycharm.sh, theres no ./configure and other.
How can i add that app to Cubic?

**Comment by PJ-Singh-001** [comment]
You need to share:
- Which OS and version you are running Cubic on?
- Which version of Cubic you are using?
- The version of Linux Mint ISO and the download link?
- The exact steps you have taken? (Please use the code formatting so they are easy to copy).
- Download links for any software/`*.deb` packages, etc., as necessary?

**Comment by fornakter** [comment]
Mint 21.1
Cubic 2023.04.81
linuxmint-21.1-mate-64bit.iso
I just drag-and-drop a pycharm.tar.gz. Upload /copy it to Cubic. Extract... and thats all. I dont know what to do next, to add PyCharm to system.

**Comment by PJ-Singh-001** [comment]
What is the download link for PyCharm ?

(I already have a downloaded copy of linuxmint-21.1-mate-64bit.iso, so you don't have to provide that).

**Comment by FabioLolix** [comment]
https://www.jetbrains.com/edu-products/download/#section=pycharm-edu

https://download.jetbrains.com/python/pycharm-community-2023.1.tar.gz

Above there is the direct download, that tar.gz is pre-built, it is also available as snap

`But i cant run pycharm.sh, theres no ./configure and other.`

For building from source (https://github.com/JetBrains/intellij-community/tags pycharm tags ) you can look at Arch packaging https://github.com/archlinux/svntogit-community/blob/packages/pycharm-community-edition/trunk/PKGBUILD

**Comment by fornakter** [comment]
@FabioLolix can You explane me that step-by-step?
Im new in Linux world.
Thank You.

**Comment by PJ-Singh-001** [comment]
@FabioLolix,

Thank you for providing the link and information! :+1: 

@fornakter,

When asking a question, it is important to share as much information as possible.
It is also considered _polite_ to not make the person answering your question do extra work (such as searching for download links on the 'Net).
If you had included a download link for the software you are trying to install in your original question, you would have had an answer last week on the very same day.

---

 1. Launch Cubic and navigate to the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

 2. Execute the following in Cubic to download PyCharm.

        cd ~
        wget https://download.jetbrains.com/python/pycharm-community-2023.1.1.tar.gz

 3. Install PyCharm into the `/opt` directory.

        tar -zxvf ~/pycharm-community-*.tar.gz -C /opt
        mv /opt/pycharm-community-2023.1.1 /opt/pycharm-community
        ls -la /opt

4. Remove the downloaded file.

        rm ~/pycharm-community-*.tar.gz

 5. Create a PyCharm launcher.

    On your host machine open a text editor such as gedit or xed.

    Create a new file with the following contents.

        [Desktop Entry]
        Type=Application
        Terminal=false
        Exec=/opt/pycharm-community/bin/pycharm.sh
        Name=PyCharm
        Comment=PyCharm
        Icon=/opt/pycharm-community/bin/pycharm.svg

    Save the file as `pycharm.desktop`.

 6. Copy the launcher into Cubic.

    In Cubic, on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), execute the following.

        cd /usr/share/applications

    Then drag the `pycharm.desktop` file onto Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) to [copy the file](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Copy-Page) into the current directory.

 7. Set the permissions for the launcher.

        chmod u=rw,g=r,o=r /usr/share/applications/pycharm.desktop
        ls -la /usr/share/applications/pycharm.desktop

 8. Continue customizing your OS and generate the customized ISO.
