### ISSUE TITLE
Slackware

### ISSUE THREAD

**Issue by NathanYinYang** [PJ-Singh-001/Cubic#200]
I know it's bizzare, but can you add slackware support?

**Comment by PJ-Singh-001** [comment]
What is Slackware ?

**Comment by FabioLolix** [comment]
https://en.wikipedia.org/wiki/Slackware

**Comment by PJ-Singh-001** [comment]
Download links:
https://mirrors.slackware.com/slackware/slackware-iso/

**Comment by PJ-Singh-001** [comment]
@NathanYinYang, @FabioLolix,

Do you know if the ISO contains a `squashfs` compressed Linux file system?
I looked but I couldn't spot it (if it exists).

    .
    ├── ANNOUNCE.15.0
    ├── ChangeLog.txt
    ├── CHANGES_AND_HINTS.TXT
    ├── CHECKSUMS.md5
    ├── CHECKSUMS.md5.asc
    ├── COPYING
    ├── COPYING3
    ├── COPYRIGHT.TXT
    ├── CRYPTO_NOTICE.TXT
    ├── EFI
    │   └── BOOT
    ├── extra
    │   ├── aspell-word-lists
    │   ├── bash-completion
    │   ├── bittornado
    │   ├── brltty
    │   ├── CHECKSUMS.md5
    │   ├── CHECKSUMS.md5.asc
    │   ├── FILE_LIST
    │   ├── fltk
    │   ├── getty-ps
    │   ├── google-chrome
    │   ├── java -> source/java
    │   ├── MANIFEST.bz2
    │   ├── PACKAGES.TXT
    │   ├── php80
    │   ├── php81
    │   ├── README.TXT
    │   ├── rust-for-mozilla
    │   ├── sendmail
    │   ├── source
    │   ├── tigervnc
    │   ├── xf86-video-fbdev
    │   ├── xf86-video-nouveau-blacklist
    │   ├── xfractint
    │   └── xv
    ├── FILELIST.TXT
    ├── GPG-KEY
    ├── isolinux
    │   ├── boot.cat
    │   ├── efiboot.img
    │   ├── f2.txt
    │   ├── initrd.img
    │   ├── isolinux.bin
    │   ├── isolinux.cfg
    │   ├── iso.sort
    │   ├── message.txt
    │   ├── README_SPLIT.TXT
    │   ├── README.TXT
    │   ├── sbootmgr
    │   └── setpkg
    ├── kernels
    │   ├── huge.s
    │   ├── memtest
    │   ├── speakup.s
    │   └── VERSIONS.TXT
    ├── PACKAGES.TXT
    ├── pasture
    │   ├── apmd-3.2.2-x86_64-3.txt
    │   ├── apmd-3.2.2-x86_64-3.txz
    │   ├── apmd-3.2.2-x86_64-3.txz.asc
    │   ├── CHECKSUMS.md5
    │   ├── CHECKSUMS.md5.asc
    │   ├── FILE_LIST
    │   ├── MANIFEST.bz2
    │   ├── PACKAGES.TXT
    │   ├── php-5.6.40-x86_64-1.txt
    │   ├── php-5.6.40-x86_64-1.txz
    │   ├── php-5.6.40-x86_64-1.txz.asc
    │   └── source
    ├── patches
    │   ├── CHECKSUMS.md5
    │   ├── CHECKSUMS.md5.asc
    │   ├── FILE_LIST
    │   ├── MANIFEST.bz2
    │   └── PACKAGES.TXT
    ├── README_CRYPT.TXT
    ├── README.initrd
    ├── README_LVM.TXT
    ├── README_RAID.TXT
    ├── README.TXT
    ├── README_UEFI.TXT
    ├── RELEASE_NOTES
    ├── slackware64
    │   ├── a
    │   ├── ap
    │   ├── CHECKSUMS.md5
    │   ├── CHECKSUMS.md5.asc
    │   ├── d
    │   ├── e
    │   ├── f
    │   ├── FILE_LIST
    │   ├── k
    │   ├── kde
    │   ├── l
    │   ├── MANIFEST.bz2
    │   ├── n
    │   ├── PACKAGES.TXT -> ../PACKAGES.TXT
    │   ├── t
    │   ├── tcl
    │   ├── x
    │   ├── xap
    │   ├── xfce
    │   └── y
    ├── Slackware-HOWTO
    ├── SPEAK_INSTALL.TXT
    ├── SPEAKUP_DOCS.TXT
    ├── testing
    │   ├── CHECKSUMS.md5
    │   ├── CHECKSUMS.md5.asc
    │   ├── FILE_LIST
    │   ├── MANIFEST.bz2
    │   ├── packages
    │   ├── PACKAGES.TXT
    │   └── source
    ├── UPGRADE.TXT
    └── usb-and-pxe-installers
        ├── pxelinux.cfg_default
        ├── README_PXE.TXT
        ├── README_USB.TXT
        ├── usbboot.img
        └── usbimg2disk.sh

**Comment by NathanYinYang** [comment]
**Do you know if the ISO contains a `squashfs` compressed Linux file system? I looked but I couldn't spot it (if it exists).**
I'm pretty sure slackware uses SquashFS, but i don't know where it is located.
Sorry if I got this wrong.

**Comment by NathanYinYang** [comment]
Sorry I forgot about this, but during the graphical installer, the user decides which FS to format the drive with. I know this because Slackware is pain

**Comment by PJ-Singh-001** [comment]
I try to accommodate user requests to extend Cubic to work with other distributions.

Cubic unpacks the original ISO. It then locates and uncompresses the Squashfs file (which contains the Linux file system), and presents the user with a terminal environment where they can modify the files contained within the Squashfs file. ([See Wikipedia to learn more about Squashfs](https://en.wikipedia.org/wiki/SquashFS)).

Cubic expects the ISO's directory structure to be similar to Ubuntu/Debian. However, as long as the Squashfs file is present, I could modify Cubic to work with a different directory structure (although this in-itself would be a lot of work).

After reviewing the installation instructions in the `Slackware-HOWTO` document and the ISO file structure, it looks like Slackware is packaged very differently compared to Ubuntu or Debian.

Based on this research, I do not think Cubic can be adapted to work with Slackware.

However, I will keep this request in mind for future enhancements.
