### ISSUE TITLE
How to customize `gsettings`?

### ISSUE THREAD

**Issue by Mihot7** [PJ-Singh-001/Cubic#201]
Input: gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM
Output: (process:45): dconf-WARNING **: 16:59:28.316: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY

I wanted to make dock in the bottom automatic and unmake dock a panel and set a default wallpaper

**Expected behavior**
Set the dock to bottom

**OS Information (please complete the following information): Lenovo ideapad gaming 3 Amd ryzen 5 5600h 16gb ram 512 ssd GTX 1650**
 - OS/Distro Name: lubuntu
 - OS Version 22.04.2

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.04.81
 - ISO Customizing: ubuntu-23.04-desktop-amd64.iso
 - Download Link:  https://ubuntu.man.lodz.pl/ubuntu-releases/23.04/ubuntu-23.04-desktop-amd64.iso
 Sorry I'm new to linux and my English is very bad!

**Comment by PJ-Singh-001** [comment]
@Mihot7,

Welcome to Linux!

You can search through the [closed issues](https://github.com/PJ-Singh-001/Cubic/issues?q=is%3Aissue+is%3Aclosed) for tips and instructions.

Here are two questions that will help you. The `gsettings` keys and values will be different for Lubuntu than in the examples below, but you will need to add your configurations into a `*.gschema.override` file.

Issue #22: [How to customize the wallpaper, icon theme, desktop theme, and Plymouth boot splash theme (in English & Japanese)?](https://github.com/PJ-Singh-001/Cubic/issues/22#issuecomment-1032011784). (See the **Configure Defaults** section on how to set the `gsettings` values using a `*.gschema.override` file).

Issue #184: [How to customize Linux Mint Cinnamon wallpaper, icons, and theme?](https://github.com/PJ-Singh-001/Cubic/issues/184#issuecomment-1491084093). (See the **Configure Defaults** section on how to set the `gsettings` values using a `*.gschema.override` file).

*Update: Issue #184 no longer exists. See Issue #252 instead.*

Issue #252: [How to customize Linux Mint Cinnamon wallpaper, icons, and theme?](https://github.com/PJ-Singh-001/Cubic/issues/252#issue-1846104506). (See the **Configure Defaults** section on how to set the `gsettings` values using a `*.gschema.override` file).
