### ISSUE TITLE
How to copy `.sh` scripts into Cubic?

### ISSUE THREAD

**Issue by ghost** [PJ-Singh-001/Cubic#205]
How do i import .sh scripts into the terminal, i have a .sh script with all the apps i want to install and it would make it alot easier if i could.

Hope someone can help me.

Best regards,
Midas.

**Comment by PJ-Singh-001** [comment]
Take a look at the [Wiki](https://github.com/PJ-Singh-001/Cubic/wiki).

Specifically, check out the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) and the [Terminal Copy Page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Copy-Page).
(Also, you can select the "Help on this Page" option from the hamburger menu in Cubic).
