### ISSUE TITLE
How to export a Cubic project to another computer?

### ISSUE THREAD

**Issue by DeclanMorrison** [PJ-Singh-001/Cubic#206]
**Describe the question**

Wondering if Cubic supports "exporting" a project, so I can transfer it from one device to another without needing to go through each step and redo all the customizations. 

**What you have tried**

I've tried copying the entire project folder, but run into some permissions issues when copying some of the resources contained therein. After attempting to use the copied project folder in Cubic to load the project, it says that it doesn't recognize the folder as a Cubic project (the exact wording escapes me and I've since recreated the project).

**Expected behavior**

No expectations if this isn't currently a supported feature (I recognize that transferring a Cubic project is likely a niche issue).

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 20.04.6
 - 
**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.04.81
 - ISO Customizing: ubuntu-20.04.6-desktop-amd64.iso

**Comment by PJ-Singh-001** [comment]
Since you are customizing a Linux file system, file permissions are extremely critical.

Cubic projects can be moved and/or archived, and Cubic was explicitly designed to be able to continue customizing a project that had been moved.

So I can provide an answer for your specific situation, are you trying to move your existing Cubic project to...
1. a different folder?
2. a different partition?
3. a different computer?

**Comment by DeclanMorrison** [comment]
I'm trying to move the project to a new computer. Thanks!

**Comment by PJ-Singh-001** [comment]
Here are the steps to archive your Cubic project, transfer it to another computer, and extract it.
I've included steps to verify and compare the project before and after the move, but this is optional.

## Archive Cubic Project

Perform these steps on your 1st computer.

 1. Change to the parent directory of your Cubic project.

        cd /parent/directory

 2. Optionally, to save space and time, remove the `*.iso` and `*.md5` files, if they exist. (These can always be regenerated).

        rm MyCubicProject/*.iso
        rm MyCubicProject/*.md5

 3. List all files and ownerships for the original Cubic project.
    This is optional for the verification step below.

        cd MyCubicProject
        sudo tree -pugfia ./ > ../01_project.txt
        cd -

 4. Archive (`tar`) the Cubic project directory, preserving file permissions.

        sudo tar -cvpzf my_cubic_project.tar.gz MyCubicProject

 5. Change the ownership of the archive file.

        sudo chown `whoami`:`whoami` ~/my_cubic_project.tar.gz

## Copy Archived Cubic Project to Another Computer

Perform these steps on your 2nd computer.

 1. Make sure the parent directory exists.
    This directory can be different from the directory on the 1st computer.

        mkdir --parents /parent/directory

 2. Change to the parent directory of your Cubic project.

        cd /parent/directory

 3. Copy the archived project.

        rcp user@computer_01.local:"/parent/directory/my_cubic_project.tar.gz" ./

 4. Copy the verification file.
    This is optional for the verification step below.

        rcp user@computer_01.local:"/parent/directory/01_project.txt" ./


## Restore Cubic Project

Perform these steps on your 2nd computer.

 1. Change to the parent directory of your Cubic project folder.

        cd /parent/directory

 2. Delete the original Cubic project (if it exists).

        sudo rm -rf MyCubicProject

 3. Extract the archived Cubic project directory.

        sudo tar -zxvf ~/my_cubic_project.tar.gz

    (Note: You can change the Cubic project directory name, if you want).

 4. List all files and ownerships for the extracted Cubic project.
    This is optional for the verification step below.

        cd MyCubicProject
        sudo tree -pugfia ./ > ../02_project.txt
        cd -

## Verify Restored Cubic Project

This verification step is optional.
Perform these steps on your 2nd computer.

 1. Check if files or ownerships have changed.
    There should be no differences†.

        diff 01_project.txt 02_project.txt

    † This assumes the user ids on both systems are the same. If the user ids are different, just make the user ids the same in both files before doing the comparison. For example `sed -i "s|user_01|user_02|g" 01_project.txt` where `user_01` is the user id from the 1st computer, and `user_02` is the user id from the 2nd computer.

## Test Restored Cubic Project

Perform these steps on your 2nd computer.

 1. Start Cubic.
 2. Open the restored project.
 3. Generate the customized `*.iso` file.
 4. Click the <kbd>Test</kbd> button to [test the project](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page).
 6. Exit Cubic.

**Comment by PJ-Singh-001** [comment]
If you have issues with the above steps, feel free to reopen this issue.
