### ISSUE TITLE
The Live Environment runs out of disk space after customizing with too much "stuff".

### ISSUE THREAD

**Issue by MacroHard-Winux** [PJ-Singh-001/Cubic#207]
**Describe the question**

I think I have added too many themes/programmes/features to my distro, and now when I boot up the live environment, there are only a few megabytes left on the live environment. And this leads to the ubiquity installer crashing halfway through installation or straight up not starting

**What you have tried**

I don't know what can I do in this situation :(

**Comment by PJ-Singh-001** [comment]
I need more information...

- Are you talking about disk space or memory?
- How much disk space (or memory) do you have available before you customize your ISO?
- How much disk space (or memory) do you have available after you customize your ISO?
- Are you copying the `*.iso` to a USB stick?
- What is the size of the USB stick?
- Are you talking about the [<kbd>Test</kbd> button in Cubic](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page)?
- Which ISO are you customizing (with download URL)?
- What is the OS you are running Cubic in?
- Is this OS installed on hardware, or is it a virtual machine?
- How much memory and disk space does your computer or virtual machine have?

_Side Note: A "Distro" includes all of the back end repositories / servers / PPAs / unique packages / binaries / branding / team members / etc. that support the OS. If you are just customizing the ISO, it is still just a "customized" version of the original "Distro"._

**Comment by MacroHard-Winux** [comment]
Are you talking about disk space or memory?
Disk space, shown in the file manager when in the live environment

How much disk space (or memory) is available before customising your ISO?
1GB

How much disk space (or memory) is available after customising your ISO?
584.2MB

Are you copying the *.iso to a USB stick?
I am using Ventory to boot from the USB

What is the size of the USB stick?
16GB

Are you talking about the [Test button in Cubic](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Test-Page)?
No

Which ISO are you customizing (with download URL)?
https://www.linuxmint.com/edition.php?id=292

What is the OS you are running Cubic in?
Ubuntu 22.04 LTS

Is this OS installed on the hardware, or is it a virtual machine?
On hardware

How much memory and disk space does your computer or virtual machine have?
8GB Ram, 256GB SSD

**Comment by PJ-Singh-001** [comment]
The amount of disk space remaining on your USB doesn't matter for the installer.

The Live Environment uses a RAM Disk. Essentially, a portion of your 8GB RAM is being used as a virtual disk. So you need enough memory to store and run your customized Linux file system.

> A live CD (also live DVD, live disc, or live operating system) is a complete bootable computer installation including operating system which runs directly from a CD-ROM or similar storage device into a computer's memory ([Wikipedia](https://en.wikipedia.org/wiki/Live_CD))

> A RAM drive (also called a RAM disk) is a block of random-access memory (primary storage or volatile memory) that a computer's software is treating as if the memory were a disk drive (secondary storage). ([Wikipedia](https://en.wikipedia.org/wiki/RAM_drive))

I suspect what is happening is that your customizations are so much, that after you've loaded your live OS, there isn't enough memory left to run the installer.

On [Cubic's Generate page](https://github.com/PJ-Singh-001/Cubic/wiki/Generate-Page), the "customized Linux filesystem size" shown will give you an idea of the amount of of RAM your system will require when booting into the Live environment. The running OS, services, and any programs that you run in the Live Environment (such as the Installer) will require additional RAM to run.

![image](https://user-images.githubusercontent.com/19394936/236628579-f1ef02a7-c2a6-49e7-9f9c-a7c729b6d82f.png)


To address your issue, you can try to reduce the size of your ISO...

 1. Clean the downloaded packages cache.

    In your case, this may be a significant amount of files.

        apt -f install
        apt --yes autoremove
        apt --yes autoclean
        apt --yes clean
        
    (See the [`apt-get` man page](https://manpages.ubuntu.com/manpages/kinetic/en/man8/apt-get.8.html) for explanations of these options.)

 2. Clean up additional files you have downloaded while you were customizing your OS.

        # This folder shouldn't exist.
        rm -rf /home/root

        # Clean up /root.
        cd ~
        ls -la
        rm -rf ~/.cache ~/.cargo ~/.config ~/.local ~/.wget-hsts ~/.launchpadlib ~/.bash_history
        rm -rf ~/<any other folders you've added to /root while customizing>
        ls -la

        # Clean up /tmp
        rm -rf /tmp/*

        # Clear your bash history
        history -c

 3. Remove the "pool" files. This is the local repository of `*.deb` packages that come with the Live ISO (to allow users to install packages directly from the ISO without an Internet connection). You've already installed the packages you wanted, so you don't need these. Also, you've already updated your OS, so these are probably outdated anyway.

    Open a terminal on your host computer (where you run Cubic), and execute the following command to delete all of the "pool" files. Cubic does not have to be running when you do this, but make sure you do this *before* you [generate](https://github.com/PJ-Singh-001/Cubic/wiki/Generate-Page) your customized ISO.

        rm -rf <your Cubic project>/custom-disk/pool/*

 4. Remove some packages or files you could live without in your customized OS.
    I've noticed that wallpapers contribute a significant amount to the final ISO size. You may want to consider including fewer wallpapers if you have added too many.

**Comment by PJ-Singh-001** [comment]
If you have a partition on your 256GB SSD that you will _not_ be formatting during installation, you _may_ be able to create a swap file in that partition, allowing the Live Environment to cache RAM to the swap file.

I have no idea if this will work, since I have never tried it. You may need to do additional research on this approach.

Take the following steps in the Live Environment (after booting your customized Live ISO)...

 1. Mount the partition you will _not_ be formatting during installation.
    You can use the Disks utility to do this.
 2. Open a terminal.
 3. Create a swap file on the mounted partition.

        cd <mounted partition>
        sudo fallocate -l 8G <mounted partition>/swapfile
        sudo chmod 600 <mounted partition>/swapfile
        ls -lh <mounted partition>/swapfile
        sudo mkswap <mounted partition>/swapfile
        sudo swapon <mounted partition>/swapfile
        sudo swapon --show

I have no idea if this will work. If it works, the Live Environment and Installer may be extremely slow and sluggish, since most of the required RAM will be cached to the swap file.

Even if you try this, you should still [follow the recommended steps above](https://github.com/PJ-Singh-001/Cubic/issues/207#issuecomment-1537148721), to make your ISO a little smaller.
