### ISSUE TITLE
how to create auto-install .iso for Ubuntu 22.04?

### ISSUE THREAD

**Issue by Luke-Jaeger** [PJ-Singh-001/Cubic#210]
**Cubic is awesome, thank you!!**
However I can't figure out how to make a working auto-install .iso for Ubuntu server 22.04

I've tried setting up the autoinstall options based on [this article](https://www.pugetsystems.com/labs/hpc/ubuntu-22-04-server-autoinstall-iso/) among others ...
I can burn the resulting .iso file to a flash drive and boot from it, but I can't get the installer to run automatically. It boots into the usual interactive installer no matter what I do to the grub.cfg file.

I know I'm editing the right grub.cfg file because I see the changes I made to menu titles and timeout period.

**Cubic host computer**
 - Dell Optiplex 7010 running Ubuntu Desktop 22.04
 - Editing .iso files with Cubic and burning them with Startup Disk Creator

**Cubic Information (please complete the following information):**
 - Cubic Version: `2023.04.81`
 - ISO Customizing: `ubuntu-22.04.2-live-server-amd64.iso`
 - Download Link:  [ubuntu server 22.04](https://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-live-server-amd64.iso?_ga=2.4198003.1160770961.1683749514-1024164191.1683210752)

**Comment by PJ-Singh-001** [comment]
You should be able to use cloud-init with autoinstall.

See this answer for detailed steps: https://github.com/PJ-Singh-001/Cubic/issues/101#issuecomment-1336728758
