### ISSUE TITLE
Debian Live iso customization 

### ISSUE THREAD

**Issue by WhatTheKernel** [PJ-Singh-001/Cubic#215]
Hello,
I'm customizing the debian live ISO without desktop enviroment.
how do i remove the image in the background that shows when it boots,
change the boot name,
and remove the legal information?
Thanks!

**Comment by PJ-Singh-001** [comment]
Does Debian use Plymouth?
If so, this should help: [How to customize the Boot Splash Screen (Plymouth)](https://github.com/PJ-Singh-001/Cubic/issues/5#issuecomment-1001224949)

Regarding the legal information, this is a very large task, and I am sure you need to consider the requirements of each licenses that you remove. Many, such as GPL, require you to include the original license and attribution in any redistributed or derived software. Licenses are going to be all over the place in the Linux distribution, so you will need to handle each situation individually. You should consult an attorney if you plan on redistributing your work with removed or modified licenses.

**Comment by WhatTheKernel** [comment]
No I mean when it boots, i don't want the legal stuff cluttering the screen

**Comment by PJ-Singh-001** [comment]
Share a picture of what you mean, and I may be able to suggest an approach.

Also, did the [Plymouth link](https://github.com/PJ-Singh-001/Cubic/issues/5#issuecomment-1001224949) above solve your 1st problem?
