### ISSUE TITLE
How to customize the wallpaper, icon theme, desktop theme, and Plymouth boot splash theme (in English & Japanese)?

### ISSUE THREAD

**Issue by 810drawing** [PJ-Singh-001/Cubic#22]
**Describe the question**

Hello.
I want to change the wallpaper, icon, theme and splash screen that appear when I start with iso.

**What you have tried**

I tried the contents of this article and video to replace the wallpaper.
https://qiita.com/basictomonokai/items/a3d1bea33fe150c3ce53
https://www.youtube.com/watch?v=T_5EpbzWYgw

**Expected behavior**

The replacement was not reflected and the wallpaper changed to plain blue.

**OS Information (please complete the following information):**
 - OS/Distro Name: [Ubuntu]
 - OS Version [Ubuntu 20.04]

**Cubic Information (please complete the following information):**
 - Cubic Version: [Newest Version]
 - ISO Customizing: [e.g. ubuntu-20.04-desktop-amd64.iso]
 - Download Link:  The download link for the ISO you are customizing

**Screenshots**

**Comment by PJ-Singh-001** [comment]
It will take me a few days to respond to your question.

**Comment by brianhenson** [comment]
I did it by creating override files. If you need more info I can provide it but I set all my settings such as lockdowns, default backgrounds etc with it

**Comment by PJ-Singh-001** [comment]
I used an online translation tool. I hope the translation from English to Japanese is reasonable.

私はオンライン翻訳ツールを使用しました。英語から日本語への翻訳が妥当だといいですね。

## Install Wallpapers 壁紙をインストールする

 1. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), create a directory (or directories) for your custom wallpapers.

    キュービックの[ターミナル](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)で、カスタム壁紙のディレクトリ(またはディレクトリ)を作成します。

        mkdir /usr/share/backgrounds/my-backgrounds

    (You can replace the `my-backgrounds` directory name with whatever name you like).

    (`my-backgrounds` ディレクトリ名は、好きな名前に置き換えることができます)。

 2. Change directory to the new wallpapers directory.

    ディレクトリを新しい壁紙ディレクトリに変更します。

        cd /usr/share/backgrounds/my-backgrounds

 3. On your host computer, open a File browser (such as Nautilus), and drag your wallpaper(s) onto on Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

    ホストコンピュータで、ファイルブラウザ(ノーチラスなど)を開き、立方体の[ターミナルページ](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)に壁紙をドラッグします。

    Click the Copy button to copy the file(s) into the current directory (`/usr/share/backgrounds/my-backgrounds`).

    [コピー] ボタンをクリックして、ファイルを現在のディレクトリ (`/usr/share/backgrounds/my-backgrounds`) にコピーします。

 4. On your host computer, open a new text document using Gedit or other text editor, and add the following contents.

    ホスト コンピュータで、Gedit または他のテキスト エディタを使用して新しいテキスト ドキュメントを開き、次の内容を追加します。

        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">
        <wallpapers>
          <wallpaper>
            <name>My First Wallpaper</name>
            <filename>/usr/share/backgrounds/my-backgrounds/my_first_wallpaper.jpg</filename>
            <options>zoom</options>
            <pcolor>#ffffff</pcolor>
            <scolor>#000000</scolor>
            <shade_type>solid</shade_type>
          </wallpaper>
          <wallpaper>
            <name>My Second Wallpaper</name>
            <filename>/usr/share/backgrounds/my-backgrounds/my_second_wallpaper.jpg</filename>
            <options>zoom</options>
            <pcolor>#ffffff</pcolor>
            <scolor>#000000</scolor>
            <shade_type>solid</shade_type>
          </wallpaper>
        </wallpapers>

    - You can replace "My First Wallpaper" and "My Second Wallpaper" with whatever names you like.

      "My First Wallpaper" と "My Second Wallpaper" は、好きな名前に置き換えることができます。

    - Use the same file path from Step 1 above, for example `/usr/share/backgrounds/my-backgrounds`.

      上記の手順 1 のファイル パスと同じファイル パスを使用します (例: `/usr/share/backgrounds/my-backgrounds`)。

    - Ensure the wallpaper names ("my_first_wallpaper.jpg", "my_second_wallpaper.jpg"., etc.) match the actual file names of your wallpapers.

      壁紙名(「my_first_wallpaper.jpg」「my_second_wallpaper.jpg」など)が、壁紙の実際のファイル名と一致していることを確認します。

    - You can add other wallpapers by including additional `<wallpaper>...</wallpaper>` tags.

      あなたは、追加の`<wallpaper>...</wallpaper>`タグを含めることによって、他の壁紙を追加することができます。

 5. Save this file. For example, you may name it `my-wallpapers.xml`.

    このファイルを保存します。たとえば、`my-wallpapers.xml` という名前を付けます。

 6. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), change directory to the background properties directory.

    立方体の[ターミナル](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)で、ディレクトリを背景プロパティディレクトリに変更します。

        cd /usr/share/gnome-background-properties

 7. Open a File browser (such as Nautilus), and drag your background properties file (`my-wallpapers.xml`) onto on Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

    ファイルブラウザ(ノーチラスなど)を開き、立方体の[ターミナルページ](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)上にバックグラウンドプロパティファイル(`my-wallpapers.xml`)をドラッグします。

    Click the Copy button to copy the file into the current directory (`/usr/share/gnome-background-properties`).

    [コピー] ボタンをクリックして、ファイルを現在のディレクトリ (`/usr/share/gnome-background-properties`) にコピーします。

## Install Icons アイコンのインストール

 1. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), install your icon theme, such as [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme).

    キュービックの[ターミナルページ](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)で、アイコンのテーマを[パピルス](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)などのテーマにインストールします。

        add-apt-repository ppa:papirus/papirus
        apt-get update
        apt-get install papirus-icon-theme

 2. Verify that your icons were installed to the correct location.

    アイコンが正しい場所にインストールされていることを確認します。

        ls -1 /usr/share/icons

        Papirus
        Papirus-Dark
        Papirus-Light

## Install Theme テーマのインストール

 1. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), install your desktop theme, such as [Materia Theme](https://github.com/nana-4/materia-theme).

    キュービックの[ターミナルページ](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)で、[マテリアテーマ](https://github.com/nana-4/materia-theme)などのデスクトップテーマをインストールします。

        apt-add-repository universe
        apt install materia-gtk-theme

 2. Verify that your theme was installed to the correct location.

    テーマが正しい場所にインストールされていることを確認します。

        ls -1 /usr/share/themes/

        Materia
        Materia-compact
        Materia-dark
        Materia-dark-compact
        Materia-light
        Materia-light-compact

## Configure Defaults デフォルトの構成

 1. On your host computer, open a new text document using Gedit or other text editor, and add the following contents.

    ホスト コンピュータで、Gedit または他のテキスト エディタを使用して新しいテキスト ドキュメントを開き、次の内容を追加します。

        # Default Wallpaper
        [org.gnome.desktop.background]
        picture-uri = 'file:///usr/share/backgrounds/my-backgrounds/my_second_wallpaper.jpg'

        # Default Icon Theme
        [org.gnome.desktop.interface:ubuntu]
        icon-theme = "Papirus"

        # Default Desktop Theme
        [org.gnome.desktop.interface:ubuntu]
        gtk-theme = "Materia"

 2. Save this file as `90_ubuntu-settings.gschema.override`.

    このファイルを `90_ubuntu-settings.gschema.override` として保存します。

 3. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), change directory to the schemas directory.

    キュービックの[ターミナル](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)で、ディレクトリをスキーマディレクトリに変更します。

        cd /usr/share/glib-2.0/schemas

 4. Open a File browser (such as Nautilus), and drag your schema file (`90_ubuntu-settings.gschema.override`) onto on Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

    ファイルブラウザ(ノーチラスなど)を開き、立方体の[ターミナルページ](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)上にスキーマファイル(`90_ubuntu-settings.gschema.override`)をドラッグします。

    Click the Copy button to copy the file into the current directory (`/usr/share/glib-2.0/schemas`).

    [コピー]ボタンをクリックして、ファイルを現在のディレクトリ(`/usr/share/glib-2.0/schemas`)にコピーします。

 5. On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), compile the schemas.

    立方体の[ターミナルページ](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)で、スキーマをコンパイルします。

        glib-compile-schemas /usr/share/glib-2.0/schemas

## Gnome Shell Theme ノームシェルテーマ

 1. To use your desktop theme as the Gnome shell theme, please see [How to set a custom Gnome-shell theme?](https://github.com/PJ-Singh-001/Cubic/issues/6#issuecomment-1006339208).

    デスクトップテーマをGnomeシェルテーマとして使用するには、[カスタムのGnomeシェルテーマを設定するには?](https://github.com/PJ-Singh-001/Cubic/issues/6#issuecomment-1006339208)を参照してください。

## Splash Screen スプラッシュスクリーン

 1. To update your Plymouth boot splash screen, please see [How to customize the Plymouth Splash Screen?](https://github.com/PJ-Singh-001/Cubic/issues/5#issuecomment-1001224949).

    プリマスブートスプラッシュ画面を更新するには、[プリマススプラッシュ画面をカスタマイズする方法?](https://github.com/PJ-Singh-001/Cubic/issues/5#issuecomment-1001224949)を参照してください。

**Comment by 810drawing** [comment]
Thank you very much for the great answer.
I will try it later.

**Comment by PJ-Singh-001** [comment]
> I have tried this on linuxmint 21.1 cinnamon 64bit. Didn't work.
> Themes are installed but not set when the system boots

You need to use the correct file paths, gsettings schemas, key, and values for Mint. I don’t know what those are, so please research them.

**Comment by ImGGAAVVIINN** [comment]
Do you mean in the Configure Defaults part, that I shoudent use 90_ubuntu-settings.gschema.override?

**Comment by PJ-Singh-001** [comment]
@ImGGAAVVIINN,

I think I found the issue you are having.
I'll write up a solution in the next couple of days.

**Comment by ImGGAAVVIINN** [comment]
I found where the file is :D
custom-root/usr/share/glib-2.0/schemas/mint-artwork.gschema.override

**Comment by PJ-Singh-001** [comment]
> I found where the file is! custom-root/usr/share/glib-2.0/schemas/mint-artwork.gschema.override
> 
> Now I can change the theme in Linux Mint :D

I do not recommend you modify `mint-artwork.gschema.override` directly, because this file may be reverted by a future update or upgrade, and your customizations will be lost.

Refer to Issue #184, [How to customize Linux Mint Cinnamon wallpaper, icons, and theme?](https://github.com/PJ-Singh-001/Cubic/issues/184) for a better solution.
