### ISSUE TITLE
Installed packages via Cubic are not registered in final installed OS - Ubuntu 22.04

### ISSUE THREAD

**Issue by RipperSK** [PJ-Singh-001/Cubic#225]
**Describe the bug**

In the final installed OS the packages that are added via Cubic in terminal are not registered to dpkg. This means that the binary files and libraries are in fact present on the filesystem, however if I run `dpkg -l | grep <package>` it yields no results. Using `mlocate` for example throws error message: `unknown group: plocate` - which suggests binary is present however group under which command runs is not.

**To Reproduce**

In a step where Cubic opens a terminal for user to install and adjust the OS that is going to be installed I've installed lxqt desktop environment
I've used ISO ubuntu 22.04.2 for Ubuntu server
I've selected LZ compression and made no other adjustments
I've finished the ISO build via Cubic
I've installed the OS in proxmox virtualisation environment (it does not matter where you install it on)
I've run the command: 
```
root@u22-tst:~# dpkg -l|grep lxqt|wc -l
0
```
I've run the commands:
```
root@u22-tst:~# which lxqt-about
/usr/bin/lxqt-about
root@u22-tst:~# locate lxqt|wc -l
2304
```
To verify that lxqt is installed - it is - however dpkg does not register that.

**Expected behavior**

It is expected that once squashfs is unsquashed and you are chrooted into it - the contents and the package database will be transferred into a working OS during installation. This is not the case.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: 22.04

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.05-83-release~202305230205~ubuntu22.04.1 all 
 - ISO Customizing: ubuntu-22.04.2-live-server-amd64.iso
 - Download Link:  https://releases.ubuntu.com/22.04.2/ubuntu-22.04.2-live-server-amd64.iso

**Cubic Log:**
```
Cubic - Custom Ubuntu ISO Creator                                               

  \u2022 Set application directory.............. /usr/share/cubic                    
  \u2022 Set application user home.............. /home/tfs-admin                     
  \u2022 Execute synchronously.................. dpkg-query                          
                                            --admindir="/var/lib/dpkg" --show   
                                            --showformat="${Version} " "cubic"  
  \u2022 The process id is...................... 34013                               
  \u2022 Set application cubic version.......... 2023.05-83-                         
                                            release~202305230205~ubuntu22.04.1  
  \u2022 Set application kernel version......... 5.15.0-73-generic                   

  Setup pages                              

  \u2022 Setup.................................. boot copy page                      
  \u2022 Setup.................................. compression page                    
  \u2022 Setup.................................. delete page                         
  \u2022 Setup.................................. extract page                        
  \u2022 Setup.................................. finish page                         
  \u2022 Setup.................................. generate page                       
  \u2022 Setup.................................. migrate page                        
  \u2022 Setup.................................. options page                        
  \u2022 Setup.................................. packages page                       
  \u2022 Setup.................................. prepare page                        
  \u2022 Setup.................................. preseed copy page                   
  \u2022 Setup.................................. project page                        
  \u2022 Setup.................................. start page                          
  \u2022 Setup.................................. terminal copy page                  
  \u2022 Setup.................................. terminal page                       
  \u2022 Set terminal colors?................... Skip                                
  \u2022 Setup.................................. test 1 page                         
  \u2022 Setup.................................. test 2 page                         

  Setup file choosers                      

  \u2022 Setup (ignore warnings)................ copy file chooser                   
  \u2022 Setup (ignore warnings)................ directory chooser                   
  \u2022 Setup (ignore warnings)................ iso image chooser                   

Handle navigation from no page on open action                                   

  \u2022 Interrupt previous thread.............. No thread                           

Get the new page                                                                

  \u2022 Current page........................... no page                             
  \u2022 Action................................. open                                
  \u2022 New page............................... start page                          

Navigate from no page to start page on open action                              

  \u2022 The thread id is....................... 140072230708800                     
  \u2022 Set application configuration.......... /home/tfs-                          
                                            admin/.config/cubic/cubic.conf      

  Load application configuration           

  \u2022 Load application configuration......... 2021 layout from /home/tfs-         
                                            admin/.config/cubic/cubic.conf      
  \u2022 Set application visited sites.......... []                                  
  \u2022 Delete file............................ /home/tfs-admin/.config/cubic/visite
                                            d_sites.conf                        
  \u2022 Cannot delete file..................... File does not exist                 
  \u2022 The result is.......................... File /home/tfs-admin/.config/cubic/v
                                            isited_sites.conf does not exist.   
  \u2022 The exit status, signal status is...... None, 1                             
  \u2022 Read lines from file................... /home/tfs-                          
                                            admin/.config/cubic/projects.conf   
  \u2022 Warning. File does not exist........... /home/tfs-                          
                                            admin/.config/cubic/projects.conf   
  \u2022 Set application projects............... []                                  
  \u2022 Delete file............................ /home/tfs-                          
                                            admin/.config/cubic/projects.conf   
  \u2022 Cannot delete file..................... File does not exist                 
  \u2022 The result is.......................... File /home/tfs-                     
                                            admin/.config/cubic/projects.conf   
                                            does not exist.                     
  \u2022 The exit status, signal status is...... None, 1                             

  Transition pages                         

  \u2022 Show new page.......................... start page                          
  \u2022 Clicked................................ Exit                                

Handle navigation from start page on quit action                                

  \u2022 Interrupt previous thread.............. No thread                           

Get the new page                                                                

  \u2022 Current page........................... start page                          
  \u2022 Action................................. quit                                
  \u2022 New page............................... no page                             

Navigate from start page to no page on quit action                              

  \u2022 The thread id is....................... 140072439510592                     
  \u2022 Create all directories in the path..... /home/tfs-admin/.config/cubic       

  Save application configuration           

  \u2022 Save application configuration......... 2022 layout to /home/tfs-           
                                            admin/.config/cubic/cubic.conf      
```

**Screenshots**

N/A

**Comment by RipperSK** [comment]
related subiquity bug report: https://bugs.launchpad.net/subiquity/+bug/2022315

**Comment by PJ-Singh-001** [comment]
This is an unfortunate side effect of the new structure Canonical uses for ISOs with the Subiquity installer.

Here is the explanation I had [provided for another question](https://github.com/PJ-Singh-001/Cubic/issues/216#issuecomment-1560288812)...

The Ubuntu Server ISO has two layers (conceptually):

- Ubuntu Standard Layer
- Ubuntu Minimal Layer

![Ubuntu Servr ISO Diagram 2023-05-23-01-PS](https://github.com/PJ-Singh-001/Cubic/assets/19394936/9e184625-d0e4-4e48-bb46-ac92ab33fc35)

The Ubuntu Standard Layer overrides your changes in Cubic, because Cubic allows you to customize the Minimal Layer, not the Standard Layer.

You will _not_ be able to see your customizations in the Live Environment (accessed by selecting "Enter Shell" from the "Help" menu item at the top right) because the Live Environment shows the Standard Layer.

However, you can ensure your customizations are reflected in the installed OS by selecting "Ubuntu Server (minimized)" during installation.

![Ubuntu Server Installer 2023-05-23-01-PS](https://github.com/PJ-Singh-001/Cubic/assets/19394936/1583e916-0db5-479a-bd7b-1182317f842a)

**Comment by PJ-Singh-001** [comment]
Here is the workaround...

 1. In your case, install (or remove) all the packages you want in Cubic.

    Remember, you will be customizing a "Minimal" install.

    If you want all of the packages from a "Standard" install, you can execute the `unminimize` script inside Cubic.

        You have entered the virtual environment.
        root@cubic:~# unminimize
        This system has been minimized by removing packages and content that are
        not required on a system that users do not log into.

        This script restores content and packages that are found on a default
        Ubuntu server system in order to make this system more suitable for
        interactive use.
        ...
        This operation may take some time.

        Would you like to continue? [y/N]

 2. When you are done with your customizations/changes, do _not_ expect them to be present in the Live Environment. (For example, `dpkg -l` will give incorrect results in the Live Environment).

 3. However, when you install your customized OS, select "Ubuntu Server (minimized)" during installation. This will ensure all of your  customizations/changes are copied to your installed OS. After you've installed the OS using "Ubuntu Server (minimized)", `dpkg -l` will return the expected results.

**Comment by RipperSK** [comment]
@PJ-Singh-001 👍  Thanks for the explanation. Can you please link any source material from Ubnutu / Canonical that deals with SquashFS layout for 22.04 server ? Due to the automation level I'm trying to achieve the Cubic customisation is not enough as I'm doing a complete auto-install with cloud init.

Thanks.

In the meantime I think the answer you provided has sufficient info for workaround with Cubic - Thanks and I'm closing this issue.
