### ISSUE TITLE
Can't install packages in CUBIC Chroot Enviromnent

### ISSUE THREAD

**Issue by ZakDevOnGitHub** [PJ-Singh-001/Cubic#231]
**Describe the bug**

When I tried installing packages like KDE Plasma or KDE Full, I get an error saying "E: unable to locate package KDE-Plasma-Desktop", "E: unable to locate package KDE-Full"
**To Reproduce**
For KDE Plasma:
apt update && apt upgrade -y
apt install kde-plasma-desktop
 For KDE-Full:
apt-add-repository ppa:kubuntu-ppa/backports
apt update
apt install Kde-Full -y
**Expected behavior**
KDE Plasma:
The operation completed successfully!
KDE Full:
The operation completed successfully!

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version Ubuntu 22.04

**Cubic Information (please complete the following information):**
 - Cubic Version: [#](`url`)
 - ISO Customizing: ubuntu-22.04-desktop-amd64.iso]
 - Download Link:  The download link for the ISO you are customizing

**Cubic Log:**

![Screenshot 2023-06-09 123832](https://github.com/PJ-Singh-001/Cubic/assets/118214377/80dd7639-7683-4d6d-af36-6afd375186f9)
![Screenshot 2023-06-09 123818](https://github.com/PJ-Singh-001/Cubic/assets/118214377/6eee0fd3-fb11-4052-a745-754b51fb46d9)

**Screenshots**
![Screenshot 2023-06-09 123053](https://github.com/PJ-Singh-001/Cubic/assets/118214377/3c608dc8-d4d9-4249-8b9a-75cd9fae19f9)
![Screenshot 2023-06-09 123041](https://github.com/PJ-Singh-001/Cubic/assets/118214377/e9799a93-dbc2-4cff-a442-a504e174e61e)

**Comment by PJ-Singh-001** [comment]
This isn't a Cubic bug.
As you would do in a normal Ubuntu, you need to add the repositories before you use `apt` commands.
