### ISSUE TITLE
Bug: after apt-get shows the message "ERROR couldn't connect to zsys daemon" 

### ISSUE THREAD

**Issue by cfgnunes** [PJ-Singh-001/Cubic#233]
**Describe the bug**

Inside the virtual environment terminal, after installing a package by using the apt-get, appear the error message:

> ERROR couldn't connect to zsys daemon: connection error: desc = "transport: Error while dialing dial unix /run/zsysd.sock: connect: no such file or directory" 

**To Reproduce**

Open the virtual environment terminal and execute the command:

```shell
apt-get install inkscape
``` 

**Expected behavior**

The error message must now show.

**OS Information:**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 22.04.2

**Cubic Information:**
 - Cubic Version: 2023.05.83
 - ISO Customizing: ubuntu-22.04.2-desktop-amd64.iso
 - Download Link: https://releases.ubuntu.com/jammy/ubuntu-22.04.2-desktop-amd64.iso

**Comment by PJ-Singh-001** [comment]
This is not a Cubic bug.
Please read information on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).
Services do not run in Cubic's virtual environment.

Also, please see Issue #162, [ zsys daemon error](https://github.com/PJ-Singh-001/Cubic/issues/162#issue-1603804085).

**Comment by cristiandgal** [comment]
I'm building ubuntu22.04 iso on a running ubuntu22.04. What worked for me was:

```
base="~/Cubic/custom-root"

mount --rbind /dev $base/dev
mount --rbind /proc $base/proc
mount --rbind /sys $base/sys

chroot "$base"
mount -t devpts none /dev/pts
## install DUPs
exit
umount $base/dev
umount $base/proc
umount $base/sys
```
