### ISSUE TITLE
Ubuntu 23.10+ support?

### ISSUE THREAD

**Issue by hasanmerkit** [PJ-Singh-001/Cubic#238]
Problems:
1. Customized OS name not working with new installer (ubuntu-desktop-installer), detect as "Ubuntu".
2. "casper" folder manifest system changed. Package selector page not supported for Ubuntu 23.10.

Test with daily build : https://cdimage.ubuntu.com/daily-live/current/

**Comment by PJ-Singh-001** [comment]
What do you plan on using the Packages page for?

**Comment by hasanmerkit** [comment]
The Casper folder has been changed a lot. It also has a new installer. You should check out the new Ubuntu Daily Build. I think you will understand what I mean. Sorry for my bad English.

**Comment by hasanmerkit** [comment]
And when booting customized Ubuntu 23.10 iso file, new file /casper/minimal.standard.live.squashfs is mounting. Example new problem:
![image](https://github.com/PJ-Singh-001/Cubic/assets/18331715/3c7a5115-20b7-475e-a897-60f6404e3569)
![image](https://github.com/PJ-Singh-001/Cubic/assets/18331715/b3ffbd26-77ad-42f2-a9d6-0086c2b1ffb5)

In this example, /casper/minimal.standard.live.squashfs required chrooting for remove libreoffice-calc.

**Comment by hasanmerkit** [comment]
Did you plan any update?
New problems with Ubuntu latest version:

- Changing kernel crashes custom disk boot. (BusyBox boots.)
- Custom OS name not supported by new ubuntu-desktop-installer.
- Chrooting minimal.standard.live.squashfs required.
- Packages page no longer supported.

**Comment by PJ-Singh-001** [comment]
I'll look at Ubuntu 23.10 later, as the release date nears.

In my experience, the early daily builds do not work with Cubic, but the issues get resolved before release.

If the ISO structure has changed (again), I may need to make changes to Cubic to support it, if possible.

**Comment by PJ-Singh-001** [comment]
Regarding your [screenshot above](https://github.com/PJ-Singh-001/Cubic/issues/238#issuecomment-1621224663
) about Libre Office, is Libre Office now a snap package?

If so, you can not use `apt` to uninstall it.

Unfortunately, you can not manage snaps in Cubic. Therefore, I usually just uninstall snap:

    apt purge snapd gnome-software-plugin-snap

This will remove *all* snap packages from the system.

Then you can install the `deb` packages for those applications.

If you still want the end user to be able to manually install snap packages (in the installed customized OS), you can reinstall snap:

    apt install snapd gnome-software-plugin-snap

(Just remember, you will not be able to install snap packages while customizing the OS in Cubic).

**Comment by danimesq** [comment]
My log when trying to use the latest (hmm, of about 1 or 2 weeks ago) 23.10 daily build:

>  Find the compressed Linux file system    
> 
>   • Search for file name pattern........... .*\.squashfs$                       
>   • In directory........................... /media/daniella/ceb6a175-7104-43d8- 
>                                             8064-                               
>                                             48e6ef72cd27/cubic/manticdebug/sourc
>                                             e-disk                              
>   • The squashfs file paths are............ ['casper/standard.squashfs',        
>                                             'casper/standard.de.squashfs',      
>                                             'casper/standard.en.squashfs',      
>                                             'casper/standard.enhanced-          
>                                             secureboot.de.squashfs',            
>                                             'casper/standard.enhanced-          
>                                             secureboot.en.squashfs',            
>                                             'casper/standard.enhanced-          
>                                             secureboot.es.squashfs',            
>                                             'casper/standard.enhanced-          
>                                             secureboot.fr.squashfs',            
>                                             'casper/standard.enhanced-          
>                                             secureboot.it.squashfs',            
>                                             'casper/standard.enhanced-          
>                                             secureboot.no-languages.squashfs',  
>                                             'casper/standard.enhanced-          
>                                             secureboot.pt.squashfs',            
>                                             'casper/standard.enhanced-          
>                                             secureboot.ru.squashfs',            
>                                             'casper/standard.enhanced-          
>                                             secureboot.squashfs',               
>                                             'casper/standard.enhanced-          
>                                             secureboot.zh.squashfs',            
>                                             'casper/standard.es.squashfs',      
>                                             'casper/standard.fr.squashfs',      
>                                             'casper/standard.it.squashfs',      
>                                             'casper/standard.live.squashfs',    
>                                             'casper/standard.no-                
>                                             languages.squashfs',                
>                                             'casper/standard.pt.squashfs',      
>                                             'casper/standard.ru.squashfs',      
>                                             'casper/standard.zh.squashfs']      
>   • Error.................................. Unable to locate the squashfs file  
>                                             path

**Comment by danimesq** [comment]
> In my experience, the early daily builds do not work with Cubic, but the issues get resolved before release.

@PJ-Singh-001 are there a way to analyse these common patterns and catch them, so newer daily builds (24.04, 25.04) could potentially work?
Newbie question, BTW.

**Comment by PJ-Singh-001** [comment]
It's impossible to predict what Canonical will do with newer versions.

By the way, Cubic was already built to "catch" common file name patterns (which allows Cubic to work on other Ubuntu and Debian based distributions).

However, the ISO structure has become very complex now.

**Comment by mirek190** [comment]
@PJ-Singh-001   Do you have any plans to support snap packages?

**Comment by PJ-Singh-001** [comment]
Regarding [Snap support in Cubic](https://github.com/PJ-Singh-001/Cubic/issues/238#issuecomment-1739955063):
- Unfortunately,  Canonical will not be developing the ability to work with Snaps in chroot-like environments, such as [Cubic's virtual environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).
- See [Launchpad Bug # 1609903, "Enable the installation of snaps in a classic chroot"](https://bugs.launchpad.net/snappy/+bug/1609903).
- There was a method that had worked in the past, and I had documented it ("[How to install snap packages in Cubic?](https://answers.launchpad.net/cubic/+question/697883)"), but it no longer works.
- Perhaps I can come up with a work-around in the future, but I can not offer anything in the near term.

Regarding your comment that ["The Casper folder has been changed a lot"](https://github.com/PJ-Singh-001/Cubic/issues/238#issuecomment-1621210918):
- I just downloaded and tested [Ubuntu 23.10 Beta](https://releases.ubuntu.com/mantic/ubuntu-23.10-beta-desktop-amd64.iso), and it works fine in Cubic.
- With the Beta version, I do not experience the [issues you reported in your log above](https://github.com/PJ-Singh-001/Cubic/issues/238#issuecomment-1720306854).
- As I mentioned previously, [the early daily builds typically do not work with Cubic, but the issues get resolved](https://github.com/PJ-Singh-001/Cubic/issues/238#issuecomment-1674165504).

Regarding [LibreOffice](https://github.com/PJ-Singh-001/Cubic/issues/238#issuecomment-1621224663):
- Cubic allows you to customize the minimal install.
- LibreOffice is no longer included in the minimal install.
- Simply install it using `apt`. (Make sure you've added the `universe` repository first, using `apt-add-repository`).
- During installation, select "Minimal Install". (This is now the default, anyway).

Regarding your statement that ["Package selector page not supported for Ubuntu 23.10"](https://github.com/PJ-Singh-001/Cubic/issues/238#issue-1769783758):
- This is true.
- The [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) is specifically for the Ubiquity installer.
- Ubuntu 23.10 uses the Subiquity installer.
- Therefore, the Packages page in not needed, so Cubic does not show it.
- Remember to add and remove packages on [Cubic's Terminal page](https://github..com/PJ-Singh-001/Cubic/wiki/Terminal-Page). (You should not be relying on the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) to select which packages are included in your Customized OS).

Thus, Cubic is working with Ubuntu 23.10 Mantic Minotaur (Beta) as expected, with the limitations I have pointed out above.

Based on my test of [Ubuntu 23.10 Beta](https://releases.ubuntu.com/mantic/ubuntu-23.10-beta-desktop-amd64.iso), I will close this issue.

**Comment by hasanmerkit** [comment]
Has anyone found a way to use just filesystem.squashfs? I want to merge the squashfs files in the official latest ISO.

Installer, ISO build, snap force. Ubuntu really makes me hate it.

Ubuntu 23.10 Beta is not solution for me and i need LTS versions.

**Comment by hasanmerkit** [comment]
Lubuntu and some flavors still using single file (filesystem.squashfs) and new Ubuntu Installer not changes distro name.

**Comment by PJ-Singh-001** [comment]
UPDATE:

Cubic version 2026-07-107 (and newer) introduced a new [Snaps page](https://github.com/PJ-Singh-001/Cubic/wiki/Snaps-Page), that allows you to remove snap packages.

When removing certain snaps like Firefox, Libre Office, or Thunderbird, be sure to remove the corresponding deb packages, as described (for Firefox) on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

**Comment by mirek190** [comment]
nowadays I implemented that myself using codrx-cli within a few minutes 

But thanks ;)
