### ISSUE TITLE
ParrotOS/installing Gnome

### ISSUE THREAD

**Issue by DeForestDiamond** [PJ-Singh-001/Cubic#239]
The reason for these question is I'm pretty new to this and more just messing around and I'm trying to avoid trying to do things that aren't actually doable, which I keep doing lately. A simple yes/no is more than enough, I don't mind diving in to figure out how, that's half the fun.

Seeing as ParrotOS is based on Debian, it should work in Cubis, right?

Is it possible to change the desktop environment well creating the .ISO?

Thank you so much for your time and your awesome program!

**Comment by PJ-Singh-001** [comment]
I checked ParrotOS, and the ISO does not contain a compressed Linux file system, as does Ubuntu and the Debian Live ISO. Therefore you will not be able to customize ParrotOS using Cubic.

When customizing an OS that works with Cubic, yes, you would be able to change the desktop environment.

**Comment by DeForestDiamond** [comment]
Thank you! I really appreciate your time and this fantastic program you've created.
