### ISSUE TITLE
Does Cubic support Secure Boot/UEFI?

### ISSUE THREAD

**Issue by omarcusmoreira** [PJ-Singh-001/Cubic#240]
**Describe the question**

I need to create a custom ubuntu verison with some software installed that would run live on USB flash drive. But most tools I've used encoutered issues with Secure Boot when creating the bootable drive.
Does Cubic supports Secure Boot?

**What you have tried**

I have not tryied it

**Expected behavior**

N/A

**OS Information (please complete the following information):**
 N/A

**Cubic Information (please complete the following information):**
N/A

**Screenshots**

**Comment by hasanmerkit** [comment]
Yes, im not developer but i creating Secure Boot supported Custom images with Cubic. Just don't touch the grub-* packages.

**Comment by PJ-Singh-001** [comment]
@hasanmerkit

Thanks for chiming in! :-)
I will close this issue based on your input.
