### ISSUE TITLE
stuck at 50% when build the iso

### ISSUE THREAD

**Issue by Daggermaster** [PJ-Singh-001/Cubic#247]
stuck at 50% progress in copy selected boot kernel when generating customized iso. 
this is the log

```
Exception in thread Thread-20 (navigate):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/cubic/cubic/navigator.py", line 613, in navigate
    result = new_page.enter(action, page) if new_page else None
  File "/usr/share/cubic/cubic/pages/generate_page.py", line 144, in enter
    is_error = copy_kernel_files()
  File "/usr/share/cubic/cubic/pages/generate_page.py", line 377, in copy_kernel_files
    is_pop_os_based = constructor.os_is_distribution('pop', model.project.custom_root_directory)
  File "/usr/share/cubic/cubic/utilities/constructor.py", line 245, in os_is_distribution
    key, value = line.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by PJ-Singh-001** [comment]
It's always a good idea to include basic information when seeking help, such as the version of Cubic you are using, the OS and version you are running Cubic in, and the OS and version you are trying to customize.

**Comment by Daggermaster** [comment]
im using oracle virtual box 6.7 as vm, the latest cubic version, ubuntu 22.04 as the os and also os that im trying to customize

**Comment by PJ-Singh-001** [comment]
In Cubic's [Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), please execute the following. and cut-and-paste the output here:

    cat /etc/os-release

(After you paste it here, you can use the "<>" button above to format your output so it is easier).

**Comment by Daggermaster** [comment]
ok thanks for the help, im already know the problem and the solution. i want to asked another topic, should i asked here or create new issue?

**Comment by PJ-Singh-001** [comment]
Please open separate issues for different questions.
