### ISSUE TITLE
How do i customize LM 21.2 Cinnamon desktop

### ISSUE THREAD

**Issue by Rizk086** [PJ-Singh-001/Cubic#251]
**Describe the question**

I want to customize linux mint cinnamon wallpapers, themes, etc

**What you have tried**

I have tried replacing the default wallpaper with the custom wallpaper, replacing the theme, and creating and compiling override file, but when im booting custom linux mint, it's not displaying the custom wallpaper and theme i made, instead it's displaying default linux mint theme .

sorry im newb to linux, and my english is bad

**Expected behavior**

It's showing my theme and wallpaper.

**OS Information (please complete the following information):**
 - OS/Distro Name: Linux Mint XFCE
 - OS Version 21.2

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.05.83
 - ISO Customizing: linuxmint-21.2-cinnamon-64bit.iso
 - Download Link:  https://mirror.gi.co.id/linuxmint-iso/stable/21.2/linuxmint-21.2-cinnamon-64bit.iso

**Comment by PJ-Singh-001** [comment]
@Rizk086,

Issue #184 explained how to customize Linux Mint. For some reason, that issue no longer exists.

However, I have created a new Issue (#252: [How to customize Linux Mint Cinnamon wallpaper, icons, and theme?](https://github.com/PJ-Singh-001/Cubic/issues/252#issue-1846104506)), with the original answer.
