### ISSUE TITLE
$250 Bounty: Creating an Ubuntu ISO which automatically installs to an encrypted LVM is currently impossible.

### ISSUE THREAD

**Issue by springfielddatarecovery** [PJ-Singh-001/Cubic#255]
**Cubic context**
Currently, it is impossible to use Cubic to customize the latest Ubuntu desktop ISOs to automatically install with an encrypted LVM like is available with the Ubuquity GUI installer. The preseed format provides options for doing this, but they do not work for newer versions of Ubuntu. This isn't Cubic's fault, of course, but it does effect Cubic users. 

So we are putting some money on a bounty for somebody to find a workaround. Please see [our main post](https://springfielddatarecovery.com/bug-bounty-solve-preseed-encrypted-lvm-on-ubuntu-22-04/) about this for the latest information. This issue will be closed when it is solved. The bounty is also posted on [Lemmy's bug bounty community](https://lemmy.ml/post/3796605).

**Bounty Amount and Terms:**

This bounty is for $250 USD and will be paid out via PayPal. You can also be paid in BTC if you prefer. This bounty amount will increase at random amounts and intervals until it is claimed. The bounty is open to residents of all countries except those under embargo or sanction by the US govt. The bounty will be paid out to the first person to produce a working preseed recipe or steps to achieve the desired result. When the bounty is successfully claimed, this post will be updated.  By submitting your fix and claiming your bounty, you agree to release any code, preseed files, etc delivered to us into the public domain and surrender all rights you hold to them. Contact office {at} springfielddatarecovery.com with any questions or submissions. Once the bounty is fulfilled, we will post the solution publicly to support the Ubuntu community.

**Problem:**

We want to create an Xubuntu 22.04 ISO using Cubic. Using the preseed, we want to automatically partition the drive with a standard encrypted LVM setup (same one that is achieved manually via the GUI installer). Unfortunately, all existing recipes, which supposedly worked in prior Ubuntu versions, fail with the error No modifications can be made to the device: Encrypted Volume (sda1p2_crypt) for the following reasons: In use by LVM module group crypt or whatever the volume is titled in the partman recipe. Some [addl background](https://askubuntu.com/questions/1481523/how-to-get-around-device-in-use-error-when-preseeding-ubuntu-22-04-install-wit) on this issue.

**Desired Solution:**

 - A preseed file which enables automatic encrypted LVM partitioning identical to what is achieved by choosing it manually in the GUI installer
 - This solution must be compatible with Cubic and may involve making modifications to the underlying iso, for example, by issuing commands at the chroot terminal provided by Cubic. It should not require any modifications to the ISO outside of the abilities provided by Cubic.
 - This must work for the desktop version of Ubuntu ISO.

**Comment by springfielddatarecovery** [comment]
Bounty closed as we found a workaround that didn't require solving this issue

**Comment by gitgonewithwind** [comment]
I did encrypt successful in ubuntu 22.04 server . I am thinking how to use here to convert ubuntu 22.04  server  version  to ubuntu 22.04 desktop version   https://github.com/michaeltandy/ubuntu-desktop-22.04-autoinstall/blob/main/desktop-squashfs-modifications.sh
I hope it can work!
