### ISSUE TITLE
Tracking Cubic Progress via Script

### ISSUE THREAD

**Issue by PicoMitchell** [PJ-Singh-001/Cubic#259]
**Describe the question**

I have a custom script which sets up a new Cubic project and guide a user through clicking buttons in Cubic. Previously (some months or maybe even up to a year back), I could track the step that Cubic was on by having the script wait for things like `is_success_copy = True` (among other things) in the `cubic.conf` file: https://github.com/freegeek-pdx/Linux-Deployment-and-Support-Scripts/blob/c9b6470c229ec0ea58cad2a722a5f1a04f256732/Mint%20Installer%20Resources/setup-mint-installer-cubic-project.sh#L187 & https://github.com/freegeek-pdx/Linux-Deployment-and-Support-Scripts/blob/c9b6470c229ec0ea58cad2a722a5f1a04f256732/Mint%20Installer%20Resources/setup-mint-installer-cubic-project.sh#L245

At some point the timing of when these lines were updated in the Cubic config file, and now that `is_success_copy = True` line (for example) does not get written right after the copy is done, but only after clicking back from the Cubic Terminal window.

**What you have tried**

Could not find another programmatic way to determine the current step that Cubic is on.

**Expected behavior**

I'm hoping there is some way that I can programmatically determine the exact step that Cubic is currently on. Maybe there is some way in Cubic that I'm not aware of, or maybe it would be possible to adjust the config update timing logic back to these values being updated immediately when the task is done, rather than after the back button is clicked after the task was done.

**OS Information (please complete the following information):**
 - OS/Distro Name: Linux Mint
 - OS Version: 21.2

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.05.83
 - ISO Customizing: linuxmint-21.2-cinnamon-64bit.iso
 - Download Link:  https://www.linuxmint.com/edition.php?id=305

**Comment by PicoMitchell** [comment]
With a little digging, it looks like this was an intentional change back in March: https://github.com/PJ-Singh-001/Cubic/issues/171

**Comment by PicoMitchell** [comment]
The 2 specific configuration updates that I would like to be immediate would the after the initial ISO extraction process is fully completed, and then after the custom ISO is fully generated and exported.

**Comment by PJ-Singh-001** [comment]
@PicoMitchell,

The fix to #171 corresponded to another set of bug fixes as well, so the change was not simply "stop writing the config file"...

- Fixed Bug #167
- Enhancement #171
- Fixed issue where the required boot configurations (i.e. the filtered list of boot configuration files) were not updated in the project configuration file, if the user quit Cubic while on the Boot Copy page.

I wonder if you could use the Cubic log output to look for specific text printed to the console?
You can run Cubic in verbose mode using:

    cubic --verbose

**Comment by PicoMitchell** [comment]
Thanks for getting back to me. I did look into writing the `cubic -v` output to a file to use that to monitor the step, but it seemed like for both spots that I was wanting to track the log was not updated until after the next step completed or after the app was quit. For example during the extraction phase the verbose output written to the file stayed at the 10% complete line even after it finished as was at the terminal page. It only updated to show the full progress after I clicked past the terminal page.

I need to look into that more though, maybe the issue was with writing it to the file and now with `cubic` itself.

**Comment by PicoMitchell** [comment]
Oddly, when `cubic --verbose` is run in a Terminal, it logs all the steps just fine as expected.

But, when I run something like `cubic --verbose > /path/to/cubic.log 2> /dev/null & disown` to run cubic in the background and save the log to a file, the lines past `Completed... 10%` (or sometimes just `The process id is...` line when extracting the ISO (and generating the custom ISO) do not get written to the file until after the Terminal page is exited.

I'm not sure why it would behave differently when stdout is written to a terminal vs a log file.

Are you able to reproduce this behavior on your end? Any thoughts as to the cause?

**Comment by PJ-Singh-001** [comment]
If Cubic wrote a log file based on a command line argument, like `cubic --log`, would you be able to read the log file and do what you need to?

The name of the log file will be of the format `cubic.YYYYMMDDHHMMSS.log`. It will be placed in the project folder. There will be multiple log files, one for each launch of the Cubic application, so you would need to read the most recent one.

**Comment by PicoMitchell** [comment]
Yes, definitely!

But, if an app update is necessary, would it be possible to just have Cubic update the config right when the Extraction and Generate phases have finished?

**Comment by PicoMitchell** [comment]
But, I could also see that a plaintext `--log` option which doesn't include any of the ANSI styling could be useful for scripting and debugging.

**Comment by PJ-Singh-001** [comment]
> But, I could also see that a plaintext `--log` option which doesn't include any of the ANSI styling could be useful for scripting and debugging.

I'll be able to remove the ANSI escape codes for the titles and headings in the output (i.e. the text with the yellow or green backgrounds). I won't be able to remove the escape codes for some of the messages shown in the right hand column (like the process ids, thread ids, and messages about entering/exiting the virtual environment, etc.).

(See [this comment on issue #261](https://github.com/PJ-Singh-001/Cubic/issues/261#issuecomment-1736363770)).

**Comment by PJ-Singh-001** [comment]
Fix released in Cubic version 2023.09-84. See Issue #261, [Add a `--log` command line option to Cubic](https://github.com/PJ-Singh-001/Cubic/issues/261).

**Comment by PicoMitchell** [comment]
Awesome, thank you so much! I will test this out next week.

**Comment by PicoMitchell** [comment]
I've just tested and this new `--log` option works perfectly for my needs to track the cubic progress in a script.

Thank you!
