### ISSUE TITLE
Custom Cubic Plymouth configuration works in Qemu but not VMWare or flashed disk.

### ISSUE THREAD

**Issue by woflydev** [PJ-Singh-001/Cubic#26]
# Describe the question:

The custom plymouth splashscreen does not show on VMWare or flashed disk, however, it does indeed work within the 'test' function implemented in Cubic.

# What you have tried?

I installed a custom theme in plymouth following these steps: https://github.com/PJ-Singh-001/Cubic/issues/5#issuecomment-1001224949

After selecting the new kernel (NOT the default one) that I updated with 'update-initramfs -u -k all' and generating the ISO, I clicked 'test' and it booted up with the flash screen in a separate window (Qemu). Everything was running as normal.

Everything seemed pretty normal until I flashed the ISO using Balena Etcher. Plugged the USB into my desktop and booted from it (my desktop runs Windows 10) but there was no splash screen (not even the spinning-circle thing you get on stock Ubuntu LTS).

I tried once more by copying the ISO to my desktop (unflashed) and sticking it in VMware Workstation Pro. It couldn't even boot.

I'm not exactly sure why this is the case, and any help is greatly appreciated.

Thanks :)

# Expected behavior?

Plymouth should show with the configured splashscreen.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu 20.04 LTS (unmodified)

**Cubic Information:**
 - Cubic Version: 2022.01.70
 - ISO Customizing: ubuntu-21.04LTS-desktop-amd64.iso (I renamed it to just 'ubuntu.iso'.
 - Download Link:  Can be found on the Ubuntu official website.

**Comment by PJ-Singh-001** [comment]
1. From Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), please share the output of

        ls -l /boot

2. Also, please share a screenshot of the [Kernel tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab) from Cubic's [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), and let me know which of the listed items you have selected for your custom ISO (ie. 1st item, 2nd item, etc.)?

**Comment by woflydev** [comment]
Here are the screenshots, (btw thank you for the quick reply, it's so hard to find a well maintained project these days);
![Screenshot from 2022-02-16 08-32-20](https://user-images.githubusercontent.com/99102040/154160917-602edb57-d734-4764-ae52-3425d45b48a8.png)

![Screenshot from 2022-02-16 08-31-07](https://user-images.githubusercontent.com/99102040/154160905-7f011b6f-4290-40fe-b9c6-be1c11ec2545.png)

I did figure out the cause of the problem while tinkering with some of the GRUB boot settings. However I still don't know a fix for it yet. The steps I took to figure out the problem:

- Made a new 'testing' Cubic project using the same ubuntu.iso file as above.
- Only changed the Plymouth settings.
- Updated kernel with update-initramfs -uk all.
- Changed kernel in the options menu.
- Generated the test-splashscreen.iso file.

The generated image's Plymouth settings worked on VMware AND the Qemu test window within Cubic. I deduced that it didn't work on my desktop because of my Nvidia graphics card, which made the installer default back to the 'Safe Graphics' option.

What's funny is that I didn't even get the chance to pick, and there was no GRUB menu shown when booted from my desktop. 

When I booted it from my Intel Iris powered laptop (after I flashed the test-splashscreen.iso) it did work. The GRUB menu was also shown.

On VMware, the GRUB menu shown was the colored one with 'Ubuntu 20.04 LTS' as the title. However, it was the standard GRUB menu (black and white) when booted from my laptop.

If it helps, the thing that shows before (and what I think is causing it to boot in the 'Safe Graphics' mode) before booting on my desktop is 'nouveau [number] unknown chipset (my graphics card id)'.

My new question is: how do I fix the Nvidia driver problem, and why isn't the GRUB menu showing on my Nvidia desktop?

Thank you :)

**Comment by woflydev** [comment]
While I was customizing the ISO within the chroot terminal, I also tried install Plank using:

``apt-get update`` and then
``apt-get install plank``.

However, it returned:
``Plank depends on libplank1 (= 0.11.89+git20211104.e2c9502e-0ubuntu1~20.04~ricotz1) but it is not going to be installed.
E: Unable to correct problems, you have held broken packages.``

I've also tried using ``apt-get install -f`` but it doesn't seem to work either way.

I know I should create a separate issue for this, but I didn't want to bother you with opening a bunch of pages from the same person.

Thank you.

**Comment by PJ-Singh-001** [comment]
The version of `libplank1` in Ubuntu 20.02 is `0.11.89-1` from the Universe repository.
It looks like the `plank` package you are trying to install requires a very specific version of `libplank1` (e.g. `0.11.89+git20211104.e2c9502e-0ubuntu1~20.04~ricotz1`).
To me, this version number looks like a customized non-standard version (notice the `+git20211104.e2c9502e-0ubuntu1~20.04~ricotz1` at the end of the version number).

There are a couple of options you have:
 1. Determine which source or PPA you can get this specific version of `libplank1`, that satisfies the dependency for `plank`. If it is a PPA, then add the PPA to your sources list and execute:

        apt update
        apt install libplank1

 2. Contact the developer of `plank` and point out the issue. If the official Ubuntu version of `libplank1` (e.g.  `0.11.89-1` from the Universe repository) will work with their software, then they probably need to fix their dependencies. Instead of the dependency `= 0.11.89+git...` ("equal to 0.11.89+git..."), it probably needs to be changed to `>= 0.11.89` ("greater than or equal to 0.11.89").

**Comment by woflydev** [comment]
I tested the Plymouth splashscreen some more and I figured out that it works on EFI boot mode (all the tests I'm doing are on my Desktop with the Nvidia Graphics Card).

However, it doesn't on Legacy BIOS mode, no matter the parameters. I've tried adding and omitting 'nomodeset', '$vt_handoff', 'rdblacklist=nouveau', and the like. However, it just shows the default kernel splashscreen. 

Would you know any reason why this is so?

(Thank you for the information on plank, I'll try what you said)

**Comment by PJ-Singh-001** [comment]
What do you see as a splash screen? Your laptop manufacturer logo, or the Ubuntu logo with the dots?

**Comment by PJ-Singh-001** [comment]
I haven't heard back from you, so I'll assume you have solved this or it is no longer an issue.
