### ISSUE TITLE
An Unintended Feature: Cubic Runs in ChromeOS with Crostini Support!

### ISSUE THREAD

**Issue by ZGStuff** [PJ-Singh-001/Cubic#264]
Cubic, unintentionally, due to the fact that Project Crostini (ChromeOS) runs Debian 11 (upgradable to Debian 12), can run Cubic almost perfectly, allowing for you to make a distro with a Chromebook, or anything that runs ChromeOS with Crostini support!

**Comment by PJ-Singh-001** [comment]
Wow! I did not realize this. Thanks for sharing.

**Comment by ZGStuff** [comment]
xD
