### ISSUE TITLE
when cubic compile iso complete is use a lot of disk space 

### ISSUE THREAD

**Issue by jygytfugi** [PJ-Singh-001/Cubic#267]
when i delete project Directory and iso file it not have any thing begin is not return from 186 to 255 gb

**Comment by PJ-Singh-001** [comment]
Did you delete your Cubic project using the Delete button on the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page)?

![image](https://github.com/PJ-Singh-001/Cubic/assets/19394936/af7b8d3d-2253-472b-9a98-443a5de14563)

**Comment by PJ-Singh-001** [comment]
If you select the "Delete all files..." option on the [Finish page](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Page), the generated ISO (`*.iso`) and the Checksum file (`*.md5`) files will not be deleted. You will need to delete them manually, if you no longer need them.

![image](https://github.com/PJ-Singh-001/Cubic/assets/19394936/4cfc817b-e652-4b0f-94a3-3c50c8afbdcc)
