### ISSUE TITLE
ubuntu server 22.04.3 can not install by cubic

### ISSUE THREAD

**Issue by jupyzhu** [PJ-Singh-001/Cubic#271]
**Describe the question**
I also following the instruction in here , add user-data/meta-data , update grub/loopback.cfg and then make a iso file with ubuntu-22.04.3-live-server-amd64.iso
https://github.com/PJ-Singh-001/Cubic/issues/101#issuecomment-1336728758

A clear and concise description of what the question is.
i can't install custom ubuntu server 22.04.3, and the installation screen cannot be displayed.

**What you have tried**
apt update&&apt upgrade -y
apt -y remove --purge snap*&&apt autoremove
apt install -y vim tree iftop net-tools netcat htop traceroute  apt-file tree unzip p7zip jq apt-offline gdb iotop expect dos2unix sysstat 
apt install -y chrony firewalld supervisor
echo "hello new-iso">hello.txt

#creatre a user named jupy
useradd -m jupy -s /bin/bash
usermod -aG sudo jupy
#set the passwd 'jupy'
passwd jupy

Steps you already took.

**Expected behavior**
1) I hope the custom iso can get the system
2) I want the installed system to have users:jupy、user1、user2、user3、psingh. And the user saves the corresponding password.
3) The software I set was installed by default in the installed system.
The installation failed at the first step. I can not install the custom-iso.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version:ubuntu-22.04.3-live-server-amd64(the newest server LTS release version)

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.09.84
 - ISO Customizing: ubuntu-22.04.3-live-server-amd64.iso(the newest server LTS release version)
 - Download Link:  https://releases.ubuntu.com/22.04.3/ubuntu-22.04.3-live-server-amd64.iso

**Screenshots**
![图片](https://github.com/PJ-Singh-001/Cubic/assets/38723187/a111f1b6-9279-41fe-a2a1-1931a37357b9)
![图片](https://github.com/PJ-Singh-001/Cubic/assets/38723187/66cb8eeb-e3e4-4564-91de-acd8876526e4)
![图片](https://github.com/PJ-Singh-001/Cubic/assets/38723187/0f5048d6-f762-4fef-8312-308a23ed88b7)
![图片](https://github.com/PJ-Singh-001/Cubic/assets/38723187/88bf8580-3eff-4480-be78-e2489794690c)
![图片](https://github.com/PJ-Singh-001/Cubic/assets/38723187/017a340d-77a2-4002-9aae-731ab152c1fb)
![图片](https://github.com/PJ-Singh-001/Cubic/assets/38723187/a6dfcf95-c04b-41b0-a3ff-139fc0d26cbf)
![图片](https://github.com/PJ-Singh-001/Cubic/assets/38723187/86a85231-ad16-44e1-893a-4d4865eada70)
![图片](https://github.com/PJ-Singh-001/Cubic/assets/38723187/a2a84fe8-7c0d-4bc5-9b0e-2a3ea8e1e4d4)
![图片](https://github.com/PJ-Singh-001/Cubic/assets/38723187/981191d2-7828-4fdf-a966-63dab6f62903)
when run test, it's stuck in the picture below. After the output "[ OK ]finished casper-md5check verify live ISO checksum" , it does not continue. After a day of waiting, still the same.
![图片](https://github.com/PJ-Singh-001/Cubic/assets/38723187/0846810e-70d1-435a-9b77-544928ddbabf)

My guess is that test might fail, but the installation on an actual physical machine would not fail. But in fact, the result is the same, still stuck in the above  startup screen.

**Comment by UnstoppableDrew** [comment]
Have you tried hitting enter in the qemu window? I have found on real systems it gets to this point and is done, and is actually ready to login, but hasn't printed out the prompt until you hit enter.

**Comment by jupyzhu** [comment]
> Have you tried hitting enter in the qemu window? I have found on real systems it gets to this point and is done, and is actually ready to login, but hasn't printed out the prompt until you hit enter.

I've already pressed Enter, and nothing has changed

**Comment by phillips321** [comment]
> Have you tried hitting enter in the qemu window? I have found on real systems it gets to this point and is done, and is actually ready to login, but hasn't printed out the prompt until you hit enter.

I have the same problem on 24.04 when using multi-user (no gui). It never displays the logon prompt (however i have it working fine with 22.04). See my issue #313

**Comment by PJ-Singh-001** [comment]
@jupyzhu, @phillips321,

The latest version of Cubic (currently 2024.09.89) should address your issues.

Instead of `user-data`/`meta-data` files, use an `autoinstall.yaml` file as described in Issue #338, [How to remove all snaps from Ubuntu?](https://github.com/PJ-Singh-001/Cubic/issues/338#issuecomment-2325417166). (Obviously you do not need to include the `late-commands` that remove all snaps, if you don't want to).

Update Cubic using:

    sudo apt update
    sudo apt install --no-install-recommends cubic

With the information provided, I will close this issue.
If you experience problems with the new version of Cubic, please open a new issue.
