### ISSUE TITLE
"Wait until snapd is fully seeded"

### ISSUE THREAD

**Issue by TriveniSean** [PJ-Singh-001/Cubic#272]
We've noticed that with some ISOs, if we do an apt upgrade in the virtual environment, the resultant ISO will hang on startup when testing.  We had to disable the quiet kernel boot option to see the reason, and it appears to be related to snapd seeding.

The only workaround we've found is to modify the snapd.seeded.service an insert a timeout value.

We've noticed this on Ubuntu server 20.04 and 22.04.

 - Cubic Version: 2023.09-84-release
 - ISO Customizing: ubuntu-20.04.6-live-server-amd64
 - Download Link:  https://releases.ubuntu.com/focal/ubuntu-20.04.6-live-server-amd64.iso

![Screenshot_20231115_102343](https://github.com/PJ-Singh-001/Cubic/assets/36745873/fa6ac3e6-5984-41c2-a580-a0b3d55a649e)

We suspect this has nothing to do with cubic, but are curious if others have encountered this problem and found a better solution.

**Comment by PJ-Singh-001** [comment]
@TriveniSean,

Thanks for sharing this issue and the work around.
(I have not experienced the "wait until snapd is fully seeded" issue myself, but it has been a while since I tested the server ISO for 20.04 or 22.04).

**Comment by jupyzhu** [comment]
i meet the same situation when i used ubuntu server 22.04.3

**Comment by aniruddha-a** [comment]
Just to re-confirm, do you mean the following @TriveniSean :

To edit the file `/lib/systemd/system/snapd.seeded.service` like

```
[Unit]
Description=Wait until snapd is fully seeded
After=snapd.socket
Requires=snapd.socket

[Service]
Type=oneshot
ExecStart=/usr/bin/snap wait system seed.loaded
RemainAfterExit=true
TimeoutStartSec=30   <<<<<<<<<<<<
```

Is `30` seconds a sane value here ?

I am on 22.04.4 and running into the exact same issue after repackaging.

**Comment by tcatlas** [comment]
For anyone stumbling onto this page in the future, I have found this to pop up when the network interface's default route is misconfigured (i.e., no internet access or inter-vlan traffic).
