### ISSUE TITLE
Some packages are deleted after installation of LMDE 6 "Faye"

### ISSUE THREAD

**Issue by eband** [PJ-Singh-001/Cubic#274]
After making an image of LMDE 6 using the Debian tool, many programs like smplayer, mint-meta-codecs, clementine, and k3b, are deleted after installing the newly-made image.

This is what happened:
1. I use the Debian variant of Cubic to customise Linux Mint Debian Edition ISO.
2. I restart the computer, followed by booting the image.
3. All seems fine; the included software was on the Live environment.
4. I install the system.
5. I restart the computer.
6. I boot up the new customisation and smplayer, clementine, and mint-meta-codecs are gone. from the new installation.

After trying Remastersys for Debian and finding out the labyrinthe process, I found out that Debian is indeed supported in Cubic. I expected that the customisation process would go smoothly as I was previously used the tool to remaster Linux Mint, and that version of Cubic impressed me over the years.

I'm using LMDE 6 "Faye" 32-bit on my old laptop, which is based on Debian bookworm. I added the repository without the instructions to get the newer dpkg version since it already has that version, so I left out those instructions.

I couldn't keep the logs and the software needed to produce the logs because the system wiped them out after the installation. If you need anything, I suppose I can try again. My guess would be that it's the latest x86 version as of November 21, 2023. That's all I know.

**Comment by eband** [comment]
In my last paragraph, I said that it's the "latest x86 version of November 21, 2023."

I meant the latest Debian Cubic variant of November 21, 2023 that customises, well, Debian. That was the last question, right?

**Comment by PJ-Singh-001** [comment]
Do you remember if Cubic presented you with the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page), while you were customizing?

![](https://github.com/PJ-Singh-001/Cubic/raw/release/screenshots/Cubic%20Packages%20Page.png)

**Comment by PJ-Singh-001** [comment]
I checked the LMDE iso, and the `/casper/filesystem.packages-remove` exists.
This is one of the files Cubic allows you to update on the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page).

However, Cubic only shows the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) if you have Ubiquity installed.
Obviously, LMDE does not use Ubiquity.

As a result the following packages will be removed when installing LMDE. These are the default packages to be removed, as defined on the _original_ ISO. Packages that depend on the following packages will also be removed.

@eband, do you know if `smplayer`, `clementine`, and `mint-meta-codecs` depend on any of these packages?...

```
boot-repair
boot-sav
boot-sav-extra
glade2script
glade2script-python3
gparted
gparted-common
imagemagick
imagemagick-6-common
imagemagick-6.q16
insserv
isoquery
libfftw3-double3:amd64
libimath-3-1-29:amd64
libjxr-tools
libjxr0:amd64
liblqr-1-0:amd64
libmagickcore-6.q16-6:amd64
libmagickcore-6.q16-6-extra:amd64
libmagickwand-6.q16-6:amd64
libnetpbm11:amd64
libopenexr-3-1-30:amd64
libqt5designer5:amd64
libqt5help5:amd64
libqt5printsupport5:amd64
libqt5sql5:amd64
libqt5sql5-sqlite:amd64
libqt5test5:amd64
libqt5xml5:amd64
libwmflite-0.2-7:amd64
live-boot
live-boot-doc
live-boot-initramfs-tools
live-config
live-config-doc
live-config-systemd
live-installer
live-tools
menu
mint-live-session
netpbm
pastebinit
python3-pyqt5
python3-pyqt5.sip
startpar
syslinux-utils
sysv-rc
```

**Comment by eband** [comment]
@PJ-Singh-001, I think it will be easier if you just tell me which Debian flavour supports Ubiquity.

I can do away with LMDE as it's not as good as its Ubuntu-based offering, It's not hard to change here.

**Comment by PJ-Singh-001** [comment]
Does it have to be Debian flavor other than Ubuntu?

If you are willing to use Ubuntu, I recommend Ubuntu 22.04.4 LTS, which still uses the Ubiquity installer.
(With the 23.04 desktop ISO, Canonical switched away from Ubiquity, and now the Live environment can not be customized to match the customized install. This gives an inconsistent experience, since you can't test your changes in the Live ISO before you install it.)

If you can't use Ubuntu, and you need another Distro based on Debian, give me some time to research what options are available.
(I will also consider if I can make changes to Cubic to allow you to edit the removable packages list for Debian).

**Comment by PJ-Singh-001** [comment]
> @PJ-Singh-001, I think it will be easier if you just tell me which Debian flavour supports Ubiquity.
> 
> I can do away with LMDE as it's not as good as its Ubuntu-based offering, It's not hard to change here.

You can customize **Debian 12.05 Live with Cinnamon** (Download: [debian-live-12.5.0-amd64-cinnamon.iso](https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-12.5.0-amd64-cinnamon.iso)).

Debian does _not_ use Ubiquity, so the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) will still not be displayed. However, Debian does not automatically remove packages during an install, so this will not be an issue for you.

Note: If you try to launch the Debian installer from the Grub menu of the customized ISO, you will be taken to the live environment, not the installer. This is a minor issue, and you can simply launch the installer once you are booted into the live environment. See Issue #173, [Customization breaks the Graphical Debian Installer](https://github.com/PJ-Singh-001/Cubic/issues/173) for a solution, if you want.

Regarding LMDE, I am considering adding support to Cubic to show the [Packages page](https://github.com/PJ-Singh-001/Cubic/wiki/Packages-Page) when this distro is being customized. However, it will take some time, so in the near-term, I suggest you customize Ubuntu 22.04.4 LTS, as suggested in the [comment above](https://github.com/PJ-Singh-001/Cubic/issues/274#issuecomment-1962987408), or customize Debian 12.05 Live, as suggested in this comment.

**Comment by eband** [comment]
All right, PJ. Problem solved.
