### ISSUE TITLE
Cubic does not work on WSL2

### ISSUE THREAD

**Issue by leeteral** [PJ-Singh-001/Cubic#275]
**Describe the bug**

[**WSL2** fully supports **GUI apps**](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps), but Cubic **will not work**. It shows the following message when run using `cubic`:
```bash
(cubic:16525): Gtk-CRITICAL **: 17:30:34.151: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(cubic:16525): Gtk-CRITICAL **: 17:30:34.152: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(cubic:16525): Gtk-CRITICAL **: 17:30:34.152: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault (core dumped)
```

**To Reproduce**

- Install Ubuntu 22.04.02 LTS from Microsoft Store
- Enter initial setup information and follow the Cubic installation instructions for Ubuntu
- Run `cubic` in the command prompt.

**Expected behavior**

The GTK window should open.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 22.04 LTS

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.09.84
 - ISO Customizing: N/A
 - Download Link: N/A

**Cubic Log:**

```bash
Cubic - Custom Ubuntu ISO Creator

  • Set application directory.............. /usr/share/cubic
  • Set application user home.............. /home/kneesdev
  • Execute synchronously.................. dpkg-query
                                            --admindir="/var/lib/dpkg" --show
                                            --showformat="${Version} " "cubic"
  • The process id is...................... 16539
  • Set application cubic version.......... 2023.09-84-
                                            release~202309300046~ubuntu22.04.1
  • Set application kernel version......... 4.4.0-19041-Microsoft

(cubic:16535): Gtk-CRITICAL **: 17:35:30.250: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(cubic:16535): Gtk-CRITICAL **: 17:35:30.251: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(cubic:16535): Gtk-CRITICAL **: 17:35:30.252: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault (core dumped)
```

**Comment by ohjhas** [comment]
i dont remember how i do that but, i use cubic on my WSL2 windows 10 completely, it works like a charm, i think u need some gtk related dependencies, i dont know which

**Comment by HumbleDeer** [comment]
Can you check again with a fresh installation of the distro? I suspect you may be missing some paths or dependencies that are usually pre-defined or pre-installed. This error should not be happening in WSL2 because there's nothing about the specific error's components that's different in WSL2.

Alternatively, check with and without sudo. there's a root and user binary directory and using sudo uses the root one.

**Comment by leeteral** [comment]
Hello, it does work with WSL2. I was apparently still using WSL1 then, sorry.

**Comment by HumbleDeer** [comment]
> Hello, it does work with WSL2. I was apparently still using WSL1 then, sorry.

Great to hear.
