### ISSUE TITLE
Cubic gets stuck at 50% during "Copy Selected Boot Kernel files to the disk"

### ISSUE THREAD

**Issue by ContractISover** [PJ-Singh-001/Cubic#277]
Bug: Cubic gets stuck at 50% during "Copy Selected Boot Kernel files to the disk"

To Reproduce: Idk, sometimes happens and sometimes doesn't. 

OS Information:
 - OS/Distro Name: Debian
 - OS Version: 12.0.2
Cubic Information:
 - Cubic Version: 2023.09.84
 - ISO Customizing: debian-live-12.2.0-amd64-gnome.iso
 - Download Link:  https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/
**Cubic Log:**

  Copy file number 1 of 2                  

  • The source file path is................ /home/saddam/cubic-pro/custom-root/b
                                            oot/vmlinuz-6.5.0-0.deb12.1-amd64   
  • The target file path is................ /home/saddam/cubic-pro/custom-      
                                            disk/live/vmlinuz                   
  • Started process thread id.............. 139859579094720          
  • Process started by thread id........... 139859949778624                     
  • The process started at................. 19:04:16.547832                     
  • Execute asynchronously................. copy-path /home/saddam/cubic-       
                                            pro/custom-root/boot/vmlinuz-6.5.0- 
                                            0.deb12.1-amd64 /home/saddam/cubic- 
                                            pro/custom-disk/live/vmlinuz saddam 
  • The process id is...................... 17290                               
  • The process finished at................ 19:04:16.781214                     
  • The exit status, signal status is...... 0, None                             
  • The message is......................... 0.00kB/s    0:00:00 (xfr#0, to-     
                                            chk=0/1)                            
  • Stopped process thread id.............. 139859579094720          
  • Adjust the final percent............... from 0.00% to 100.00%               
  • Completed.............................. 10%                                 
  • Completed.............................. 20%                                 
  • Completed.............................. 30%                                 
  • Completed.............................. 40%                                 
  • Completed.............................. 50%                                 
  • The custom OS distribution is.......... nabatean                            
Exception in thread Thread-8 (navigate):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/cubic/cubic/navigator.py", line 613, in navigate
    result = new_page.enter(action, page) if new_page else None
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cubic/cubic/pages/generate_page.py", line 144, in enter
    is_error = copy_kernel_files()
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cubic/cubic/pages/generate_page.py", line 377, in copy_kernel_files
    is_pop_os_based = constructor.os_is_distribution('pop', model.project.custom_root_directory)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cubic/cubic/utilities/constructor.py", line 246, in os_is_distribution
    key, value = line.split('=', 1)
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Screenshots**

![Screenshot from 2023-12-05 18-29-13](https://github.com/PJ-Singh-001/Cubic/assets/153002750/ea3dec18-1c1d-411c-8858-72c9280ec2c5)

**Comment by PJ-Singh-001** [comment]
What is the output of:

    cat /etc/os-release

(Execute this from the [Terminal](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) in Cubic).

**Comment by PJ-Singh-001** [comment]
This issue looks like it is similar to https://github.com/PJ-Singh-001/Cubic/issues/273.
I won't know for sure until I see your `/etc/os-release` file.

**Comment by RieanTheCatboy** [comment]
> This issue looks like it is similar to #273. I won't know for sure until I see your `/etc/os-release` file.

Okay, https://pastebin.com/FaF367Nh
I'd like to note that during the customization of the ISO, I did edit /etc/os-release so here is the original. https://pastebin.com/btuKhUQV

**Comment by PJ-Singh-001** [comment]
My understanding is that you get this error when customizing the ISO using the Updated version of `/etc/os-release` but not when you try to customize the ISO containing the original version of `/etc/os-release`.

Do you always get this error when customizing  the ISO using the Updated version of `/etc/os-release`?

Original `/etc/os-release`:

    PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
    NAME="Debian GNU/Linux"
    VERSION_ID="12"
    VERSION="12 (bookworm)"
    VERSION_CODENAME=bookworm
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"

Updated `/etc/os-release`:

    PRETTY_NAME="Nabatean GNU+Linux 1.9 Beta1"
    NAME="Nabatean GNU+Linux"
    VERSION_ID="1.9"
    VERSION="1.9 (Beta1)"
    VERSION_CODENAME=Beta1
    ID=nabatean
    HOME_URL="https://codeberg.org/contractover/Nabatean-gnulinux"
    SUPPORT_URL="https://codeberg.org/contractover/Nabatean-gnulinux"
    BUG_REPORT_URL="https://codeberg.org/contractover/Nabatean-gnulinux"

**Comment by PJ-Singh-001** [comment]
Would you please check if there is an empty line immediately following `ID=nabatean` in `/etc/os-release`?

(In the file you pasted to pastebin, there was no empty line, but this is the only thing I could come up with that could cause the error you reported).

**Comment by PJ-Singh-001** [comment]
Please let me know if the following patch woks?

 1. Copy the following text and save it to a file named `constructor.patch`.

        *** constructor.original.py	2023-10-31 00:14:56.769665241 -0400
        --- constructor.py	2023-12-06 21:06:26.112335337 -0500
        ***************
        *** 211,215 ****
                          key, value = line.split('=', 1)
        !                 key = key.upper() if key else None
                          if key == 'ID':
        !                     distribution = value.rstrip().lower() if value else None
                              break
        --- 211,215 ----
                          key, value = line.split('=', 1)
        !                 key = key.strip().upper() if key else None
                          if key == 'ID':
        !                     distribution = value.strip().lower() if value else None
                              break
        ***************
        *** 245,249 ****
                      for line in file:
                          key, value = line.split('=', 1)
        !                 key = key.upper() if key else None
        !                 value = value.rstrip().lower() if value else None
                          if key == 'ID':
        --- 245,252 ----
                      for line in file:
        +                 line = line.strip()
        +                 if not line: continue
        +                 if line.startswith('#'): continue
                          key, value = line.split('=', 1)
        !                 key = key.strip().upper() if key else None
        !                 value = value.strip().lower() if value else None
                          if key == 'ID':

 2. Execute the following command to apply the patch:

        cd <directory where you saved constructor.patch>
        sudo patch /usr/share/cubic/cubic/utilities/constructor.py constructor.patch

**Comment by RieanTheCatboy** [comment]
> Do you always get this error when customizing the ISO using the Updated version of `/etc/os-release`?

No, sometimes I get this issue and sometimes I don't.

>Please let me know if the following patch woks?

Yes, I have just tested and everything works now. :)

**Comment by PJ-Singh-001** [comment]
Thank you for testing.
I will issue a new release this month with the fix.

**Comment by PJ-Singh-001** [comment]
Fix released in Cubic version 2023.12-85.
