### ISSUE TITLE
Can not add ppa in ubuntu 22.04 of virtual box

### ISSUE THREAD

**Issue by henaiguo** [PJ-Singh-001/Cubic#278]
**Describe the question**

Hi, when I execute the following command to add Cubic's PPA, it fails  
`sudo apt-add-repository ppa:cubic-wizard/release`    
  
This is error message
![111](https://github.com/PJ-Singh-001/Cubic/assets/14122312/1da5f839-8cb3-404b-bbec-213e9441f9f6)

**What you have tried**

Later on, I manually added the PPA, but it still couldn't be installed    
```
sudo apt-add-repository universe
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B7579F80E494ED3406A59DF9081525E2B4F1283B
sudo apt update
sudo apt install --no-install-recommends cubic  
```

**OS Info**
 - ubuntu 22.04 in VirtualBox 7.0

**Comment by PJ-Singh-001** [comment]
This looks like an issue with your installation. Make sure you have installed and updated Ubuntu correctly. Also, make sure you have the latest version of `software-properties-common` package.

**Comment by henaiguo** [comment]
Thank you for your reply！  
After reinstalling the brand new Ubuntu 22.04 on virtualbox or vmware player, I still cannot add PPA. In addition, `software properties common` is also the latest. Is there any way to confirm that the installation is correct

**Comment by henaiguo** [comment]
I found the problem myself, it was the local network operator who blocked access to this part
