### ISSUE TITLE
Xorriso has some errors when customizing the ISO.

### ISSUE THREAD

**Issue by ghost** [PJ-Singh-001/Cubic#28]
**Describe the bug**
---
When generating the ISO, Cubic will encounter some problems

**To Reproduce**
---
1. Download Ubuntu 20.04 
2. Remove Zsys 
3. Install i3,rice it, add a PPA for a Liquorix kernel and for the latest Mesa drivers  
4. Generate the ISO.

**Expected behavior**
---
Cubic should generate the ISO just fine

**OS Information (please complete the following information):**
---
 - OS/Distro Name: Pop!_OS
 - OS Version: Pop!_OS 21.10

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.01.70
 - ISO Customizing: ubuntu-20.04-desktop-amd64.iso
 - Download Link:  https://tux.rainside.sk/ubuntu-releases/focal/

**Cubic Log:**
---
```
_PyErr_SetObject: exception EOF("End
                                            Of File (EOF). Exception style      
                                            platform.\n<pexpect.pty_spawn.spawn 
                                            object at 0x7fd697bc98b0>\ncommand: 
                                            /usr/bin/xorriso\nargs:             
                                            [b'/usr/bin/xorriso', b'-as',       
                                            b'mkisofs', b'-r', b'-J', b'-joliet-
                                            long', b'-l', b'-iso-level', b'3',  
                                            b'-V', b'MatuusOS', b'-isohybrid-   
                                            mbr', b'--interval:local_fs:0s-15s:z
                                            ero_mbrpt,zero_gpt,zero_apm:/home/ma
                                            tus/projects/MatuusOS-on-           
                                            Ubuntu/partition-1.img',            
                                            b'-partition_cyl_align', b'on',     
                                            b'-partition_offset', b'0',         
                                            b'-partition_hd_cyl', b'184',       
                                            b'-partition_sec_hd', b'32', b'--   
                                            mbr-force-bootable', b'-apm-block-  
                                            size', b'2048',                     
                                            b'-iso_mbr_part_type', b'0x00',     
                                            b'-c', b'/isolinux/boot.cat', b'-b',
                                            b'/isolinux/isolinux.bin', b'-no-   
                                            emul-boot', b'-boot-load-size',     
                                            b'4', b'-boot-info-table',          
                                            b'-eltorito-alt-boot', b'-e',       
                                            b'/boot/grub/efi.img', b'-no-emul-  
                                            boot', b'-boot-load-size', b'8000', 
                                            b'-isohybrid-gpt-basdat',           
                                            b'-isohybrid-apm-hfsplus', b'-o',   
                                            b'/home/matus/projects/MatuusOS-on- 
                                            Ubuntu/MatuusOS-semirolling.iso',   
                                            b'.']\nbuffer (last 100 chars):     
                                            ''\nbefore (last 100 chars): '      
                                            failure with writing.\\r\\nxorriso :
                                            NOTE : -return_with SORRY 32        
                                            triggered by problem severity       
                                            FATAL\\r\\n'\nafter: <class         
                                            'pexpect.exceptions.EOF'>\nmatch:   
                                            None\nmatch_index: None\nexitstatus:
                                            None\nflag_eof: True\npid:          
                                            22122\nchild_fd: 31\nclosed:        
                                            False\ntimeout: 300\ndelimiter:     
                                            <class                              
                                            'pexpect.exceptions.EOF'>\nlogfile: 
                                            None\nlogfile_read:                 
                                            None\nlogfile_send: None\nmaxread:  
                                            2000\nignorecase:                   
                                            False\nsearchwindowsize:            
                                            None\ndelaybeforesend:              
                                            0.05\ndelayafterclose:              
                                            0.1\ndelayafterterminate:           
                                            0.1\nsearcher: searcher_re:\n    0: 
                                            re.compile('[0-9]{1,3}(\\\\.[0-9]{2}
                                            ){0,1}%')\nmessage: xorriso 1.5.2 : 
                                            RockRidge filesystem manipulator,   
                                            libburnia project.\n\nDrive current:
                                            -outdev 'stdio:/home/matus/projects/
                                            MatuusOS-on-Ubuntu/MatuusOS-        
                                            semirolling.iso'\nMedia current:    
                                            stdio file, overwriteable\nMedia    
                                            status : is blank\nMedia summary: 0 
                                            sessions, 0 data blocks, 0 data,    
                                            1666g free\nxorriso : WARNING :     
                                            -volid text does not comply to ISO  
                                            9660 / ECMA 119 rules\nAdded to ISO 
                                            image: directory                    
                                            '/'='/home/matus/projects/MatuusOS- 
                                            on-Ubuntu/custom-disk'\nxorriso :   
                                            UPDATE :    1042 files added in 1   
                                            seconds\nxorriso : UPDATE :    1042 
                                            files added in 1 seconds\nxorriso : 
                                            NOTE : Copying to System Area: 32768
                                            bytes from file '--interval:local_fs
                                            :0s-15s:zero_mbrpt,zero_gpt,zero_apm
                                            :/home/matus/projects/MatuusOS-on-  
                                            Ubuntu/partition-1.img'\nlibisofs:  
                                            WARNING : Cannot add /dists/stable  
                                            to Joliet tree. Symlinks can only be
                                            added to a Rock Ridge               
                                            tree.\nlibisofs: WARNING : Cannot   
                                            add /dists/unstable to Joliet tree. 
                                            Symlinks can only be added to a Rock
                                            Ridge tree.\nlibisofs: WARNING :    
                                            Cannot add /ubuntu to Joliet tree.  
                                            Symlinks can only be added to a Rock
                                            Ridge tree.\nlibisofs: NOTE :       
                                            Automatically adjusted MBR geometry 
                                            to 1022/206/32\nlibisofs: NOTE :    
                                            Aligned image size to cylinder size 
                                            by 1307 blocks\nxorriso : UPDATE :  
                                            Thank you for being patient. Working
                                            since 0 seconds.\nlibburn : SORRY : 
                                            Failed to open device (a pseudo-    
                                            drive) : Permission denied\nlibburn 
                                            : FATAL : Burn run failed\nxorriso :
                                            FATAL : -abort_on 'FAILURE'         
                                            encountered 'FATAL' during image    
                                            writing\nxorriso : NOTE : libburn   
                                            has now been urged to cancel its    
                                            operation\nxorriso : UPDATE : Thank 
                                            you for being patient. Working since
                                            2 seconds.\nxorriso : UPDATE : Thank
                                            you for being patient. Working since
                                            3 seconds.\nxorriso : UPDATE : Thank
                                            you for being patient. Working since
                                            3 seconds.\nxorriso : UPDATE : Thank
                                            you for being patient. Working since
                                            4 seconds.\nlibisofs: MISHAP : Image
                                            write cancelled\nxorriso : FAILURE :
                                            libburn indicates failure with      
                                            writing.\nxorriso : NOTE :          
                                            -return_with SORRY 32 triggered by  
                                            problem severity FATAL") is not a   
                                            BaseException subclass              

```

**Screenshots**
---
![Snímka obrazovky z 2022-02-27 17-36-42](https://user-images.githubusercontent.com/76532262/155891063-9d53725d-ed7c-4966-8ed2-0bbc541943c7.png)

**Comment by PJ-Singh-001** [comment]
I was not able to reproduce this issue, and I was able to successfully generate the custom ISO.

- I installed Pop!_OS 21.10 using `pop-os_21.10_amd64_intel_6.iso`.
- I did not modify or update Pop!_OS.
- I installed Cubic version 2022.01.70.
- I selected `ubuntu-20.04.3-desktop-amd64.iso` to customize in Cubic.
- I did not make any changes to Ubuntu 20.04, since we are looking for bugs in Cubic (as opposed to issues with the OS being customized).

Here is the screenshot of the Generate page:

![image](https://user-images.githubusercontent.com/19394936/155901853-36150347-34cb-4d7d-af2c-2d0ff352b26e.png)

The log output shows no issues:

    Create disk image

    • Started process thread id.............. 140628797392448
    • Process started by thread id........... 140628780607040
    • The process started at................. 16:56:21.523465
    • Execute asynchronously................. xorriso -as mkisofs -r -J -joliet-
                                              long -l -iso-level 3 -V 'Ubuntu
                                              20.04.3 2022.02.27 LTS' -isohybrid-
                                              mbr --interval:local_fs:0s-15s:zero_
                                              mbrpt,zero_gpt,zero_apm:'/home/user_
                                              1/Ubuntu/partition-1.img'
                                              -partition_cyl_align on
                                              -partition_offset 0
                                              -partition_hd_cyl 184
                                              -partition_sec_hd 32 --mbr-force-
                                              bootable -apm-block-size 2048
                                              -iso_mbr_part_type 0x00 -c
                                              '/isolinux/boot.cat' -b
                                              '/isolinux/isolinux.bin' -no-emul-
                                              boot -boot-load-size 4 -boot-info-
                                              table -eltorito-alt-boot -e
                                              '/boot/grub/efi.img' -no-emul-boot
                                              -boot-load-size 8000 -isohybrid-gpt-
                                              basdat -isohybrid-apm-hfsplus  -o "/
                                              home/user_1/Ubuntu/ubuntu-20.04.3-20
                                              22.02.27-desktop-amd64.iso" .
    • The process id is...................... 9225
    • Completed.............................. 10%
    • Completed.............................. 20%
    • Completed.............................. 30%
    • Completed.............................. 40%
    • Completed.............................. 50%
    • Completed.............................. 60%
    • Completed.............................. 70%
    • Completed.............................. 80%
    • Completed.............................. 90%
    • The process finished at................ 16:56:56.523512
    • The exit status, signal status is...... 0, None
    • The message is......................... done ISO image produced: 1499968
                                              sectors Written to medium : 1499968
                                              sectors at LBA 0 Writing to 'stdio:/
                                              home/user_1/Ubuntu/ubuntu-20.04.3-20
                                              22.02.27-desktop-amd64.iso'
                                              completed successfully.
    • Stopped process thread id.............. 140628797392448
    • Adjust the final percent............... from 97.55% to 100.00%
    • Completed.............................. 100%

Nevertheless, I noticed the following message in your log file:

    SORRY :
    Failed to open device (a pseudo-
    drive) : Permission denied\nlibburn
    : FATAL : Burn run failed\nxorriso :
    FATAL : -abort_on 'FAILURE'
    encountered 'FATAL' during image
    writing\nxorriso : NOTE : libburn
    has now been urged to cancel its
    operation\nxorriso : UPDATE : Thank
    you for being patient.

Questions:

- Do you have write permissions to the file system where your are generating the ISO file?
- Is it a Linux compatible file system such as (ext3)?
- Is there enough space on the file system?

**Comment by ghost** [comment]
1.  Yes
 2. Yes, it is. (ext4)
 3. I have like 1.6 TB on my disk space.

**Comment by PJ-Singh-001** [comment]
In this case, would you please share the full log from Cubic?

**Comment by PJ-Singh-001** [comment]
This bug has been open for a while.
I was not able to recreate your issue, so I can only debug the issue by looking at your full Cubic logs.
Whenever you are able to attach the full logs, please feel free to re-open this issue.
