### ISSUE TITLE
how to change linux kernel version in customized iso

### ISSUE THREAD

**Issue by ohjhas** [PJ-Singh-001/Cubic#280]
Describe the question
i i want to change kernel 6.2.0-39 to 5.15.145 from ubuntu kernel ppa in my customized lubuntu 22.04.3 iso, the live boots with that kernel, but, in the installed system in hard disk it boots with the 6.2 one

  What you have tried

i tried sudo apt autoremove linux-image-6.2.0-39-generic but it deletes important packages for the system working, i tried puging the kernel, i do that then reinstalling amd64-microcode, intel-microcode, iucode-tool and thermald but it reinstall the 6.2 kernel

  Expected behavior

i expected that 6.2.0 kernel will not install, and the system boots with the 5.15 one

 - OS/Distro Name: Lubuntu
 - OS Version 22.04.3 LTS

  Cubic Information 
 - Cubic Version: 2023.09.84
 - ISO Customizing: lubuntu-22.04.3-desktop-amd64.iso
 - Download Link:  https://cdimage.ubuntu.com/lubuntu/releases/jammy/release/lubuntu-22.04.3-desktop-amd64.iso
 -
sorry for my bad english

**Comment by PJ-Singh-001** [comment]
You are downgrading your kernel.
Nevertheless, the process is the same as installing an updated or newer kernel.
The kernel files you are installing must be available in the repositories.

 1. Start with the unmodified 22.04.3 desktop ISO.
    _Do not uninstall_ your existing 6.2.0-39 kernel! (Theoretically, you could uninstall the existing kernel, but it sounds like this is also removing other important files on your system).

 2. Inside Cubic, on the [Terminal Page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page),...

        apt update
        apt install --reinstall linux-image-5.15.0-1007 linux-image-5.15.0-1007-generic
        update-initramfs -u

    This will ensure your installed OS runs kernel 5.15 by default.

 3. To confirm, list the newly installed kernel files.

        ls -la /boot

 5. If you also want to use kerne 5.15 in the Live Environment, on the [Options Page Kernel Tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), select the downgraded kernel. (You will have to remember to always select this kernel each time you update your Cubic project, because Cubic always assumes you want the newest available kernel).

**Comment by ohjhas** [comment]
> You are downgrading your kernel. Nevertheless, the process is the same as installing an updated or newer kernel. The kernel files you are installing must be available in the repositories.
> 
>     1. Start with the unmodified 22.04.3 desktop ISO.
>        _Do not uninstall_ your existing 6.2.0-39 kernel! (Theoretically, you could uninstall the existing kernel, but it sounds like this is also removing other important files on your system).
> 
>     2. Inside Cubic, on the [Terminal Page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page),...
>        ```
>        apt update
>        apt install --reinstall linux-image-5.15.0-1007 linux-image-5.15.0-1007-generic
>        update-initramfs -u
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        This will ensure your installed OS runs kernel 5.15 by default.
> 
>     3. To confirm, list the newly installed kernel files.
>        ```
>        ls -la /boot
>        ```
> 
>     4. If you also want to use kerne 5.15 in the Live Environment, on the [Options Page Kernel Tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), select the downgraded kernel. (You will have to remember to always select this kernel each time you update your Cubic project, because Cubic always assumes you want the newest available kernel).

thank you, it fixed! another question, i can customize the debian 12 lxde iso with cubic or only i can ubuntu?

**Comment by PJ-Singh-001** [comment]
You're welcome.

It's usually good open a new issue to ask a different question.
However, Cubic does support customizing Debian.

Here are some [Debian related questions that have been answered](https://github.com/PJ-Singh-001/Cubic/issues?q=is%3Aissue+is%3Aclosed+Debian).

Also, see [this](https://github.com/PJ-Singh-001/Cubic/wiki/About-Cubic) and [this](https://github.com/PJ-Singh-001/Cubic/wiki/Install-Cubic#-debian-and-derivatives).

**Comment by KittyBua** [comment]
> > You are downgrading your kernel. Nevertheless, the process is the same as installing an updated or newer kernel. The kernel files you are installing must be available in the repositories.
> > ```
> > 1. Start with the unmodified 22.04.3 desktop ISO.
> >    _Do not uninstall_ your existing 6.2.0-39 kernel! (Theoretically, you could uninstall the existing kernel, but it sounds like this is also removing other important files on your system).
> > 
> > 2. Inside Cubic, on the [Terminal Page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page),...
> >    ```
> >    apt update
> >    apt install --reinstall linux-image-5.15.0-1007 linux-image-5.15.0-1007-generic
> >    update-initramfs -u
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    This will ensure your installed OS runs kernel 5.15 by default.
> > 
> > 3. To confirm, list the newly installed kernel files.
> >    ```
> >    ls -la /boot
> >    ```
> > 
> > 4. If you also want to use kerne 5.15 in the Live Environment, on the [Options Page Kernel Tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), select the downgraded kernel. (You will have to remember to always select this kernel each time you update your Cubic project, because Cubic always assumes you want the newest available kernel).
> > ```
> 
> thank you, it fixed! another question, i can customize the debian 12 lxde iso with cubic or only i can ubuntu?

But first, you need to add the focal source; otherwise, cubic won't find the 5.15 kernel.

nano /etc/apt/sources.list

deb http://archive.ubuntu.com/ubuntu/ focal main restricted
deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted
deb http://archive.ubuntu.com/ubuntu/ focal-security main restricted
deb http://archive.ubuntu.com/ubuntu/ focal universe multiverse
deb http://archive.ubuntu.com/ubuntu/ focal-updates universe multiverse
deb http://archive.ubuntu.com/ubuntu/ focal-security universe multiverse


apt update 

apt install linux-image-5.15.0-78-generic linux-headers-5.15.0-78-generic

update-initramfs -u

**Comment by KittyBua** [comment]
and this Work 

apt install linux-image-5.15.0-78-generic linux-headers-5.15.0-78-generic

No this added

apt install --reinstall linux-image-5.15.0-1007 linux-image-5.15.0-1007-generic

This fail

**Comment by ohjhas** [comment]
> > > You are downgrading your kernel. Nevertheless, the process is the same as installing an updated or newer kernel. The kernel files you are installing must be available in the repositories.
> > > ```
> > > 1. Start with the unmodified 22.04.3 desktop ISO.
> > >    _Do not uninstall_ your existing 6.2.0-39 kernel! (Theoretically, you could uninstall the existing kernel, but it sounds like this is also removing other important files on your system).
> > > 
> > > 2. Inside Cubic, on the [Terminal Page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page),...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > apt update
> > > apt install --reinstall linux-image-5.15.0-1007 linux-image-5.15.0-1007-generic
> > > update-initramfs -u
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This will ensure your installed OS runs kernel 5.15 by default.
> > > 
> > > 3. To confirm, list the newly installed kernel files.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ls -la /boot
> > > ```
> > > 
> > > 4. If you also want to use kerne 5.15 in the Live Environment, on the [Options Page Kernel Tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#kernel-tab), select the downgraded kernel. (You will have to remember to always select this kernel each time you update your Cubic project, because Cubic always assumes you want the newest available kernel).
> > > ```
> > 
> > 
> > thank you, it fixed! another question, i can customize the debian 12 lxde iso with cubic or only i can ubuntu?
> 
> But first, you need to add the focal source; otherwise, cubic won't find the 5.15 kernel.
> 
> nano /etc/apt/sources.list
> 
> deb http://archive.ubuntu.com/ubuntu/ focal main restricted deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted deb http://archive.ubuntu.com/ubuntu/ focal-security main restricted deb http://archive.ubuntu.com/ubuntu/ focal universe multiverse deb http://archive.ubuntu.com/ubuntu/ focal-updates universe multiverse deb http://archive.ubuntu.com/ubuntu/ focal-security universe multiverse
> 
> apt update
> 
> apt install linux-image-5.15.0-78-generic linux-headers-5.15.0-78-generic
> 
> update-initramfs -u

i posted this issue and closed it almost 3 years ago gng
dude im crine 😭
