### ISSUE TITLE
how to remove snapd on custom iso?

### ISSUE THREAD

**Issue by ohjhas** [PJ-Singh-001/Cubic#281]
hi, again with my lubuntu customized iso, i want to remove snap on the customized iso, but when i do auso apt autoremove snapd or sudo apt autoremove --purge snapd it will uninstall squashfs-tools, and when i uninstall snapd but i install squashfs-tools again, it will install automatically snapd, the package i dont want to be on my system cuz snap is too slow and too heavy and it consumes ram

**Comment by hasanmerkit** [comment]
There are multiple squashfs files in the new Ubuntu ISO files. (Example: Ubuntu 23.10 and Ubuntu 24.04) And Cubic organizes only one of them. This is why Snapd is available in multiple locations. I think Cubic developer should review this after Ubuntu 24.04 is released. A solution will be found for this.

Anyway, the new Ubuntu installation also works via Snap. However, if you want to remove it, you will need to manually chroot outside of Cubic.

**Comment by PJ-Singh-001** [comment]
I use the following to remove `snapd` and it works for me:

    apt purge snapd gnome-software-plugin-snap

According to the [Package information for `snapd`](https://packages.ubuntu.com/mantic/snapd), `snapd` depends on `squashfs-tools`.

But according the [Package information for `squashfs-tools`](https://packages.ubuntu.com/mantic/squashfs-tools), `squashfs-tools` does not depend on `snapd`.

Therefore, when you install `squashfs-tools`, `snapd` should not be automatically reinstalled.

There is something else causing `snapd` to be reinstalled.
