### ISSUE TITLE
"Close" button in the About dialog doesn't work

### ISSUE THREAD

**Issue by danimesq** [PJ-Singh-001/Cubic#282]
**Describe the bug**

Can't close the About dialog via the "Close" button.

**To Reproduce**

1. Click the sandwich button
2. Click "About Cubic"
3. Try to click "Close" in the bottom-right button: it won't close; I'll have to click the "X" of your DE/Window Manager

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: 23.10
 - DE: Cinnamon

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.09.84

**Comment by PJ-Singh-001** [comment]
Thanks for reporting this.
Please note, upgrade to the latest version of Cubic, version 2023.12-85.

Nevertheless, the "Close" button in the About Dialog in Cinnamon is a known issue.
This has to do with GTK3 which does not show the "Close" button in About Dialogs.
Other DEs still show this button, but it does not work.

I will add this to my backlog.

**Comment by PJ-Singh-001** [comment]
Update:

I looked at this again. It seems Cinnamon is adding the close button to the `GtkButtonBox`.

The GTK3 `GtkButtonBox` container does not have any buttons by default. Therefore, there is no button widget, so I can't add a signal to capture a button press event.

**Comment by PJ-Singh-001** [comment]
The solution is to add a handler for the About dialog's `response` signal.
We can reuse the `on_close_about_dialog` handler from the About dialog's `delete-event` signal.

**Comment by PJ-Singh-001** [comment]
Fix released in Cubic version 2024.09-89.
