### ISSUE TITLE
How to detect Cubic?

### ISSUE THREAD

**Issue by danimesq** [PJ-Singh-001/Cubic#283]
I want my [install scripts](https://github.com/Floflis/Floflis-DNA) to detect when they're running on Cubic, so they'll perform custom actions tailored specifically for Cubic.

Many thanks in advance 🙏

**Comment by hasanmerkit** [comment]
Maybe you want to do chroot detection? Cubic is a great tool that does this.

**Comment by RieanTheCatboy** [comment]
I'm not 100% sure, but you could probably grep the cubic host name and have it detect it based on that.

**Comment by PJ-Singh-001** [comment]
Checking the host name is a good way to do this...

    root@cubic:~ # hostname
    cubic
