### ISSUE TITLE
Preseeding Ubuntu 22.04 Desktop Troubles

### ISSUE THREAD

**Issue by mikejp56** [PJ-Singh-001/Cubic#284]
**Describe the question**
I am trying to preseed some settings in Ubuntu 22.04 desktop and I am having major problems. I can only get the full name, user name, and auto login to fill in correctly. I have had no luck creating a normal user, setting a clear text password, setting the locale/location/time zone, setting the installation type, and the keyboard.

**What you have tried**
I have used multiple examples from the 'net to no avail. I have tried using d-i and ubiquity. I just cannot grasp the workings of cloud-init.

Steps you already took.
I have spent hours and hours checking syntax and spelling, and changing from one person's example to the next without any success.
**Expected behavior**
a properly preseeded ubuntu 22.04 desktop install.

a properly preseeded ubuntu 22.04 desktop instal

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu Jammy Jellyfish
 - OS Version: Ubuntu 22.04 Desktop

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.12.85
 - ISO Customizing: ubuntu-22.04.3-desktop-amd64.iso
 - Download Link: https://ubuntu.com/download

**Screenshots**

**Comment by mikejp56** [comment]
EDIT:
I have already seen post #266 and tried his commands using d-i and ubiquity to no avail.

**Comment by gitgonewithwind** [comment]
@mikejp56  can you successfully create ubuntu 22.04  Desktop ISO image?
