### ISSUE TITLE
Não consigo fazer "apt upgrade" no ubuntu 22.04 

### ISSUE THREAD

**Issue by joaopedrordeo** [PJ-Singh-001/Cubic#286]
Não consigo fazer "apt upgrade" no ubuntu 22.04 .
Após o erro não consigo instalar nada 

![Captura de tela 2024-01-21 201836](https://github.com/PJ-Singh-001/Cubic/assets/45084266/20eb7bf5-5cae-437e-b369-d08b1310751a)

**Comment by PJ-Singh-001** [comment]
Does this help?...
Isso ajuda?...
#162, [zsys daemon error](https://github.com/PJ-Singh-001/Cubic/issues/162)
