### ISSUE TITLE
How to customize icons on the Ubiquity Try / Install screen?

### ISSUE THREAD

**Issue by ghost** [PJ-Singh-001/Cubic#288]
**Describe the question**
I want to change the image displayed during the installation of Ubuntu 20.04.1, which typically features the Ubuntu logo inside a laptop. I have already replaced 'Try Ubuntu' with 'Try l1feOS,' and now I want to customize the image by replacing it with my own.

**OS Information :**
 - OS/Distro Name: Ubuntu
 - OS Version : Ubuntu 20.04.3

**Cubic Information :**
 - Cubic Version: 2023.12.85
 - ISO Customizing:  ubuntu-22.04.3-desktop-amd64.iso
 - Download Link:  https://ubuntu.com/download/desktop

**Screenshots**
![Screenshot from 2024-02-06 21-07-25](https://github.com/PJ-Singh-001/Cubic/assets/87390719/8c98b0e7-a3d4-4bfc-9904-209a0bb1e455)

**Comment by PJ-Singh-001** [comment]
This isn't the slide show, so I have changed your question title accordingly.

The icon you  are looking for is from the `ubiquity-frontend-gtk` package.
It is located in `/usr/share/ubiquity/pixmaps` folder.
The icon name is `ubuntu_installed.png`
