### ISSUE TITLE
Unable to calculate checksum

### ISSUE THREAD

**Issue by MacroHard-Winux** [PJ-Singh-001/Cubic#289]
**Describe the bug**

When building a Linux Mint 21.3 (edited or unedited) Cubic sill stuck at "Update the checksums for all files on the disk" with the error "Error. Unable to cacluate checksums.
![image](https://github.com/PJ-Singh-001/Cubic/assets/129944538/87d1eebe-df8f-4f22-9e09-74458be09d2a)

**To Reproduce**

Download Linux Mint 21.3 cinnamon iso. open Cubic, load the iso and build

**Expected behavior**

The iso should finished building 

**OS Information (please complete the following information):**
 - OS/Distro Name: Debian sid

**Cubic Information (please complete the following information):**
 - Cubic Version: 2023.05.83
 - ISO Customizing: linuxmint-21.3-cinnamon-64bit.iso
 - Download Link:  http://ucmirror.canterbury.ac.nz/linux/mint/isos/stable/21.3/linuxmint-21.3-cinnamon-64bit.iso

**Comment by MacroHard-Winux** [comment]
cubic --verbose > log.txt :
[log.txt](https://github.com/PJ-Singh-001/Cubic/files/14216921/log.txt)

on line 1111 it says [Errno 2] No such file or directory:
                                            '/home/ascend910/cubic/Winux7Basic/c
                                            ustom-disk/EFI/boot/bootx64.efi' 

But the file does exist
ls /home/ascend910/cubic/Winux7Basic/custom-disk/EFI/boot
bootia32.efi  bootx64.efi  grubx64.efi
weirdly bootx64.efi is red maybe a problom with Cubic unpacking the iso???

**Comment by PJ-Singh-001** [comment]
Red usually means this is a link to a file, and the file it links to does not exist.

You can see which file this links points to by typing

    ls -la

...or...

    readlink -f bootx64.efi

Nevertheless, thank you for attaching your log file; I'll look into this.

**Comment by PJ-Singh-001** [comment]
For reference, the relevant portion of the log file is...

    • Exclude files from the checksum........ ['/home/ascend910/cubic/Winux7Basic/
                                              custom-disk/md5sum.txt', '/home/asce
                                              nd910/cubic/Winux7Basic/custom-     
                                              disk/isolinux/isolinux.bin', '/home/
                                              ascend910/cubic/Winux7Basic/custom- 
                                              disk/isolinux/boot.cat']            
    • Get relative file paths in the      
      directory.............................. /home/ascend910/cubic/Winux7Basic/cu
                                              stom-disk                           
    • Write to file.......................... /home/ascend910/cubic/Winux7Basic/cu
                                              stom-disk/md5sum.txt                
    • Unable to calculate the md5 hash for
      file................................... EFI/boot/bootx64.efi                
    • The exception is....................... [Errno 2] No such file or directory:
                                              '/home/ascend910/cubic/Winux7Basic/c
                                              ustom-disk/EFI/boot/bootx64.efi'    
    • The trace back is...................... Traceback (most recent call last):  
                                              File "/usr/share/cubic/cubic/utiliti
                                              es/file_utilities.py", line 916, in 
                                              calculate_md5_hash     with         
                                              open(full_file_path, 'rb') as file: 
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^          
                                              FileNotFoundError: [Errno 2] No such
                                              file or directory: '/home/ascend910/
                                              cubic/Winux7Basic/custom-           
                                              disk/EFI/boot/bootx64.efi'          
    • Error.................................. Unable to update checksums          
    • The exception is....................... [Errno 2] No such file or directory:
                                              '/home/ascend910/cubic/Winux7Basic/c
                                              ustom-disk/EFI/boot/bootx64.efi'    
    • Do not propagate exception............. [Errno 2] No such file or directory:
                                              '/home/ascend910/cubic/Winux7Basic/c
                                              ustom-disk/EFI/boot/bootx64.efi'

**Comment by MacroHard-Winux** [comment]
ls -la:
lrwxrwxrwx 1 ascend910 ascend910      36 Feb  9 13:42 bootx64.efi -> /etc/alternatives/shimx64.efi.signed

readlink -f bootx64.efi:
/etc/alternatives/shimx64.efi.signed

**Comment by PJ-Singh-001** [comment]
`bootx64.efi` is a link to `/etc/alternatives/shimx64.efi.signed`, but `/etc/alternatives/shimx64.efi.signed` doesn't exist.

I've downloaded the linuxmint-21.3-cinnamon-64bit.iso ISO you shared...
- I see that `<ISO>/EFI/boot/bootx64.efi` is a link.
- This link does point to `<ISO>/etc/alternatives/shimx64.efi.signed`.
- However, there is no `/etc` directory on the ISO.

I compared this to `linuxmint-21.1-cinnamon-64bit.iso`.
- This 2.21 ISO does not have this superfluous link in the `<ISO>/EFI/boot/` directory.

Therefore, this is a bug in the Linux Mint 21.3 ISO. 

However, I will modify Cubic to ignore missing files (i.e. broken links) when calculating the checksum.

It will take me a few day to issue a new Cubic release.
In the meant time, you might want to open a bug with Linux Mint to correct this issue at the source.

**Comment by MacroHard-Winux** [comment]
ok thx :)

**Comment by PJ-Singh-001** [comment]
This is interesting.

I just tested Cubic using the [linuxmint-21.3-cinnamon-64bit.iso](http://ucmirror.canterbury.ac.nz/linux/mint/isos/stable/21.3/linuxmint-21.3-cinnamon-64bit.iso) file you linked to above.

I did not get the same error as you reported.

Even though, `<ISO>/EFI/boot/bootx64.efi` is a broken link, it should still have a md5 checksum.
It is also a file that appears on the ISO, and all files on the ISO need a checksum.
So my original idea, to not calculate the checksum for broken symlinks, is not the correct approach.

Which OS and version are you running Cubic in?

     lsb_release --all

Which version of Python do you have?

    python3 --version

**Comment by PJ-Singh-001** [comment]
On your system (where you run Cubic), what are the outputs of these commands:

    cd /home/ascend910/cubic/Winux7Basic/custom-disk/EFI/boot/

    readlink -f bootx64.efi

    file bootx64.efi
    
    file `readlink -f bootx64.efi`
    
    md5sum bootx64.efi
    
    md5sum `readlink -f bootx64.efi`

**Comment by PJ-Singh-001** [comment]
Update:

> I did not get the same error as you reported.

My host system is Ubuntu, and the `<ISO>/EFI/boot/bootx64.efi` actually resolves to `/etc/alternatives/shimx64.efi.signed` which exists on my system.

I suspect you are running Cubic with Linux Mint as your host OS, and `/etc/alternatives/shimx64.efi.signed` does not exist on a Linux Mint install. (Or perhaps, you do not have an EFI system).

I checked the man page for `md5sum`, but there was no explanation of how it behaves with symlinks.

However, I did find  [this accepted answer on stackoverflow](https://stackoverflow.com/a/44169620) which indicates that `md5sum` always follows symlinks and does not treat symlinks as individual files.

Note: Although Cubic does not directly invoke the `md5sum` command, the behavior of Cubic's implementation must be the same as the `md5sum` command.

**Comment by PJ-Singh-001** [comment]
The solution will be to **not** calculate the checksum for files that are symlinks.
Additionally, symlinks will not be listed in the `md5sum.txt` file (although the target files will still be listed along with their corresponding checksums).

**Comment by PJ-Singh-001** [comment]
Fix released in version 2024.02-86.

Please test, and report any issues.

**Comment by jpkuntz90** [comment]
> Fix released in version 2024.02-86.
> 
> Please test, and report any issues.

Same issue and always there for 21.3 Mate

**Comment by johncarterofmars** [comment]
I am running Mint 21.3 and trying to make a 21.3 ISO and also have the same issue. However, my error comes from something different. I will paste the portion of the log here - 
 • Unable to calculate the md5 hash for
    file................................... casper/filesystem.squashfs          
  • The exception is....................... [Errno 13] Permission denied: '/media/user/drive/Mint/custom-disk/casper/filesystem.squashfs'    
  • The trace back is...................... Traceback (most recent call last):  
                                            File "/usr/share/cubic/cubic/utilities/file_utilities.py", line 972, in 
                                            calculate_md5_hash with open(full_file_path, 'rb') as file: 
                                            PermissionError: [Errno 13]         
                                            Permission denied: '/media/user/drive/Mint/custom-               
                                            disk/casper/filesystem.squashfs'    
  • Error.................................. Unable to update checksums          
  • The exception is....................... [Errno 13] Permission denied: '/media/user/drive/Mint/custom-    
                                            disk/casper/filesystem.squashfs'    
  • Do not propagate exception............. [Errno 13] Permission denied: '/media/user/drive/Mint/custom-disk/casper/filesystem.squashfs'

**Comment by hatl** [comment]
I ran into the same issue.
I could work around it by running the following command:

```sh
sudo chmod a+r /path/to/my_live_cd/custom-disk/casper/filesystem.squashfs
```
