### ISSUE TITLE
Cubic appends ".. cubic...v..) name to the OS system name, how can I prevent this?

### ISSUE THREAD

**Issue by dat-linux** [PJ-Singh-001/Cubic#29]
Cubic adds its name to the OS system name, how can I prevent this?

**Comment by PJ-Singh-001** [comment]
Uncheck the "Update the release description" check box on the Project page.

![image](https://user-images.githubusercontent.com/19394936/155899339-c7a0d1ec-8009-4fb0-8ea7-8517e82192b6.png)

**Comment by PJ-Singh-001** [comment]
By the way, Cubic updates the "release description", not the OS name.

However, the "release description" is used in various GUI windows (such as System | About) in place of the OS name, which is why you see this.

**Comment by dat-linux** [comment]
I want the release description to show the custom info WITHOUT the "cubic.date.." part at the end. Cubic attaches extra info that should not be there.

**Comment by dat-linux** [comment]
I'm patching the code locally, but this part of the release descr. string should be removed.
`
#description = f'{model.custom.iso_volume_id} (Cubic {model.project.modify_date})'

description = f'{model.custom.iso_volume_id}'
`

Thanks for help.

**Comment by PJ-Singh-001** [comment]
1. On the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page), highlight the value for "Volume ID" (in the "Custom Disk" section). Then, from the right-click context menu, select "Copy" to save this value for later.

 2. Un-check the "Update the release description" check box, as show [above](https://github.com/PJ-Singh-001/Cubic/issues/29#issuecomment-1053676908). This will prevent Cubic from overwriting your changes in step 3.

 3. On the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), manually edit the following files with the copied value of "Volume ID" from step 1. Edit the values for `DISTRIB_DESCRIPTION` and `PRETTY_NAME`. (You can use [`nano`](https://www.nano-editor.org/dist/latest/cheatsheet.html) to edit these files).

        /etc/lsb-release
        /etc/os-release
        /usr/lib/os-release

**Comment by dat-linux** [comment]
You should never change the lsb_release for a respin. As it affects the apt repos, and anything else that depends on knowing what the release is (eg "xenial").

Please remove the "(Cubic {model.project.modify_date})" text in the code, it is not helpful to add this text to my release.

**Comment by PJ-Singh-001** [comment]
> lsb_release

@dat-linux,

You should never use the `lsb_release`'s `Description` value to check the release. If this is not helpful to your personal respin, I suggest correcting the package management code you wrote to not use this value. Otherwise, you may consider using `apt` as your package manager, which does not rely on the `Description` value.
