### ISSUE TITLE
unable to locate the compressed linux file system

### ISSUE THREAD

**Issue by naufalha** [PJ-Singh-001/Cubic#291]
![Screenshot 2024-02-12 095307](https://github.com/PJ-Singh-001/Cubic/assets/80652763/c5549845-2e9a-4bae-a624-96993bbc23c6)
i wanto customizing debian 11-dvd-netinst.iso
running this machine in virtualbox ubuntu 22
i have been trying using another iso like ubuntu 22 and debian 12
try running cubic with virtual machine ubuntu 20 still same

**Comment by PJ-Singh-001** [comment]
@naufalha,

In Github, you can [click on "Issues" and then click on "Closed,"](https://github.com/PJ-Singh-001/Cubic/issues?q=is%3Aissue+is%3Aclosed) to search if there is already an answer to your question.

You must download and customize the _Live_ ISO. The Network Install ISO is not a _Live_ Linux system.

Here are similar questions:

#276, [Unable to locate the compressed Linux file system on Debian 12](https://github.com/PJ-Singh-001/Cubic/issues/276)
#218, [Debian 12: cubic unable to locate the compressed linux file system](https://github.com/PJ-Singh-001/Cubic/issues/218)
#228, ["Unable to locate the compressed Linux File system" (Tried Debian 11.2, 11.6, and 11.7))](https://github.com/PJ-Singh-001/Cubic/issues/224)

**Comment by PJ-Singh-001** [comment]
By the way, you can download the Live ISOs for Debian from here:

https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/

(I assume you have an amd64 architecture).
