### ISSUE TITLE
(initramfs) /cow format specified as 'overlay' and no support found

### ISSUE THREAD

**Issue by ishaanbhimwal** [PJ-Singh-001/Cubic#293]
**Describe the bug**

I cannot boot into the iso. Receive this error:
```
(initramfs) /cow format specified as 'overlay' and no support found
```

**To Reproduce**

Steps to reproduce the behaviour.

* Add Ubuntu 20.04 iso and `apt update && apt upgrade`. That's it. I am selecting kernel `5.15-0.94`.

**OS Information (please complete the following information):**
 - Ubuntu 22.04 as base.

**Screenshots**

![306475121-4e6b3848-cdb4-4462-a4a8-f98cfd1ef497](https://github.com/PJ-Singh-001/Cubic/assets/79986754/a74c78e1-535d-42a9-b2c9-751d4c0853c7)

I would really appreciate your help @PJ-Singh-001. It's very important for me to generate these isos. Thanks!

**Comment by ishaanbhimwal** [comment]
There's also no installer page available if I boot into the iso. This error doesn't happen if I choose 5.15-0.67 as my default kernel. I wanted to change username and hostname so that's why I installed kernel 5.15-0.94 and edited and `/etc/casper.conf` and regenerated initrd files.

**Comment by ishaanbhimwal** [comment]
Fixed issue. Seems my `casper.conf` was edited wrong.

**Comment by PJ-Singh-001** [comment]
Glad you found the issue.
I was going to point you to https://github.com/PJ-Singh-001/Cubic/issues/189
