### ISSUE TITLE
How to create custom users on the login screen?

### ISSUE THREAD

**Issue by oldtime54** [PJ-Singh-001/Cubic#3]
I added custom user to iso and added to groups but when I boot the live iso and try to login it just brings me back to the login screen.

**Comment by PJ-Singh-001** [comment]
Please share the following details:
- OS/Distro Name
- OS/Distro Version
- Cubic Version
- Which `*.iso` are you customizing in Ubuntu?

I suspect the issue is not related to the users you've added.
Did you make any other customization?

**Comment by oldtime54** [comment]
Ubuntu 20.04.3
2021.12.67
Ubuntu 20.04.3

**Comment by PJ-Singh-001** [comment]
I tested using `ubuntu-20.04-desktop-amd64.iso`.

I created three users and added each user to the sudo group.

    You have entered the virtual environment.

    root@cubic:~# adduser user_1
    Adding user `user_1' ...
    Adding new group `user_1' (1000) ...
    Adding new user `user_1' (1000) with group `user_1' ...
    Creating home directory `/home/user_1' ...
    Copying files from `/etc/skel' ...
    New password: 
    Retype new password: 
    passwd: password updated successfully
    Changing the user information for user_1
    Enter the new value, or press ENTER for the default
	    Full Name []: User One
	    Room Number []: 
	    Work Phone []: 
	    Home Phone []: 
	    Other []: 
    Is the information correct? [Y/n] Y

    root@cubic:~# usermod -a -G sudo user_1

    root@cubic:~# adduser user_2
    Adding user `user_2' ...
    Adding new group `user_2' (1001) ...
    Adding new user `user_2' (1001) with group `user_2' ...
    Creating home directory `/home/user_2' ...
    Copying files from `/etc/skel' ...
    New password: 
    Retype new password: 
    passwd: password updated successfully
    Changing the user information for user_2
    Enter the new value, or press ENTER for the default
	    Full Name []: User Two
	    Room Number []: 
	    Work Phone []: 
	    Home Phone []: 
	    Other []: 
    Is the information correct? [Y/n] Y

    root@cubic:~# usermod -a -G sudo user_2

    root@cubic:~# adduser user_3
    Adding user `user_3' ...
    Adding new group `user_3' (1002) ...
    Adding new user `user_3' (1002) with group `user_3' ...
    Creating home directory `/home/user_3' ...
    Copying files from `/etc/skel' ...
    New password: 
    Retype new password: 
    passwd: password updated successfully
    Changing the user information for user_3
    Enter the new value, or press ENTER for the default
	    Full Name []: User Three
	    Room Number []: 
	    Work Phone []: 
	    Home Phone []: 
	    Other []: 
    Is the information correct? [Y/n] Y

    root@cubic:~# usermod -a -G sudo user_3

Cubic successfully generated the custom ISO.

![Screenshot from 2021-12-17 22-14-06](https://user-images.githubusercontent.com/19394936/146627367-81327957-924f-4259-b215-9da5232cbb14.png)


The ISO booted without error.

![Screenshot from 2021-12-17 22-14-34](https://user-images.githubusercontent.com/19394936/146627390-7c94878d-2b73-45b2-b302-dfcc139e6be7.png)

I was presented with three users on the GDM screen.

![Screenshot from 2021-12-17 22-16-02](https://user-images.githubusercontent.com/19394936/146627396-bcdd80b7-72c6-4206-988d-36d8825becd7.png)

I selected "User Three" and entered the password.

![Screenshot from 2021-12-17 22-16-15](https://user-images.githubusercontent.com/19394936/146627398-3c5b2ea5-42a9-4958-b0ca-db9085640c56.png)

User Three was able to login. I also verified the user's groups membership, and it was correct.

![Screenshot from 2021-12-17 22-18-08](https://user-images.githubusercontent.com/19394936/146627402-4be12a85-494e-4c0f-86b0-f06c55214772.png)

**Comment by PJ-Singh-001** [comment]
As you can see, I am not able to recreate your issue.

Usually, when there a bug in Cubic, you will see an error message in the Log output in the terminal (if you run Cubic from the command line). Furthermore, your ISO will simply not be bootable.

Since Cubic generated a bootable ISO, I suspect there were additional changes you made on the Terminal page that you were not forthcoming about. It is likely this broke your customized system and this is preventing you from logging in.

Do you have more information you can share?
Did you make other customizations (other than simply adding users and groups)?
Did you add users and groups using a different command?
Did you add any video drivers?
Did you attempt to change the Ubuntu theme or the GDM theme?

**Comment by oldtime54** [comment]
I deleted the user and this time it created the user correctly. I can say that the issue isn't really an issue.
One issue I am still having is getting a custom gnome-shell active when I log into the user.

**Comment by PJ-Singh-001** [comment]
Glad it's working.
Getting a custom Gnome Shell to be used is a bit tricky.
Open up a new Issue (make sure you pick "Question"), and I'll share some of the steps I take to make it work.
