### ISSUE TITLE
The ubuntu(20.04.5) image containing ros1 made by Cubic deletes the ros1 function package

### ISSUE THREAD

**Issue by lbqit** [PJ-Singh-001/Cubic#300]
**Describe the question**

The ubuntu(20.04.5) image containing ros1 made by Cubic deletes the ros1 function package.
As a result, when I use the ubuntu image made by Cubic for installation, some functions of ros1 cannot be used.
There are 95 ROS feature packs in /opt/ros/noetic/share in ubuntu that contains ros1 in Cubric, but only 35 feature packs are left under /opt/ros/noetic/share after installing the created image on the server. Cubic selects the installer options to be deleted, all of which are Cubic default options, and do not include ros.

**What you have tried**

The minimal option described in Packages-Page is Cubic by default, and I didn't change it

**OS Information (please complete the following information):**
 - OS/Distro Name:  Ubuntu
 - OS Version Ubuntu 20.04.5

**Cubic Information (please complete the following information):**
 - Cubic Version: 2024.02.86
 - ISO Customizing: [ubuntu-20.04.5-desktop-amd64.iso](https://mirrors.aliyun.com/oldubuntu-releases/releases/20.04.5/ubuntu-20.04.5-desktop-amd64.iso)
 - Download Link:  [this link can download](https://mirrors.aliyun.com/oldubuntu-releases/releases/20.04.5/ubuntu-20.04.5-desktop-amd64.iso)

**Screenshots**
![ros1_packages](https://github.com/PJ-Singh-001/Cubic/assets/135289490/7f4c26f0-7d28-448e-98e7-6923eb001f19)
![Cubic_minimal](https://github.com/PJ-Singh-001/Cubic/assets/135289490/431e35d5-6559-46c7-a4ae-dbe2f4f7cbe6)

![after use cubic ubuntu](https://github.com/PJ-Singh-001/Cubic/assets/135289490/117fa5fe-7b78-40f9-9303-6e63575f49bb)

**Comment by PJ-Singh-001** [comment]
How did you install these packages?

**Comment by lbqit** [comment]
> How did you install these packages?


90/5000
install in cubic via apt-get update && apt-get install ros-noetic-desktop-full -y, because ros-noetic-desktop-full is a complete collection of ros software packages.
![desk](https://github.com/PJ-Singh-001/Cubic/assets/135289490/22011643-c6be-474d-b7fb-b893d0a4a3d0)

**Comment by PJ-Singh-001** [comment]
There is no package named `ros-noetic-desktop-full` in the repositories.
Did you add a PPA for these?

**Comment by lbqit** [comment]
> There is no package named `ros-noetic-desktop-full` in the repositories. Did you add a PPA for these?


I executed the following command in Cubic:
```sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'```
![Screenshot from 2024-03-25 13-43-00](https://github.com/PJ-Singh-001/Cubic/assets/135289490/47541f2f-e2aa-448a-8301-291ebac7e027)

**Comment by lbqit** [comment]
I tried to perform the apt-mark ros-noetic-* operation in Cubic. After creating the iso file and installing it, the ROS1 feature package was not deleted

**Comment by PJ-Singh-001** [comment]
That's an interesting approach. There must be a package that ROS1 requires, that is automatically removed by the installer following a standard install. Once that package is removed, ROS1 will also be deleted. However, with your approach, you do not need to analyze what that package could be, saving a lot of time in research.
