### ISSUE TITLE
Compressed ISO used xz are security risk ?

### ISSUE THREAD

**Issue by Augusto7743** [PJ-Singh-001/Cubic#302]
Hello Cubic creator. All good in your path ?
Recently was discovered an security problem in xz utils.
In moment all system need return to several previous version avoiding that recent problem.
In my OS I had installed xz utils version 5.4 and so used Cubic to compress disc using xz compression.
My question is if in iso creation was used xz compression has any security risk ?

Have an nice week for you and all cubic users.

**Comment by PJ-Singh-001** [comment]
According to [ArsTechnica](https://arstechnica.com/security/2024/04/what-we-know-about-the-xz-utils-backdoor-that-almost-infected-the-world/), the malicious code was added to xz Utils versions 5.6.0 and 5.6.1.

Based on this, I do not think xz Utils version 5.4 is affected.

Canonical has already [removed the affected packages](https://discourse.ubuntu.com/t/xz-liblzma-security-update/43714) from the Ubuntu repositories.

Only systems with the malicious versions of `xz` (5.6.0 and 5.6.1) installed are vulnerable, but files compressed using those malicious versions of `xz` are not affected (per my understanding). In other words, if you created a customized OS using Cubic with xz Utils 5.6.0, your ISO would not be compromised. (However, if you also installed xz Utils versions 5.6.0 in your customized OS, it would be vulnerable to a backdoor attack).

**Comment by Augusto7743** [comment]
Thanks very much for your reply.
I wish an nice week for you.
