### ISSUE TITLE
Any plans to make cubic properely support ubuntu 24.04?

### ISSUE THREAD

**Issue by focuspointlinux** [PJ-Singh-001/Cubic#307]
Hi, thanks a lot for your work on cubic, I really love the app and how easy it makes it building proper images from it.
Now, I've been trying to build a image for ubuntu noble, and it builds it fine, but there are some issues
- It doesn't really take into consideration that i've done apt update on the terminal screen of the app, if I boot into live on the new image I suddenly have about 600 updates!
-  update-initramfs -u does absolutely nothing in the terminal screen

There are other issues as well, so I just want to know if there are plans for support of ubuntu 24.04?

**Comment by PJ-Singh-001** [comment]
@focuspointlinux,

Thanks for your kind words.
With the current version of Cubic, your changes would be reflected on an installed system, but not in the Live Environment.

I am working to update Cubic to better support the newer ISO structure that Canonical is using.
Unfortunately, it is taking some time, so please be patient.

**Comment by focuspointlinux** [comment]
@PJ-Singh-001 Sounds good, thanks for answering!

**Comment by Augusto7743** [comment]
@PJ-Singh-001
Thanks very much for helping me very much with your amazing software.
