### ISSUE TITLE
Cubic breaks iso

### ISSUE THREAD

**Issue by jateagle** [PJ-Singh-001/Cubic#308]
**Describe the bug**

Using a known working ubuntu server 22.04.4 iso that auto installs with cloud init, customizing the iso breaks installation without even actually customizing anything.

**To Reproduce**

Customize iso, choose next until iso is customized and created, attempt install, failed.

**Expected behavior**

Expected behavior is to preserve the iso as is without any customization and successfully install.

**OS Information (please complete the following information):**
 - Ubuntu Server
 - 22.04.4

**Cubic Information (please complete the following information):**
 - Cubic Version: 2024.02.86-release-202402210133~ubuntu22.04.1
 - ISO Customizing: Known working iso
 - Download Link:  n/a

**Cubic Log:**

Cubic - Custom Ubuntu ISO Creator                                               

  • Set application directory.............. /usr/share/cubic                    
  • Set application user home.............. /home/username                       
  • Execute synchronously.................. dpkg-query                          
                                            --admindir="/var/lib/dpkg" --show   
                                            --showformat="${Version} " "cubic"  
  • The process id is...................... 2852551                             
  • Set application cubic version.......... 2024.02-86-                         
                                            release~202402210133~ubuntu22.04.1  
  • Set application kernel version......... 6.5.0-28-generic                    

  Setup pages                              

  • Setup.................................. boot copy page                      
  • Setup.................................. compression page                    
  • Setup.................................. delete page                         
  • Setup.................................. extract page                        
  • Setup.................................. finish page                         
  • Setup.................................. generate page                       
  • Setup.................................. migrate page                        
  • Setup.................................. options page                        
  • Setup.................................. packages page                       
  • Setup.................................. prepare page                        
  • Setup.................................. preseed copy page                   
  • Setup.................................. project page                        
  • Setup.................................. start page                          
  • Setup.................................. terminal copy page                  
  • Setup.................................. terminal page                       
  • Set terminal colors?................... Yes                                 
  • Setup.................................. test 1 page                         
  • Setup.................................. test 2 page                         

  Setup file choosers                      

  • Setup (ignore warnings)................ copy file chooser                   

(cubic:2852547): Gtk-WARNING **: 14:20:16.040: Content added to the action area of a dialog using header bars

(cubic:2852547): Gtk-WARNING **: 14:20:16.040: Content added to the action area of a dialog using header bars
  • Setup (ignore warnings)................ directory chooser                   

(cubic:2852547): Gtk-WARNING **: 14:20:16.052: Content added to the action area of a dialog using header bars

(cubic:2852547): Gtk-WARNING **: 14:20:16.052: Content added to the action area of a dialog using header bars
  • Setup (ignore warnings)................ iso image chooser                   

(cubic:2852547): Gtk-WARNING **: 14:20:16.065: Content added to the action area of a dialog using header bars

(cubic:2852547): Gtk-WARNING **: 14:20:16.065: Content added to the action area of a dialog using header bars

Handle navigation from no page on open action                                   

  • Interrupt previous thread.............. No thread                           

Get the new page                                                                

  • Current page........................... no page                             
  • Action................................. open                                
  • New page............................... start page                          

  • The thread id is....................... 134302314526272                     
Navigate from no page to start page on open action                              

  • Set application configuration.......... /home/username/.config/cubic/cubic.co
                                            nf                                  

  Load application configuration           

  • Load application configuration......... 2022 layout from /home/username/.conf
                                            ig/cubic/cubic.conf                 
  • Set application visited sites.......... []                                  
  • Set application projects............... ['/home/username/ubuntuserver7',     
                                            '/home/username/ubuntuserver6',      
                                            '/home/username/ubuntuserver5',      
                                            '/home/username/debian1',            
                                            '/home/username/ubuntuserver4']      
  • Set application iso file path.......... /home/username/Downloads/test/u22.04-
                                            autoinstall-                        
                                            ISO/ubuntutetstfinal6.iso           

  Transition pages                         

  • Show new page.......................... start page

**Comment by Augusto7743** [comment]
Which packages components was removed ?

**Comment by jateagle** [comment]
Nothing was removed from the image.  I followed the instructions found on https://www.pugetsystems.com/labs/hpc/How-To-Make-Ubuntu-Autoinstall-ISO-with-Cloud-init-2213/ to customize the iso and the only thing I'm doing differently is I have specified a proxy in the user-data.  Again, this iso does work, but I'd like to further customize it with our internal tools.

**Comment by PJ-Singh-001** [comment]
@jateagle, @Augusto7743,

The upcoming release may fix your issue.

You can preview it by installing Cubic from the "experimental" branch.
Otherwise, I should be publishing the new release within a few weeks.

    # Remove release version 2024.02.86 of Cubic.
    sudo apt autoremove --purge cubic

    # Optionally make sure there are no old files left by apt.
    sudo rm -rf /usr/share/cubic

    # Remove the Cubic "Release" repository.
    sudo add-apt-repository --remove ppa:cubic-wizard/release

    # Add the Cubic "Experimental" repository.
    sudo apt-add-repository universe
    sudo apt-add-repository ppa:cubic-wizard/experimental
    sudo apt update

    # Install an EXPERIMENTAL version of Cubic.
    sudo apt install --no-install-recommends cubic

**Comment by PJ-Singh-001** [comment]
Cubic version 2024.09.88 should remedy this issue.
The generated ISO now aggregates packages and files from _both_ the Minimal Install _and_ the Standard Install.

The previous version of Cubic you had used (version 2024.02.86) _only_ customized the Minimal Install, which is why you saw a difference when customizing the ISO.

You can update to Cubic version 2024.09.88 as follows:

    sudo apt update
    sudo apt install --no-install-recommends cubic
