### ISSUE TITLE
Can  `*.run` files be executed in Cubic's Terminal evironment?

### ISSUE THREAD

**Issue by eband** [PJ-Singh-001/Cubic#31]
Not an issue per se, just a curious question; can I run .RUN script files in Cubic?

**Comment by PJ-Singh-001** [comment]
You can run programs and scripts in Cubic's Terminal environment.

The only restriction is that the script should not expect any services to be running. Services do not run in the Terminal environment. (This protects your customized system from being modified by any services which may change configurations or leave behind unwanted log files).

Make sure you make your script executable using `chmod +x` first.
