### ISSUE TITLE
Missing user after new install of Ubuntu 22.04

### ISSUE THREAD

**Issue by manguera1** [PJ-Singh-001/Cubic#310]
Hi , 

Whenever I install a customize ubuntu 22.04 iso , after the installation the user is missing . I get an error message saying : "Sorry , password authentication didn´t work" . 

Users created with cubic do appear/are listed and work but the user created during the installation is missing . 

I do only install a couple of packages I need and run an apt-get upgrade for the iso customization and thats it . 

**What you have tried**

I tried without installing packages and doing basically nothing and that works but thats not the intend . 

checked etc/passwd getent passwd and the user is not there . 

checked the logs and the only thing I found is pam saying user unknown . 

Checked the iso is correct and hash/md5 is correct . 

**OS Information:**
 - OS/Distro Name: Ubuntu Desktop
 - OS 22.04.4 Desktop 

**Cubic Information:**
 - Cubic Version: 2024.02.86
 - ISO Customizing: Ubuntu desktop 22.04.4

![image](https://github.com/PJ-Singh-001/Cubic/assets/125322195/3c8f6dd1-1975-4aae-b7b9-23d812534be4)
![image](https://github.com/PJ-Singh-001/Cubic/assets/125322195/fe916b59-1c7e-419d-9fdc-9964a3f37038)

**Comment by magixyu** [comment]
are you use autoinstall as well?

**Comment by manguera1** [comment]
> are you use autoinstall as well?

Nope , I don´t use Autoinstall .

**Comment by magixyu** [comment]
It might be the same issue. #315  The user specified in the autoinstall isn't created after installation.

**Comment by PJ-Singh-001** [comment]
You didn't explain how you are creating a user.
