### ISSUE TITLE
Cubic doesn't work together with autoinstall identity.

### ISSUE THREAD

**Issue by magixyu** [PJ-Singh-001/Cubic#315]
**Describe the bug**
The user defined in the autoinstall(user-data) identity section is missing.

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**OS Information (please complete the following information):**
 - OS/Distro Name: [e.g. Ubuntu, Mint, Kubuntu]
 - OS Version [e.g. Ubuntu 21.10]
Ubuntu 24.04

**Cubic Information (please complete the following information):**
 - Cubic Version: [e.g. 2021.12.67 from the About dialog, or 2021.12-67-release from `dpkg -l`]
 - ISO Customizing: [e.g. ubuntu-21.10-desktop-amd64.iso]
 - Download Link:  The download link for the ISO you are customizing

**Cubic Log:**

 Cut and paste the log after running `cubic --verbose` from the command line
rnxt@rnxt-build:~/cubic$ cubic --verbose

Cubic - Custom Ubuntu ISO Creator

  • Set application directory.............. /usr/share/cubic
  • Set application user home.............. /home/rnxt
  • Execute synchronously.................. dpkg-query
                                            --admindir="/var/lib/dpkg" --show
                                            --showformat="${Version} " "cubic"
  • The process id is...................... 167528
  • Set application cubic version.......... 2024.02-86-
                                            release~202402210133~ubuntu24.04.1
  • Set application kernel version......... 6.8.0-31-generic

  Setup pages

  • Setup.................................. boot copy page
  • Setup.................................. compression page
  • Setup.................................. delete page
  • Setup.................................. extract page
  • Setup.................................. finish page
  • Setup.................................. generate page
  • Setup.................................. migrate page
  • Setup.................................. options page
  • Setup.................................. packages page
  • Setup.................................. prepare page
  • Setup.................................. preseed copy page
  • Setup.................................. project page
  • Setup.................................. start page
  • Setup.................................. terminal copy page
  • Setup.................................. terminal page
  • Set terminal colors?................... Yes
  • Setup.................................. test 1 page
  • Setup.................................. test 2 page

  Setup file choosers

  • Setup (ignore warnings)................ copy file chooser
  • Setup (ignore warnings)................ directory chooser
  • Setup (ignore warnings)................ iso image chooser

Handle navigation from no page on open action

  • Interrupt previous thread.............. No thread

Get the new page

  • Current page........................... no page
  • Action................................. open
  • New page............................... start page

Navigate from no page to start page on open action

  • The thread id is....................... 136429122356928
  • Set application configuration.......... /home/rnxt/.config/cubic/cubic.conf

  Load application configuration

  • Load application configuration......... 2022 layout from
                                            /home/rnxt/.config/cubic/cubic.conf
  • Set application visited sites.......... []
  • Set application projects............... ['/home/rnxt/cubic']
  • Set application iso file path.......... /home/rnxt/ubuntu-24.04-live-server-
                                            amd64.iso

  Transition pages

  • Show new page.......................... start page

  Project directory changed

  • Set project directory.................. /home/rnxt/cubic
  • Check if directory is writable......... /home/rnxt/cubic
  • Directory is writable?................. True
  • Get file system type................... /home/rnxt/cubic
  • Execute synchronously.................. df --output=fstype
                                            "/home/rnxt/cubic"
  • The process id is...................... 167672
  • The file system type is................ ext4
  • The application directory is........... /usr/share/cubic
  • The application user home is........... /home/rnxt
  • The application kernel version is...... 6.8.0-31-generic
  • The application configuration is....... /home/rnxt/.config/cubic/cubic.conf
  • The application cubic version is....... 2024.02-86-
                                            release~202402210133~ubuntu24.04.1
  • The application visited sites are...... []
  • The application projects are........... ['/home/rnxt/cubic']
  • The application iso file path is....... /home/rnxt/ubuntu-24.04-live-server-
                                            amd64.iso
  • Set project configuration.............. /home/rnxt/cubic/cubic.conf

  Initialize

  • Set project iso mount point............ /home/rnxt/cubic/source-disk
  • Set project custom root directory...... /home/rnxt/cubic/custom-root
  • Set project custom disk directory...... /home/rnxt/cubic/custom-disk

  Load project configuration

  • Load project configuration............. 2023 layout from
                                            /home/rnxt/cubic/cubic.conf
  • Set project cubic version.............. 2024.02-86-
                                            release~202402210133~ubuntu24.04.1
  • Set project create date................ 2024-05-07 15:42
  • Set project modify date................ 2024-05-07 16:16
  • Set original iso file name............. ubuntu-24.04-live-server-amd64.iso
  • Set original iso directory............. /home/rnxt
  • Set original iso volume id............. Ubuntu-Server 24.04 LTS amd64
  • Set original iso release name.......... Noble Numbat
  • Set custom iso version number.......... RNXT Plato 2024.05.07
  • Set custom iso file name............... RNXT-Plato-2024.05.07-server-
                                            amd64.iso
  • Set custom iso directory............... /home/rnxt/cubic
  • Set custom iso volume id............... Ubuntu-Server 24.04.0 RNXT Plato
  • Set custom iso release name............ RNXT Plato on Noble Numbat
  • Set custom iso disk name............... RNXT-Plato-2024.05.07-server-
                                            amd64.iso
  • Set status is success copy............. True
  • Set status is success extract.......... True
  • Set status iso template................ 789C8D51CD8EA42010BEFB14DCBC6C8D808E
                                            AD3EC85E4901A52141314077D23399775FEC
                                            763BB3C926BB07087C05F5FD14FC64F5E72D
                                            F8EB4ACAD9AFBA0258E2554B587564006ECB
                                            146FE8271F0C7A35A7892710EF69FAA01854
                                            79B3E71F8FE3B2E7A9FED42164E5565C4859
                                            17C9E410EF5FCD8E31BBECC206E2CDADCBC1
                                            B1C7904BD9DD08D66443028F9A7C05AFA7CA
                                            DCBD42EF968D8579FE5E28D7449989BEB429
                                            02600ED1101CCCA83D5580FB4E9B55AF0F4C
                                            32395C5A894688791EAC144263A739476EC6
                                            96CAD27F376A4170D18E76FA0F63F234F624
                                            A727BDC274E452814B8FAC9E60BEEFC45022
                                            B79C34BDEBB16DBB6EB818DE0FBAD717D98F
                                            A3B9546058DD1CAC6F0633FA7034D727D41C
                                            136A5C3BF4B09B867C11E37238156C0168BD
                                            FA4720D563071FD042721FC4BA1371DB1CE0
                                            CCEB9CF70BAFE07747409FCF3EC4EA6F19FD
                                            E1F2391539A1F725A97F08288976BCFA05BE
                                            A6D84D
  • Set status squashfs directory.......... casper
  • Set status squashfs file name.......... ubuntu-server-minimal
  • Set status casper directory............ casper
  • Set status iso checksum................ ddb60cb108d7047259e832af01d52d84
  • Set status iso checksum file name...... RNXT-Plato-2024.05.07-server-
                                            amd64.md5
  • Set options update os release.......... True
  • Set options boot configurations........ ['boot/grub/grub.cfg',
                                            'boot/grub/loopback.cfg']
  • Set options compression................ gzip
  • Set installer has typical install...... False
  • Set installer has minimal install...... False
  • Set installer has subiquity............ True
  • Clicked................................ Next

Handle navigation from start page on next action

  • Interrupt previous thread.............. No thread

Get the new page

  • Current page........................... start page
  • Action................................. next
  • New page............................... project page

Navigate from start page to project page on next action

  Check if the mount point is mounted

  • The thread id is....................... 136429132842688
  • The mount point is..................... /home/rnxt/cubic/source-disk
  • Is mounted?............................ False
  • Create directory....................... /home/rnxt/cubic/source-disk

  Mount the ISO image

  • The ISO file path is................... /home/rnxt/ubuntu-24.04-live-server-
                                            amd64.iso
  • The mount point is..................... /home/rnxt/cubic/source-disk
  • The user id is......................... 1000
  • The group id is........................ 1000
  • Execute synchronously.................. mount-iso
                                            /home/rnxt/ubuntu-24.04-live-server-
                                            amd64.iso /home/rnxt/cubic/source-
                                            disk 1000 1000
  • The process id is...................... 167674
  • The result is.......................... mount: /home/rnxt/cubic/source-disk:
                                            WARNING: source write-protected,
                                            mounted read-only.
  • The exit status, signal status is...... 0, None

  Get ISO image release notes URL

  • ISO image mount point.................. /home/rnxt/cubic/source-disk
  • Read file.............................. /home/rnxt/cubic/source-
                                            disk/.disk/release_notes_url
  • Warning. File does not exist........... /home/rnxt/cubic/source-
                                            disk/.disk/release_notes_url

  Get ISO image release notes URL

  • ISO image mount point.................. /home/rnxt/cubic/custom-disk
  • Read file.............................. /home/rnxt/cubic/custom-
                                            disk/.disk/release_notes_url
  • Set custom iso release notes url....... https://www.radionxt.com

  Initialize the status fields from the
  model

  • Set status is success copy............. True
  • Set status is success extract.......... True
  • Set status iso template................ 789C8D51CD8EA42010BEFB14DCBC6C8D808E
                                            AD3EC85E4901A52141314077D23399775FEC
                                            763BB3C926BB07087C05F5FD14FC64F5E72D
                                            F8EB4ACAD9AFBA0258E2554B587564006ECB
                                            146FE8271F0C7A35A7892710EF69FAA01854
                                            79B3E71F8FE3B2E7A9FED42164E5565C4859
                                            17C9E410EF5FCD8E31BBECC206E2CDADCBC1
                                            B1C7904BD9DD08D66443028F9A7C05AFA7CA
                                            DCBD42EF968D8579FE5E28D7449989BEB429
                                            02600ED1101CCCA83D5580FB4E9B55AF0F4C
                                            32395C5A894688791EAC144263A739476EC6
                                            96CAD27F376A4170D18E76FA0F63F234F624
                                            A727BDC274E452814B8FAC9E60BEEFC45022
                                            B79C34BDEBB16DBB6EB818DE0FBAD717D98F
                                            A3B9546058DD1CAC6F0633FA7034D727D41C
                                            136A5C3BF4B09B867C11E37238156C0168BD
                                            FA4720D563071FD042721FC4BA1371DB1CE0
                                            CCEB9CF70BAFE07747409FCF3EC4EA6F19FD
                                            E1F2391539A1F725A97F08288976BCFA05BE
                                            A6D84D
  • Set status squashfs directory.......... casper
  • Set status squashfs file name.......... ubuntu-server-minimal
  • Set status casper directory............ casper
  • Set status iso checksum................ ddb60cb108d7047259e832af01d52d84
  • Set status iso checksum file name...... RNXT-Plato-2024.05.07-server-
                                            amd64.md5

  Initialize the options fields from the
  model

  • Set options boot configurations........ ['boot/grub/grub.cfg',
                                            'boot/grub/loopback.cfg']
  • Set options compression................ gzip

  Initialize the installer fields from the
  model

  • Set installer has typical install...... False
  • Set installer has minimal install...... False
  • Set installer has subiquity............ True

  Initialize the original fields from the
  model

  • Set original iso file name value....... ubuntu-24.04-live-server-amd64.iso
  • Set original iso directory value....... /home/rnxt
  • Set original iso volume id value....... Ubuntu-Server 24.04 LTS amd64
  • Set original iso release name value.... Noble Numbat
  • Is original iso version number
    valid?................................. True

  Check if the ISO image is mounted

  • The mount point is..................... /home/rnxt/cubic/source-disk
  • The ISO file path is................... /home/rnxt/ubuntu-24.04-live-server-
                                            amd64.iso
  • Execute synchronously.................. mount
  • The process id is...................... 167717
  • Is mounted?............................ True
  • Is original iso file name valid?....... True
  • Is original iso directory valid?....... True
  • Is original iso volume id valid?....... True
  • Is original iso release name valid?.... True
  • Is original iso disk name valid?....... True
  • Is original iso release notes url
    valid?................................. True
  • Is original update os release valid?... True

  Initialize the custom fields from the
  model

  • Set custom iso version number value.... RNXT Plato 2024.05.07
  • Set custom iso file name value......... RNXT-Plato-2024.05.07-server-
                                            amd64.iso
  • Set custom iso directory value......... /home/rnxt/cubic
  • Set custom iso volume id value......... Ubuntu-Server 24.04.0 RNXT Plato
  • Set custom iso release name value...... RNXT Plato on Noble Numbat
  • Set custom iso disk name value......... RNXT-Plato-2024.05.07-server-
                                            amd64.iso
  • Set custom iso release notes url
    value.................................. https://www.radionxt.com
  • Set custom update os release value..... True
  • Is custom iso version number valid?.... True
  • Is custom iso file name valid?......... True
  • Check if directory is writable......... /home/rnxt/cubic
  • Directory is writable?................. True
  • Is custom iso directory valid?......... True
  • Is custom iso volume id valid?......... True
  • Is custom iso release name valid?...... True
  • Is custom iso disk name valid?......... True
  • Is custom iso release notes url
    valid?................................. True
  • Is custom update os release valid?..... True

  Save the generated ISO values from the
  model

  • Set generated iso version number....... RNXT Plato 2024.05.07
  • Set generated iso file name............ RNXT-Plato-2024.05.07-server-
                                            amd64.iso
  • Set generated iso directory............ /home/rnxt/cubic
  • Set generated iso volume id............ Ubuntu-Server 24.04.0 RNXT Plato
  • Set generated iso release name......... RNXT Plato on Noble Numbat
  • Set generated iso disk name............ RNXT-Plato-2024.05.07-server-
                                            amd64.iso
  • Set generated iso release notes url.... https://www.radionxt.com
  • Is page valid?......................... True
  • Execute synchronously.................. dpkg-query
                                            --admindir="/var/lib/dpkg" --show
                                            --showformat="${Version} " "qemu-
                                            system-x86"
  • The process id is...................... 167748
  • Total system memory.................... 3.82 GiB (3916.07 MiB)
  • Minimum available memory required to
    enable testing......................... 1.50 GiB (1536.00 MiB)
  • Available system memory................ 3.21 GiB (3287.72 MiB)
  • The generated ISO file path is......... /home/rnxt/cubic/RNXT-
                                            Plato-2024.05.07-server-amd64.iso
  • System has adequate available memory
    to enable testing?..................... Yes
  • Enable testing?........................ Yes

  Transition pages

  • Hide old page.......................... start page
  • Show new page.......................... project page
  • Clicked................................ Customize

Handle navigation from project page on next terminal action

  • Interrupt previous thread.............. No thread

Get the new page

  • Current page........................... project page
  • Action................................. next terminal
  • New page............................... terminal page

Navigate from project page to terminal page on next terminal action

  • The thread id is....................... 136429122356928
  • Set project modify date................ 2024-05-07 16:27
  • Set options update os release.......... True

  Update the custom ISO release notes url

  • The custom ISO release notes URL is.... https://www.radionxt.com
  • Create all directories in the path..... /home/rnxt/cubic/custom-disk/.disk
  • Not creating directories............... The directory path already exists
  • Write to file.......................... /home/rnxt/cubic/custom-
                                            disk/.disk/release_notes_url

  Transition pages

  • Hide old page.......................... project page
  • Show new page.......................... terminal page

  Enter virtual environment

  • The virtual environment directory is... /home/rnxt/cubic/custom-root
  • Command................................ start-console cubic
                                            /home/rnxt/cubic/custom-root
  • Execute synchronously.................. replace-text DISTRIB_DESCRIPTION.*
                                            DISTRIB_DESCRIPTION="Ubuntu-Server
                                            24.04.0 RNXT Plato (Cubic 2024-05-07
                                            16:27)" /home/rnxt/cubic/custom-
                                            root/etc/lsb-release
  • The process id is...................... 167751

  Watch virtual environment

  • System bus id.......................... 136429267703504
  • Subscribe to virtual environment
    entered signals with subscription id... 136429267806416
  • The pseudo terminal process id is...... 167750
  • Subscribe to virtual environment
    exited events for process id........... 167750

  Entered virtual environment

  • Active State........................... active
  • Sub State.............................. running
  • Job status............................. 0
  • Job path............................... /
  • Unsubscribe from virtual environment
    entered signals with subscription id... 136429267806416
  • Set new pseudo terminal................ 20
  • Send bytes to terminal................. You have entered the virtual
                                            environment.
  • Virtual environment status message..... You are in the virtual environment.
  • Execute synchronously.................. replace-text PRETTY_NAME.*
                                            PRETTY_NAME="Ubuntu-Server 24.04.0
                                            RNXT Plato (Cubic 2024-05-07 16:27)"
                                            /home/rnxt/cubic/custom-
                                            root/usr/lib/os-release
  • The process id is...................... 167781
  • Clicked................................ Next

Handle navigation from terminal page on next action

  • Interrupt previous thread.............. No thread

Get the new page

  • Current page........................... terminal page
  • Action................................. next
  • New page............................... prepare page

Navigate from terminal page to prepare page on next action

  • The thread id is....................... 136429122356928

  Exit virtual environment

  • Execute synchronously.................. stop-process 167750
  • The process id is...................... 167788

  Exited virtual environment

  • Process id............................. 167750
  • Pseudo terminal........................ 20
  • Status................................. 9
  • Signal................................. 9
  • Exit Code.............................. 0
  • Virtual environment status message..... You are not in the virtual
                                            environment.
  • Cannot unsubscribe from virtual
    environment entered signals............ The subscription does not exist
  • MAX_ATTEMPTS........................... 3
  • First time............................. False
  • Reenter................................ False
  • Attempts............................... 1 of 3 times
 You have exited the    al.................
                                            virtual environment.
  • Execute synchronously.................. replace-text DISTRIB_DESCRIPTION.*
                                            DISTRIB_DESCRIPTION="Ubuntu-Server
                                            24.04.0 RNXT Plato (Cubic 2024-05-07
                                            16:27)" /home/rnxt/cubic/custom-
                                            root/etc/lsb-release
  • The process id is...................... 167800
  • Execute synchronously.................. replace-text PRETTY_NAME.*
                                            PRETTY_NAME="Ubuntu-Server 24.04.0
                                            RNXT Plato (Cubic 2024-05-07 16:27)"
                                            /home/rnxt/cubic/custom-
                                            root/usr/lib/os-release
  • The process id is...................... 167806
  • Attempt to restart the virtual
    environment?........................... No
  • Delete file............................ /home/rnxt/cubic/.#custom-root.lck
  • Execute synchronously.................. delete-path
                                            /home/rnxt/cubic/.#custom-root.lck
  • The process id is...................... 167812
  • The result is.......................... None
  • The exit status, signal status is...... 0, None
  • Show the Packages page?................ No

  Transition pages

  • Hide old page.......................... terminal page
  • Show new page.......................... prepare page

  Create kernel details list

  Create vmlinuz details list

  • ▹ Search directory..................... /home/rnxt/cubic/custom-root/boot
  • ▹ Number of vmlinuz files found........ 0

  Create vmlinuz details list

  • ▹ Search directory..................... /home/rnxt/cubic/source-disk/casper
  • ▹ Number of vmlinuz files found........ 1
  • Get vmlinuz version name from file
    name................................... /home/rnxt/cubic/source-
                                            disk/casper/vmlinuz
  • ▹ The version name is.................. None
  • Get vmlinuz version name from file
    type................................... /home/rnxt/cubic/source-
                                            disk/casper/vmlinuz
  • Execute synchronously.................. file "vmlinuz"
  • The process id is...................... 167818
  • ▹ The version name is.................. 6.8.0-31
  • ▹ The vmlinuz version is............... 6.8.0-31

  Create initrd details list

  • ▹ Search directory..................... /home/rnxt/cubic/custom-root/boot
  • ▹ Number of initrd files found......... 0

  Create initrd details list

  • ▹ Search directory..................... /home/rnxt/cubic/source-disk/casper
  • ▹ Number of initrd files found......... 1
  • Get initrd version name from file
    name................................... /home/rnxt/cubic/source-
                                            disk/casper/initrd
  • ▹ The version name is.................. None
  • Get initrd version name from file
    contents............................... /home/rnxt/cubic/source-
                                            disk/casper/initrd
  • Execute asynchronously................. lsinitramfs
                                            "/home/rnxt/cubic/source-
                                            disk/casper/initrd"
  • The process id is...................... 167819
  • ▹ The version name is.................. 6.8.0-31
  • ▹ The initrd version is................ 6.8.0-31
  • Get initrd compression format from
    file type.............................. /home/rnxt/cubic/source-
                                            disk/casper/initrd
  • Execute synchronously.................. file "/home/rnxt/cubic/source-
                                            disk/casper/initrd"
  • The process id is...................... 185196
  • The initrd file type information is.... /home/rnxt/cubic/source-
                                            disk/casper/initrd: ASCII cpio
                                            archive (SVR4 with no CRC)
  • Initrd compression format found?....... No
  • Get initrd compression format from
    file contents.......................... /home/rnxt/cubic/source-
                                            disk/casper/initrd
  • Execute asynchronously................. binwalk --include="compressed data"
                                            "/home/rnxt/cubic/source-
                                            disk/casper/initrd"
  • The process id is...................... 185197
  • The initrd file contents information
    is..................................... 8217299       0x7D62D3        gzip
                                            compressed data, last modified:
                                            2080-03-21 14:19:55 (bogus date)
  • Initrd compression format found?....... Yes
  • The compression format is.............. gzip
  • Delete existing files with pattern..... /var/tmp/unmkinitramfs_*

  Collate kernel versions

  • Directory.............................. /home/rnxt/cubic/source-disk/casper
  • Matching vmlinuz and initrd versions... 6.8.0-31

  List the kernel details

  • Version................................ 6.8.0-31
  • ▹ Index................................ 1 of 1
  • ▹ Vmlinuz file name.................... vmlinuz
  • ▹ New vmlinuz file name................ vmlinuz
  • ▹ Initrd file name..................... initrd
  • ▹ New initrd file name................. initrd.gz
  • ▹ Directory............................ /home/rnxt/cubic/source-disk/casper
  • ▹ Note................................. This kernel is used to bootstrap the
                                            original disk. Use this kernel to
                                            bootstrap Ubuntu Server 21.10+ or
                                            Desktop 23.04+. Reference these
                                            files as <span font_family="monospac
                                            e">vmlinuz</span> and <span font_fam
                                            ily="monospace">initrd.gz</span> in
                                            the disk boot configurations.
  • ▹ Is selected.......................... True
  • Number of valid disk boot kernels
    found.................................. 1

  Create list of installed packages

  • Execute synchronously.................. dpkg-query
                                            --admindir="/home/rnxt/cubic/custom-
                                            root/var/lib/dpkg" --show
  • The process id is...................... 185198
  • Number of installed packages found..... 442

  Create the removable packages list for a
  typical install

  • Read lines from file................... /home/rnxt/cubic/custom-
                                            disk/casper/filesystem.manifest-
                                            remove
  • Warning. File does not exist........... /home/rnxt/cubic/custom-
                                            disk/casper/filesystem.manifest-
                                            remove
  • Total number of installed packages..... 442
  • Number of packages to be removed for
    a typical install...................... 0
  • Number of packages to be retained
    for a typical install.................. 442
  • Number of installed packages
    matching typical install list.......... 0

  Create the removable packages list for a
  minimal install

  • Read lines from file................... /home/rnxt/cubic/custom-
                                            disk/casper/filesystem.manifest-
                                            minimal-remove
  • Warning. File does not exist........... /home/rnxt/cubic/custom-
                                            disk/casper/filesystem.manifest-
                                            minimal-remove
  • Total number of installed packages..... 442
  • Number of packages to be removed for
    a minimal install...................... 0
  • Number of packages to be retained
    for a minimal install.................. 442
  • Number of installed packages
    matching minimal install list.......... 0

  Create new file system manifest file

  • Write file system manifest to.......... /home/rnxt/cubic/custom-
                                            disk/casper/ubuntu-server-
                                            minimal.manifest
  • Show the Packages page?................ No

Get the new page

  • Current page........................... prepare page
  • Action................................. next options
  • New page............................... options page

Navigate from prepare page to options page on next options action

  Transition pages

  • Hide old page.......................... prepare page
  • Show new page.......................... options page

  Initialize Kernel Tab

  Initialize Preseed Tab

  Initialize Files Tab

  • Create directory....................... /home/rnxt/cubic/custom-disk/preseed
  • Not creating directory................. Directory already exists

  Initialize files tree

  • The root file paths are................ ['preseed']
  • The required file paths are............ None

  Build tree

  • File path.............................. preseed
  • Source file path....................... preseed
  • Adding watch for....................... /home/rnxt/cubic/custom-disk/preseed
  • Asyncio thread......................... Start

  Initialize Boot Tab

  Initialize Files Tab

  • Create all directories in the path..... /home/rnxt/cubic/custom-disk/boot
  • Not creating directories............... The directory path already exists

  Initialize files tree

  • The root file paths are................ ['boot']
  • The required file paths are............ ['boot/grub/grub.cfg',
                                            'boot/grub/loopback.cfg']

  Build tree

  • File path.............................. boot
  • Source file path....................... boot
  • Adding watch for....................... /home/rnxt/cubic/custom-disk/boot
  • Asyncio thread......................... Start

  Update boot configurations

  Search and replace in file

  • File path.............................. boot/grub/grub.cfg
  • Create source view for................. /home/rnxt/cubic/custom-
                                            disk/boot/grub/grub.cfg
  • Search and replace in source view...... /home/rnxt/cubic/custom-
                                            disk/boot/grub/grub.cfg
  • 1. Removed the vmlinuz path on line.... 9
  • 2. Updated the vmlinuz path on line.... 9
  • 3. Removed the initrd path on line..... 10
  • 4. Updated the initrd path on line..... 10
  • Number of updates...................... 4
  • Save changes to........................ boot/grub/grub.cfg

  Search and replace in file

  • File path.............................. boot/grub/loopback.cfg
  • Create source view for................. /home/rnxt/cubic/custom-
                                            disk/boot/grub/loopback.cfg
  • Search and replace in source view...... /home/rnxt/cubic/custom-
                                            disk/boot/grub/loopback.cfg
  • 1. Removed the vmlinuz path on line.... 3
  • 2. Updated the vmlinuz path on line.... 3
  • 3. Removed the initrd path on line..... 4
  • 4. Updated the initrd path on line..... 4
  • Number of updates...................... 4
  • Save changes to........................ boot/grub/loopback.cfg

  Show Options page, Kernel tab

  • Change tree selection to............... preseed
  • Show pane for file..................... preseed
  • Change tree selection to............... preseed
  • Show pane for file..................... preseed
  • Change tree selection to............... boot
  • Show pane for file..................... boot

  Process close write

  • Path name.............................. /home/rnxt/cubic/custom-
                                            disk/boot/grub/grub.cfg
  • Base name.............................. grub.cfg
  • Watch Descriptors...................... [{'/home/rnxt/cubic/custom-
                                            disk/boot': 1,
                                            '/home/rnxt/cubic/custom-
                                            disk/boot/grub': 2,
                                            '/home/rnxt/cubic/custom-
                                            disk/boot/grub/i386-pc': 3,
                                            '/home/rnxt/cubic/custom-
                                            disk/boot/grub/x86_64-efi': 4,
                                            '/home/rnxt/cubic/custom-
                                            disk/boot/grub/fonts': 5}]
  • File changed by........................ Cubic
  • Undo buffer............................ Do not reset

  Process close write

  • Path name.............................. /home/rnxt/cubic/custom-
                                            disk/boot/grub/loopback.cfg
  • Base name.............................. loopback.cfg
  • Watch Descriptors...................... [{'/home/rnxt/cubic/custom-
                                            disk/boot': 1,
                                            '/home/rnxt/cubic/custom-
                                            disk/boot/grub': 2,
                                            '/home/rnxt/cubic/custom-
                                            disk/boot/grub/i386-pc': 3,
                                            '/home/rnxt/cubic/custom-
                                            disk/boot/grub/x86_64-efi': 4,
                                            '/home/rnxt/cubic/custom-
                                            disk/boot/grub/fonts': 5}]
  • File changed by........................ Cubic
  • Undo buffer............................ Do not reset
  • Clicked................................ Next

Handle navigation from options page on next action

  • Interrupt previous thread.............. No thread

Get the new page

  • Current page........................... options page
  • Action................................. next
  • New page............................... compression page

Navigate from options page to compression page on next action

  • The thread id is....................... 136429143328448

  Transition pages

  • Hide old page.......................... options page
  • Show new page.......................... compression page
  • Leave.................................. Options page Kernel tab
  • Clicked................................ Generate

Handle navigation from compression page on generate action

  • Interrupt previous thread.............. No thread

Get the new page

  • Current page........................... compression page
  • Action................................. generate
  • New page............................... generate page

Navigate from compression page to generate page on generate action

  • The thread id is....................... 136429143328448

  Transition pages

  • Hide old page.......................... compression page
  • Show new page.......................... generate page

  Identify the selected kernel

  • The selected kernel is index number.... 0

  Update the vmlinuz boot file

  • Delete existing files with pattern..... /home/rnxt/cubic/custom-
                                            disk/casper/vmlinuz*
  • Keep files............................. ['/home/rnxt/cubic/custom-
                                            disk/casper/vmlinuz']

  Copy file number 1 of 2

  • The source file path is................ /home/rnxt/cubic/source-
                                            disk/casper/vmlinuz
  • The target file path is................ /home/rnxt/cubic/custom-
                                            disk/casper/vmlinuz
  • Started process thread id.............. 136429132842688
  • Process started by thread id........... 136429143328448
  • The process started at................. 16:27:54.921642
  • Execute asynchronously................. copy-path /home/rnxt/cubic/source-
                                            disk/casper/vmlinuz
                                            /home/rnxt/cubic/custom-
                                            disk/casper/vmlinuz rnxt
  • The process id is...................... 185206
  • The process finished at................ 16:27:55.096642
  • The exit status, signal status is...... 0, None
  • The message is......................... 0.00kB/s    0:00:00 (xfr#0, to-
                                            chk=0/1)
  • Stopped process thread id.............. 136429132842688
  • Adjust the final percent............... from 0.00% to 100.00%
  • Completed.............................. 10%
  • Completed.............................. 20%
  • Completed.............................. 30%
  • Completed.............................. 40%
  • Completed.............................. 50%
  • The custom OS distribution is.......... ubuntu
  • The custom OS distribution like is..... debian

  Update the initrd boot file

  • Delete existing files with pattern..... /home/rnxt/cubic/custom-
                                            disk/casper/initrd*
  • Keep files............................. ['/home/rnxt/cubic/custom-
                                            disk/casper/initrd.gz']
  • Delete file............................ /home/rnxt/cubic/custom-
                                            disk/casper/initrd
  • Execute synchronously.................. delete-path /home/rnxt/cubic/custom-
                                            disk/casper/initrd
  • The process id is...................... 185214
  • The result is.......................... None
  • The exit status, signal status is...... 0, None

  Copy file number 2 of 2

  • The source file path is................ /home/rnxt/cubic/source-
                                            disk/casper/initrd
  • The target file path is................ /home/rnxt/cubic/custom-
                                            disk/casper/initrd.gz
  • Started process thread id.............. 136429132842688
  • Process started by thread id........... 136429143328448
  • The process started at................. 16:27:55.492926
  • Execute asynchronously................. copy-path /home/rnxt/cubic/source-
                                            disk/casper/initrd
                                            /home/rnxt/cubic/custom-
                                            disk/casper/initrd.gz rnxt
  • The process id is...................... 185221
  • The process finished at................ 16:27:55.663920
  • The exit status, signal status is...... 0, None
  • The message is......................... 0.00kB/s    0:00:00 (xfr#0, to-
                                            chk=0/1)
  • Stopped process thread id.............. 136429132842688
  • Adjust the final percent............... from 0.00% to 100.00%
  • Completed.............................. 60%
  • Completed.............................. 70%
  • Completed.............................. 80%
  • Completed.............................. 90%
  • Completed.............................. 100%
  • For Ubuntu 23.04+, create symlink...... from initrd.gz to initrd in
                                            /home/rnxt/cubic/custom-disk/casper

  Compress the Linux file system

  • The source file path is................ /home/rnxt/cubic/custom-root
  • The target file path is................ /home/rnxt/cubic/custom-
                                            disk/casper/ubuntu-server-
                                            minimal.squashfs
  • Started process thread id.............. 136429132842688
  • Process started by thread id........... 136429143328448
  • The process started at................. 16:27:56.936434
  • Execute asynchronously................. compress-root
                                            /home/rnxt/cubic/custom-root
                                            /home/rnxt/cubic/custom-
                                            disk/casper/ubuntu-server-
                                            minimal.squashfs gzip
  • The process id is...................... 185230
cubic --verbose  • Completed.............................. 10%
  • Completed.............................. 20%
  • Completed.............................. 30%
  • Completed.............................. 40%
  • Completed.............................. 50%
  • Completed.............................. 60%
  • Completed.............................. 70%

**Screenshots**

**Comment by magixyu** [comment]
https://github.com/PJ-Singh-001/Cubic/issues/310

**Comment by PJ-Singh-001** [comment]
Try latest version of Cubic (currently 2024.09.89).

Instead of `user-data`/`meta-data` files, use an `autoinstall.yaml` file as described in Issue #338, [How to remove all snaps from Ubuntu?](https://github.com/PJ-Singh-001/Cubic/issues/338#issuecomment-2325417166). (Obviously you do not need to include the `late-commands` that remove all snaps, if you don't want to).

Update Cubic using:

    sudo apt update
    sudo apt install --no-install-recommends cubic

With the information provided, I will close this issue.
If you experience problems with the new version of Cubic, please open a new issue.
