### ISSUE TITLE
24.04 Custom ISOs not reflecting snap removals / some installed app icons not displayed

### ISSUE THREAD

**Issue by XA-Hydra** [PJ-Singh-001/Cubic#316]
Removing firefox and thunderbird snaps, configuring Mozilla's PPA/setting priority and installing the DEBs in their place (so that these may be updated as snaps cannot be in a chroot environment) is wiped and the snaps are put right back when booting the live environment. Installed applications ARE present, although some of them (strangely not ALL of them, just most) are not showing their proper icons, but rather the generic 'grey gear' icon in the GNOME app menu.

I have a strong feeling this is related to the new installer and it's many squashfs files now in casper (I'm guessing the minimal.squashfs is the base and anything already there is taking priority over the changes), but I as of yet just can't figure out what to do about it.

**Comment by PJ-Singh-001** [comment]
You are correct. This is an issue for any ISO that uses the Subiquity installer.

- Ubiquity [OK]
  - Ubuntu Server 21.04, and prior versions
  - Ubuntu Desktop 22.10, and prior versions

- Subiquity [ISSUE]
  - Ubuntu Server 21.10, and newer versions
  - Ubuntu Desktop 23.04, and newer versions

Take a look at my response to [another question](https://github.com/PJ-Singh-001/Cubic/issues/312#issuecomment-2119100787) about how to handle snaps and how to test.

Please note, I am working on a potential solution to this issue, but it is taking longer than I expected. In the mean time, you can follow the approached I linked to above.

**Comment by XA-Hydra** [comment]
Thank you for the response. I really appreciate all your work.
