### ISSUE TITLE
Errors when install cubic on ubuntu 24.04

### ISSUE THREAD

**Issue by magixyu** [PJ-Singh-001/Cubic#317]
**Describe the bug**
Install cubic on fresh-installed ubuntu server, there are some error reported.

![image](https://github.com/PJ-Singh-001/Cubic/assets/1633415/9db7a076-daf7-4773-a617-842118a34d8b)

**To Reproduce**

1. Install ubuntu 24.04 
2. Follow the guide to install cubic on this system.

**Expected behavior**

**OS Information (please complete the following information):**
 - OS/Distro Name: [e.g. Ubuntu, Mint, Kubuntu]
 - OS Version [e.g. Ubuntu 21.10]

**Cubic Information (please complete the following information):**
 - Cubic Version: [e.g. 2021.12.67 from the About dialog, or 2021.12-67-release from `dpkg -l`]
            2024.02-86-release~202402210133~ubuntu24.04.1
 - ISO Customizing: [e.g. ubuntu-21.10-desktop-amd64.iso]
 - Download Link:  The download link for the ISO you are customizing
`
> rnxt@rnxt-builder:~$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 24.04 LTS
> Release:        24.04
> Codename:       noble
> rnxt@rnxt-builder:~$ echo $LANG
> en_US.UTF-8
> 

`
**Cubic Log:**

 Cut and paste the log after running `cubic --verbose` from the command line

**Screenshots**

**Comment by PJ-Singh-001** [comment]
These are not invalid escape sequences. There may be something wrong with your install, or perhaps the version of Python you have? Make sure your installation supports unicode UTF-8.

**Comment by magixyu** [comment]
Thanks for your time. This only happened when firewalld installed.
If there is no firewalld, then no issue.

**Comment by PJ-Singh-001** [comment]
I see these syntax warnings for other Python applications as well. They seem to be warnings, and Cubic seems to run just fine.
