### ISSUE TITLE
cubic project folder selection page 

### ISSUE THREAD

**Issue by kassrose** [PJ-Singh-001/Cubic#319]
**issue**
im having an issue selecting a project folder in the cubic app. i click on the icon to select a folder and the then the window  and it opens up but the top and bottoms of the window extend beyond the screen edge of the top and bottom of the screen

**To Reproduce**
open cubic on kde neon 6 and attempt to select a folder. 

**Expected behavior**

open a pop up window within the borders of my screen that lets me select a cubic project

**OS Information (please complete the following information):**
 - OS/Distro Name: kde neon
 - OS Version kde neon 6

**Cubic Information (please complete the following information):**
 - Cubic Version: 2024.02.86
 - ISO Customizing: kde neon 6
 - Download Link:  https://neon.kde.org/download

**Cubic Log:**

Cubic - Custom Ubuntu ISO Creator                                               

  • Set application directory.............. /usr/share/cubic                    
  • Set application user home.............. /home/kassie-b                      
  • Execute synchronously.................. dpkg-query                          
                                            --admindir="/var/lib/dpkg" --show   
                                            --showformat="${Version} " "cubic"  
  • The process id is...................... 6275                                
  • Set application cubic version.......... 2024.02-86-                         
                                            release~202402210133~ubuntu22.04.1  
  • Set application kernel version......... 6.5.0-35-generic                    

(cubic:6270): Gtk-WARNING **: 18:11:36.533: Theme directory 16x16/panel of theme Mkos-Big-Sur-Night has no size field

(cubic:6270): Gtk-WARNING **: 18:11:36.537: Theme directory 16x16@2x/places of theme Mkos-Big-Sur-Night has no size field

(cubic:6270): Gtk-WARNING **: 18:11:36.541: Theme directory 24x24/apps of theme Mkos-Big-Sur-Night has no size field

(cubic:6270): Gtk-WARNING **: 18:11:36.544: Theme directory 24x24@2x/panel of theme Mkos-Big-Sur-Night has no size field

(cubic:6270): Gtk-WARNING **: 18:11:36.545: Theme directory 24x24@2x/panel of theme Mkos-Big-Sur-Night has no size field

  Setup pages                              

  • Setup.................................. boot copy page                      
  • Setup.................................. compression page                    
  • Setup.................................. delete page                         
  • Setup.................................. extract page                        
  • Setup.................................. finish page                         
  • Setup.................................. generate page                       
  • Setup.................................. migrate page                        
  • Setup.................................. options page                        
  • Setup.................................. packages page                       
  • Setup.................................. prepare page                        
  • Setup.................................. preseed copy page                   
  • Setup.................................. project page                        
  • Setup.................................. start page                          
  • Setup.................................. terminal copy page                  
  • Setup.................................. terminal page                       
  • Set terminal colors?................... Skip                                
  • Setup.................................. test 1 page                         
  • Setup.................................. test 2 page                         

  Setup file choosers                      

  • Setup (ignore warnings)................ copy file chooser                   

(cubic:6270): Gtk-WARNING **: 18:11:36.852: Content added to the action area of a dialog using header bars

(cubic:6270): Gtk-WARNING **: 18:11:36.852: Content added to the action area of a dialog using header bars
  • Setup (ignore warnings)................ directory chooser                   

(cubic:6270): Gtk-WARNING **: 18:11:36.886: Content added to the action area of a dialog using header bars

(cubic:6270): Gtk-WARNING **: 18:11:36.886: Content added to the action area of a dialog using header bars
  • Setup (ignore warnings)................ iso image chooser                   

(cubic:6270): Gtk-WARNING **: 18:11:36.918: Content added to the action area of a dialog using header bars

(cubic:6270): Gtk-WARNING **: 18:11:36.918: Content added to the action area of a dialog using header bars

Handle navigation from no page on open action                                   

  • Interrupt previous thread.............. No thread                           

Get the new page                                                                

  • Current page........................... no page                             
  • Action................................. open                                
  • New page............................... start page                          

  • The thread id is....................... 134060949104192                     
Navigate from no page to start page on open action                              

  • Set application configuration.......... /home/kassie-                       
                                            b/.config/cubic/cubic.conf          

  Load application configuration           

  • Load application configuration......... 2022 layout from /home/kassie-      
                                            b/.config/cubic/cubic.conf          
  • Set application visited sites.......... []                                  
  • Set application projects............... []                                  

  Transition pages                         

  • Show new page.......................... start page                          

**Screenshots**

**Comment by PJ-Singh-001** [comment]
Would you please attach a screenshot?

**Comment by kassrose** [comment]
The issue was fixed. It was an issue with kde neon 6 not cubic. 

On May 31, 2024 at 10:06 AM, PJ Singh ***@***.***> wrote:

Would you please attach a screenshot?

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you authored the thread.Message ID: ***@***.***>

-- 
Sent with https://mailfence.com  
Secure and private email
