### ISSUE TITLE
Can Cubic be used to customize Debian ISO?

### ISSUE THREAD

**Issue by paulocoghi** [PJ-Singh-001/Cubic#32]
Is Cubic also compatible with Debian?

**Comment by PJ-Singh-001** [comment]
No.

Cubic only works on ISOs that use the Ubuntu file structure.
Most Ubuntu based distributions work with Cubic.

Debian uses a different file layout, so it is not supported.

**Comment by PJ-Singh-001** [comment]
This capability has been added in Cubic version 2022.11.73.

See Issue #114, [Add support for Debian](https://github.com/PJ-Singh-001/Cubic/issues/114) for more details.

Please test and report any issues.

**Comment by paulocoghi** [comment]
Thanks a lot, @PJ-Singh-001! This is huge!
