### ISSUE TITLE
After booting created ISO it looks like broken installed OS

### ISSUE THREAD

**Issue by szymekTS** [PJ-Singh-001/Cubic#323]
**Describe the question**

I have a problem with making iso file. After doing my changes in OS I get nice iso. In liveboot it works well, installed packages, making autoinstall.yaml file etc. i tested it i was ok. Last thing i was trying to add autologin option to os ( throught editing /etc/gdm3/custom.conf file). And after that it corrupt project. When I boot ISO i get blue background and OS looks like It think it was installed. 
If you proceed with steps OS get soft lock after 

Have anyone some idea how to fix it ? 

**What you have tried**

I have tried undoo last changes but no luck, And also tried doing new project with Good ISO and it also do the same thing without any changes, only load source disk, and go straight to iso creation.

**Expected behavior**

After booting output iso I want to get standard liveiso flow.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version Ubuntu 24.041 LTS

**Cubic Information (please complete the following information):**
 - Cubic Version: 24.02.86
 - ISO Customizing: ubuntu-24.04LTS
 - Download Link:  [LINK](https://ubuntu.com/download/desktop)

**Screenshots**

![screen shot from quemu vm](https://github.com/PJ-Singh-001/Cubic/assets/33700704/e468ff25-42bd-4529-bc6e-cbecb322286a)

**Comment by szymekTS** [comment]
I tried some more and on physical machine it doesn't soft lock alfter going throught forms showed on Screen shot. I open standard liveISO enviroment. I tried to install it works well after reboot.
But it's really anoying, If

**Comment by szymekTS** [comment]
sorry but button

**Comment by PJ-Singh-001** [comment]
The blue background is usually due to a messed up GDM. Some of the changes you have done are causing this.

**Comment by PJ-Singh-001** [comment]
I do not think this is a Cubic issue and may be related to how you customized the OS.

I suggest trying the latest version of Cubic (currently version 2024.09.89).

    sudo apt update
    sudo apt install --no-install-recommends cubic
