### ISSUE TITLE
PopOs 22.04 custom iso works like a charm but the install fails.

### ISSUE THREAD

**Issue by tacogerbil** [PJ-Singh-001/Cubic#324]
**Describe the bug**

After installing a few apps (Edge, inTune, Amazon Workspaces) and basic gnome theme additions..  I create the iso with no other alterations.  I read that 22.04 ubuntu based can't use preseeds (It'll fail) so I've been looking for a way to auto install... so I haven't touched anything else yet.
Once i have the image created I use Ventoy and boot up (also directly burning the image, ventoy is faster for testing though). 
Once on the Desktop I have to look for the installer, activate it and perform the install.  I'm not that familiar with the required partitions so I always do an automatic install.   

**To Reproduce**
Create an iso with something that will increase it's size vs the recover partition size?

Steps to reproduce the behavior.
Install apps and create the iso, then install it.
**Expected behavior**

For whatever voodoo magic Cubic is doing in order to create the bootable media to also take this into account? or skip the recovery partition?  I'm not all too familiar with the black magic used here for this awesome app... I'm learning, I just wish I could tell you more 😎
**OS Information (please complete the following information):**
 - OS/Distro Name: [e.g. Ubuntu, Mint, Kubuntu]
 **PopOs** 
 - OS Version [e.g. Ubuntu 21.10]
**22.04 LTS** (_Not the Nvidia release_)

**Cubic Information (please complete the following information):**
 - Cubic Version: [e.g. 2021.12.67 from the About dialog, or 2021.12-67-release from `dpkg -l`]
 - **2024.02.86**
 - ISO Customizing: [e.g. ubuntu-21.10-desktop-amd64.iso]
 **pop-os_22.04_amd64_intel_41.iso**
 - Download Link:  The download link for the ISO you are customizing
https://iso.pop-os.org/22.04/amd64/intel/41/pop-os_22.04_amd64_intel_41.iso

**Cubic Log:**
[Cubiclog.txt](https://github.com/user-attachments/files/16090900/Cubiclog.txt)

 Cut and paste the log after running `cubic --verbose` from the command line

**Screenshots**

Once it gets to the creation of the recovery partition it fails.  This is the log and some screenshots.
[installer.log](https://github.com/user-attachments/files/16090790/installer.log)
**The Error/failure**
![falure](https://github.com/PJ-Singh-001/Cubic/assets/12961907/8c1ea965-57a9-4999-bcf7-f4f966f811a1)

**The Partitions as created by the installer**
![partitions](https://github.com/PJ-Singh-001/Cubic/assets/12961907/84549f7b-c44c-4033-8b8b-54e10ff5ebc3)

**I used GParted to increase the size of the Recovery partition after choosing the option to try the Installation AGAIN, this time choosing the MANUAL method as the partitions were already created on the first failed run (The "Modify Partitions" option).**
![Gparted_After](https://github.com/PJ-Singh-001/Cubic/assets/12961907/ce52c7db-ea72-4702-beb5-a9bd321b6e5e)

**It completes!!!**
![success](https://github.com/PJ-Singh-001/Cubic/assets/12961907/6fe3a187-7d2d-42e9-8f53-557eef675bd8)

**Comment by PJ-Singh-001** [comment]
Does this happen with an unmodified Pop_OS! ISO?

**Comment by PJ-Singh-001** [comment]
Tested `pop-os_22.04_amd64_intel_42.iso` in VirtualBox using Cubic "Experimental" version 2024.08-37-experimental.

I get the following error about the installer not being able to unmount a partition in `/media/pop-os/...`.

![Screenshot from 2024-08-09 21-30-05](https://github.com/user-attachments/assets/9d6dec4d-6e1b-4f40-a7c8-aeb1f0df94c4)

**Comment by PJ-Singh-001** [comment]
@tacogerbil,

I used the partition tool available within the installer to delete the existing partitions and create a new empty partition. Then I selected the "Retry Install" option, and chose the "Erase all" option.

Pop!_OS installed without issue.

![Screenshot from 2024-08-09 21-51-19](https://github.com/user-attachments/assets/dbef4c45-d003-4b9b-8b6c-d320bbc61f4f)

Based on this, I suspect the issue I had encountered during testing was due to Pop!_OS, and not Cubic.

Nevertheless, the new version of Cubic likely fixes the problem you had encountered, and it should be released within a few weeks.

If you would like to preview the new release, you can install it as follows. If you choose to try the "experimental" version, you should create a new Cubic project to benefit from the fixes / enhancements.

    # Remove release version 2024.02.86 of Cubic.
    sudo apt autoremove --purge cubic

    # Optionally make sure there are no old files left by apt.
    sudo rm -rf /usr/share/cubic

    # Remove the Cubic "Release" repository.
    sudo add-apt-repository --remove ppa:cubic-wizard/release

    # Add the Cubic "Experimental" repository.
    sudo apt-add-repository universe
    sudo apt-add-repository ppa:cubic-wizard/experimental
    sudo apt update

    # Install an EXPERIMENTAL version of Cubic.
    sudo apt install --no-install-recommends cubic

**Comment by tacogerbil** [comment]
> @tacogerbil,
> 
> I used the partition tool available within the installer to delete the existing partitions and create a new empty partition. Then I selected the "Retry Install" option, and chose the "Erase all" option.
> 
> Pop!_OS installed without issue.
> 
> ![Screenshot from 2024-08-09 21-51-19](https://private-user-images.githubusercontent.com/19394936/356782354-dbef4c45-d003-4b9b-8b6c-d320bbc61f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDcyNDYsIm5iZiI6MTcyMzMwNjk0NiwicGF0aCI6Ii8xOTM5NDkzNi8zNTY3ODIzNTQtZGJlZjRjNDUtZDAwMy00YjliLThiNmMtZDMyMGJiYzYxZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE2MjIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMDUyYWQyZDE1YzRjYmJmZjFmNjFmNDkyNWU3YjE3NzEzM2JmOTJmMzE0MWI4NThhOTViMzAwMzI0ZDRiZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g6DZ2RD8djoFITpw2v8PKw5IYdhHtchPWwvd46ih-WM)
> 
> Based on this, I suspect the issue I had encountered during testing was due to Pop!_OS, and not Cubic.
> 
> Nevertheless, the new version of Cubic likely fixes the problem you had encountered, and it should be released within a few weeks.
> 
> If you would like to preview the new release, you can install it as follows. If you choose to try the "experimental" version, you should create a new Cubic project to benefit from the fixes / enhancements.
> 
> ```
> # Remove release version 2024.02.86 of Cubic.
> sudo apt autoremove --purge cubic
> 
> # Optionally make sure there are no old files left by apt.
> sudo rm -rf /usr/share/cubic
> 
> # Remove the Cubic "Release" repository.
> sudo add-apt-repository --remove ppa:cubic-wizard/release
> 
> # Add the Cubic "Experimental" repository.
> sudo apt-add-repository universe
> sudo apt-add-repository ppa:cubic-wizard/experimental
> sudo apt update
> 
> # Install an EXPERIMENTAL version of Cubic.
> sudo apt install --no-install-recommends cubic
> ```

Hello :)
The main issue for the ticket was that the intent of using Cubic was to create a standalone install that doesn not require the user to touch anything.  I was hoping to use it to automate the process of imaging computers without user interaction.  In the current method if the contents of the base iso image is increased by adding additional software, the recovery partition causes the install to fail because the recovery image seems to be preconfigured for a specific size (of the original iso) so it's smaller than it needs to be with the added software.  You have to manually interact with the partition editor in order to enlarge it so that the installer can use the partition.
The more I think about it it seems it's more Pop than Cubic, forcing a recovery partiton to be made.
If tehre was a way to disable the recovery partition if you use Cubic.. it would probably fix the whole thing.  I'm still trying to learn enough about this to find a way to do that.
