### ISSUE TITLE
Is it possible to get the source code of Cubic?

### ISSUE THREAD

**Issue by makejiang** [PJ-Singh-001/Cubic#33]
Dear owner,
I am learning how to make a customized iso distro base on ubuntu.
I found Cubic. It is so great and stable!
But It looks not an opensource tool.
Is it possible to get the source code?

Thanks!
Kejaing.

**Comment by eband** [comment]
It's on this very site.

Click on the green "Code" button.

**Comment by mikeschinkel** [comment]
> It's on this very site.
> Click on the green "Code" button.

Uh, that's the theory of GitHub.  But not the practice for this repo; note the only thing here is effectively the README.

Source appears to be [**here**](https://bazaar.launchpad.net/~cubic-wizard/cubic/release/files/head:/usr/share/cubic), but trying to download the tarball from [**here**](https://bazaar.launchpad.net/~cubic-wizard/cubic/release/revision/70) currently fails for me. 

You could visit and download each file one-by-one, but man that would take a motivated individual!

_(P.S. But if you are so motivated, how about creating a repo and sharing with the rest of us? 😁)_

**Comment by Ashark** [comment]
Not quite understand, the code is not available in git. This issue is marked as "completed" by mistake?
