### ISSUE TITLE
How to remove all snaps from Ubuntu?

### ISSUE THREAD

**Issue by PJ-Singh-001** [PJ-Singh-001/Cubic#338]
Ubuntu Server 21.10 and Ubuntu Desktop 23.04 use a layered file system for the ISO, and they use the Subiquity snap package for the installer.

Considering these limitations, how to customize Ubuntu in Cubic to remove all snaps?

**Comment by PJ-Singh-001** [comment]
How to remove all snaps from Ubuntu?

**Requirements:**

- Cubic version 2024.09.88 or newer
- Ubuntu Server 21.10 or newer
- Ubuntu Desktop 23.04 or newer

**Background:**

You can not use the `snap` command in Cubic's [Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page). Furthermore, you can not simply execute `apt autoremove --purge snapd` to remove all snap packages, like you could with previous versions of Ubuntu. The new installer, Subiquity, is a snap package itself, so it requires `snapd` to be present.

**Approach:**

Therefore we must leave `snapd` installed to allow the Live ISO to boot up. However, we can leverage `cloud-config` to automatically remove `snapd` once the installation is complete.

**Limitations:**

Although version 2024.09.88 of Cubic better reflects your changes in the Live environment, there are still some limitations. These are due to the snap based Subiquity installer and the layered file system Caonical adopted in Ubuntu Server 21.10 and Ubuntu Desktop 23.04.

Here is a list of known limitations.

 1. The _Live Environment_ of your customized ISO will contain `snapd` and the standard snap packages. For Ubuntu Desktop, these are:
    - bare
    - core22
    - firefox
    - firmware-updater
    - gnome-42-2204
    - gtk-common-themes
    - snap-store
    - snapd
    - snapd-desktop-integration
    - thunderbird

    If you have installed the deb versions of Firefox or Thunderbird, your customized ISO will retain both the snap and deb versions of these applications while the user is in the Live Environment. After installation, only your deb packages will remain, because we will instruct the installer to remove `snapd` (along with all snap packages).

 2. You will not be able to edit `/etv/default/grub` because the file does not exist in Cubic's Terminal environment. If you want to make changes to this file and execute `update-grub`, use the `late-commands` section of `coud-config`, which we discuss below.

 3. I've noticed some App Icons do not render in the Live Environment. But they worked fine after installing the customized OS.

 There may be other issues or challenges that you encounter because certain files are stored in the "Installer Layer" of the ISO (which Cubic can not customize) or because the Live ISO requires `snapd`. You may be able to work around these by using `late-commands`, shown below.

**Instructions:**

 1. Launch Cubic version 2024.09.88 or newer.
 2. Customize your ISO. Do NOT remove `snapd`.
 3. Click on the [Preseed tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#preseed-tab), and create a file named `autoinstall.yaml` in the `preseed` folder.

    ![Screenshot from 2024-09-02 19-14-28](https://github.com/user-attachments/assets/de82f4c4-ec46-46ea-99e2-5d0f057d73b2)

 4. Add the following to `autoinstall.yaml`:

        #cloud-config
        version: 1
        interactive-sections:
          # Prompt the user during installation.
          - locale
          - refresh
          - keyboard
          - network
          - storage
          - identity
          - timezone
          - user-data
        late-commands:
          # Remove snapd.
          - curtin in-target --target=/target -- rm -rf /var/cache/snapd
          - curtin in-target --target=/target -- rm -rf /var/lib/snapd
          - curtin in-target --target=/target -- rm -rf /var/cache/snapd
          - curtin in-target --target=/target -- apt --yes remove --purge snapd
          - curtin in-target --target=/target -- apt --yes install snapd

    ![Screenshot from 2024-09-02 21-02-35](https://github.com/user-attachments/assets/123ba0d1-1504-4d6e-be2f-d023d2d5547d)

    This is an autoinstall file which would normally install Ubuntu without user input. (This could be dangerous, especially if it overwrites your partitions). Therefore, under under `interactive-sections`, we specify that the installer must _stop_ and _ask_ the user for input for the listed sections.

    After the installation is complete, we instruct the installer to execute a series of commands in the newly installed OS. These commands are listed in the `late-commands` section, and this is where we remove `snapd`. You should not need to use `sudo`, but make sure the commands do not require any user interaction; this is why we use the `--yes` argument to `apt`. You could add other commands here as well. (Note that executing the `snap` command does not seem to work here because it requires the `snapd` service to be running in the target environment. If you try to execute a `snap` command here, it will actually run on your Live Environment, and this is not what you intended).

 5. Click on the [Boot tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#boot-tab).

 6. Select `grub.cfg` in the left hand pane and add `subiquity.autoinstallpath=/cdrom/preseed/autoinstall.yaml` as shown. This will instruct the installer to use the `autoinstall.yaml` file you created in step 4. NOTE: On the Boot tab, you are editing the `grub.cfg` file used by the live ISO; this is NOT the `grub.cfg` used by your customized OS.

        set timeout=30

        loadfont unicode

        set menu_color_normal=white/black
        set menu_color_highlight=black/light-gray

        menuentry "Try or Install Ubuntu" {
	        set gfxpayload=keep
	        linux	/casper/vmlinuz subiquity.autoinstallpath=/cdrom/preseed/autoinstall.yaml --- quiet splash
	        initrd	/casper/initrd.gz
        }
        menuentry "Ubuntu (safe graphics)" {
	        set gfxpayload=keep
	        linux	/casper/vmlinuz nomodeset subiquity.autoinstallpath=/cdrom/preseed/autoinstall.yaml --- quiet splash
	        initrd	/casper/initrd.gz
        }
        grub_platform
        if [ "$grub_platform" = "efi" ]; then
        menuentry 'Boot from next volume' {
	        exit 1
        }
        menuentry 'UEFI Firmware Settings' {
	        fwsetup
        }
        else
        menuentry 'Test memory' {
	        linux16 /boot/memtest86+x64.bin
        }
        fi

    ![Screenshot from 2024-09-02 19-42-42](https://github.com/user-attachments/assets/f1624d86-39f3-4d53-ac1a-758316014fd8)


 7. Select `loopback.cfg` in the left hand pane and add `subiquity.autoinstallpath=/cdrom/preseed/autoinstall.yaml` as shown. This will instruct the installer to use the `autoinstall.yaml` file you created in step 4. NOTE: On the Boot tab, you are editing the `loopback.cfg` file used by the live ISO; this is NOT the `loopback.cfg` used by your customized OS.

        menuentry "Try or Install Ubuntu" {
	        set gfxpayload=keep
	        linux	/casper/vmlinuz subiquity.autoinstallpath=/cdrom/preseed/autoinstall.yaml iso-scan/filename=${iso_path} --- quiet splash
	        initrd	/casper/initrd.gz
        }
        menuentry "Ubuntu (safe graphics)" {
	        set gfxpayload=keep
	        linux	/casper/vmlinuz nomodeset subiquity.autoinstallpath=/cdrom/preseed/autoinstall.yaml iso-scan/filename=${iso_path} --- quiet splash
	        initrd	/casper/initrd.gz
        }

    ![Screenshot from 2024-09-02 20-28-36](https://github.com/user-attachments/assets/9e2adef3-590d-4d02-b4bb-59c82eb01acd)

8. Click <kbd>Next</kbd> and proceed to generate your Custom ISO.

**Comment by Proman4713** [comment]
Is there no way to at least remove a single snap package like Firefox from a chroot environment?

**Comment by PJ-Singh-001** [comment]
@Proman4713 ,

I just saw your message.

No. There is no way I could find to remove a single snap package (like Firefox) from a chroot environment.

I've tried deleting specific files related to a snap package, but it does not work.

**Comment by PJ-Singh-001** [comment]
UPDATE:

@Proman4713 ,

Cubic version 2026-07-107 (and newer) introduced a new [Snaps page](https://github.com/PJ-Singh-001/Cubic/wiki/Snaps-Page), that allows you to remove snap packages.

When removing the Firefox snap, be sure to follow the additional instructions on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

**Comment by Proman4713** [comment]
> UPDATE:
> 
> [@Proman4713](https://github.com/Proman4713) ,
> 
> Cubic version 2026-07-107 (and newer) introduced a new [Snaps page](https://github.com/PJ-Singh-001/Cubic/wiki/Snaps-Page), that allows you to remove snap packages.
> 
> When removing the Firefox snap, be sure to follow the additional instructions on the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page).

@PJ-Singh-001 Hey, thanks for pinging me! I think we can actually *install* snaps and not just remove them...

I just finished writing documentation for the project I mentioned earlier. In the [Snap Seeding section](https://github.com/Proman4713/Utile-OS?tab=contributing-ov-file#snap-seeding), I wrote my findings on how snaps are seeded into the system.

Now, I'm not aware how this would play into the layered filesystems that Ubuntu ISOs use, but we could potentially wipe all directories in `/var/lib/snapd` except `seed/`, and then remove/add the `.snap` and `.assert` files as we want (they can be downloaded for new snaps using `snap download` or the [Snapcraft API](https://github.com/Proman4713/Utile-OS/blob/main/src/preseed-snaps.js)), then run `/usr/lib/snapd/snap-preseed` (from the host, not inside the chroot, so this needs the host to have snapd installed) to regenerate the directories we wiped.

Edit: Cubic could also use the `snap debug validate-seed` command to do some checks on the seed before running `snap-preseed`

**Comment by PJ-Singh-001** [comment]
Your documentation is amazing! Thank you for sharing and putting it together. (As you noted, most of this is undocumented!).

It seems the "Live" layer is required to boot the ISO.
It also contains the installer.
I tried removing all snaps using Cubic's Snaps page.
Then I removed snapd on the terminal page.
The ISO boots perfectly. (Obviously there is no installer).

The approach you outlined seems like it will work.

(Note: If you manually add the installer to the seed file, it will go into the standard/minimal file system, not the "Live" overlay file system. When you install the OS onto a computer, everything form the standard/minimal file system is copied, which means your installed system will have the Ubuntu installer. You'll have to figure out a way to remove the installer after installation. Another option is to use Calamares to install, if you can figure that out).

**Comment by Proman4713** [comment]
I'm glad to help, and thank you for the kind words!

I like how the Ubuntu installer looks more than Calamares, but I think you're right: the Snap installer has been hard to satisfy, and it would leave remnants on the system even if it installed successfully. And no one really controls what the multi-layered filesystems are supposed to look like other than Canonical, so I only use a single `filesystem.squashfs`. I can maybe switch to Calamares for now...

I suspect that the Live layer is required because of the Ubuntu Desktop Bootstrap classic Snap itself. In my testing with a single layer, the desktop failed to behave correctly (or showed GNOME OS's initial setup on a broken desktop before leading to a working desktop) when the snap failed to install properly. But the Live layer also adds packages that my OS just includes in its single layer, so the root cause might be there; I haven't checked.

It's good to hear that this could work. Let me know if you need anything from me.

**Comment by Proman4713** [comment]
@PJ-Singh-001 You should run `/usr/lib/snapd/snap-preseed --reset` before running `snap-preseed` after the user has finished modifying their snaps. The official ISOs already come preseeded and `snap-preseed` would error out in an already-preseeded chroot; I found this out while creating a new live layer in my ISO to preseed the installer (Calamares couldn't look as good as I wanted even with custom styling).

The live layer also has the `user-setup` package, which needs to be available in the live environment so that the GNOME setup doesn't show in a broken desktop, I'm not sure if that tells you any more than you already knew, but pretty much everything else in the live layer is just in case the user makes specific choices during installation (e.g., Active Directory, BTRFS)
