### ISSUE TITLE
How do I downgrade/remove foreign packages?

### ISSUE THREAD

**Issue by eband** [PJ-Singh-001/Cubic#34]
I am practising on how to upgrade from Linux Mint 19.3 to 20 to get used to the commands needed to upgrade from 20.3 to 21, and I want to do it on Cubic.

At the stage where I have to downgrade/delete foreign packages, I have not found a single guide on how to do so using command line.

Is there a way to commence that step using command line or am I dreaming?

**Comment by PJ-Singh-001** [comment]
Yes, you can add or remove packages from the command line using the `apt` command.

But, what do you mean by "foreign" packages?

If you start out with the original Linux Mint 19.3 ISO, the only packages on the ISO will be the official Linux Mint packages.
There will be no "foreign" packages on the ISO.
However, perhaps you mean something different, when you say"foreign" ?

**Comment by eband** [comment]
https://linuxmint-user-guide.readthedocs.io/en/latest/upgrade-to-mint-20.html

Linux Mint will face a major upgrade in July of  this year.

To prepare, I wanted to research on how Mint is upgraded like that in the past, so when I looked up the instructions,  "foreign packages" are mentioned like so:

----------------------------------------------------
Purge PPAs and 3rd party repositories

PPAs or 3rd party repositories can introduce issues during the upgrade if the versions of the packages they provide are higher than in Linux Mint 20. This can result in unmet dependencies, held packages or resolver issues.

To purge 3rd party packages follow these steps:

        Launch the Software Sources tool from Menu ‣ Administration ‣ Software Sources.
        Open the Additional repositories tab and disable all additional repositories.
        Open the PPA tab and disable all PPAs.
        Click on the button to refresh your APT cache.
        Open the Maintenance tab and click on Downgrade Foreign Packages.
        Select all foreign packages and click Downgrade.
        Click on Remove Foreign Packages.
        Select all foreign packages and click Remove.
        Reboot the computer.
        Create another Timeshift snapshot.
----------------------------------------------------

Since Cubic is made for Ubuntu and derivates, I thought you'd know.

I want you know, though, that I have decided to compromise with the unfortunate truth: I have to just do a clean install instead of a direct upgrade from 20.3 to 21 while upgrading the minor milestones using Cubic.

Thank you for the response anyway.

**Comment by PJ-Singh-001** [comment]
The instructions you listed above are only for a running/installed system, in which you may have added 3rd party repositories.
They advise you to remove those repositories before upgrading.

However, when you customize the original Linux Mint ISO using Cubic, there will be no 3rd party repositories.
Therefore you do not need to remove these repositories.

Nevertheless, note that the 3rd party PPAs can be found under `/etc/apt/sources.list.d`. 

Here is what I see in `/etc/apt/sources.list.d` for `linuxmint-20.3-cinnamon-64bit.iso`.
As you can see there are no 3rd party repositories on the official ISO.

    root@cubic:~# cd /etc/apt/sources.list.d

    root@cubic:/etc/apt/sources.list.d# ls -1

        official-package-repositories.list

    root@cubic:/etc/apt/sources.list.d# cat official-package-repositories.list

    # Do not edit this file manually, use Software Sources instead.

    deb http://packages.linuxmint.com una main upstream import backport #id:linuxmint_main

    deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse
    deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
    deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse

    deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
    deb http://archive.canonical.com/ubuntu/ focal partner

**Comment by eband** [comment]
I guess I'll just dabble with the settings.

Thanks!

**Comment by eband** [comment]
I do have one more question: if I am using Cubic to upgrade my Mint customisation, are the first steps as follows:
1. Disable the 3rd party repositories in the terminal (I know how to do that), leaving the official ones unaltered.
2. Download the new upgrade packages and install them as directed by the instructions (using the command mintupgrade).

Or am I missing anything?
