### ISSUE TITLE
Change default shell for users to fish

### ISSUE THREAD

**Issue by Borderliner** [PJ-Singh-001/Cubic#347]
I was wondering how I could set the default shell for users to fish. Does it suffice to change it for the root?

**Comment by bashbers** [comment]
Have you looked at the `etc/skel/` folder and it's corresponding docs? If you create a new user using `adduser borderliner`, any files from /etc/skel/ will be copied over to the home dir of the new user.

**Comment by Borderliner** [comment]
Yup, thank you!
