### ISSUE TITLE
KDE custom ISOs always failed on installation

### ISSUE THREAD

**Issue by marceloengecom** [PJ-Singh-001/Cubic#35]
My Custom ISO failed on installation.

Original ISO: Ubuntu 20.04 LTS Server
Cubic Version: 2022.01.70
SO Cubic: Ubuntu 21.10 with  kde-plasma-desktop

Installed pagages:
apt update && apt upgrade && apt dist-upgrade
add-apt-repository ppa:kubuntu-ppa/backports
apt upgrade
apt install kde-plasma-desktop (minimal plasma)

apt install okular && apt install imagemagick && apt install gwenview && apt install elisa && apt install kmix && apt install dragonplayer && apt install kate && apt install ark && apt install kcalc && apt install sweeper && apt install kamoso && apt install kde-spectacle && apt install simplescreenrecorder && apt install plasma-systemmonitor && apt install kwave -y

apt install cmake build-essential libkf5config-dev libkdecorations2-dev libqt5x11extras5-dev qtdeclarative5-dev extra-cmake-modules libkf5guiaddons-dev libkf5configwidgets-dev libkf5windowsystem-dev libkf5coreaddons-dev gettext libkf5style-dev

apt update && apt upgrade && apt dist-upgrade && apt autoremove && apt autoclean && apt clean

The ISO is generate, but installation guide does not start.

Thanks,
Marcelo Costa

**Comment by PJ-Singh-001** [comment]
What is "installation guide" ?

**Comment by marceloengecom** [comment]
Installation process does not start and sometimes the live cd doesn't also even start.

I believe it can be the KDE Plasma.

**Comment by PJ-Singh-001** [comment]
By "Installation process does not start" you mean?...

1. You burn a live CD
2. You insert the live CD and attempt to boot into it
3. The live environment starts
4. You select the "Install" option
5. The installation process does not start

**Comment by marceloengecom** [comment]
Hello,

I burn iso to usb drive with Balena Etcher.

After boot with usb drive, sometimes start the live distro, but always the system is  restarted after a few seconds.

**Comment by PJ-Singh-001** [comment]
I am not able to recreate this issue.
