### ISSUE TITLE
Cant get past boot - Failed to start gdm.service

### ISSUE THREAD

**Issue by bashbers** [PJ-Singh-001/Cubic#353]
**Describe the question**

I am currently trying to modify a ubuntu-24.04.1-2024.10.06-desktop-amd64.iso.

**What you have tried**

- Reinstalling gmk3
- reinstalling gnome-desktop
- reinstalling ubuntu-session

Appening `:ubuntu` to gnome overrides in `90_ubuntu-settings.gschema.override`

**Expected behavior**

I've customized the following on the ISO:

- curl
- installed vscode using a curl'ed .deb file
- installed intellij using a curl'ed .deb file
- installed sublimetext using a curl'ed .deb file
- Added a user
- Altered `/etc/skel/` to contain testfiles and a Amazon Corretto 17 JDK
- Altered the `/etc/skel/.bashrc` file to export PATH with the amazon corretto JDK bin path
- Added a custom background to `/usr/share/backgrounds/cloud.jpg`
- Created a `90_ubuntu-settings.gschema.override` in /usr/share/glib2.0/schemas and recompiled the schemas using `glib-compile-schemas /usr/share/glib-2.0/schemas/`

the override file:
```sh
[org.gnome.desktop.background:ubuntu]
picture-uri = 'file:///usr/share/backgrounds/cloud.jpg'
show-desktop-icons = false

[org.gnome.desktop.screensaver:ubuntu]
picture-uri = 'file:///usr/share/backgrounds/cloud.jpg'

[org.gnome.desktop.wm.preferences:ubuntu]
button-layout = 'close,minimize,maximize:appmenu'
titlebar-font = 'Roboto Regular 10'

[org.gnome.desktop.interface:ubuntu]
document-font-name = 'Roboto Regular 10'
font-name = 'Roboto Regular 10'

[org.gnome.shell]
favorite-apps = ['intellij.desktop', 'code.desktop','firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.gedit.desktop', 'org.gnome.Terminal.desktop', 'meld.desktop', 'org.gnome.Screenshot.desktop', 'gnome-system-monitor.desktop']

```

After customizing the above and generating an ISO, the following issue occured.

The created ISO is not booting past this screen
![image](https://github.com/user-attachments/assets/42739a3c-81c7-4545-bb20-034cb5aeed3d)

I tried it first on a laptop using a USB stick, but decided to debug it in a hyper-v vm. This resulted in the same outcome.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version Ubuntu 24.-04

**Cubic Information (please complete the following information):**
 - Cubic Version: 2024.09.89
 - ISO Customizing: ubuntu-24.04.1-2024.10.06-desktop-amd64.iso
 - Download Link:  The download link for the ISO you are customizing

**Comment by bashbers** [comment]
@PJ-Singh-001 Would you be able to help me please? I'm kinda stuck and out of options..

**Comment by kleeedolinux** [comment]
apt install gdm3

**Comment by bashbers** [comment]
@kleeedolinux I've used `apt install gdm3 --reinstall` and that gave me the same result (I've removed the --quiet from caspar in the boot so there are extra lines in the console):
![image](https://github.com/user-attachments/assets/27741192-681c-4530-a694-af5c1e1322b1)

**Comment by hymRedemption** [comment]
`systemctl status gdm.service` or `journalctl -u gdm.service -e` to get more info about the failure

**Comment by bashbers** [comment]
@hymRedemption i cant type commands into the console when its booting. Alternate tty's wont open either (Ctrl shift f2 or f3)

**Comment by hymRedemption** [comment]
you may need to disable `gdm.service` first when you build your iso file(in the cubic console, type `systemctl disable gdm.service`). Then after installing your iso image on another computer and entering the console, you start the `gdm.service` manually, then check the log to know what happened exactly.

**Comment by hymRedemption** [comment]
<img width="855" alt="image" src="https://github.com/user-attachments/assets/35357c19-8560-4065-a91f-72efe3fef3aa">
 according to the config you pasted above, There are three slashes after the `file:`. Is that correct? not very familiar with the syntax

**Comment by bashbers** [comment]
> you may need to disable `gdm.service` first when you build your iso file(in the cubic console, type `systemctl disable gdm.service`). Then after installing your iso image on another computer and entering the console, you start the `gdm.service` manually, then check the log to know what happened exactly.

https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page It says that you can't access systemd services in the terminal, so I don't think that that will work..

**Comment by bashbers** [comment]
I think there is something wrong whenever I process the schemas with glib-process-schemas. I tried from scratch with minimal changes and now it posts with a green gdm.service.
