### ISSUE TITLE
How to resolve "Package is not available" error with `sources.list`?

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#38]
Hello

I am trying to install (apt-get) the same apps as I installed before unter native Ubuntu1804.
Among others, the following messages are shown:

    ->Package python-scipy is not available, but is referred to by another package.
    ->This may mean that the package is missing, has been obsoleted, or
    ->is only available from another source

    ->Package python-gtk2 is not available, but is referred to by another package.
    ->This may mean that the package is missing, has been obsoleted, or
    ->is only available from another source

    ->E: Unable to locate package libcppunit-dev
    ->E: Unable to locate package swig
    ->E: Unable to locate package liblog4cpp5-dev
    ->E: Package 'python-scipy' has no installation candidate
    ->E: Package 'python-gtk2' has no installation candidate

Questions: 
1:
Could the different sources.list be the problem?

2:
If so, why does cubic not pull the sources.list from the host-os?

Thank's a lot in advance for your help!

Joe

---

    You have entered the virtual environment.
    root@cubic:~# lsb_release -c
    Codename:	bionic

    root@cubic:/etc/apt#  cat sources.list
    deb http://archive.ubuntu.com/ubuntu/ bionic main restricted
    deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted
    deb http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted
    root@cubic:/etc/apt# 

---

    test@ub1804:~$ lsb_release -c
    Codename:	bionic

    test@ub1804:/etc/apt$ cat sources.list
    # deb cdrom:[Ubuntu 18.04.6 LTS _Bionic Beaver_ - Release amd64 (20210915)]/ bionic main restricted
    ##
    ##
    ##
    deb http://security.ubuntu.com/ubuntu bionic-security main restricted
    # deb-src http://security.ubuntu.com/ubuntu bionic-security main restricted
    deb http://security.ubuntu.com/ubuntu bionic-security universe
    # deb-src http://security.ubuntu.com/ubuntu bionic-security universe
    deb http://security.ubuntu.com/ubuntu bionic-security multiverse
    # deb-src http://security.ubuntu.com/ubuntu bionic-security multiverse

**Comment by PJ-Singh-001** [comment]
According to the [Ubuntu Releases Wiki](https://wiki.ubuntu.com/Releases), Bionic Beaver is supported until April 2023, so you should be able to get software for this version of Ubuntu.

**_Question 1: Could the different `sources.list` be the problem?_**

Yes. Your `sources.list` is the problem.

The package `python-scipy` is [available in Bionic](https://packages.ubuntu.com/bionic/python-scipy). However, it is available in the **universe** repository.

I noticed you do not have the **universe** repository enabled in the Cubic environment or in your "test" machine. Furthermore, on your "test" machine, you _only_ have the **security** repositories enabled.

Your `/etc/apt/sources.list` file should look like this:

    deb http://us.archive.ubuntu.com/ubuntu/ bionic main multiverse restricted universe
    deb http://us.archive.ubuntu.com/ubuntu/ bionic-security main multiverse restricted universe
    deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates main multiverse restricted universe
    deb http://us.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse

You can edit this file in Cubic using [`nano`](https://www.nano-editor.org/dist/latest/cheatsheet.html).
When you are done, type <kbd>Ctrl</kbd><kbd>X</kbd>, <kbd>Y</kbd>, <kbd>Enter</kbd> to save the file and exit [`nano`](https://www.nano-editor.org/dist/latest/cheatsheet.html).

Alternatively, an easier way to add the missing repositories is:

    add-apt-repository --yes main
    add-apt-repository --yes restricted
    add-apt-repository --yes universe
    add-apt-repository --yes multiverse

If you do not have the the `add-apt-repository` command, install the package `software-properties-common` to get it.

    apt install software-properties-common

Remember to execute `apt update` before trying to install packages.

**_Question 2: If so, why does cubic not pull the sources.list from the host-os?_**

As I mentioned in [the answer to your other question](https://github.com/PJ-Singh-001/Cubic/issues/37), the [Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) in Cubic is a secure, isolated file system that you have root access to.

This allows you to edit, add, or delete files without harming your host OS. So the [Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) in Cubic does not read files, such as `sources.list`, from your host machine.  In fact, the files from your host machine may not be relevant or appropriate for the OS you are customizing. (The only information that us used from your host machine is the network configuration, so you have internet access, and this is used in read-only mode).

This approach gives you maximum control of how you want to customize your OS, and it allows you to run a different OS (such as Linux Mint, Elementary, etc.) or a different OS Version (such as Ubuntu 18.04, 20.04, 21.04, etc.) on your host machine.

Note that Cubic does run the same kernel as your host OS; the running kernel version is displayed near the top right of the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) in Cubic.
