### ISSUE TITLE
`cryptsetup "Couldn't resolve device"` error while upgrading packages.

### ISSUE THREAD

**Issue by paolodina** [PJ-Singh-001/Cubic#4]
**Describe the bug**

`apt upgrade` terminates with an error.

**To Reproduce**

At the Cubic terminal page type:
```
apt update
apt upgrade
```

**Expected behavior**

The update should terminate without errors.

**OS Information**
 - OS/Distro Name: Xubuntu
 - OS Version 20.04 LTS

**Cubic Information (please complete the following information):**
 - Cubic Version: 2021.12.67
 - ISO Customizing: xubuntu-20.04.3-desktop-amd64.iso
 - Download Link:  https://cdimage.ubuntu.com/xubuntu/releases/20.04.3/release/xubuntu-20.04.3-desktop-amd64.iso

**Cubic Log:**

I don't file the log file.

**Screenshots**
![OIdsE1u](https://user-images.githubusercontent.com/1157401/146834670-9f984b6c-d0e0-4a31-bd9b-cba170db9a08.png)

**Additional notes:**
Even with the `ERROR` and `WARNING`, **at the end of the process the packages get upgraded**.
```
# apt upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by PJ-Singh-001** [comment]
This is normal, and won't impact your customizations.

This happens because the "virtual terminal" in Cubic is not an actual running system. It is just a set of files that you have read/write access to as user "root".
