### ISSUE TITLE
What is the boot time of an XZ compressed ISO?

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#40]
Hello forum,

Xz compression makes my Ubuntu 1804 Desktop LTS ISO about 300-500 mb smaller and the fan of the CPU is going to turn much faster :)

Do you have experiences of how much this high compression does increase the startup time of rather old PC's (if the PC is booted from USB-stick or DVD)? Are there downsides of this high ISO compression to be expected?

Thank's a lot!

Joe

**Comment by PJ-Singh-001** [comment]
In my experience, although compression using `xz` is quite slow, I've found that booting from an ISO created using `xz` compression is "bearable", although it is still slow compared to decompression of a `gzip` archive.

(I know you are looking for as small an ISO as possible, but I would like to mention that `zstd` is a newer algorithm with compression comparable to `gzip`, but with faster decompression speed than `gzip`).
