### ISSUE TITLE
Getting "No root file system defined" error during installation.

### ISSUE THREAD

**Issue by pqvindesland** [PJ-Singh-001/Cubic#41]
**Describe the question**

During the installation I am getting the above error, i am newbie in using preseed so this is most probably an error from my side.

Could you please have a look at my preseed configuration and suggest how I can resolve this? I really need a configuration that would work on multiple machine types with uefi boot, if that is possible.

**What you have tried**

Tried multiple suggestions after googling but nothing has so far resolved the issue

**Expected behavior**

A completed installation
Ubuntu 20.04
Cubic 2022.01.70

My seed configuration

    # Localization
    d-i debian-installer/language string en_US:en
    d-i debian-installer/country string RU
    d-i debian-installer/locale select en_US.UTF-8
    d-i localechooser/preferred-locale en_US.UTF-8

    # Keyboard
    d-i console-setup/ask_detect boolean false
    d-i keyboard-configuration/layoutcode string ru
    d-i keyboard-configuration/toggle select Alt+Shift

    # Networking
    d-i netcfg/choose_interface select auto
    d-i netcfg/get_domain string lan.forstwoof.ru

    # Mirror
    d-i mirror/protocol select http
    d-i mirror/country string manual
    d-i mirror/http/hostname string mirror.yandex.ru
    d-i mirror/http/directory string /ubuntu
    d-i mirror/http/proxy string

    # Clock and time
    d-i clock-setup/utc boolean true
    d-i time/zone string Europe/Oslo
    d-i clock-setup/ntp boolean true
    d-i clock-setup/ntp-server string kangaroo

    # Partitioning
    #d-i partman-auto/disk string /dev/vda
    d-i partman-auto/method string lvm
    d-i partman-lvm/device_remove_lvm boolean true
    d-i partman-lvm/device_remove_lvm_span boolean true
    d-i partman-auto/purge_lvm_from_device boolean true
    d-i partman-auto-lvm/new_vg_name string vg00
    d-i partman-auto-lvm/guided_size string max
    d-i partman/alignment select cylinder
    d-i partman-auto/choose_recipe select boot-root
    d-i partman-auto/expert_recipe string \
      boot-root ::                    \
        228 8000 256 ext2             \
          $primary{ }                     \
          $bootable{ }                \
          method{ format }            \
          format{ }                       \
          use_filesystem{ }               \
          filesystem{ ext2 }              \
          mountpoint{ /boot } .       \
        100 7000 1000000000 ext4      \
          $primary{ }                     \
          $defaultignore{ }       \
          method{ lvm }           \
          device{ /dev/sda }          \
          vg_name{ vg00 } .               \
        322 5000 1000000000 ext4      \
          $lvmok{ }               \
          in_vg{ vg00 }           \
          lv_name{ root }         \
          method{ format }        \
          format{ }               \
          use_filesystem{ }       \
          filesystem{ ext4 }          \
          mountpoint{ / } .              \
        4096 6000 4128 swap       \
          $lvmok{ }               \
          in_vg{ vg00 }           \
          lv_name{ swap }         \
          method{ swap }          \
          format{ } .             \
        1024 4000 1088 ext4           \
          $lvmok{ }               \
          in_vg{ vg00 }           \
          lv_name{ tmp }          \
          method{ format }        \
          format{ }               \
          use_filesystem{ }       \
          filesystem{ ext4 }          \
          mountpoint { /tmp } .       \
        10240 3000 10256 ext4         \
          $lvmok{ }               \
          in_vg{ vg00 }           \
          lv_name{ usr }          \
          method{ format }        \
          format{ }               \
          use_filesystem{ }       \
          filesystem{ ext4 }          \
          mountpoint { /usr } .       \
        5120 2000 5168 ext4           \
          $lvmok{ }               \
          in_vg{ vg00 }           \
          lv_name{ var }          \
          method{ format }        \
          format{ }               \
          use_filesystem{ }       \
          filesystem{ ext4 }          \
          mountpoint { /var } .       \
        153600 1000 1000000000 ext4       \
          $lvmok{ }               \
          in_vg{ vg00 }           \
          lv_name{ home }         \
          method{ format }        \
          format{ }               \
          use_filesystem{ }       \
          filesystem{ ext4 }          \
          mountpoint { /home } .
    d-i partman-lvm/confirm boolean true
    d-i partman/confirm_write_new_label boolean true
    d-i partman/choose_partition select Finish
    d-i partman/confirm boolean true
    d-i partman/confirm_nooverwrite boolean true

    # Base system installation
    d-i base-installer/initramfs-tools/driver-policy select most
    d-i live-installer/mode select normal
    d-i base-installer/kernel/image string linux-image-generic

    # Account setup
    d-i passwd/shadow boolean true
    d-i passwd/root-login boolean true
    d-i passwd/make-user boolean false

    # Package management
    d-i apt-setup/restricted boolean true
    d-i apt-setup/universe boolean true
    d-i apt-setup/multiverse boolean true
    d-i apt-setup/backports boolean true
    d-i apt-setup/use_mirror boolean true
    d-i apt-setup/services-select-ubuntu multiselect security, partner
    d-i apt-setup/security_host string mirror.yandex.ru
    d-i apt-setup/security_path string /ubuntu

    # Packages
    tasksel tasksel/first multiselect server, openssh-server
    d-i pkgsel/include string kexec-tools open-vm-tools rng-tools zsh nano
    d-i pkgsel/upgrade select full-upgrade
    d-i pkgsel/update-policy select unattended-upgrades
    popularity-contest popularity-contest/participate boolean true

    # Boot loader
    ![Screenshot from 2022-04-05 18-15-17](https://user-images.githubusercontent.com/18611311/161799384-dce74d99-2ce6-48af-945a-cd09c1569b24.png)

    d-i grub-installer/only_debian boolean true
    d-i grub-installer/with_other_os boolean false
    d-i debian-installer/add-kernel-opts string text console=tty0 console=ttyS0,115200n8

    # kexec should handle reboots
    kexec-tools kexec-tools/load_kexec boolean true

    # Finishing up the installation
    d-i finish-install/reboot_in_progress note

**Comment by PJ-Singh-001** [comment]
This is hard for me to answer because I've never done partitioning using preseed.

However, the message you are getting seems to indicate that a partition for `/` has not been defined.

Do you need to specify the location for `/` in your preseed?

**Comment by PJ-Singh-001** [comment]
I formatted the preseed configuration in your comment, and I can (now) see you have specified "mountpoint{ / }" for the root partition.

**Comment by tcboeira** [comment]
Hi pqvindesland, if I may have a question...
In this example, did you define exactly the size of the partitions OR is there a way to define it in percentage?
I mean, instead of saying in MB the size of each partition I say that / would be x% of the disk, that SWAP would be y% and so on...
Or not, this is insane madness...
Hugs

**Comment by PJ-Singh-001** [comment]
@pqvindesland, I'll assume you've resolved your problem, so I will close this issue.
