### ISSUE TITLE
How do I make my OS updatable?

### ISSUE THREAD

**Issue by AHumanIBelieve** [PJ-Singh-001/Cubic#45]
I am making a custom iso in cubic. I then realised that there is no way for people to be able to update it without re-installing the os. Is there any way to point the iso to a place where it can receive updates?

Also, the docs mention an emulator. I cannot see that anywhere. Where can I find it?

Thank you in advance.

My OS is Linux Mint 20.3
Cubic 2022.01.70
Customising Lubuntu 20.04.4 LTS (Focal Fossa)
[https://cdimage.ubuntu.com/lubuntu/releases/20.04.4/release/lubuntu-20.04.4-desktop-amd64.iso](https://cdimage.ubuntu.com/lubuntu/releases/20.04.4/release/lubuntu-20.04.4-desktop-amd64.iso)

**Comment by PJ-Singh-001** [comment]
I'll answer your second question first:

The button to launch the emulator is on the left in the header bar, and it has the label "Test".

_This button will only be shown if your system has at least 1.5 GB of memory currently available to run the emulator. (While running Cubic, you can check System Monitor to see how much memory your system currently has available)._

In Cubic, there are only two pages where this button may be shown:

 1. On the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page), only if you have opened an existing project for which you have already generated a custom ISO using Cubic.

    ![image](https://user-images.githubusercontent.com/19394936/163069979-0f821c02-fe9f-49b6-9b3a-a3ecb0be4fc4.png)

 2. On the [Finish page](https://github.com/PJ-Singh-001/Cubic/wiki/Finish-Page).
 
    ![image](https://user-images.githubusercontent.com/19394936/163069784-a1e2b91f-798c-480a-906b-b14c456b1b1b.png)

Also, note that if your CPU doesn't support virtualization, or if you attempt to run Cubic in a virtual machine (such as Virtual Box), the emulator's performance will be severely degraded.

**Comment by PJ-Singh-001** [comment]
Regarding your first question, the ability to upgrade depends on what kind of customizations you've done.

 1. If you've simply installed software using `apt`, then this software will be updated when the user does an update (or upgrade) using `apt` or the Software Center. This should not be an issue.

 2. If you've manually changed installed packages, configuration files, or themes, then those changes may be overwritten when the user does an update (or upgrade) using `apt` or the Software Center.

One technique I use to overcome the problem with # 2 is to add scripts to `/etc/apt/apt.conf.d/80update`. Therefore, after each time `apt` runs, my custom scripts will be invoked. These scripts, which I keep in `/opt`, reapply my custom configurations. You can research online on how to use `/etc/apt/apt.conf.d/80update`.

Another way you can ensure your custom OS users are getting only your "approved" updates is to host your own package repositories, and configure your custom OS to point to those repositories. However, I've never done this, and I don't know what is involved.

**Comment by AHumanIBelieve** [comment]
Thank you! I'm still not sure about the first answer, however as this is my top bar. 
![image](https://user-images.githubusercontent.com/103516619/163171183-0af7ccd6-eb7f-4788-b9a1-4b626d4f36b2.png)
I thank you for all your help and hope you have a nice day.

EDIT:
I have found the test button, my ram was just clogged up
