### ISSUE TITLE
Cubic doesn't open on WSL 2.

### ISSUE THREAD

**Issue by partisani** [PJ-Singh-001/Cubic#46]
**Describe the bug**

See, when i try to open it in my wsl 2, it throws an error and exits

**To Reproduce**

Download it with the commands in WSL 2:
```
sudo apt-add-repository universe
sudo apt-add-repository ppa:cubic-wizard/release
sudo apt update
sudo apt install --no-install-recommends cubic
```

Run It.

**OS Information (please complete the following information):**
 - OS/Distro Name: None
 - OS Version: None

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.01-70-release~202201240317~ubuntu

**Cubic Log:**
```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(cubic:475): Gtk-CRITICAL **: 17:21:06.373: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(cubic:475): Gtk-CRITICAL **: 17:21:06.373: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(cubic:475): Gtk-CRITICAL **: 17:21:06.373: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault
```

**Comment by PJ-Singh-001** [comment]
See if  [How to run Cubic in WSL?](https://github.com/PJ-Singh-001/Cubic/issues/18#issuecomment-1021485758) helps.
