### ISSUE TITLE
How to create a user with sudo permissions (if booted from the ISO)?

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#47]
Hello list

just booted my PC from the newly remasterd cubic ISO (Ubuntu 18.04 LTS DVD)

If I try to use "sudo", the following message is shown:

[sudo] password for test: 
test is not in the sudoers file.  This incident will be reported.

Question:
Is there  a way to fix this in the cubic environment before creating the ISO?

Thank you very much in advance for your  help!

Joe

PS
By the way, your explanations are excellent in all of my recent posts/questions :)

**Comment by PJ-Singh-001** [comment]
Here is how to create users for two scenarios:

 1. If you want to create _one_ user that is available _after_ installation, use the preseed technique [as shown in step 6 here](https://github.com/PJ-Singh-001/Cubic/issues/24#issuecomment-1043662684).
    (Be sure to include `sudo` in the `passwd/user-default-groups` list).

 2. If you want to create user(s) available in the _Live environment_ (and after installation), create the user(s) in Cubic's Terminal page, as [shown here](https://github.com/PJ-Singh-001/Cubic/issues/3#issuecomment-997134540).
    (Be sure to execute `usermod -a -G sudo <user>` for each user that requires `sudo` privileges).
