### ISSUE TITLE
Will held-back packages interfere with an OS upgrade?

### ISSUE THREAD

**Issue by eband** [PJ-Singh-001/Cubic#50]
I have Wine and Samba held-back for personal reasons.

If I try a Mint OS upgrade, will the held-back packages interfere?

**Comment by PJ-Singh-001** [comment]
Heldback packages interfere with upgrades when other packages need newer versions of the heldback packages.

I don't see this being an issue with wine.

However `samba` may be different...

 1. Use the following command to see which version of `samba` you have:

        dpkg -l samba

 2. Then, use the following command to see which packages on your system depend on `samba`. 

        apt rdepends samba

    For example, on my machine, this is what I see:

        apt rdepends samba
        samba
        Reverse Depends:
          Breaks: samba-vfs-modules (<< 2:4.3.2+dfsg-1)
          Enhances: samba-vfs-modules
          Replaces: samba-vfs-modules (<< 2:4.3.2+dfsg-1)
          Breaks: samba-vfs-modules (<< 2:4.3.2+dfsg-1)
          Replaces: samba-libs (<< 2:4.3.3+dfsg-1)
          Suggests: qemu-system-x86
          Suggests: qemu-system-sparc
          Suggests: qemu-system-ppc
          Suggests: qemu-system-misc
          Suggests: qemu-system-mips
          Suggests: qemu-system-arm
          Breaks: libldb2 (<< 2:4.7.0~)
          Depends: peony-share
          Depends: kworkflow
          Suggests: kinfocenter
          Suggests: kdenetwork-filesharing
          Depends: gadmin-samba
          Suggests: fbx-all
          Enhances: samba-vfs-modules
          Replaces: samba-vfs-modules (<< 2:4.3.2+dfsg-1)
          Replaces: samba-libs (<< 2:4.3.3+dfsg-1)
          Suggests: nautilus-share (>= 3.0.27a)
          Suggests: qemu-system-x86
          Suggests: qemu-system-sparc
          Suggests: qemu-system-ppc
          Suggests: qemu-system-misc
          Suggests: qemu-system-mips
          Suggests: qemu-system-arm
          Breaks: libldb2 (<< 2:4.7.0~)

    The packages that _depend_ on `samba` are the ones you need to worry about.

    In the above example, `peony-share`, `kworkflow`, and `gadmin-samba` are the ones we need to investigate further.

 3. For each of these packages, check what is the minimum version of `samba` that packages on the *upgraded* system require.

 4. Option 1 is to check this in a virtual machine, running the newer version of your OS, using the command:

        apt depends <package name>

    Continuing with this example, let's check `gadmin-samba`:

        apt depends gadmin-samba
        gadmin-samba
          Depends: libatk1.0-0 (>= 1.12.4)
          Depends: libc6 (>= 2.14)
          Depends: libgdk-pixbuf2.0-0 (>= 2.22.0)
          Depends: libglib2.0-0 (>= 2.12.0)
          Depends: libgtk2.0-0 (>= 2.8.0)
          Depends: libpango-1.0-0 (>= 1.14.0)
          Depends: menu
          Depends: samba
          Depends: samba-common-bin

    Thus, we can see that `gadmin-samba` can work with _any_ version of `samba` because a version number is not listed (it just says `Depends: samba`).

 5. Option 2 is to check this by using an [online package search](https://packages.ubuntu.com/). (Linux Mint may have a similar website?) For example, for Ubuntu Impish, the [online package search for gadmin-samba](https://packages.ubuntu.com/impish/gadmin-samba) gives the same information as Option 1.

    ![image](https://user-images.githubusercontent.com/19394936/165340277-48b381ae-99a3-4cd6-a6c5-f127b8b6b5cd.png)


    Thus, we can see that `gadmin-samba` can work with _any_ version of `samba` because a version number is not listed (it just shows a dependency on samba).

 6. If, however, a particular version of `samba` was specified, we would have to ensure that the heldback version of `samba` qualifies by comparing it to the version # you obtained in step 1.

You must repeat step 3 for every packaged listed as "Depends" in step 2.

You may also want to check your `wine` package as well, just in case.

**Comment by PJ-Singh-001** [comment]
One final comment:

If the process outlined above seems complicated, a very easy way to check all of this is to simply create a Cubic project. Hold back the packages you want to hold back. Then do an a upgrade. If you get errors, you know there is an issue with your held back packages. You can always easily delete and create new Cubic projects, so using Cubic is a very quick and easy way to check things like this automatically.

**Comment by eband** [comment]
Thank you for your response.

Very well, I shall try it.
