### ISSUE TITLE
Ubuntu Autoinstall ISO with Cloud-init

### ISSUE THREAD

**Issue by xrkzor** [PJ-Singh-001/Cubic#51]
Hello!
I'm actualy trying to create an automatic installation on USB Key of ubuntu server 20.04 with user-data & meta-file on Cubic.

1. I have installed Ubuntu server and take back my user-data files into preseed folder (/preseed/user-data)
2. I modified grub.cfg & /isolinux/txt.cfg to point out both data files.

 > kernel /casper/vmlinuz
 > append boot=casper initrd=/casper/initrd.lz quiet autoinstall 
 > ds=nocloud\;s=/cdrom/preseed/ ---

> menuentry "Install Ubuntu Server" {
 > set gfxpayload=keep
  > linux  /casper/vmlinuz boot=casper quiet autoinstall ds=nocloud\;s=/cdrom/preseed/ ---
   >initrd   casper/initrd.lz
>}

The installation starts but it's like he's ignoring user-data files.
Does anyone know what i'm missing or which solution i can try ?

I'm using Cubic 2022.01.70

Best Regards

**Comment by PJ-Singh-001** [comment]
Can you share your user-data and meta-file files (or simplified versions of those files), so I can try this on my end?

**Comment by xrkzor** [comment]
Hello,

There is my user-data :

[user-data.txt](https://github.com/PJ-Singh-001/Cubic/files/8570402/user-data.txt)

meta-data files is an empty files.

Best regards

**Comment by elor** [comment]
Had the same issue:
The semicolon in `ds=nocloud;s=/cdrom/preseed/` seems to start a comment, so everything following it is ignored.

Could you try `"ds=nocloud;s=/cdrom/preseed/"` or `ds=nocloud\;s=/cdrom/preseed/` ?

**Comment by elor** [comment]
To confirm: We're escaping the semicolon using a backslash, i.e.:

    linux	/casper/vmlinuz autoinstall ds=nocloud-net\;s=http://123.124.125.126:5005/ ---

This was for the desktop iso of ubuntu 21.04

**Comment by xrkzor** [comment]
I tried both (`ds=nocloud;s=/cdrom/preseed/` or `ds=nocloud \;s=/cdrom/preseed/`) but still unsuccessful .

**Comment by PJ-Singh-001** [comment]
@elor,

Does the empty space character before `\;s` make a difference?
(See @xrkzor's comment above).

**Comment by elor** [comment]
It did, at least in 21.04.
Without it, our workstations didn't install themselves.

I found out about it on a Ubuntu Server dev group, but couldn't give the link anymore, sorry.

It may be unnecessary

**Comment by PJ-Singh-001** [comment]
@xrkzor,

Try using the following (without spaces):

    ds=nocloud\;s=/cdrom/preseed/

**Comment by PJ-Singh-001** [comment]
@xrkzor, I'll assume you have resolved your problem, so I will close this issue.
