### ISSUE TITLE
"Authentication required" to access the hdd if booted from ISO/DVD

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#52]
Hello

booted an Ubuntu1804 based Cubic ISO form DVD and would like to access the hdd of the pc with the filemanager of the os,
but the following message is shown:

"Authentication required"

Using the cubic login/user-password (in my case the same user and password already defined in the non-cubic environment)
does NOT work.

What I am doing wrong?

Thank's in advance for your help!

Joe

**Comment by PJ-Singh-001** [comment]
I'm assuming you mounted the HDD in the Live environment (i.e. the OS you are running from DVD)?

**Comment by sudo-joe** [comment]
Yes I did mount the HDD in the Live environment.

**Comment by sudo-joe** [comment]
USB memory sticks can me mounted/accessed (with the filemanager) without the need to enter a password.

**Comment by PJ-Singh-001** [comment]
Is this issue happening with the same "test" user from your other question, #54?

Also, what is the output of the following command, when executed from your Live environment?...

    groups

**Comment by sudo-joe** [comment]
>Is this issue happening with the same "test" user from your other question, https://github.com/PJ-Singh-001/Cubic/issues/54?

Yes that happens with the "test" user

>Also, what is the output of the following command, when executed from your Live environment?...
>    `groups`

    test@ubuntu:~$ groups
    test
    test@ubuntu:~$

**Comment by PJ-Singh-001** [comment]
This is your problem.

Your user should belong to the following *additional* groups:
- `adm`
- `cdrom`
- `sudo`
- `dip`
- `plugdev`
- `lpadmin`
- `lxd`
- `sambashare`

The `adduser <user>` command you used to create your "test" user should have taken care of all of these, except `sudo`. (To add the `sudo` privilege, in addition to the default privileges, you would need to execute `usermod -a -G sudo <user>`).

However, in your case, you should execute the following command to add all of the missing groups to your "test" user:

    usermod -a -G adm cdrom sudo dip plugdev lpadmin lxd sambashare <user>
