### ISSUE TITLE
I can't install the cubic on Ubuntu 20.04

### ISSUE THREAD

**Issue by CoulsonYing** [PJ-Singh-001/Cubic#53]
**Describe the question**
I can't install the cubic on Ubuntu20.04

**What you have tried**
I did the following commands firstly:
`sudo apt-add-repository ppa:cubic-wizard/release`
`sudo apt update`
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B7579F80E494ED3406A59DF9081525E2B4F1283B`
`sudo apt install --no-install-recommends cubic`
but I got this error:
![2022-05-02_11-14](https://user-images.githubusercontent.com/28505451/166180019-a020c644-6ba9-41d4-94ed-3edbee119d24.png)

then I tried to install `systemd-container` by command
``sudo apt install systemd-container
![2](https://user-images.githubusercontent.com/28505451/166180580-4f43fce5-ef06-494a-bcf4-997ace764bdb.png)

then I tried to install `systemd-container` by command
`sudo apt install systemd=245.4-4ubuntu3.16`
![3](https://user-images.githubusercontent.com/28505451/166180847-3468c583-69a8-4526-b399-5304d85f19eb.png)

then I installed the `systemd`, but the OS told I've got the newest one.
![4](https://user-images.githubusercontent.com/28505451/166180924-6a307de2-7dd9-4365-b6fa-a1626b56ccf9.png)

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 20.4

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.5.2 from PPA

**Comment by PJ-Singh-001** [comment]
What is the output of?...

    sudo apt-add-repository --list

**Comment by CoulsonYing** [comment]
![image](https://user-images.githubusercontent.com/28505451/166390362-def2d8ca-6a0e-4227-9f50-af73c3e4f953.png)

**Comment by CoulsonYing** [comment]
![image](https://user-images.githubusercontent.com/28505451/166390532-e61e4d23-2afe-4184-9a2b-35180905b6d7.png)

**Comment by PJ-Singh-001** [comment]
What is the output of?...

    sudo apt-add-repository --list

If you do not have the `apt-add-repository` command, you can install it using:

    sudo apt install software-properties-common

Please copy and paste the output here, instead of a screen shot. Be sure to format your output using the "<>" code button above, so it is easy to read.

**Comment by CoulsonYing** [comment]
I am sure that I have the `apt-add-repository` command, but there is no option : `--list`
As long as I enter this command, I get this output:
````
Usage: apt-add-repository <sourceline>

apt-add-repository is a script for adding apt sources.list entries.
It can be used to add any repository and also provides a shorthand
syntax for adding a Launchpad PPA (Personal Package Archive)
repository.

<sourceline> - The apt repository source line to add. This is one of:
  a complete apt line in quotes,
  a repo url and areas in quotes (areas defaults to 'main')
  a PPA shortcut.
  a distro component

  Examples:
    apt-add-repository 'deb http://myserver/path/to/repo stable myrepo'
    apt-add-repository 'http://myserver/path/to/repo myrepo'
    apt-add-repository 'https://packages.medibuntu.org free non-free'
    apt-add-repository http://extras.ubuntu.com/ubuntu
    apt-add-repository ppa:user/repository
    apt-add-repository ppa:user/distro/repository
    apt-add-repository multiverse

If --remove is given the tool will remove the given sourceline from your
sources.list

apt-add-repository: error: no such option: --list
````
By the way, I have already installed `apt-add-repository` command.

**Comment by PJ-Singh-001** [comment]
OK, I had not realized that the `--list` option was added to `apt-add-repository` in a later version than what is available in Ubuntu 20.04 Focal Fossa.

Let's try this:

What is the output of...

 1. `apt-cache policy systemd`

 2. `apt-cache policy libsystemd0`

 3. `apt-cache policy systemd-container`

Cubic can work with any version of `systemd-container` >= version 237.

Package `systemd-container` needs the package `systemd`.

The issue is that, as you can see from your output, `systemd-container` requires `systemd` version 245.4-4ubuntu3.**16**.

However you have `systemd` version 245.4-4ubuntu3.**17** already installed, so `apt` is not able to install the *older* version of `systemd-container`.

According to the [Ubuntu Packages site](https://packages.ubuntu.com/focal-updates/systemd), the highest version of `systemd` available in Focal Fossa is version 245.4-4ubuntu3.**16**.

We need to figure out from where did your Ubuntu installation get `systemd` version 245.4-4ubuntu3.**17**, and why is it not able to get the matching versions of `libsystemd0` and `systemd-container` from the same place? Hopefully, the output of the three commands above will help answer this question.

**Comment by CoulsonYing** [comment]
Thanks, bro!
The output of `apt-cache policy systemd` is
```
systemd:
  Installed: 245.4-4ubuntu3.17
  Candidate: 245.4-4ubuntu3.17
  Version table:
 *** 245.4-4ubuntu3.17 100
        100 /var/lib/dpkg/status
     245.4-4ubuntu3.16 500
        500 http://mirrors.aliyun.com/ubuntu focal-updates/main amd64 Packages
     245.4-4ubuntu3.15 500
        500 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 Packages
     245.4-4ubuntu3 500
        500 http://mirrors.aliyun.com/ubuntu focal/main amd64 Packages
```
The output of `apt-cache policy libsystemd0` is
```
libsystemd0:
  Installed: 245.4-4ubuntu3.17
  Candidate: 245.4-4ubuntu3.17
  Version table:
 *** 245.4-4ubuntu3.17 100
        100 /var/lib/dpkg/status
     245.4-4ubuntu3.16 500
        500 http://mirrors.aliyun.com/ubuntu focal-updates/main amd64 Packages
     245.4-4ubuntu3.15 500
        500 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 Packages
     245.4-4ubuntu3 500
        500 http://mirrors.aliyun.com/ubuntu focal/main amd64 Packages
```
And the output of `apt-cache policy systemd-container` is
```
systemd-container:
  Installed: (none)
  Candidate: 245.4-4ubuntu3.16
  Version table:
     245.4-4ubuntu3.16 500
        500 http://mirrors.aliyun.com/ubuntu focal-updates/main amd64 Packages
     245.4-4ubuntu3.15 500
        500 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 Packages
     245.4-4ubuntu3 500
        500 http://mirrors.aliyun.com/ubuntu focal/main amd64 Packages
```

**Comment by PJ-Singh-001** [comment]
You have version 245.4-4ubuntu3.17 of *both* `systemd` and `libsystemd0`.

Take a look at the [details for package `systemd`](https://packages.ubuntu.com/focal-updates/systemd). You can see that the **official** most up-to-date version should be **245.4-4ubuntu3.16**.

By the way, I do not think `http://mirrors.aliyun.com/ubuntu` is an official mirror site for Ubuntu.
- It is not listed [here](https://packages.ubuntu.com/focal-updates/amd64/libsystemd0/download).
- It is also not listed [here](https://launchpad.net/ubuntu/+archivemirrors).
- It is *possible* this mirror is hosting the wrong versions of `systemd` and `libsystemd0`.

*However, more likely* is that one of your PPAs in `/etc/apt/sources.list.d` is supplying the incorrect versions of `systemd` and `libsystemd0`.

Take a look at which packages on your system are using `systemd`.

    apt-cache --installed rdepends systemd

Were any of these packages installed by you (using one of the PPAs from `/etc/apt/sources.list.d`) ?

Also, please cut and paste the output of this command, and I'll compare your output with mine.

**Comment by CoulsonYing** [comment]
Thanks for your reply.
The mirror I used is listed [here](https://launchpad.net/ubuntu/+mirror/mirrors.aliyun.com-archive)(the second one of your listed mirror site). It is the mirror of Alibaba in China.

And the output of `apt-cache --installed rdepends systemd` is:
```
coulson@dell:~$ apt-cache --installed rdepends systemd
systemd
Reverse Depends:
  udev
  udev
  systemd-timesyncd
  systemd-timesyncd
  libnss-systemd
  systemd-timesyncd
  systemd-sysv
  systemd-sysv
    systemd:i386
  libpam-systemd
  libnss-systemd
  udev
  udev
  systemd-timesyncd
  systemd-timesyncd
  systemd-timesyncd
  systemd-sysv
  systemd-sysv
    systemd:i386
  snapd
    systemd:i386
  libpam-systemd
  netplan.io
    systemd:i386
  xserver-xorg-core
  udev
  udev
  systemd-timesyncd
  systemd-timesyncd
  systemd-timesyncd
    systemd:i386
  systemd-sysv
    systemd:i386
  systemd-sysv
    systemd:i386
  snapd
    systemd:i386
  plymouth
    systemd:i386
  packagekit
    systemd:i386
  libnss-systemd
    systemd:i386
  libpam-systemd
    systemd:i386
  iio-sensor-proxy
    systemd:i386
  dbus-user-session
    systemd:i386
  xserver-xorg-core
  udev
  udev
  sysvinit-utils
  systemd-timesyncd
  systemd-timesyncd
  systemd-timesyncd
  systemd-sysv
  systemd-sysv
    systemd:i386
  snapd
    systemd:i386
  plymouth
    systemd:i386
  netplan.io
    systemd:i386
  packagekit
    systemd:i386
  libnss-systemd
  libpam-systemd
  init-system-helpers
  dbus-user-session
    systemd:i386
  iio-sensor-proxy
    systemd:i386
```

**Comment by PJ-Singh-001** [comment]
Your package `systemd` matches the output I see for Focal Fossa. (Except you have a lot of i386 architecture packages, but that shouldn't matter at all).

Can you also provide the output for `libsystemd0` ?

    apt-cache rdepends --installed libsystemd0

**Comment by CoulsonYing** [comment]
this is the output of `libsystemd0`:
```
coulson@dell:~$ apt-cache rdepends --installed libsystemd0
libsystemd0
Reverse Depends:
  systemd
  openssh-server
  gvfs-daemons
  wireshark-common
  systemd
  sane-utils
  pulseaudio
  openssh-server
  libwbclient0
  libpulse0
  libgdm1
  libapt-pkg6.0
  gnome-shell
  gdm3
  apt
  xwayland
  xserver-xorg-core
  xserver-xephyr
  uuid-runtime
  util-linux
  udisks2
  systemd
  spice-vdagent
  sane-utils
  rsyslog
  pulseaudio
  policykit-1
  packagekit
  openvpn
  openssh-server
  network-manager
  netplan.io
  modemmanager
  libwebkit2gtk-4.0-37
  libwbclient0
  libvte-2.91-0
  libpulse0
  libprocps8
  libpolkit-gobject-1-0
  libpam-fprintd
  libmutter-6-0
  libjavascriptcoregtk-4.0-18
  libgnome-desktop-3-19
  libgdm1
  libdbus-1-3
  libapt-pkg6.0
  libaccountsservice0
  gnome-system-monitor
  gnome-shell
  gnome-logs
  gnome-disk-utility
  gdm3
  gamemode
  fwupd
  dbus
  cups-daemon
  bsdutils
  apt
  wireshark-common
  vlc-plugin-base
  python3-systemd
  xwayland
  xserver-xorg-core
  xserver-xephyr
  uuid-runtime
  util-linux
  udisks2
  systemd
  spice-vdagent
  sane-utils
  rtkit
  rsyslog
  packagekit
  pulseaudio
  policykit-1
  libvte-2.91-0
  openvpn
  openssh-server
  network-manager
  netplan.io
  modemmanager
  libwbclient0
  libpam-fprintd
  libpulse0
  libprocps8
  libpolkit-gobject-1-0
  libmutter-6-0
  libapt-pkg6.0
  libgnome-desktop-3-19
  libgdm1
  libdbus-1-3
  gnome-disk-utility
  libaccountsservice0
  irqbalance
  inputattach
  gvfs-daemons
  gnome-system-monitor
  gnome-shell
  gnome-session-bin
  gnome-logs
  gamemode
  gdm3
  apt
  dbus
  cups-daemon
  colord
  bsdutils
  brltty
```

**Comment by PJ-Singh-001** [comment]
There are some minor differences. (I've sorted them and removed duplicates to make comparison easy).
- Yours is on the left.
- Mine is on the right.

![image](https://user-images.githubusercontent.com/19394936/167055669-a59caf4d-98f3-44d8-9bd9-7c772f5ad4c9.png)

- [`openssh-server`](https://packages.ubuntu.com/focal-updates/openssh-server) does not specify a particular version of `libsystemd0`
- [`vlc-plugin-base`](https://packages.ubuntu.com/focal/vlc-plugin-base) does not specify a particular version of `libsystemd0`
- [`wireshark-common`](https://packages.ubuntu.com/focal/wireshark-common) does not specify a particular version of `libsystemd0`

**Comment by CoulsonYing** [comment]
Oh, sorry, but what should I do?

**Comment by PJ-Singh-001** [comment]
This is good news. It doesn't look like there are *no* other packages on your system that depend on version 245.4-4ubuntu3.17 of `libsystemd0` and `systemd`.

Try manually installing version **245.4-4ubuntu3.16** of `libsystemd0` and `systemd`.

    sudo apt update
    sudo apt install libsystemd0=245.4-4ubuntu3.16 systemd=245.4-4ubuntu3.16

Hopefully, you will be able to do this without errors from `apt`.

**Comment by CoulsonYing** [comment]
OK, I try to do it now!

**Comment by CoulsonYing** [comment]
Bro, I get the following output, should I continue?
```
coulson@dell:~$ sudo apt install libsystemd0=245.4-4ubuntu3.16 systemd=245.4-4ubuntu3.16
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apg aptdaemon-data apturl-common cheese-common colord-data dconf-cli diffstat dns-root-data
  dnsmasq-base evolution-data-server evolution-data-server-common gdebi-core gdisk gettext
  gir1.2-accountsservice-1.0 gir1.2-clutter-1.0 gir1.2-clutter-gst-3.0 gir1.2-cogl-1.0
  gir1.2-coglpango-1.0 gir1.2-dbusmenu-glib-0.4 gir1.2-dee-1.0 gir1.2-gck-1 gir1.2-gcr-3
  gir1.2-gdm-1.0 gir1.2-geoclue-2.0 gir1.2-gnomebluetooth-1.0 gir1.2-goa-1.0 gir1.2-graphene-1.0
  gir1.2-gst-plugins-base-1.0 gir1.2-gtkclutter-1.0 gir1.2-gweather-3.0 gir1.2-ibus-1.0
  gir1.2-javascriptcoregtk-4.0 gir1.2-json-1.0 gir1.2-mutter-6 gir1.2-nm-1.0 gir1.2-nma-1.0
  gir1.2-rsvg-2.0 gir1.2-snapd-1 gir1.2-soup-2.4 gir1.2-unity-5.0 gir1.2-upowerglib-1.0
  gir1.2-vte-2.91 gir1.2-webkit2-4.0 gkbd-capplet gnome-control-center-faces gnome-online-accounts
  gnome-session-bin gnome-session-common gnome-shell-common gnome-startup-applications
  gstreamer1.0-clutter-3.0 gvfs-libs intltool-debian libapt-pkg-perl libarchive-zip-perl
  libasync-mergepoint-perl libatasmart4 libb-hooks-endofscope-perl libb-hooks-op-check-perl
  libblockdev-crypto2 libblockdev-fs2 libblockdev-loop2 libblockdev-part-err2 libblockdev-part2
  libblockdev-swap2 libblockdev-utils2 libblockdev2 libbluetooth3 libcamel-1.2-62 libcapture-tiny-perl
  libcdio-cdda2 libcdio-paranoia2 libcdio18 libcheese-gtk25 libcheese8 libclass-method-modifiers-perl
  libclass-xsaccessor-perl libclone-perl libclutter-1.0-0 libclutter-1.0-common libclutter-gst-3.0-0
  libclutter-gtk-1.0-0 libcogl-common libcogl-pango20 libcogl-path20 libcogl20 libcolord-gtk1
  libcolorhug2 libcpanel-json-xs-perl libcroco3 libcue2 libdee-1.0-4 libdevel-callchecker-perl
  libdevel-size-perl libdigest-bubblebabble-perl libdynaloader-functions-perl libebackend-1.2-10
  libebook-1.2-20 libebook-contacts-1.2-3 libecal-2.0-1 libedata-book-1.2-26 libedata-cal-2.0-1
  libedataserver-1.2-24 libedataserverui-1.2-2 libemail-valid-perl libept1.6.0 libexiv2-27
  libexporter-tiny-perl libfile-find-rule-perl libfont-ttf-perl libfprint-2-2 libfuture-perl
  libgdata-common libgdata22 libgdm1 libgeoclue-2-0 libgeocode-glib0 libgexiv2-2 libgif7
  libgnome-autoar-0-0 libgnomekbd-common libgnomekbd8 libgoa-1.0-0b libgoa-1.0-common
  libgoa-backend-1.0-1 libgsf-1-114 libgsf-1-common libgsound0 libgssdp-1.2-0 libgtk2-perl
  libgupnp-1.2-0 libgupnp-av-1.0-2 libgupnp-dlna-2.0-3 libgweather-3-16 libgweather-common
  libimport-into-perl libio-async-loop-epoll-perl libio-async-perl libio-pty-perl libio-string-perl
  libipc-run-perl libjson-maybexs-perl liblinux-epoll-perl liblist-compare-perl liblist-moreutils-perl
  libmediaart-2.0-0 libmodule-implementation-perl libmodule-runtime-perl libmoo-perl
  libmoox-aliases-perl libnamespace-clean-perl libndp0 libnet-dns-perl libnet-dns-sec-perl
  libnet-domain-tld-perl libnet-ip-perl libnm0 libnma0 libnumber-compare-perl libpackage-stash-perl
  libpackage-stash-xs-perl libpango-perl libparams-classify-perl libparted-fs-resize0
  libpath-tiny-perl libpcre2-32-0 libperl4-corelibs-perl libperlio-gzip-perl libphonenumber7
  libpkcs11-helper1 libprotobuf17 libpulse-mainloop-glib0 libreadonly-perl libref-util-perl
  libref-util-xs-perl librole-tiny-perl librygel-core-2.6-2 librygel-db-2.6-2 librygel-renderer-2.6-2
  librygel-server-2.6-2 libsereal-decoder-perl libsereal-encoder-perl libsereal-perl libsodium23
  libstrictures-perl libstruct-dumb-perl libsub-exporter-progressive-perl libsub-identify-perl
  libsub-quote-perl libsysmetrics1 libteamdctl0 libtest-fatal-perl libtest-refcount-perl
  libtext-glob-perl libtext-levenshtein-perl libtotem-plparser-common libtotem-plparser18
  libtracker-control-2.0-0 libtracker-miner-2.0-0 libtracker-sparql-2.0-0 libtype-tiny-perl
  libtype-tiny-xs-perl libudisks2-0 libunicode-utf8-perl libunity-protocol-private0
  libunity-scopes-json-def-desktop libunity9 libvariable-magic-perl libvolume-key1 libxapian30
  libxklavier16 libxml-writer-perl libyaml-libyaml-perl lintian mobile-broadband-provider-info
  nautilus-data openvpn patchutils ppp pptp-linux python3-dateutil python3-debconf python3-debian
  python3-defer python3-macaroonbakery python3-nacl python3-protobuf python3-pymacaroons
  python3-rfc3339 python3-software-properties python3-tz rygel switcheroo-control t1utils tracker
  tracker-extract tracker-miner-fs unattended-upgrades update-notifier-common xwayland
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libopts25 ntp
Suggested packages:
  ntp-doc systemd-container policykit-1
Recommended packages:
  sntp
The following packages will be REMOVED:
  aptdaemon apturl brltty colord dbus-user-session fprintd friendly-recovery gdebi gdm3
  gnome-control-center gnome-disk-utility gnome-initial-setup gnome-settings-daemon gnome-shell
  gnome-shell-extension-appindicator gnome-shell-extension-desktop-icons
  gnome-shell-extension-ubuntu-dock gstreamer1.0-packagekit gvfs gvfs-backends gvfs-daemons gvfs-fuse
  init language-selector-gnome libnss-systemd libpam-fprintd libpam-systemd nautilus nautilus-share
  network-manager network-manager-config-connectivity-ubuntu network-manager-gnome
  network-manager-openvpn network-manager-openvpn-gnome network-manager-pptp
  network-manager-pptp-gnome packagekit packagekit-tools policykit-1 python3-aptdaemon
  python3-aptdaemon.gtk3widgets rtkit software-properties-common software-properties-gtk synaptic
  systemd-sysv systemd-timesyncd ubuntu-desktop ubuntu-desktop-minimal ubuntu-minimal
  ubuntu-release-upgrader-gtk ubuntu-session ubuntu-standard udisks2 update-manager update-notifier
The following NEW packages will be installed:
  libopts25 ntp
The following packages will be DOWNGRADED:
  libsystemd0 systemd
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  init systemd-sysv (due to init)
0 upgraded, 2 newly installed, 2 downgraded, 56 to remove and 0 not upgraded.
Need to get 0 B/4,794 kB of archives.
After this operation, 52.6 MB disk space will be freed.
You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
 ?] 


```

**Comment by PJ-Singh-001** [comment]
Don’t continue

**Comment by CoulsonYing** [comment]
I backed up the OS, then did continue and got something wrong. I recorded the output.
My computer is rebooting now.
Wait a moment......

**Comment by CoulsonYing** [comment]
Following messages were showed after I did continue
``` ?] Yes, do as I say!
(Reading database ... 241629 files and directories currently installed.)
Removing ubuntu-desktop (1.450.2) ...
Removing ubuntu-desktop-minimal (1.450.2) ...
Removing gnome-control-center (1:3.36.5-0ubuntu4) ...
Removing language-selector-gnome (0.204.2) ...
Removing nautilus-share (0.7.3-2ubuntu3) ...
Removing apturl (0.5.2ubuntu19) ...
Removing brltty (6.0+dfsg-4ubuntu6) ...
Removing colord (1.4.4-2) ...
Removing network-manager-gnome (1.8.24-1ubuntu3) ...
Removing dbus-user-session (1.12.16-2ubuntu2.1) ...
Removing libpam-fprintd:amd64 (1.90.9-1~ubuntu20.04.1) ...
Removing fprintd (1.90.9-1~ubuntu20.04.1) ...
Removing friendly-recovery (0.2.41ubuntu0.20.04.1) ...
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.13.0-41-generic
Found initrd image: /boot/initrd.img-5.13.0-41-generic
Found linux image: /boot/vmlinuz-5.13.0-40-generic
Found initrd image: /boot/initrd.img-5.13.0-40-generic
Found linux image: /boot/vmlinuz-5.13.0-30-generic
Found initrd image: /boot/initrd.img-5.13.0-30-generic
Adding boot menu entry for UEFI Firmware Settings
done
Removing gdebi (0.9.5.7+nmu3) ...
Removing gdm3 (3.36.3-0ubuntu0.20.04.4) ...
Removing gnome-disk-utility (3.36.3-0ubuntu1) ...
Removing gnome-initial-setup (3.36.2-0ubuntu2) ...
Removing gnome-shell-extension-ubuntu-dock (68ubuntu1~20.04.1) ...
Removing gnome-shell-extension-desktop-icons (20.04.0-3~ubuntu20.04.6) ...
Removing ubuntu-session (3.36.0-2ubuntu1) ...
Removing gnome-shell-extension-appindicator (33.1-0ubuntu0.20.04.2) ...
Removing gstreamer1.0-packagekit (1.1.13-2ubuntu1.1) ...
Removing gvfs-backends (1.44.1-1ubuntu1.1) ...
Removing gvfs-fuse (1.44.1-1ubuntu1.1) ...
Removing ubuntu-minimal (1.450.2) ...
Removing init (1.57) ...
Removing libnss-systemd:amd64 (245.4-4ubuntu3.17) ...
Checking NSS setup...
Removing ubuntu-standard (1.450.2) ...
Removing nautilus (1:3.36.3-0ubuntu1.20.04.1) ...
Removing network-manager-config-connectivity-ubuntu (1.22.10-1ubuntu2.3) ...
Removing network-manager-pptp-gnome (1.2.8-2) ...
Removing network-manager-pptp (1.2.8-2) ...
Removing network-manager-openvpn-gnome (1.8.12-1) ...
Removing network-manager-openvpn (1.8.12-1) ...
Removing software-properties-gtk (0.99.9.8) ...
Removing software-properties-common (0.99.9.8) ...
Removing packagekit-tools (1.1.13-2ubuntu1.1) ...
Removing packagekit (1.1.13-2ubuntu1.1) ...
Removing synaptic (0.84.6ubuntu5) ...
Removing rtkit (0.12-4) ...
Removing gvfs:amd64 (1.44.1-1ubuntu1.1) ...
Removing gvfs-daemons (1.44.1-1ubuntu1.1) ...
Removing udisks2 (2.8.4-1ubuntu2) ...
Removing network-manager (1.22.10-1ubuntu2.3) ...
Removing update-manager (1:20.04.10.10) ...
Removing update-notifier (3.192.30.10) ...
Removing python3-aptdaemon.gtk3widgets (1.1.1+bzr982-0ubuntu32.3) ...
Removing python3-aptdaemon (1.1.1+bzr982-0ubuntu32.3) ...
Removing gnome-shell (3.36.9-0ubuntu0.20.04.2) ...
Removing gnome-settings-daemon (3.36.1-0ubuntu1.1) ...
Removing ubuntu-release-upgrader-gtk (1:20.04.38) ...
Removing aptdaemon (1.1.1+bzr982-0ubuntu32.3) ...
Removing policykit-1 (0.105-26ubuntu1.3) ...
Removing libpam-systemd:amd64 (245.4-4ubuntu3.17) ...
Removing systemd-sysv (245.4-4ubuntu3.17) ...
Selecting previously unselected package libopts25:amd64.
(Reading database ... 240045 files and directories currently installed.)
Preparing to unpack .../libopts25_1%3a5.18.16-3_amd64.deb ...
Unpacking libopts25:amd64 (1:5.18.16-3) ...
dpkg: warning: downgrading systemd from 245.4-4ubuntu3.17 to 245.4-4ubuntu3.16
Preparing to unpack .../systemd_245.4-4ubuntu3.16_amd64.deb ...
Unpacking systemd (245.4-4ubuntu3.16) over (245.4-4ubuntu3.17) ...
dpkg: systemd-timesyncd: dependency problems, but removing anyway as you request
ed:
 systemd depends on systemd-timesyncd | time-daemon; however:
  Package systemd-timesyncd is to be removed.
  Package time-daemon is not installed.
  Package systemd-timesyncd which provides time-daemon is to be removed.
 systemd depends on systemd-timesyncd | time-daemon; however:
  Package systemd-timesyncd is to be removed.
  Package time-daemon is not installed.
  Package systemd-timesyncd which provides time-daemon is to be removed.

(Reading database ... 240050 files and directories currently installed.)
Removing systemd-timesyncd (245.4-4ubuntu3.17) ...
Selecting previously unselected package ntp.
(Reading database ... 240037 files and directories currently installed.)
Preparing to unpack .../ntp_1%3a4.2.8p12+dfsg-3ubuntu4.20.04.1_amd64.deb ...
Unpacking ntp (1:4.2.8p12+dfsg-3ubuntu4.20.04.1) ...
dpkg: warning: downgrading libsystemd0:amd64 from 245.4-4ubuntu3.17 to 245.4-4ub
untu3.16
Preparing to unpack .../libsystemd0_245.4-4ubuntu3.16_amd64.deb ...
Unpacking libsystemd0:amd64 (245.4-4ubuntu3.16) over (245.4-4ubuntu3.17) ...
Setting up libsystemd0:amd64 (245.4-4ubuntu3.16) ...
Setting up libopts25:amd64 (1:5.18.16-3) ...
Setting up ntp (1:4.2.8p12+dfsg-3ubuntu4.20.04.1) ...
Created symlink /etc/systemd/system/network-pre.target.wants/ntp-systemd-netif.p
ath → /lib/systemd/system/ntp-systemd-netif.path.
Created symlink /etc/systemd/system/multi-user.target.wants/ntp.service → /lib/s
ystemd/system/ntp.service.
ntp-systemd-netif.service is a disabled or a static unit, not starting it.
invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to bloc
k.
Setting up systemd (245.4-4ubuntu3.16) ...
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
Processing triggers for shared-mime-info (1.15-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.64.6-1~ubuntu20.04.4) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Processing triggers for man-db (2.9.1-1) ...
```

**Comment by PJ-Singh-001** [comment]
That was a pretty dangerous step you took!
I am glad you took a backup.

At this point, you have two options:

1. Reinstall Focal Fossa or a newer Ubuntu version, and copy all your files from your backup.
2. Recover your computer, and continue debugging this issue.

**Comment by CoulsonYing** [comment]
all right😂

**Comment by PJ-Singh-001** [comment]
If you recover your install from the backup, let me know, and we can try a few more things.

If you reinstall, please let me know what the installed versions of `systemd` and `libsystemd0` are?

You might want to check these using `dpkg -l systemd` before and after you install any PPAs and software to see if you can identify where version 245.4-4ubuntu3.17 is coming from.

**Comment by CoulsonYing** [comment]
I have installed my OS from backup now.
Can we talk in email? My email address is on my profile

**Comment by PJ-Singh-001** [comment]
I think I might have figured out what happened that caused you to get version 245.4-4ubuntu3.17 of `libsystemd0` and `systemd` on your system:

 1. You *enabled* the Focal Proposed repository from the Developer Options tab in Software & Updates.

    ![image](https://user-images.githubusercontent.com/19394936/167237873-5befed64-ee2a-4fbd-aa36-96449c03a436.png)

 2. You updated your system.
 
     You can see that version 245.4-4ubuntu3.17 comes from `http://archive.ubuntu.com/ubuntu focal-proposed/main`, as marked by "***" in the output below:
 
        $ apt-cache policy libsystemd0
        libsystemd0:
          Installed: 245.4-4ubuntu3.17
          Candidate: 245.4-4ubuntu3.17
          Version table:
         *** 245.4-4ubuntu3.17 500
                500 http://archive.ubuntu.com/ubuntu focal-proposed/main amd64 Packages
                100 /var/lib/dpkg/status
             245.4-4ubuntu3.16 500
                500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
             245.4-4ubuntu3.15 500
                500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
             245.4-4ubuntu3 500
                500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages

 3. You *disabled* the Focal Proposed repository from the Developer Options tab in Software & Updates.

    Notice that version 245.4-4ubuntu3.17 is *now* listed as coming from `/var/lib/dpkg/status`, as marked by "***" in the output below. This output exactly matches your output for the command [`apt-cache policy libsystemd0`](https://github.com/PJ-Singh-001/Cubic/issues/53#issuecomment-1118115188) (except your mirror is mirrors.aliyun.com).

        $ apt-cache policy libsystemd0
        libsystemd0:
          Installed: 245.4-4ubuntu3.17
          Candidate: 245.4-4ubuntu3.17
          Version table:
         *** 245.4-4ubuntu3.17 100
                100 /var/lib/dpkg/status
             245.4-4ubuntu3.16 500
                500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
             245.4-4ubuntu3.15 500
                500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
             245.4-4ubuntu3 500
                500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages

 4. You ended up with version 245.4-4ubuntu3.17 of `libsystemd0` and `systemd` on your system. You also ended up with *a lot* of other important packages that depend on version  245.4-4ubuntu3.17 of `libsystemd0`. 

 5. When you executed `sudo apt install libsystemd0=245.4-4ubuntu3.16`, this uninstalled version 245.4-4ubuntu3.17 of `libsystemd0` and "bricked" your system, because all of the other dependent packages were also removed!

        You are about to do something potentially harmful.
        To continue type in the phrase 'Yes, do as I say!'

**Comment by PJ-Singh-001** [comment]
You shouldn't really use the "proposed" repository, unless you are testing out unreleased software.

Nevertheless, to solve your immediate problem of not being able to install Cubic, you can continue to use the "proposed" repository to get the missing package `systemd-container`. To do this, you will need to temporary re-enable the "proposed" repository.

---

 1. Add the "focal-proposed" repository to your sources list.

    You can do this by using the Developer Options tab in Software & Updates.

    ![image](https://user-images.githubusercontent.com/19394936/167237873-5befed64-ee2a-4fbd-aa36-96449c03a436.png)

    Or, you can do this by adding the following line to `/etc/apt/sources.list`:

        deb http://archive.ubuntu.com/ubuntu/ focal-proposed restricted universe multiverse main

 2. Update your packages cache:

        sudo apt update

 3. Install version 245.4-4ubuntu3.17 of  `systemd-container` that matches the versions of `libsystemd0` and `systemd` on your system.

        sudo apt install systemd-container

 4. Disable the "focal-proposed" repository in your sources list.

    You can do this by using the Developer Options tab in Software & Updates.

    Or, you can comment-out or remove the corresponding line in `/etc/apt/sources.list`:

        # deb http://archive.ubuntu.com/ubuntu/ focal-proposed restricted universe multiverse main

 5. Refresh your packages cache:

        sudo apt update

 6. Install Cubic using the following steps:

        sudo apt-add-repository universe
        sudo apt-add-repository ppa:cubic-wizard/release
        sudo apt update
        sudo apt install --no-install-recommends cubic

    Since Cubic works with any version of `systemd-container` >= 237, you should not have any issues during installation, even with the "proposed" repository disabled.

---

However, after installation, I can't grantee Cubic or any other software will work flawlessly on your system, since you do have packages that are currently in development and testing (`libsystemd0`, `systemd`, and many others) currently installed on your system.

**Comment by PJ-Singh-001** [comment]
Another option is to downgrade all packages you've already installed from the "proposed" repository.

If you want to try this, see [How can I revert back from an upgrade to the Proposed repository?](https://askubuntu.com/a/229663/100356).

Of course, this is risky, so make sure you have a backup.

I suggest trying [the previous solution](https://github.com/PJ-Singh-001/Cubic/issues/53#issuecomment-1120135605) first, because you can always try [this](https://askubuntu.com/a/229663/100356) later.

**Comment by CoulsonYing** [comment]
Thanks a million! Let try it now!

**Comment by CoulsonYing** [comment]
Bro, you're definitely right! After I enabled `proposed-repository`, I installed the cubic successfully! Thanks again. Thank you very very much

**Comment by PJ-Singh-001** [comment]
I’m glad it’s working for you.

This was a lot of research, and it was smart of you to keep a backup of your system.

(In the future, try not to enable the “proposed” repository unless you are helping to test packages for Ubuntu ).
