### ISSUE TITLE
installing an app in the Live environment / (user) test is not in the sudoers file

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#54]
Hello list

just booted my PC from the newly remasterd cubic ISO (Ubuntu 18.04 LTS DVD)

Since I forgot to install a small app, I tried the install it in the Live environment with the following command:

test@ubuntu:~$ sudo apt-get install minicom
[sudo] password for test: 
test is not in the sudoers file.  This incident will be reported.

Thank you!

Joe

**Comment by PJ-Singh-001** [comment]
You need to follow the instructions in [How to create custom users on the login screen?](https://github.com/PJ-Singh-001/Cubic/issues/3#issuecomment-997134540).

Be sure to note the 2nd item in [How to create a user with sudo permissions (if booted from the ISO)?](https://github.com/PJ-Singh-001/Cubic/issues/47#issuecomment-1100802706).
