### ISSUE TITLE
What can cause System generation error?

### ISSUE THREAD

**Issue by tcboeira** [PJ-Singh-001/Cubic#56]
I still don't know for sure, but some customization procedure I'm doing causes an error where when starting the new ISO, the Test (Live Mode) or Installation options are presented. In both cases, it works fine. 

However, the Installation one, when starting after the "error-free" process starts at a "Welcome to Ubuntu..." screen and some similar steps to the installation. This is very strange because at some point I had noticed this behavior when I installed one or another application, to leave it on board, such as Wine or Antivirus. But this time I just moved files in some folders. What can cause this type of inappropriate behavior.

Thank you very much for your attention
Hugs

**Comment by PJ-Singh-001** [comment]
What is the exact error message you see?

**Comment by PJ-Singh-001** [comment]
If you are able to share the exact error you see, please feel free to reopen this issue.
