### ISSUE TITLE
Add items to dock only for admin account

### ISSUE THREAD

**Issue by jeremehancock** [PJ-Singh-001/Cubic#57]
I have followed these steps to add apps to the default dock and it works great.
https://github.com/PJ-Singh-001/Cubic/issues/23

I have one issue.  When I create a new non-admin user their dock has those same default apps. Is there a way to set certain apps to only show up on the dock for admin accounts?

Thanks in advance!

**Comment by PJ-Singh-001** [comment]
When yo I say “admin” you mean any user who has `sudo` privileges, and “non-admin” is any user that is not a member of the `sudo` group?

**Comment by jeremehancock** [comment]
Yes that's what I mean. Thanks

**Comment by jeremehancock** [comment]
It is not a huge deal since the apps that I want to only show for admins require sudo, but it would just be nice to only show them for sudo group users. Thanks

**Comment by PJ-Singh-001** [comment]
It will take me some time to get to this question. I'll post something as soon as I am able to.

**Comment by jeremehancock** [comment]
No worries. Thanks so much!

**Comment by PJ-Singh-001** [comment]
You can run a script upon login that checks if the user is a member of the `sudo` group. If so, you can add the desired application launchers to the dock. If not, you can remove the specified application launchers from the dock (assuming you really don't want non-admin users to keep these apps in their dock, even if they have manually added them).

---

 1. Create a file named `update_favorites.sh` on your host computer, and copy the following into it.

        #!/bin/bash

        ########################################################################
        #                                                                      #
        # update_favorites.sh                                                  #
        #                                                                      #
        # Copyright (C) 2022 PJ Singh <psingh.cubic@gmail.com>                 #
        #                                                                      #
        ########################################################################

        ########################################################################
        #                                                                      #
        # update_favorites.sh is free software: you can redistribute it and/or #
        # modify  it under the terms of the GNU General Public License as      #
        # published by the Free Software Foundation, either version 3 of the   #
        # License, or (at your option) any later version.                      #
        #                                                                      #
        # update_favorites.sh is distributed in the hope that it will be       #
        # useful, but WITHOUT ANY WARRANTY; without even the implied warranty  #
        # of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the      #
        # GNU General Public License for more details.                         #
        #                                                                      #
        # You should have received a copy of the GNU General Public License    #
        # along with update_favorites.sh. If not, see                          #
        # <http://www.gnu.org/licenses/>.                                      #
        #                                                                      #
        ########################################################################

        # This script adds favorites to the dock for an admin user, and removes
        # the favorites for a non-admin user. Admin users are users who have
        # sudo group membership. Favorites to add (or remove) must be specified
        # in the configuration file: /opt/update_favorites/favorites.conf.
        #
        # Usage:
        # ./update_favorites.sh
        #
        # This bash script takes no arguments, but following the configuration
        # file is required: /opt/update_favorites/favorites.conf.
        #
        # In the configuration file, list each new favorite and its desired
        # position in the original dock.
        # - Each item is a *.desktop file, usually from /usr/share/applications.
        # - These items will be added for users who are in the sudo group, and
        #   these items will be removed for users who are not in the sudo group.
        # - The first position in the dock starts at zero.
        # - Items will be inserted in the dock at the position specified;
        #   existing items will shift downward (or to the right for a
        #   horizontal dock).
        # - Items with the same position will be added in the order they are
        #   listed.
        # - If the specified position is greater than the last position in the
        #   dock, the item will be appended to the dock.
        # - Appended items will be added in the order they are listed.
        # - If an item already exists in the dock, the new item will be skipped.

        ########################################################################
        # Functions
        ########################################################################

        function add_new_favorite {

            local favorite="'${1}'"

            # Do not add if this item exists in the original list.
            if [[ (( "${original_favorites[*]}" =~ "${favorite}" )) ]]; then return 0; fi

            # Otherwise add the new favorite.
            local target_position=$2
            local actual_position=${#favorites[@]}
            if (( $target_position == $index )); then
                favorites+=("${favorite}")
                echo "$actual_position) ${favorite} (inserted new favorite at position $target_position)"
            elif (($index == $count)) && (( $target_position >= $count )); then
                favorites+=("${favorite}")
                echo "$actual_position) ${favorite} (appended new favorite at position $target_position)"
            fi
        }

        function add_existing_favorite {

            local favorite="'${1}'"

            local target_position=$2
            local actual_position=${#favorites[@]}
            if (( $target_position == $index )); then
                favorites+=("${favorite}")
                echo "$actual_position) ${favorite} (inserted existing favorite at position $target_position)"
            elif (($index == $count)) && (( $target_position >= $count )); then
                favorites+=("${favorite}")
                echo "$actual_position) ${favorite} (appended existing favorite at position $target_position)"
            fi
        }

        ########################################################################
        # Main
        ########################################################################

        # Configuration file path.
        configuration_file="/opt/update_favorites/favorites.conf"

        # Get the list of applications from the Dock.
        favorites_string=$(gsettings get org.gnome.shell favorite-apps)
        echo "The original favorites are ${favorites_string}."
        echo

        # Remove the [] brackets form the string.
        favorites_string=${favorites_string:1:-1}

        # Convert the comma delimited string into an array.
        original_favorites=(${favorites_string//,/})

        # Get the original number of favorites.
        count=${#original_favorites[@]}
        echo "The original number of favorites is $count."
        echo

        # Get group membership.
        groups=$(groups)

        #
        # Add or remove favorites.
        #
        if [[ $groups == *"sudo"* ]]; then
            # Add favorites for an admin user.
            # Create a new array of favorites.
            index=0
            favorites=()
            while (( $index <= $count )); do
                # Get the original favorite, and strip the quotes from the string.
                favorite=${original_favorites[index]:1:-1}
                # Add new favorite(s) from the configuration file.
                while read -r line; do
                    arguments=(${line})
                    add_new_favorite "${arguments[0]}" "${arguments[1]}"
                done <"${configuration_file}"
                # Add the original favorite after adding (any) new favorite(s).
                if (( $index < $count )); then add_existing_favorite "${favorite}" $index; fi
                # Increment the index.
                ((index++))
            done
        else
            # Remove favorites for a non-admin user.
            # Create a new array of favorites.
            index=0
            favorites=()
            while (( $index < $count )); do
                # Get the original favorite, and strip the quotes from the string.
                favorite=${original_favorites[index]:1:-1}
                # Check if the favorite is in the configuration file.
                add=true
                while read -r line; do
                    arguments=(${line})
                    if [[ (("$favorite" == "${arguments[0]}" )) ]]; then add=false; fi
                done <"${configuration_file}"
                # Add the favorite if it is not in the configuration file.
                if [[ (( $add == true )) ]]; then add_existing_favorite "${favorite}" $index; fi
                # Increment the index.
                ((index++))
            done
        fi
        echo

        # Get the new number of favorites.
        count=${#favorites[@]}
        echo "The new number of favorites is $count."
        echo

        # Convert the array into a comma delimited string.
        favorites_string=""
        index=0
        for favorite in "${favorites[@]}"; do
            ((index++))
            if (( $index < $count )); then
                favorites_string="${favorites_string}${favorite}, "
            else
                favorites_string="${favorites_string}${favorite}"
            fi
        done

        # Add the [] brackets to the string.
        favorites_string="[${favorites_string}]"

        # Set the new list of applications in the Dock.
        echo "The new favorites are ${favorites_string}."
        gsettings set org.gnome.shell favorite-apps "${favorites_string}"
        echo

 2. Create a file named `favorites.conf` on your host computer, and copy the following into it.

        org.gnome.Terminal.desktop 0
        org.gnome.gedit.desktop 1
        org.gnome.Calculator.desktop 3
        gnome-system-monitor.desktop 100

    Edit this file and list the applications that you want to be added as favorites for all admin users upon login. The number after the application is the desired position in the *current* list of applications in the dock. The position numbers start at zero, and a favorite with a high number (like 100) will always be added to the end of the dock. Note that these applications will also be automatically removed from the favorites for non-admin users (upon login).

 3. Create a file named `update-favorites.desktop` on your host computer, and copy the following into it.

        [Desktop Entry]
        Name=Update Favorites for Admin Users
        Exec=/opt/update_favorites/update_favorites.sh
        Type=Application

 4. On Cubic's Terminal page execute the following:

        mkdir /opt/update_favorites
        cd /opt/update_favorites

 5. Drag the `update_favorites.sh` file from step 1 onto the Terminal page to [copy the file](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Copy-Page) into 
`/opt/update_favorites`.

 6. Make sure this file is executable:

        chmod a+x update_favorites.sh

 8. Drag the `favorites.conf` file from step 2 onto the Terminal page to [copy the file](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Copy-Page) into 
`/opt/update_favorites`.

 9. Next, setup autostart for this script, to run it upon each login.
 
    On Cubic's Terminal page execute the following:

        cd /etc/xdg/autostart

    (Alternatively, you can create the folder structure `/etc/skel/.config/autostart` and `cd` into it. This will create the autostart launcher in each user's home directory, instead of globally, so each user can manually delete this file, if they want to).

 11. Drag the `update-favorites.desktop` file from step 3 onto the Terminal page to [copy the file](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Copy-Page) into 
`/etc/xdg/autostart` (or `/etc/skel/.config/autostart`).

10. Create your custom ISO usign Cubic to test this script and your `favorites.conf` configuration.

**Comment by jeremehancock** [comment]
Thank you!
