### ISSUE TITLE
How to install VirtualBox GuestAdditions

### ISSUE THREAD

**Issue by EMogura** [PJ-Singh-001/Cubic#59]
I am creating a customized iso based on ubuntu-ja-22.04.0-2022.05.09-desktop-amd64.iso.
I'm stuck trying to install VirtualBox Guest Additions, assuming I'm using a customized iso with VirtualBox.

To install on VirtualBox, mount the CD in the "Device" / "Insert GuestAddition CD Image" menu and execute VBoxLinuxAdditions.run in it, so I copied the set of files on the CD to the Cubic virtual environment and ran the install command,
```
root@cubic:~/VBoxGuestAdditions# ./VBoxLinuxAdditions.run 
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.1.34 Guest Additions for Linux........
VirtualBox Guest Additions installer
Removing installed version 6.1.34 of VirtualBox Guest Additions...
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Copying additional installer modules ...
Installing additional modules ...
depmod: ERROR: could not open directory /lib/modules/5.8.0-59-generic: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel 
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Kernel headers not found for target kernel 
5.8.0-59-generic. Please install them and execute
  /sbin/rcvboxadd setup
VirtualBox Guest Additions: Running kernel modules will not be replaced until 
the system is restarted
Cannot locate the VirtualBox device
The log file /var/log/vboxadd-setup.log may contain further information.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

But could not be installed. Looking at the log file (/var/log/vboxadd-setup.log),

Cannot locate the VirtualBox device
```

It seems that it is necessary to mount the iso image.

So, I got VBoxGuestAdditions_6.1.34.iso from

http://download.virtualbox.org/virtualbox/6.1.34/

and tried to mount it. But failed.

```
root@cubic:~# mount -o loop,ro VBoxGuestAdditions_6.1.34.iso VBoxGuestAdditions

mount: VBoxGuestAdditions: mount failed: Operation not permitted.
```

 I tried changing the mounting location, but the same error occurred.
Also, the above `mount` command can be used without any problem in a normal ubuntu environment. Does that mean I can't use the mount command in a Cubic virtual environment?

**Comment by PJ-Singh-001** [comment]
You can install VirtualBox as *software* using Cubic (while your are customizing your ISO).

However, the guest additions *must be installed in each new guest OS* that you create (while using VirtualBox). This could happen when:
1. You are testing your customized ISO in the Live Environment
2. You are using your customized OS, after having installed it from your customized ISO

Per the [VirtualBox manual](https://www.virtualbox.org/manual/ch04.html#guestadd-intro):
> the Guest Additions are designed to be installed inside a virtual machine after the guest operating system has been installed.

As an analogy, you would install LibreOffice using Cubic, but you would not "*install*" a document in LibreOffice using Cubic. Instead, you would create the document when you are *using* LibreOffice. Likewise, you must be *using* VirtualBox to install an OS, and then install the GuestAdditions for *that* OS.

To make it more clear, you need to create a virtual machine inside VirtualBox, while running VirtualBox. Depending on the OS of your virtual machine, you may need to install the Windows version or the Linux version of GuestAdditins. Obviously, you need a running virtual machine first.

**Comment by EMogura** [comment]
>the Guest Additions are designed to be installed inside a virtual machine after the guest operating system has been installed.

I understand that we generally install with such a procedure. However, in the past experience, when using the remastersys ISO image creation tool (Remastersys, relinux, Pinguy Builder ,, etc), create an iso image from the virtual machine on VirtualBox with Guest Additions for Linux installed in advance.  It was possible to use in VirtualBox using this customized(pre-installed Guest Additions) iso image. I wondered if Cubic could do the same thing, but I gave up to install Guest Additions because it seems that it can only be installed in the virtual environment of VirtualBox.

By the way, is it such a specification that the iso image file cannot be mounted in the Cubic virtual environment?
