### ISSUE TITLE
Add Custom App-Folders

### ISSUE THREAD

**Issue by jeremehancock** [PJ-Singh-001/Cubic#60]
I would like to add App-Folders by default to the ISO. So when the user opens the App drawer certain apps are grouped in custom App-Folders. I have done something similar with the Favorite apps using the 90_ubuntu-settings.gschema.override file.

I would like these App-Folders to be in the Live session and post install and be the default for new users.

Thanks!

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 22.04

**Cubic Information (please complete the following information):**
 - Cubic Version: latest 
 - ISO Customizing:Ubuntu 22.04
 - Download Link: https://ubuntu.com/download/desktop/thank-you?version=22.04&architecture=amd64

**Comment by tcboeira** [comment]
Well for me it works this way, with editing the file "90_ubuntu-settings.gschema.override "

What is shown in the Live version is presented to the user after install

**Comment by jeremehancock** [comment]
> Well for me it works this way, with editing the file "90_ubuntu-settings.gschema.override "
> 
> What is shown in the Live version is presented to the user after install

So what do you add to the override file to create the app folders?

**Comment by PJ-Singh-001** [comment]
I believe you have to set the value of `org.gnome.shell.app-picker-layout` in your `gschema` override file (e.g. `90_ubuntu-settings.gschema.override`).

You could create the required value for `app-picker-layout` manually, but I suggest copying the value of this key from a running version of Ubuntu (probably your host computer that you are running Cubic on).

First, organize the apps on your host computer the way you want them.

Then, get the value of `app-picker-layout`.

    gsettings get org.gnome.shell app-picker-layout

Create a file named `90_ubuntu-settings.gschema.override` with the following contents. (Be sure to use the output from the above command in place of `[]`).

    [org.gnome.shell]
    app-picker-layout = []

In Cubic, change to the `schemas` directory.

    cd /usr/share/glib-2.0/schemas/

Drag the `90_ubuntu-settings.gschema.override` file onto the Terminal page in Cubic to copy it into the current directory.

**Comment by jeremehancock** [comment]
I think it is more complicated than this. When you create new App groups they show up with an ID to reference so I assume that I would also need to include wherever that reference is stored.

Here is an example of the output with custom App Folders.

`[{'8ed22243-7a96-41ce-9516-86f6705c646e': <{'position': <0>}>, '1aeccfba-e8f4-4ed7-83f6-6d97728a8e35': <{'position': <1>}>, '10747048-cab5-4538-9566-4d9e8ecf3f85': <{'position': <2>}>, '54522ba4-15ae-4609-8a76-36f769a464de': <{'position': <3>}>, 'Utilities': <{'position': <4>}>, '4158becc-272d-4e4a-8379-a94943fc544b': <{'position': <5>}>, '2bcb788a-c5b2-4899-b0c1-129625941a8a': <{'position': <6>}>, 'org.gnome.Calendar.desktop': <{'position': <7>}>, 'org.gnome.Nautilus.desktop': <{'position': <8>}>, 'org.gnome.Totem.desktop': <{'position': <9>}>, 'org.gnome.Calculator.desktop': <{'position': <10>}>, 'org.gnome.gedit.desktop': <{'position': <11>}>, 'display-im6.q16.desktop': <{'position': <12>}>, 'simple-scan.desktop': <{'position': <13>}>, 'gnome-language-selector.desktop': <{'position': <14>}>, 'org.gnome.Terminal.desktop': <{'position': <15>}>, 'org.remmina.Remmina.desktop': <{'position': <16>}>, 'rhythmbox.desktop': <{'position': <17>}>, 'yelp.desktop': <{'position': <18>}>, 'shotwell.desktop': <{'position': <19>}>, 'org.gnome.Cheese.desktop': <{'position': <20>}>, 'usb-creator-gtk.desktop': <{'position': <21>}>, 'org.gnome.Sudoku.desktop': <{'position': <22>}>, 'thunderbird.desktop': <{'position': <23>}>}, {'org.gnome.Todo.desktop': <{'position': <0>}>, 'transmission-gtk.desktop': <{'position': <1>}>, 'vim.desktop': <{'position': <2>}>}]
`
