### ISSUE TITLE
Regarding dist-upgrade

### ISSUE THREAD

**Issue by eband** [PJ-Singh-001/Cubic#62]
When I asked about upgrading a Ubuntu-based distro to its latest major milestone release, you talked about dist-upgrade.

I just want to know, does the dist-upgrade function upgrade most Ubuntu-based distributions to a later version when it is time?

Thanks!

EDIT: If yes, should I still use dist-upgrade to upgrade any version of a Ubuntu-based distribution regardless of the milestone's magnitude (20.3 to 21)?

**Comment by tcboeira** [comment]
Hello,
Well, I'll try to summarize... Anything we can follow this debate...

The "dist-upgrade" command does what we call a general service with some limits...

It updates packages, however, removes and installs packages if necessary. Often some software needs to be installed as dependencies for certain applications, this option does that. The dist-upgrade is a more complete but “riskier” upgrade, as it will modify the system profoundly.

It won't take you for example to the next OS version, like from 21.10 to 22.04 or even from 21.04 to 21.10... But it will work directly on top of packages very strongly!!!

If I'm wrong, someone please correct me!!!

Hugs

**Comment by PJ-Singh-001** [comment]
Closing this issue, with @tcboeira's answer.
