### ISSUE TITLE
Unable to use apt commands with 22.04 (Jammy) ISO file

### ISSUE THREAD

**Issue by stj0nes** [PJ-Singh-001/Cubic#63]
**Describe the bug**

When I try to use any apt commands in the virtual environment terminal and a 22.04 ISO file, I'm met with a "problem executing scripts" error message. Due to this, I'm unable to remove or install packages & dependencies using apt. Dpkg command works fine.

**To Reproduce**

Open Cubic to the virtual environment terminal with a 22.04 ISO file and try to run apt update, apt install, apt purge commands.

**Expected behavior**

Apt commands would work normally in the virtual environment to install/remove various packages.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: 22.04

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.01.70
 - ISO Customizing: ubuntu-22.04-desktop-amd64.iso
 - Download Link:  https://ubuntu.com/download/desktop

**Cubic Log:**

 No log provided by cubic.

**Screenshots**

No screenshots applicable, see attached text file.
[jammyError.txt](https://github.com/PJ-Singh-001/Cubic/files/8826583/jammyError.txt)

**Comment by tcboeira** [comment]
Hi, I don't know if I understand your error correctly...
When I run any command to update or ask for a package to be installed, an error occurs...
What I do is, first of all, I modify the sources.list to a new, default one, and everything works normally.

If that's not your case, I ask - if possible - to tell me what exactly your error message is....

Hugs

**Comment by tcboeira** [comment]
I apologize... I saw that I had the error attached just below...
Well, that's exactly what I said....
Fetch a new sources.list and update it before any other command...

Anything can come back!

Hugs

**Comment by PJ-Singh-001** [comment]
I suspect you are using a third-party PPA that has installed certain packages that are also supplied by official Ubuntu PPAs. The packages installed by the third-party PPA are conflicting with the official Ubuntu packages.

---

For example, in Ubuntu 22.04, `thunderbird` is version 1:91.9.1+build1-0ubuntu0.22.04.1. But, according to your log, `thunderbird-gnome-support` explicitly requires version 1:91.8.0+build2-0ubuntu1. As a result, `thunderbird` can not be installed.

---

The version of `landscape-common` that comes with Ubuntu 22.04 is `19.12-0ubuntu13`. See which version you have installed:

    dpkg -l landscape-common

If you get the message `dpkg-query: no packages found matching landscape-common`, see which package version is available to install:

    apt search landscape-common

If the installed version, or available version, is not `19.12-0ubuntu13`, then this would be another cause for the conflict.

---

The version of `libatomic1` that comes with Ubuntu 22.04 is `12-20220319-1ubuntu1`. See which version you have installed:

    dpkg -l libatomic1

If you get the message `dpkg-query: no packages found matching libatomic1`, see which package version is available to install:

    apt search libatomic1

If the installed version, or available version, is not >= `12-20220319-1ubuntu1`, then this would be another cause for the conflict.

In your logs, I see `microsoft-edge-stable` depends on `libatomic1` >= `4.8`. Ubuntu comes with `libatomic1` version `12-20220319-1ubuntu1`. `Apt` is probably comparing the "4" from `4.8` with the "1" from "`12-20220319-1ubuntu1`" and deciding that `libatomic1` 4.8 is _not_ >= `12-20220319-1ubuntu1`.

---

You will probably need to remove the additional PPAs that you have installed, and remove the packages from those PPAs. This may not be easy and could remove critical OS packages, so make sure you have a backup!

It is possible that the conflicting packages are coming from the repository `http://dl.google.com/linux/chrome/deb stable InRelease`. In your logs, I can not see which PPA you are getting `microsoft-edge-stable` from, but that could also be a cause of conflict.

May be you can search or ask a question on the forums for those PPAs, to see how to install their software on Ubuntu 22.04.

**Comment by stj0nes** [comment]
Hi Team,

So fetching a new sources.list file did not resolve this. 

I created a new project with a brand new copy of the ISO file, just in case the one I was using before had corrupted during download, and I'm still getting the same issue without adding in ANY third-party PPAs such as Google Chrome or Microsoft Edge or attempting to remove default packages such as Thunderbird.

Attached is what I receive with the brand new project and ISO file this morning from the virtual environment:
[jammyError1.txt](https://github.com/PJ-Singh-001/Cubic/files/8852852/jammyError1.txt)
