### ISSUE TITLE
Editing "Ubuntu.seed"

### ISSUE THREAD

**Issue by tcboeira** [PJ-Singh-001/Cubic#64]
Hi, I apologize if I'm not correct.
First of all I say that I reached an ideal scenario to put into production my ISO generated from Cubic for Ubuntu 22.04

There are no words to thank you and describe how motivating this is!

With the OS in production mode, in what we call version 1, I'm working on version 2, which is really focusing on "ubuntu.seed", more precisely on the item "d-i preseed/late_command". I want to eliminate that someone executes a Script after the installation already in the proper installation, that it executes the Script.

My question is:
Has anyone worked on this part to the point of instructing how to proceed?

big hugs

**Comment by tcboeira** [comment]
Hello friends,

So... After searching the web a lot, I ended up reading that the command "d-i preseed/late_command" doesn't work with Ubuntu, so "ubiquity ubiquity/success_command" should be used. I did, using pretty much the same organization, and I was successful.

Big Hug and we keep looking for more customization!

**Comment by changchichung** [comment]
hi @tcboeira , Do you succesful to install ubuntu 22.04 with preseed in cubic ?
I just edit the ubuntu.seed like hat I did last time in ubuntu 20.04 , but this time , the installer just ignore the preseed file .

**Comment by tcboeira** [comment]
Mine has a lot of information... Maybe not very big - even less than I would like hehehe...

Well, in my case, I specify username, password, hostname, network suffix, time zone, even main language... At the end, I added the instruction that a Script should be executed and the reboot should occur automatically without any questions (this there in the gfc)

What I discovered in my research, as I commented above, is that some options of "d-i preseed" and in my case "late_command" doesn't work with Ubuntu, which made me replace it with "ubiquity ubiquity/success_command"

But I'm available to exchange more ideas and even post my "seed" so I can learn more!!!

Hugs

ps: sorry for my expressions. I don't know English and I use Google Translate ;-)

**Comment by changchichung** [comment]
@tcboeira 
and all that configurations work without interruption ?

it would be great if you could paste your preseed file ! I still can not make it working in cubic .

**Comment by tcboeira** [comment]
Clear...
Only now that I remember... Sometimes, and depending on the network/connection conditions, the line "d-i time/zone string America/Sao_Paulo" is followed or not. But other than that, as they say in southern Brazil, "Vai que é um doce"

And in grub.cfg the line is like this:
linux /casper/vmlinuz boot=casper noprompt file=/cdrom/preseed/ubuntu.seed maybe-ubiquity quiet splash ---

Where I include the "noprompt" just to not ask for the removal of the media in the reboot!

Another thing... The final Script, mentioned there as "inst-end.sh", it is written and installs the package normally, in addition to making some file copies...

And all of that, absolutely all of that with the Cubic. Which I am very grateful.

Well, follow him (with some changed data). If you want to send yours, I can try to test it here.

Anything we are there...
Hugs

```
# Preseeding only locale sets language, country and locale.
d-i debian-installer/locale string pt_BR

# Set language, country and locale.
d-i debian-installer/language string pt_BR
d-i debian-installer/country string BR
d-i debian-installer/locale string pt_BR.UTF-8

# Specify additional locales to be generated.
d-i localechooser/supported-locales multiselect pt_BR.UTF-8

# Enable extras.ubuntu.com.
d-i	apt-setup/extras	boolean true
# Install the Ubuntu desktop.
tasksel	tasksel/first	multiselect ubuntu-desktop
# On live DVDs, don't spend huge amounts of time removing substantial
# application packages pulled in by language packs. Given that we clearly
# have the space to include them on the DVD, they're useful and we might as
# well keep them installed.
ubiquity	ubiquity/keep-installed	string icedtea6-plugin openoffice.org

# Any hostname and domain names assigned from dhcp take precedence over
# values set here. However, setting the values still prevents the questions
# from being shown, even if values come from dhcp.
d-i netcfg/get_hostname string NOME-PC
d-i netcfg/get_domain string DOMINIO.SUFIXO

# If you want to force a hostname, regardless of what either the DHCP
# server returns or what the reverse DNS entry for the IP is, uncomment
# and adjust the following line.
d-i netcfg/hostname string NOME-PC

# Set keyboard layout.
d-i keyboard-configuration/xkb-keymap select pt

# Set time zone and region.
d-i time/zone string America/Sao_Paulo
d-i debian-installer/region string pt_BR.UTF-8

# Create a normal user account.
d-i passwd/user-fullname string USER
d-i passwd/username string USER
d-i passwd/user-password-crypted password [AQUI MINHA SENHA CRIPTO]

# Override weak password warning.
d-i user-setup/allow-password-weak boolean false

# Add user to specific groups.
# d-i passwd/user-default-groups string audio cdrom video
d-i passwd/user-default-groups string adm cdrom sudo root USER dip plugdev lpadmin lxd

ubiquity ubiquity/success_command string \
    echo "Running Post Install Commands"; \
    in-target touch /usr/local/bin/PASTA_LOC/install/inst-end.sh; \
    in-target /bin/bash /usr/local/bin/PASTA_LOC/install/inst-end.sh
    
ubiquity ubiquity/reboot boolean true


```

**Comment by changchichung** [comment]
I think it's not ok to discuss preseed in Cubic issues, so I create a gist in 
https://gist.github.com/changchichung/e292f6652b2c30c1439709da490a7d64
maybe we can talk in there , thanks for your preseed file!
