### ISSUE TITLE
Cubic does not open in Linux Mint 20.3

### ISSUE THREAD

**Issue by c05772** [PJ-Singh-001/Cubic#65]
Installing was not a problem following the instructions. Cubic is found on Linux Mint menu but clicking on it gives a loading round then nothing more.

There is no problem during the install so it can probably happen to any Linux Mint distro user.

The expected behavior would be to see the start screen.
Now starting cubic from the command line with
username@pc: $ cubic -v ~/ISOCubic ~/ISO/linuxmint-20.3-cinnamon-64bit.iso
gives the following result:
Cubic - Custom Ubuntu ISO Creator     (<- colored line)
• Project directory argument............. /home/username/ISOCubic                 
  • Original ISO file path argument........ /home/username/ISO/linuxmint-20.3-cinnam
                                            on-64bit.iso                        
  • Set application directory.............. /usr/share/cubic                    
  • Set application user home.............. /home/username                          
  • Exception.............................. [Errno 13] Permission denied:       
                                            '//etc/apt/sources.list'            
  • The trace back is...................... Traceback (most recent call last):  
                                            File "/usr/bin/cubic", line 135, in 
                                            <module>                            
                                            model.application.cubic_version = co
                                            nstructor.get_package_version('cubic
                                            ')   File "/usr/share/cubic/cubic/ut
                                            ilities/constructor.py", line 376,  
                                            in get_package_version     apt_cache
                                            = apt.Cache(rootdir=root_directory) 
                                            File "/usr/lib/python3/dist-        
                                            packages/apt/cache.py", line 161, in
                                            __init__     self._check_and_create_
                                            required_dirs(rootdir)   File       
                                            "/usr/lib/python3/dist-             
                                            packages/apt/cache.py", line 204, in
                                            _check_and_create_required_dirs     
                                            open(rootdir + f, "w").close()      
                                            PermissionError: [Errno 13]         
                                            Permission denied:                  
                                            '//etc/apt/sources.list'            

Note that in Linux Mint 20.3 there is no file named: etc/apt/sources.list but a directory named etc/apt/sources.list.d with the following permission:

![Screenshot from 2022-06-05 16-05-31](https://user-images.githubusercontent.com/106929125/172068533-3b037d3e-ccfb-4a78-acb2-4aa5d1c9bb1a.png)
and inside the directory there is a file 'cubic-wizard-release-focal.list'

**OS Information 
 - OS/Distro Name: Linux Mint
 - OS Version : 20.3

**Cubic Information (please complete the following information):**
 - Cubic Version: Version: 2022.01-70-release~202201240317~ubuntu20.04.1

**Cubic Log:**

Did not find a cubic.log or Cubic.log file in the sytem but the trace back seems to show it is a permission problem but 
username@pc: $ sudo cubic 
does not give a result either.

**Comment by PJ-Singh-001** [comment]
You should have a file named `/etc/apt/sources.list`. (May be Linux Mint does not include this file in their distro?).

By the way, Cubic is not explicitly looking for this file, but Cubic uses `apt` libraries to get package version information, and based on the log you included, it looks like `apt` is expecting this file.

I’ll look into this further, and I will check which files are included in the Linux Mint 20.3 release. If I have to change the implementation of the way Cubic gets package info, then this will take some time to implement and release a big fix.

In the meantime, try creating an empty `sources.list` file on your host machine:

    sudo touch /etc/apt/sources.list
    sudo chmod a+r /etc/apt/sources.list

Let me know if that makes a difference. You can copy and paste the log output as you did above.

**Comment by c05772** [comment]
After creating the empty sources.list, I started directly from the GUI menu, worked OK.

I also tried from the command line as before, here is the (verbose) result:


username@PC: $ cubic -v ~/ISOCubic ~/ISO/linuxmint-20.3-cinnamon-64bit.iso

Cubic - Custom Ubuntu ISO Creator                                               

  • Project directory argument............. /home/username/ISOCubic                 
  • Original ISO file path argument........ /home/username/ISO/linuxmint-20.3-cinnam
                                            on-64bit.iso                        
  • Set application directory.............. /usr/share/cubic                    
  • Set application user home.............. /home/username                          
  • Set application cubic version.......... 2022.01-70-release~202201240317~ubun
                                            tu20.04.1                           
  • Set application kernel version......... 5.4.0-113-generic                   

  Setup pages                              

  • Setup.................................. boot copy page                      
  • Setup.................................. compression page                    
  • Setup.................................. delete page                         
  • Setup.................................. extract page                        
  • Setup.................................. finish page                         
  • Setup.................................. generate page                       
  • Setup.................................. migrate page                        
  • Setup.................................. options page                        
  • Setup.................................. packages page                       
  • Setup.................................. prepare page                        
  • Setup.................................. preseed copy page                   
  • Setup.................................. project page                        
  • Setup.................................. start page                          
  • Setup.................................. terminal copy page                  
  • Setup.................................. terminal page                       
  • Set terminal colors?................... Yes                                 
  • Setup.................................. test 1 page                         
  • Setup.................................. test 2 page                         
  • Read lines from file................... /home/username/.config/cubic/visited_sit
                                            es.conf                             
  • Number of lines read................... 0                                   
  • Set application visited sites.......... set()                               

  Setup file choosers                      

  • Setup (ignore warnings)................ copy file chooser                   
  • Setup (ignore warnings)................ directory chooser                   
  • Setup (ignore warnings)................ iso image chooser                   

Handle navigation from no page on open action                                   

  • Interrupt previous thread.............. No thread                           

Get the new page                                                                

  • Current page........................... no page                             
  • Action................................. open                                
  • New page............................... start page                          

  • The thread id is....................... 140345505478400                     
Navigate from no page to start page on open action                              

  • Read lines from file................... /home/username/.config/cubic/projects.co
                                            nf                                  
  • Error. File does not exist............. /home/username/.config/cubic/projects.co
                                            nf                                  
  • Set application projects............... []                                  

  Transition pages                         

  • Show new page.......................... start page                          

  Directory selected                       

  • Directory.............................. /home/username/ISOCubic                 

  Project directory changed                

  • Set project directory.................. /home/username/ISOCubic                 
  • Check if directory is writable......... /home/username/ISOCubic                 
  • Directory is writable?................. True                                
  • Get file system type................... /home/username/ISOCubic                 
  • Execute synchronously.................. df --output=fstype                  
                                            "/home/axel/ISOCubic"               
  • The process id is...................... 72147                               
  • The file system type is................ ext4                                
  • Set project iso mount point............ /home/username/ISOCubic/source-disk     
  • Set project custom root directory...... /home/username/ISOCubic/custom-root     
  • Set project custom disk directory...... /home/username/ISOCubic/custom-disk     
  • Set project configuration file path.... /home/username/ISOCubic/cubic.conf      
  • Initialize configuration............... 2021 Layout                         
  • Set project cubic version.............. 2022.01-70-release~202201240317~ubun
                                            tu20.04.1                           
  • Set project create date................ 2022-06-05 16:50                    
  • Set status is success copy............. False                               
  • Set status is success extract.......... False  


and of course I got to the welcome screen, so I think this the solution.
I checked again, Mint does not give the sources.list file, only the directory and then the custom list files.

**Comment by PJ-Singh-001** [comment]
The apt libraries that Cubic uses should handle a situation where `sources.list` is not present, so I think this is a bug in their software. I may decide to leave this as a "work-around", open a bug with "apt" or do something in Cubic to work-around this issue.
For now, since you have a way to move forward, I will keep this as a low priority item.

**Comment by PJ-Singh-001** [comment]
For future reference, this issue is similar to [Permission denied error after customization of image is complete](https://github.com/PJ-Singh-001/Cubic/issues/30).

**Comment by PJ-Singh-001** [comment]
I noticed that linuxmint-20.3-cinnamon-64bit.iso does have an empty `/etc/apt/sources.list` file by default.

Nevertheless, the fix for [Permission denied error after customization of image is complete](https://github.com/PJ-Singh-001/Cubic/issues/30) should also resolve this problem.

Fix released in Cubic version 2022.01.71.
