### ISSUE TITLE
Unable to proceed after bash(chroot) step when project directory contains nn.nn.n-n format.

### ISSUE THREAD

**Issue by anandchakru** [PJ-Singh-001/Cubic#7]
**Note/Update (12/25/2021)**: Might be the root-cause, was happening only when cubic directory was ~/cubic/20.04.3-4. Couldn't reproduce this issue when I tried with a different directory, ~/cubic/08

---
**Note/Update (12/24/2021)**: This is a duplicate of [1955734](https://bugs.launchpad.net/cubic/+bug/1955734)

I started a fresh cubic project with original disk image (ubuntu-20.04.3-desktop-amd64.iso). Note: I'm NOT customizing an existing project.

On "Identify disk boot kernels" step getting the following error always.

Error. No valid disk boot kernels were found.

To correct this issue, click the Back button and install missing Linux kernel packages on the Terminal page, or select the original disk image on the Project page.

This bug might have been a side-effect of fix for [1922147](https://bugs.launchpad.net/cubic/+bug/1922147).

**Comment by PJ-Singh-001** [comment]
Please supply the following information:

OS Information (please complete the following information):

    OS/Distro Name:
    OS Version:

Also, please run Cubic from the command line and cut and paste the log output here.

**Comment by PJ-Singh-001** [comment]
I see that you are customizing `ubuntu-20.04.3-desktop-amd64.iso`.

I'll assume you are using cubic 2021.12.67.

Thanks for the research regarding the directory path. I'll look into this further.

**Comment by PJ-Singh-001** [comment]
No need to provide additional information. I am able to recreate this issue.

**Comment by PJ-Singh-001** [comment]
Fix released in version 2021.12.68.

Please update and let me know if this resolves your issue.

    sudo apt update
    sudo apt install --no-install-recommends cubic
