### ISSUE TITLE
Feature request: cloud-init style automation of installs

### ISSUE THREAD

**Issue by mattadev** [PJ-Singh-001/Cubic#73]
I currently use Cubic to configure additional packages and other system config.  It would be an excellent feature if I could also automate the installation of various settings, such as language, locale, disk partitioning, etc.  I am currently exploring cloud-init for this aspect, but it would be even better if Cubic let me set those defaults to avoid most or any required user interaction during install.

**Comment by PJ-Singh-001** [comment]
How are you using cloud-init, and how do you imagine using it in Cubic ?

**Comment by mattadev** [comment]
For cloud-init, I'm essentially following this: https://ubuntu.com/server/docs/install/autoinstall-quickstart

For something similar, but better with Cubic, I imagine Cubic letting me step through all those install questions and having Cubic modify the ISO installer such that I'm not prompted in the future when running the installer.  
For example, I'd go through the install once to save my selections like username, password, geographic location, partitioning, etc., and that would then be what's used automatically in the future from the produced ISO.
Then when I boot the newly created ISO, it skips prompting me and uses the previous values I provided.

**Comment by dgillespie312** [comment]
I am currently doing most of what you mentioned with user-data and
meta-data in the preseed. Then I modify grub to use nocloud datasource.

**Comment by PJ-Singh-001** [comment]
@mattadev,

There are an infinite amount of things uses can do to customize their OS.

- In the past, users have requested to add fields to Cubic, corresponding to preseed files, so they can enter preseed information in a graphical interface.

- One person even asked that I allow him to enter information in the `cubic.conf` project configuration file, so Cubic would read this extra information and automatically customize the OS without him having to type anything in the [Terminal environment](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page)!

- You are requesting to add fields to Cubic, corresponding to Cloud-init values, so you can enter Cloud-init information in a graphical interface.

You can probably see the commonality between these requests: Users want a GUI to automatically make customizations for them.

Which of the infinite customizations should Cubic provide a user interface for? How many additional pages and fields would it take to... Add users? Add groups? Add applications? Remove applications? Modifying the theme, and if so which theme, Linux Mint, Ubuntu Gnome, KDE, Pop!_OS, etc.? Modify the default sources list? Add PPAs? ...As you can see the list can go on-and-on.

Cubic's specific job is to unpack an existing Live ISO, allow you to make *your own* customizations to the Linux file system embedded within the ISO, and repackage everything back into a new bootable ISO. This is a complex process that Cubic makes easy, so the user can focus on the actual customizations they want to make to the OS.

Thus, Cubic is not a tool to make customizations using a GUI. You have to make your own customizations. Most people create a bash script that makes the changes they like, and save this script in a safe place. Whenever they want to customize an OS, they drag and drop their script onto the [Cubic Terminal window](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) to copy it, and execute it.

If you want to do preseeding or use Cloud-init, you can do this from the [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page) in Cubic.

@dgillespie312, has the correct approach for using Cloud-init in Cubic.

Cubic already has a mechanism for you to enter and store your Cloud-init values, so you are "not prompted in the future when running the installer." Here are [instructions on how to modify your ISO and use Cloud-init](https://github.com/PJ-Singh-001/Cubic/issues/101#issuecomment-1336728758).
