### ISSUE TITLE
No longer able to query installed software when running Cubic in Ubuntu 18.04.5 thru 20.04.

### ISSUE THREAD

**Issue by dgillespie312** [PJ-Singh-001/Cubic#74]
**Describe the bug**

As of today I can't complete the cubic wizard. I reach the stage where it is querying installed software and it hangs.

**To Reproduce**

Try  to run cubic even without installing additional software.      

**Error log**

      • Execute synchronously.................. dpkg-query                          
                                                --root="/home/mtiadmin/cubic-       
                                                yard/custom-root" --show            
      • The process id is...................... 73850                               
    Exception in thread Thread-6:
    Traceback (most recent call last):
      File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.8/threading.py", line 870, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/share/cubic/cubic/navigator.py", line 616, in navigate
        result = new_page.enter(action, page) if new_page else None
      File "/usr/share/cubic/cubic/pages/prepare_page.py", line 168, in enter
        model.package_details_list = create_package_details_list(model.project.custom_root_directory)
      File "/usr/share/cubic/cubic/pages/prepare_page.py", line 1306, in create_package_details_list
        package_name, package_version = package.split()
    ValueError: too many values to unpack (expected 2)

**Version Info**

    2022.06-71-release~202206290200~ubuntu20.04.1

    5.4.0-121-generic #137-Ubuntu SMP

    NAME="Ubuntu"
    VERSION="20.04.4 LTS (Focal Fossa)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 20.04.4 LTS"
    VERSION_ID="20.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=focal
    UBUNTU_CODENAME=focal

**Comment by PJ-Singh-001** [comment]
Which OS and OS version are you running Cubic on?

**Comment by dgillespie312** [comment]
VERSION="20.04.4 LTS (Focal Fossa)"

Server

Thank you for responding.

**Comment by PJ-Singh-001** [comment]
Thanks for reporting this issue and providing the information.

I should be able to release a fix for you by tomorrow evening.

**Comment by dgillespie312** [comment]
I look forward to it. I thank you so much for looking into this.

**Comment by jacksongoode** [comment]
I'm encountering the same issue as well.

**Comment by PJ-Singh-001** [comment]
The fix has been released in Cubic version 2022.06.72.

If you experienced this bug in Cubic, and you have an existing project you would like to continue working on:

 1. Update to the new version:

        sudo apt update
        sudo apt install --no-install-recommends cubic

 2. Manually edit the `cubic.conf` for your project (located in your project's directory), and set the version number exactly as shown:

        cubic_version = 2022.01-72-release 

    (If you do not do this, you will not be able to open your project).

 3. Launch Cubic and open your existing project.
 
If you do not have an existing project, just update Cubic and create a new project, as you would normally do.
