### ISSUE TITLE
Allow install Cubic not requiring qemu

### ISSUE THREAD

**Issue by Augusto7743** [PJ-Singh-001/Cubic#75]
Thanks for read my topic.
When installing Cubic is required to install qemu files

qemu-block-extra_1%3a4.2-3ubuntu6.21_amd64.deb
qemu-system-common_1%3a4.2-3ubuntu6.21_amd64.deb
qemu-system-data_1%3a4.2-3ubuntu6.21_all.deb
qemu-system-gui_1%3a4.2-3ubuntu6.21_amd64.deb
qemu-system-x86_1%3a4.2-3ubuntu6.21_amd64.deb
and some others deb files

qemu only is required if the user want to test the ISO, but I use VirtualBox.

Any chance in future versions not requiring to install any qemu file ?
Have an nice week.

**Comment by PJ-Singh-001** [comment]
How would `apt install` know not to install `qemu` for some users, but install it for other users?

**Comment by Augusto7743** [comment]
sudo apt-get install recommends
I not use qemu. Only spread useless libraries in my OS.
If the user wish to install Cubic plus qemu the user has enough level to understand how to install recommends.

**Comment by PJ-Singh-001** [comment]
That won’t work…

Take a look at the [installation instructions](https://github.com/PJ-Singh-001/Cubic/wiki/Install-Cubic). The recommended method to install Cubic already uses `--no-install-recommends`. Without this option, many of the packages that Cubic depends on would install a bunch of unnecessary stuff. I tried to keep the extra packages installed onto your machine down to the bare minimum that Cubic absolutely needs, and always using `--no-install-recommends` to install Cubic is the only way to do that.

Surprisingly, many people who use Cubic are not that comfortable with different `apt` commands, so not all would know there is a “built in” feature that allows them to test their customizations, and that they can install it by using special `apt` commands.

I added Qemu per user request, and removing it would be undoing their request.

I’ll keep thinking about this, may be I can come up with a solution that addresses all concerns.

In the mean time, you can create a dummy package for Qemu. Then, when you install Cubic, `apt` will think the dependency is already satisfied, and will not install the actual Qemu package. (Of course, clicking the “Test” button in Cubic will result in an error, but I suspect you won’t be clicking that).

**Comment by PJ-Singh-001** [comment]
I've created a dummy package for Qemu. Here is how you can use it...

 1. Download the dummy package [`qemu-system-x86_0.0_all.deb`](https://github.com/PJ-Singh-001/Cubic/raw/2645b7ef1edcd58d71802d53f431bd0574bd40b2/qemu-system-x86_0.0_all.deb) hosted on this site.
 2. Remove Cubic (and Qemu, if you still have it installed).

        sudo apt autoremove --purge cubic
        sudo apt autoremove --purge qemu*

 3. Install the dummy package for Qemu, that you downloaded in step 1.

        sudo dpkg -i qemu-system-x86_0.0_all.deb

    Confirm that the dummy package was installed. Notice that its version number is 0.0.

        dpkg -l qemu*

        ||/ Name             Version Architecture Description
        +++-================-=======-============-============================================================================
        ii  qemu-system-x86  0.0     all          A dummy package for Qemu, in order to install Cubic without installing Qemu.


 4. Hold-back the dummy package from updates.
    This is to prevent `apt` from replacing the dummy package with a newer (full) version of Qemu during upgrades.

 5. Finally, install Cubic.
    You will notice that `apt` will not offer to install Qemu.

        sudo apt install --no-install-recommends cubic

**Comment by PJ-Singh-001** [comment]
Please let me know if the [solution presented above](https://github.com/PJ-Singh-001/Cubic/issues/75#issuecomment-1172844565) works for you.

If it does, in a future release, I can add special logic in Cubic to check if `qemu-system-x86` **version 0.0** is installed. If so, Cubic would not show the <kbd>Test</kbd> button, in order to avoid errors when the actual Qemu package is not installed on the system.

Installing the dummy Qemu package will be an option for advanced users, such as yourself, who do not want to install Qemu.

However, other users will still get Qemu installed by default for ease of use, as is the case today.

**Comment by Augusto7743** [comment]
Thanks very much for your support and making Cubic.

In moment doing some ISO tests removing components.
If in an Cubic ISO editing was used exact same apt-get purge command used in an installed OS to remove Libreoffice strangely remove anothers components that not are removed in an installed OS.
I will to do more test and after post more details.

I will test the qemu dummy.
I only use VirtualBox.
Well .. if has users using qemu the solution is your reply above.

Have an nice day.

**Comment by Augusto7743** [comment]
I has tested Cubic latest version using Qemu dummy file in Ubuntu 20.04.
Cubic load correctly.
Not tested editing ISO yet.

Now the files required are only

    binwalk_2.2.0+dfsg1-1_all.deb
    cubic_2022.06-72-release~202206302224~ubuntu20.04.1_all.deb
    gir1.2-gtksource-4_4.6.0-1_amd64.deb
    gir1.2-vte-2.91_0.60.3-0ubuntu1~20.04_amd64.deb
    isolinux_3%3a6.04~git20190206.bf6db5b4+dfsg1-2_all.deb
    libburn4_1.5.4-1~20.04.sav0_amd64.deb
    libgtksourceview-4-0_4.6.0-1_amd64.deb
    libgtksourceview-4-common_4.6.0-1_all.deb
    libisoburn1_1.5.4-2~20.04.sav0_amd64.deb
    libisofs6_1.5.4-1~20.04.sav0_amd64.deb
    libvte-2.91-0_0.60.3-0ubuntu1~20.04_amd64.deb
    libvte-2.91-common_0.60.3-0ubuntu1~20.04_amd64.deb
    python3-binwalk_2.2.0+dfsg1-1_all.deb
    python3-icu_2.4.2-0ubuntu3_amd64.deb
    python3-magic_2%3a0.4.15-3_all.deb
    python3-psutil_5.5.1-1ubuntu4_amd64.deb
    python3-pydbus_0.6.0-2build1_all.deb
    python3-pyinotify_0.9.6-1.2ubuntu1_all.deb
    qemu-system-x86_0.0_all.deb
    systemd-container_245.4-4ubuntu3.17_amd64.deb
    xorriso_1.5.4-2~20.04.sav0_amd64.deb

Thanks very much !!!!

**Comment by PJ-Singh-001** [comment]
Good, it works.
In a future release, I'll add a rule to Cubic to not display the <kbd>Test</kbd> button if the installed version of  `qemu-system-x86` is 0.0 (i.e. if the dummy package is installed).

**Comment by PJ-Singh-001** [comment]
I'm glad it works.

In a future release, I'll add a rule to Cubic to not display the <kbd>Test</kbd> button if the installed version of  `qemu-system-x86` is 0.0 (i.e. if the dummy package is installed).

**Comment by Augusto7743** [comment]
Have an nice week.
