### ISSUE TITLE
How to save the proxy source to the generated iso ?

### ISSUE THREAD

**Issue by yuanfenlyb** [PJ-Singh-001/Cubic#77]
**Describe the question**
Every time I change the proxy in etc/ apt /sources.list generate ios will become the default proxy source
A clear and concise description of what the question is.

**What you have tried**

Steps you already took.

**Expected behavior**

**OS Information (please complete the following information):**
 - OS/Distro Name: [e.g. Ubuntu, Mint, Kubuntu]
 - OS Version [e.g. Ubuntu 21.10]

**Cubic Information (please complete the following information):**
 - Cubic Version: [e.g. 2021.12.67 from the About dialog, or 2021.12-67-release from `dpkg -l`]
 - ISO Customizing: [e.g. ubuntu-21.10-desktop-amd64.iso]
 - Download Link:  The download link for the ISO you are customizing

**Screenshots**

**Comment by PJ-Singh-001** [comment]
@yuanfenlyb,

You didn't fill out any of the requested information in the question template.

![image](https://user-images.githubusercontent.com/19394936/177220517-221d3676-b092-4fc3-a6a3-23c6421393dc.png)


I believe the Ubiquity installer generates the `sources.list` file during installation.
Take a look at the Ubiquity source code to see what you need to change.
Another option is to use a `ubiquity/success_command` in your preseed file to search and replace the proxy information.
