### ISSUE TITLE
How to retain a custom `sources.list` after the customized OS has been installed?

### ISSUE THREAD

**Issue by yuanfenlyb** [PJ-Singh-001/Cubic#78]
**Describe the question**

The generated ISO image has not changed after saving the proxy source in Ubuntu.

**What you have tried**

I tried to change the proxy source on 18.04 and 20.04, but the generated ISO image is still the default source.

**Expected behavior**

I expect to save the replacement proxy source in the generated ISO image.

**OS Information**

 - OS/distribution name: Ubuntu
 - Operating system version: Ubuntu 18.04, Ubuntu 20.04

**Cubic Information**

 - Cubic Version: N/A
 - ISO Customizing: N/A
 - Download Link: https://releases.ubuntu.com/20.04/ubuntu-20.04.4-desktop-amd64.iso.torrent?_ga=2.7540603.814178193.1656995258-2087449588.1655867006

**Screenshots**

N/A

**Comment by PJ-Singh-001** [comment]
Would it be possible for you to share your `/etc/apt/sources.list` file with the updated proxy information?

**Comment by yuanfenlyb** [comment]
> 您是否可以`/etc/apt/sources.list`与更新的代理信息共享您的文件？

How to share?

**Comment by PJ-Singh-001** [comment]
Just copy and paste the contents of the file here as a comment.

     cat /etc/apt/sources.list

**Comment by yuanfenlyb** [comment]
I am here/etc/ apt /sources.list modify and save the generated iso image and there is no

**Comment by PJ-Singh-001** [comment]
What is the contents of `/etc/apt/sources.list` you WANT to have?

**Comment by yuanfenlyb** [comment]
deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ bionic main restricted universe multiverse

    deb http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted universe multiverse

    deb http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted universe multiverse

    # deb http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse
    # deb-src http://mirrors.aliyun.com/ubuntu/ bionic-proposed main restricted universe multiverse

    deb http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse
    deb-src http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse

I think so

**Comment by PJ-Singh-001** [comment]
Ok. Thank you. I'll post a possible solution soon.

**Comment by yuanfenlyb** [comment]
Okay, thank you

**Comment by PJ-Singh-001** [comment]
1. On your host machine, create a `sources.list` file with the contents you shared in your [previous comment](https://github.com/PJ-Singh-001/Cubic/issues/78#issuecomment-1177052910), and save it.

 2. In Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), create a directory to store your `sources.list` file.

        mkdir /opt/apt
        cd /opt/apt

 3. [Drag and drop](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Copy-Page) your `sources.list` file from step 1 onto the [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page) to copy it into the current directory (`/opt/apt`).

 4. Make sure the permissions are correct.

        chmod a=r,u=rw sources.list
        ls -la sources.list
        # -rw-r--r-- 1 user user 0 Jul  8 19:15 sources.list

 5. Copy the new `sources.list` file to `/etc/apt` so you can continue customizing your OS.

        cp /opt/apt/sources.list /etc/apt

 6. Continue customizing your OS.

        apt update

    Make additional changes, as desired.

 7. Use [preseeding](https://wiki.ubuntu.com/UbiquityAutomation) to update the `/etc/apt/sources.list` file after it is overwritten by [Ubiquity](https://manpages.ubuntu.com/manpages/kinetic/man8/ubiquity.8.html).

    On Cubic's [Options page](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page), on the [Preseed tab](https://github.com/PJ-Singh-001/Cubic/wiki/Options-Page#preseed-tab), add the following at the end of the `ubuntu.seed` file:

        ubiquity ubiquity/success_command string \
            in-target bash -c 'cp /opt/apt/sources.list /etc/apt/';

    This will copy the correct `sources.list` file from `/opt/apt/` to `/etc/apt/` after successful installation of your customized OS.

 8. Generate your customized ISO and test.
