### ISSUE TITLE
Remove (Cubic DATA-TIME) string in OS name

### ISSUE THREAD

**Issue by azertypy** [PJ-Singh-001/Cubic#81]
Hi. I'm trying to change OS name

neofetch:
     OS: LeLinux (Cubic 2022-07-13 23:46) x86_64 
I'm need to remove (Cubic 2022-07-13 23:46) x86_64

What I need to do that?

My desktop os info
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 22.04
 - Cubic version: 2022.06.72
 - ISO which I'm customizing: Ubuntu 22.04

Thank you in advance

**Comment by PJ-Singh-001** [comment]
The OS Name that is displayed is actually the the "Release Description".

If you are creating a new project, make sure you un-check the "OS Release" field on the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page).

<img src="https://user-images.githubusercontent.com/19394936/178861664-8d58a35e-c4e7-44f4-9095-1253f373831b.png" width="500">
