### ISSUE TITLE
How to preinstall Firefox Add-ons or Extensions in Cubic?

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#85]
Hello forum,

would like to add some Firefox Plugins into my bootable live ISO (USB or DVD).

Is this possibele? How?

Thank you very much!

Joe

**Comment by PJ-Singh-001** [comment]
@sudo-joe,

Have you resolved your question yet?
I haven't been able to get to this yet, but I think I have a solution for you; it will take me some time to post it though.
Please let me know if you are still looking for an answer.

**Comment by opensensesolutions** [comment]
This is not really a question for cubic.  cubic provides the console to run any commands, install any files you need, etc. which will affect the final ISO environment.  

I haven't worked with firefox in a while but you used to be able to just copy extension .xpi files into /usr/lib/firefox-addons/extensions/ and they would be available to all users.

**Comment by PJ-Singh-001** [comment]
This is how to install an Add-On or Extension in the `*.deb` version of Firefox. For recent versions of Ubuntu, the `*.deb` version of Firefox may be installed from the Mozilla Team PPA (`ppa:mozillateam/ppa`). These instructions do not apply to the Snap version of Firefox.

**On host computer:**

 1. In Firefox go to https://addons.mozilla.org.
 2. Search for your add-on (such as "Adblocker Ultimate").
 3. If the Add-on is not installed, install it by clicking on the <kbd>Add to Firefox</kbd> button.
     The Add-on must be installed for step 7, below.
 4. Right click on the <kbd>Remove</kbd> button and select "Copy Link" from the context menu.
     This link is required in step 9, below.
 5. In Firefox go to `about:config`.
     Click <kbd>Accept the Risk and Continue</kbd>, if prompted.
 6. Search for "`extensions.webextensions.uuids`".
 7. In the value section, you will see a list of Extension IDs and UUIDs in the format `{"Extension ID":"UUID", ... }`.
     Locate your Add-on ID (i.e. Extension ID) and copy it.
     The Add-on ID is required in step 10, below.
     For example, for Adblocker Ultimate, the Add-on ID is `adblockultimate@adblockultimate.net`.
    (Note, you do not need the hex formatted UUID).

**On Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page):**

 8. Go to the extensions directory.

        cd /usr/lib/firefox-addons/extensions/

 9. Download the Add-on using the URL from step 4.
    For example:

        wget https://addons.mozilla.org/firefox/downloads/file/4060704/adblocker_ultimate-3.7.21.xpi

10. Rename the downloaded `*.xpi` file to the Add-on ID from step 7.
     Be sure to keep the `.xpi` extension.
     For example:

        mv adblocker_ultimate-3.7.21.xpi adblockultimate@adblockultimate.net.xpi

**In the Live Environment or on an installed system:**

11. Launch Firefox.
     An additional tab for the Add-on will automatically open.
     The Add-on will automatically install for the user.
