### ISSUE TITLE
KDE themes

### ISSUE THREAD

**Issue by grenoblicronYT** [PJ-Singh-001/Cubic#86]
**Describe the question**

I would like to change KDE themes, color theme and others, but it just sais there is no display when I try to apply the theme so the user doesn't have to after the installation.

**What you have tried**

I installed the themed and everything worked but then I tried to set it as default.
I tried ` kvantummanager ` since I didn't found anything else.

**Expected behavior**

I was hopping that it would be able to set the desire theme as default.

**OS Information (please complete the following information):**
 - OS/Distro Name: Pop!_OS
 - OS Version: 21.10

**Cubic Information (please complete the following information):**
 - Cubic Version: 2022.06-72-release~202206302224~ubuntu21.10.1
 - ISO Customizing: pop-os_22.04_amd64_intel_10.iso
 - Download Link:  https://pop.system76.com/
 
**Screenshots**
![image](https://user-images.githubusercontent.com/74464524/179956437-90cc1329-d64f-4f7c-ae49-82cfe22703db.png)

**Comment by PJ-Singh-001** [comment]
I'm confused why you want to install KDE themes when you are trying to customize Pop!_OS which is a GNOME based desktop (not a KDE desktop)?

**Comment by PJ-Singh-001** [comment]
@grenoblicronYT,

I'm not clear what you want to do.

Are you trying to install a KDE them on a GNOME based system, or are you trying to make your KDE apps look native on a GNOME based system?

**Comment by PJ-Singh-001** [comment]
I am closing this question as invalid, since I have not heard back from you in quite a few days. If you continue to have an issue or question, please open a new question, and be sure to clarify what you are trying to achieve.
