### ISSUE TITLE
How to use docker in Cubic

### ISSUE THREAD

**Issue by Yefori-Go** [PJ-Singh-001/Cubic#89]
**Describe the question**

How to use docker in Cubic.

**What you have tried**

I have installed docker in Cubic virtual environment terminal, but when I use `docker pull` to pull an image, I got some errors.

I know it is because `systemctl` could not start in Cubic.

**Expected behavior**

To use docker in Cubic or pull an image when docker isn't started.

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version: Ubuntu 22.04

**Cubic Information (please complete the following information):**
 - Cubic Version: The latest version
 - ISO Customizing: ubuntu-22.04-desktop-amd64.iso
 - Download Link:  [Ubuntu](https://ubuntu.com/download/desktop/thank-you?version=22.04&architecture=amd64)

**Comment by Yefori-Go** [comment]
I tried `systemd` `systemctl` `service`, but none works.

**Comment by Yefori-Go** [comment]
Maybe I should try "Run the Docker daemon as a non-root user (Rootless mode)"

**Comment by Yefori-Go** [comment]
@PJ-Singh-001

**Comment by nelsonsilva94** [comment]
> Maybe I should try "Run the Docker daemon as a non-root user (Rootless mode)"

Were you able to solve this issue?

**Comment by Yefori-Go** [comment]
> Were you able to solve this issue?

Sorry but I finally use another way instead of containers.
But I think you should try `podman`? Seems that it can run without daemon.

**Comment by charnet1019** [comment]
> Author

operation not permitted

```bash
root@cubic:~# podman pull mysql:8.0.33
Trying to pull mysql:8.0.33...
Pulling image mysql:8.0.33 inside systemd: setting pull timeout to 5m0s
Getting image source signatures
Copying blob 89a648ecb3cf done   | 
Copying blob 49bb46380f8c done   | 
Copying blob d6eef8c26cf9 done   | 
Copying blob 0e908b1dcba2 done   | 
Copying blob 480c3912a2fd done   | 
Copying blob aab3066bbf8f done   | 
Copying blob 6313eed00780 done   | 
Copying blob 668fe2d98404 done   | 
Copying blob d3f8a843b813 done   | 
Copying blob c80ab9fc8db5 done   | 
Copying blob 1b8b6b073273 done   | 
Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:49bb46380f8cb3491e82d000b27a6eb26b2490291da814ce3363bbf2c8baeb1a": processing tar file(operation not permitted): exit status 1
```

**Comment by Yefori-Go** [comment]
> operation not permitted

seems related with selinux, but not sure

or try simpler image?

**Comment by charnet1019** [comment]
> > operation not permitted
> 
> seems related with selinux, but not sure
> 
> or try simpler image?

Ubuntu server has no selinux.
I can pull busybox and nginx but fail to pull mysql, which is weird.
