### ISSUE TITLE
How to customize the Ubiquity slideshow?

### ISSUE THREAD

**Issue by real-nickel** [PJ-Singh-001/Cubic#9]
I asked this in a different question but I was told to ask again as it didn't relate to Plymouth issue.

How do I customise the uBiquity slideshow from "Xubuntu" to "LuxOS"?

**Comment by PJ-Singh-001** [comment]
Note, this question is a follow-up to issue #5, [Ubiquity and splash screen](https://github.com/PJ-Singh-001/Cubic/issues/5).

**Comment by PJ-Singh-001** [comment]
The OS being customized is Xubuntu 20.04.

**Comment by PJ-Singh-001** [comment]
1. On Cubic's terminal page, make a backup of the original slides.

        cd /usr/share/ubiquity-slideshow
        cp -r slides slides.original

2. Update the slides.

        cd slides

        for file_path in `find . -name "*.html"`; do \
            echo "Updating file ${file_path}."; \
            sed -i "s|Xubuntu|LuxOS|g" "${file_path}"; \
        done

 3. Confirm your changes.

        grep -r LuxOS

 4. Optionally delete the backup of the original slides.

        rm -rf /usr/share/ubiquity-slideshow/slides.original

5. Finish generating the custom OS in Cubic.

6. Test by installing the custom OS.

![image](https://user-images.githubusercontent.com/19394936/148149420-af257682-c35d-47a3-8a21-acfcf15af475.png)

![image](https://user-images.githubusercontent.com/19394936/148149508-48b2d0c2-ee74-4d1b-9f1b-3f0a374468f0.png)

![image](https://user-images.githubusercontent.com/19394936/148149593-6c4c29f1-7268-4ecf-9cac-95e79a349904.png)

**Comment by real-nickel** [comment]
Ok thanks but I need to go somewhere take a covid test in a bit so I can't try it out now

**Comment by real-nickel** [comment]
Sorry, I forgot to say this worked really well and my distro is complete. If you are interested in checking it out it's at https://luxos.ga

**Comment by real-nickel** [comment]
hey in case anyone new finds this issue, you now need to install ubiquity and ubiquity slideshow
