### ISSUE TITLE
keyserver receive failed: General error

### ISSUE THREAD

**Issue by eband** [PJ-Singh-001/Cubic#90]
Using Cubic 2022.06.72 to remaster a Linux Mint 19.3 image, I ran into an error which after adding a PPA, the last line that displays before returning control to the user says, "keyserver recieve failed: General error."

Linux Mint 19.3 is based on Ubuntu 18.04 Bionic.

Yes, I know, I know, it's an old choice, but I need it to service my old computer that's sitting around.

Whatever.

As well, the image is the 32-bit version. Could it be that fact is the matter?

Please help.

**Comment by PJ-Singh-001** [comment]
What OS and version are you running Cubic in?

Someone had an issue executing `apt` commands when they tried to customize an Ubuntu 18.04 ISO while running Cubic in a much newer OS (Ubuntu 20.04).

**Comment by PJ-Singh-001** [comment]
Are you using a proxy or are you behind a firewall?

**Comment by PJ-Singh-001** [comment]
I have not heard back from you, so I will assume you no longer have this issue.
