### ISSUE TITLE
Does Cubic leave any footprint on the .iso?

### ISSUE THREAD

**Issue by RemoteDataServicesDotNet** [PJ-Singh-001/Cubic#94]
Does Cubic leave a signature behind? Or is there any way to know if a particular .iso was created using Cubic?

I made an iso in 2019 and I can't recall how I made it.

**Comment by PJ-Singh-001** [comment]
Newer versions of Cubic update the release description (unless you explicitly choose not to do this), which you can see using the command...

    lsb_release --description

It will show something like...

    Ubuntu 22.04.0 2022.04.27 LTS (Cubic 2022-08-17 22:49)

This was added as a user request, but I do not think this feature was present in 2019.

Alternatively, you can check the `README.diskdefines` file in the top-level directory of the customized ISO. Just mount your `*.iso` in your file browser, and and click on the `README.diskdefines` file.

Look at the first line, containing `DISKNOTE`. When you created your ISO using Cubic, if you had accepted the default parameters on the [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page), then you will see a date stamp immediately after the Ubuntu version. In the example below, the date stamp is "2019.04.21". The date stamp always follows the format `YYYY.MM.DD`. You may also see the word "Custom" preceding the release code name.

    #define DISKNAME Ubuntu 19.04.0 2019.04.21 amd64 "Custom Disco Dingo"

Remember, you will only see these values if you did not make changes to the defaults on Cubic's [Project page](https://github.com/PJ-Singh-001/Cubic/wiki/Project-Page). If you did make changes on this page, you will see the custom values you had entered.

For newer versions of Cubic, the `README.diskdefines` file also contains a `DISKNOTE` line which specifies the version of Cubic that was used, the date and time stamp, and the original ISO that was customized.

    #define DISKNAME  Ubuntu 22.04.0 2022.04.27 LTS "Custom Jammy Jellyfish"
    #define DISKNOTE  Generated using Cubic version 2022.01.70 on 2022-04-27 22:25 based on ubuntu-22.04-desktop-amd64.iso
