### ISSUE TITLE
Cubic for Linux Mint

### ISSUE THREAD

**Issue by sudo-joe** [PJ-Singh-001/Cubic#96]
Hello forum

I do like Cubic very much. Unfortunately I should make a remaster of a Linux Mint system.....

Do you see a possibility to include support for Linux Mint too?

Thank's a lot!

Joe

PS
I heard that the owner of Mint, Clements does try to prevent remastering Linux Mint... :(

**Comment by MarkovType** [comment]
> Hello forum
> 
> I do like Cubic very much. Unfortunately I should make a remaster of a Linux Mint system.....
> 
> Do you see a possibility to include support for Linux Mint too?
> 
> Thank's a lot!
> 
> Joe
> 
> PS I heard that the owner of Mint, Clements does try to prevent remastering Linux Mint... :(

Linux Mint is based on Ubuntu. What works on Ubuntu will on Linux Mint. This is the case for Cubic.

Also the thing about Clement trying to prevent Linux Mint remasters is false. I however would like to know where you read that information.

Cheers

**Comment by PJ-Singh-001** [comment]
@MarkovType is correct.
You can customize Linux Mint using Cubic.
Are you having issues customizing Linux Mint using Cubic?

**Comment by sudo-joe** [comment]
Thank you for the reply. If I am not wrong, I tried in the very early days of cubic, to install and use it on Mint. Probably I was the problem and not cubic :)

Than I found a forum post were it is/was mentionel, that Clement does "try to prevent remastering Linux Mint". (I try to find that post)

Sorry for spreading wrong informations!

Joe
