### ISSUE TITLE
Stuck at 50%

### ISSUE THREAD

**Issue by akshayans** [PJ-Singh-001/Cubic#98]
When I try creating the ISO, Cubic gets stuck at 50% on "Copy the selected boot kernel files to the disk" and the terminal reads:

ValueError: not enough values to unpack (expected 2, got 1).

**Comment by PJ-Singh-001** [comment]
1. What is the OS and version your are running?

 2. What is the version of Cubic your are running?

 3. What is the ISO you are customizing?

 4. What is the output of the following *before* running Cubic.

        df -h

 5. Then, run Cubic from the command line using the `--verbose` flag.

        cubic --verbose

 6. When the error occurs, copy and paste the log output here, so I can examine it.

 7. Also, let me know what is the output of the following *after* the error.

        df -h

**Comment by PJ-Singh-001** [comment]
I have not heard back from you, so I will assume you no longer have this issue.
