### ISSUE TITLE
Using Winetricks with Cubic

### ISSUE THREAD

**Issue by eband** [PJ-Singh-001/Cubic#99]
I'm trying to use winetricks with Cubic and winetricks keeps telling me that I can't use it because I have a 64-bit prefix.

How would I go about making a 32-bit prefix so that winetricks will work again on Cubic?

**Comment by Augusto7743** [comment]
Why you are trying use Winetricks in Cubic ?

**Comment by PJ-Singh-001** [comment]
Are you trying to pre-install Wine software in your customized OS ?

**Comment by PJ-Singh-001** [comment]
I haven't heard back from you, so I am closing this issue.
